### ISSUE TITLE
Inline SVG Title not showing as tooltip

### ISSUE THREAD

**Issue by AndikaTanpaH** [nwjs/nw.js#7166] opened 2019-09-19 03:14 UTC
NWJS Version : v0.40.2-ia32-sdk
Operating System : Ubuntu 16.04 32bit

### Expected behavior
SVG title shown as tooltip.

### Actual behavior
SVG title not shown as tooltip.

### How to reproduce
I was try two way,
```html
<svg viewBox="0 0 10 10" width="10" height="10" stroke-width="5">
  <title>Hello this is a Title</title>
  <line x1="0" y1="0" x2="10" y2="10" stroke="red">
  </line>
</svg>
<span>Title in SVG</span>
<br/>
<svg viewBox="0 0 10 10" width="10" height="10" stroke-width="5">
  <line x1="0" y1="0" x2="10" y2="10" stroke="red">
    <title>Hello this is a Title</title>
  </line>
</svg>
<span>Title in a child SVG</span>
```
on a browser just work see https://jsfiddle.net/Kr3Mb1Z/cw9t3bxq/3/

**Comment by TheJaredWilcurt** [comment] 2020-01-01 04:29
Both tooltips from the sample code show up properly in:

* Win 7 - 0.43.2
* Ubuntu 17 - 0.43.2
* OSX 10.11.6 - 0.43.2

Closing this issue as "Can't Reproduce". Please try in the latest version of NW.js. If you are still experiencing this issue, provide additional instructions on how to reproduce.

**Closed by TheJaredWilcurt** 2020-01-01 04:29 UTC
Labels: cant-reproduce
