### ISSUE TITLE
crashdump not generated nw 12

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#3226] opened 2015-03-12 00:45 UTC
hi

just tried

var gui = require('nw.gui');
gui.App.setCrashDumpDir('/tmp');

gui.App.crashBrowser() or crashRenderer()

it crash but no crashdump :/

an idear?

thanks

**Comment by smolleyes** [comment] 2015-03-14 21:24
hi

anyone for help with this issue in nw12

some users reports crash with

>  nw[2498]: segfault at 0 ip 00000000008a6af7 sp 00007fffd388a178 error 4 in nw[400000+43ea000]

or

> segfault at 307b004ecc08 ip 00000000017dfa2c sp 00007fff97e84840 error 6 in nw[400000+43ea000]

@rogerwang need help on this please :)

thanks

**Comment by jaymes-bearden** [comment] 2015-03-16 16:34
Looks like this was the cause of a rebase from quite some time ago. I added a comment to a stackoverflow post about this.

See here: http://stackoverflow.com/a/29082063/941187.

The commit is https://github.com/nwjs/nw.js/commit/d1dee800e65947fc0610943279a3976ff8c6962c against src/api/app/app.cc. Maybe we can get the attention of the devs on this one?

**Comment by rogerwang** [comment] 2015-03-17 02:17
Will look into this before 0.12.1.

**Comment by mn1aC** [comment] 2015-04-06 07:23
When will the next release be?

**Comment by rogerwang** [comment] 2015-04-07 05:28
@mn1aC would like to fix it in this week.

**Comment by rogerwang** [comment] 2015-04-13 03:01
released in 0.12.1

**Comment by kwokeith1989** [comment] 2015-04-17 06:29
updated with 0.12.1
I cannot find crash dump in default path in Mac

**Comment by smolleyes** [comment] 2015-04-17 06:43
nothing in /tmp ?

**Comment by kwokeith1989** [comment] 2015-04-17 06:49
I have tried with or without gui.App.setCrashDumpDir('/tmp');
However I still cannot find the minidump after triggering crashRenderer at the path I set or the default path as specified at https://github.com/nwjs/nw.js/wiki/Crash-dump

**Comment by ncd76** [comment] 2015-04-26 11:16
Same here, updated to v0.12.1-win-x64, no crash file no matter where I set the directory which is a shame as I seem quite good at making apps that crash a lot!

Tried: 
gui.App.setCrashDumpDir('/tmp'); 
gui.App.setCrashDumpDir('tmp'); 
gui.App.setCrashDumpDir(gui.App.dataPath);

triggering gui.App.crashRenderer(); and gui.App.crashBrowser(); on an onClick event, not directly after setting the path

**Comment by sergiovilar** [comment] 2015-05-20 20:20
Same issue in 0.11.5

**Comment by sergiovilar** [comment] 2015-05-20 20:28
In 0.12.1 too :(

**Comment by xueeinstein** [comment] 2015-05-22 05:59
@ncd76 , `setCrashDumpDir` doesn't work on nw.js v0.12.1 now. However, it indeed generates crashdump.  On windows, normally path is `C:\Users\<username>\AppData\Local\Temp`. BTW, large amount of messing named files in this folder. Check the time, and filetype `.dmp`, you'll find it easily.

**Comment by xueeinstein** [comment] 2015-05-22 06:03
@kwokeith1989 , currently, nw.js v0.12.1 generates crashdump under `~/Library/Breakpad` , that's different from the document. Please check it.

**Comment by sergiovilar** [comment] 2015-05-22 17:08
@xueeinstein the Breakpad folder even exists in my OSX :/

**Comment by xueeinstein** [comment] 2015-05-25 02:13
@sergiovilar , please start you nw.js app from terminal, could you see some error or warning information like '[4019:1119/211547:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed' ?

**Comment by sergiovilar** [comment] 2015-05-25 20:58
@xueeinstein yes!

```./cache/0.11.5/osx32/node-webkit.app/Contents/MacOS/node-webkit ./public/ --dev=true
[47145:0525/175747:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[47146:0525/175747:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[47147:0525/175747:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed```

**Comment by xueeinstein** [comment] 2015-05-26 01:57
>./cache/__0.11.5__/osx32/node-webkit.app/Contents/MacOS/node-webkit ./public/ --dev=true

Please try it on v0.12.1, on v0.11 it's already known issue, #2518.

**Comment by sergiovilar** [comment] 2015-05-26 02:21
@xueeinstein same problem on v0.12.1 and v0.12.2

**Comment by xueeinstein** [comment] 2015-05-26 03:20
@sergiovilar , it's a small bug in `breakpad_mac.mm`. Try to make the directory `~/Library/Breakpad` manually, and test cashdump again.

**Comment by sergiovilar** [comment] 2015-05-27 14:41
@xueeinstein works!

There's a estimate to fix this problem? I can't ask my users to make the `~/Library/Breakpad` directory.

Thank you so much!

**Comment by baconface** [comment] 2015-06-02 05:40
@sergiovilar You can [make this directory programmatically](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_mode_callback).

**Closed** 2016-09-19 06:44 UTC

**Comment by fritx** [comment] 2016-09-23 09:27
Who are you @nwjs-bot ?
