### ISSUE TITLE
macOS: Quit from the app switcher, missing "quit" string at event callback.

### ISSUE THREAD

**Issue by zdol** [nwjs/nw.js#5393] opened 2016-10-21 17:18 UTC
On a Mac  running mac OS 10.12, with nwjs (0.18.1) quitting the app from the app switcher (cmd+tab, keep the cmd pressed, highlight the app icon by pressing tab as many times it is needed and quit by pressing q, while still keeping cmd pressed) does not pass the "quit" string on the close event callback.

Quit by just pressing cmd+q, or selecting Quit from the file menu, or right-click and quit from the dock, all work just fine. It should be fixed I think.

```
var win = nw.Window.get();
win.on('close', function(e) {
    if (e === 'quit') {
      // code here should work in all cases
    }
}
```

**Comment by zdol** [comment] 2016-10-25 11:03
After some more extensive testing, it turns out that the event callback does not pass the 'quit' string when the app is not in the foreground, aka window does not have focus. One should handle the focus state properly and then handle any quit operations.

**Comment by ghostoy** [comment] 2016-11-16 06:04
I cannot reproduce this issue with NW.js between 0.17.6 to 0.18.7 on macOS 10.11 and 10.12.

How could you confirm code in the `if` statement not working?

**Comment by ghostoy** [comment] 2016-11-29 05:08
Close it since not receiving feedback for 2 weeks. Please reopen it if you have any follow ups.

**Closed by ghostoy** 2016-11-29 05:08 UTC
Labels: bug, needinfo

**Comment by zdol** [comment] 2016-11-29 16:45
Seems to work as intended on 0.18.8, thanks.
