### ISSUE TITLE
My C++ module works on node 6.2.2 but it crashes on nwjs 0.15.4 for Linux

### ISSUE THREAD

**Issue by cuongle121** [nwjs/nw.js#5086] opened 2016-07-07 08:26 UTC
Hi,

Thanks for great work with nwjs.

I am trying to use 0.15.4 for my project. My module written in C++ and wrapped using node-ffi works well with nodejs 6.2.2 but when I tried to use it with nwjs 0.15.4, it crashed (I only tested on Linux)

In the console, it says
```
nw: ../../nan/nan.h:679: Nan::MaybeLocal<v8::Object> Nan::NewBuffer(char*, size_t, node::Buffer::FreeCallback, void*): Assertion `length <= imp::kMaxLength && "too large buffer"' failed.
```
Dump file
[dump.zip](https://github.com/nwjs/nw.js/files/351668/dump.zip)

The simple sample code to reproduce the crash
https://github.com/cuongle121/nwjs-demo-0.15.4-crash

Thanks!
Cuong.

**Comment by rogerwang** [comment] 2016-07-07 10:00
It needs re-compile with the header files provided by NW. Previously we supported using node binary modules directly but now it's broken due to v8 ABI change.

**Comment by kailniris** [comment] 2016-07-07 11:02
@rogerwang I read the issue about the v8 change and i am interested, is it possible to support node binary modules in the future again?

**Comment by rogerwang** [comment] 2016-07-07 11:22
@kailniris yes, as long as the ABI of different v8 versions in Node and Chromium are compatible. So let's wait for the next v8 upgrade in Node and see.

**Comment by rogerwang** [comment] 2016-07-07 11:24
close as duplicate of #5025

**Closed by rogerwang** 2016-07-07 11:24 UTC

**Comment by cuongle121** [comment] 2016-07-07 15:12
Thank you very much for the quick response!

**Comment by shihrer** [comment] 2016-07-07 20:46
Just to make sure, does this mean we need to use nw-gyp to build native modules?  Does that mean if I want to use ffi, I need to build ffi with nw-gyp as well as my own code?  node-gyp was broken due to a recent VS update on Windows, will that affect nw-gyp?
