### ISSUE TITLE
alert message is not visible in windows 7

### ISSUE THREAD

**Issue by rezaamya** [nwjs/nw.js#6019] opened 2017-07-12 17:58 UTC
in the documentation there is [a sample](http://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/#example-2-using-nwjs-apis) that will not show anything if click 'Item A', I found that it will show alert but it's not visible and if I press "Space key" on my keyboard, it will press 'ok'.
![image](https://user-images.githubusercontent.com/8912282/28131825-5df0d298-6750-11e7-8c9b-6ac02f6bb9b3.png)

but if I change the Compatibility for the NW.exe, for example to Windows Vista, it will work:
![image](https://user-images.githubusercontent.com/8912282/28131979-c6ea3082-6750-11e7-99ac-e64f63440223.png)

![image](https://user-images.githubusercontent.com/8912282/28132177-50df6b18-6751-11e7-894e-848b6f9e6444.png)

![image](https://user-images.githubusercontent.com/8912282/28132152-4320d386-6751-11e7-8b62-174159d8d279.png)

the problem is I can't tell everyone to change the Compatibility mode! and also, some other features like sounds, will not work truly in compatibility mode...

**Comment by EdvaldoLima** [comment] 2017-07-12 19:30
@rezaamya In which version of nwjs did you run? I have a similar problem here, but it is in the newer version v0.23.6, I want to check before opening an issue.

**Comment by rezaamya** [comment] 2017-07-12 21:03
@EdvaldoLima I am using nwjs-v0.23.6-win-x64. same situation is for nwjs-v0.23.6-win-ia32 too.

**Comment by EdvaldoLima** [comment] 2017-07-12 21:26
@rezaamya ok, can you handle the alert, close, click "ok" normally?

**Comment by rezaamya** [comment] 2017-07-12 21:44
@EdvaldoLima if you mean without using NWJS, yes I can, if you mean, inside the NWJS, I can't see the message but if I press Space on my keyboard, it will press "ok" and I can continue using NWJS, before pressing Space key, it's like freezing, but in fact the focus in on the alert box and I can't do anything before closing (by clicking on the "ok") the alert box.

**Comment by EdvaldoLima** [comment] 2017-07-12 21:52
@rezaamya many thanks for the answers, I can reproduce the same problem on Windows 10 x64, version 0.23.6-Win-x64 on the NWJs.

**Comment by jtg-gg** [comment] 2017-07-13 03:55
looks like this bug is due to my "transparency" code
there is a workaround, you can run "nw --disable-transparency"
meanwhile I'll try to find a solution for this

**Comment by jtg-gg** [comment] 2017-07-13 05:47
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/88
to fix this issue
please also patch nw24, really sorry for this bug

**Comment by rogerwang** [comment] 2017-07-13 09:10
@jtg-gg no problem.

Fixed in git and will be available in the next nightly build.

**Closed** 2017-07-13 09:11 UTC

**Comment by zhuyifang** [comment] 2019-01-24 05:45
I also encountered this problem in version 14.7.
