### ISSUE TITLE
GC doesnt work well.

### ISSUE THREAD

**Issue by Fogrunner** [nwjs/nw.js#3722] opened 2015-08-01 01:22 UTC
hello. 

i'm trying to make a html5 desktop application by using NW v 12.
while developing, i've encountered a big problem about GC.

GC works inside. i've tested by using heap profiler. 
but, it does not release physical memory.

even i exactly released refs, they were sill held in physical memory. 
so, memory usage was increased gradually. finally, the app is going to be crash (out of memory)

here is my test code :
```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>NW test</title>
<script>
var testArray = null;
function Alloc()
{
	testArray = new Array(100000000).join('x');	
}

function Dealloc()
{	
	testArray = null;
}

function CallGC()
{	
	global.gc();
}

</script>
<body>
<input type="button" onClick="Alloc()" value="Alloc">
<input type="button" onClick="Dealloc()" value="Dealloc">
<input type="button" onClick="CallGC()" value="CallGC">
</body>
</html>
```
Test scenario
-----------------------------------------------------------------------------------------------------------
[after, pushing the button 'Alloc']

![3](https://cloud.githubusercontent.com/assets/11848318/9020063/cc07257c-3834-11e5-8127-0a40228d2ce0.png)

![2](https://cloud.githubusercontent.com/assets/11848318/9020064/d7ae2bf0-3834-11e5-93ca-6d8de97acc1e.png)

the memory usage of app was gained 

[after, pushing the button 'Dealloc']
![4](https://cloud.githubusercontent.com/assets/11848318/9020060/c5f3c726-3834-11e5-9f12-0168b0d151ab.png)

![5](https://cloud.githubusercontent.com/assets/11848318/9020891/3657a6d6-3862-11e5-86d9-aa9d672b974e.png)

heap profiler showed it has released well. but, memory usage was still around 100 mb.
it is the reason of crash. if i did this testing routine again, memory usage would be around 200 mb. 
im using 8 gb desktop machine. when the usage up to 8 gb, the app was suddenly closed without any error reporting. 

[after, pushing the button 'CallGC']

![6](https://cloud.githubusercontent.com/assets/11848318/9020099/27f1b50e-3836-11e5-83e6-35e4465235e1.png)

the usage turned back stable status.

did i do something wrong. or is it not a bug?

please, help me!

**Comment by Fogrunner** [comment] 2015-08-01 01:40
spec.

Window 8. 
nwjs-v0.12.2-win-x64
8 gb

**Comment by Fogrunner** [comment] 2015-08-01 01:47
https://github.com/nwjs/nw.js/issues/2408

**Comment by mscreenie** [comment] 2015-08-01 22:55
+1 

It's a widely reported bug and makes nwjs unusable for long periods unless you restart it completely - which isnt a good solution.

https://github.com/nwjs/nw.js/issues/3691
https://github.com/nwjs/nw.js/issues/3642
https://github.com/nwjs/nw.js/issues/3619
https://github.com/nwjs/nw.js/issues/3519
https://github.com/nwjs/nw.js/issues/3401
https://github.com/nwjs/nw.js/issues/3374

**Comment by Fogrunner** [comment] 2015-08-02 03:14
thanks @mscreenie  for replying.

i've realized that now its already known bug through your effort.

it seems as critical issue more than to add new features to system. i'm seriously considering to use NW. (because, my client wants to see stable and handleable big data application.) i suppose other people also consider or hesitate to use like me.

stability more important than new features.

**Comment by mscreenie** [comment] 2015-08-02 07:07
I agree, its a problem that needs to be solved as a priority.  Have you tried testing in branch 13.x to see if it persist?

**Comment by Fogrunner** [comment] 2015-08-03 06:11
yes, i did. v 13.x  showed me more terrible resulting than previous version. the version even held physical memory in spite of calling 'global.gc()'

**Comment by mscreenie** [comment] 2015-08-05 21:37
Hoping this gains enough traction to be looked at by @rogerwang . Hoping its an easy fix.

**Comment by rogerwang** [comment] 2015-08-05 21:47
Thanks for reporting. Will check this soon.

BTW, how does the case behave in Chromium browser?

**Comment by mscreenie** [comment] 2015-08-10 22:47
I'll look at how my app behaves in Chrome main stream latest. Especially when handling Iframes.

**Comment by xuanhun** [comment] 2015-08-13 08:18
simple mousemove event handle causes  memory leak:

    <script>
    window.onmousemove = function () {

    }
</script>

**Comment by pedro-lucas** [comment] 2015-08-14 18:58
Maybe it's a issue on node.js. Check the same code on Chromium Browser.

**Comment by hems** [comment] 2016-01-06 21:19
yeah that is absolutely terrible news which i just discovered very late on my  project and now i'm having problems like end users saying they can't use the app after one hour.. 

:(

**Comment by rogerwang** [comment] 2016-01-07 01:19
@Fogrunner I tried your sample with latest nightly build of 0.13 beta and it's working for me. I can see the memory consumption goes up when I press 'alloc', but after some time  the GC is triggered and the memory consumption goes down.

**Comment by hems** [comment] 2016-01-07 06:18
@rogerwang nice! i'm trying to get my 0.12 to run on 0.13 hopefully it will do the trick

**Comment by rogerwang** [comment] 2016-01-15 04:44
closing since this is not an issue in recent code.

**Closed by rogerwang** 2016-01-15 04:44 UTC

**Comment by mangaga** [comment] 2016-05-31 09:56
hi, @rogerwang 
I'm afraid issue not fixed really on nw0.13~nw0.14.5, my webapp memory increased gradually. finally, going to be crash. But it's performance well on chrome browser.
could you provide a api to release memory  like win.reload()  and not to change the UI. thks

**Comment by pedro-lucas** [comment] 2016-05-31 13:38
In node.js you can use this:

if(global['gc']) {
setInterval(function(){
if(process.memoryUsage().rss > 1024 * 1024 * 200) { //200MB
global.gc();
}
}, 5000);
}

Use the flag *--expose-gc* in node.js to activate this feature.

I think it can work in NW. Try it.

2016-05-31 6:58 GMT-03:00 mangaga <notifications@github.com>:

**Comment by mangaga** [comment] 2016-06-01 01:16
thanks for your suggestion and I tried it in NW with "js-flags":"--expose-gc", there are little memory would be released when I call global.gc() frist time, maybe several MB ,and released nothing called gc again.

**Comment by rogerwang** [comment] 2016-06-01 01:55
@mangaga you should make sure there is no memory leak in your application first. Use the heap profiler of  chrome devtools

**Comment by mangaga** [comment] 2016-06-01 02:13
@rogerwang yes, I did. It's a complex website, you could not make sure there is none any js memory leak,  and I'm tring hard to avoid leak. I will  check again and again.

But I think NW should also has the mechanism of memory control like chrome , you can not let the memory aways increase and crashed at last.

**Comment by rogerwang** [comment] 2016-06-01 02:15
@mangaga what mechanism of memory control like chrome are you referring to? NW is as same as chrome on this.

**Comment by mangaga** [comment] 2016-06-01 04:53
sorry @rogerwang  , I don't know the chrome's mechanism of memory control, if I know I will write another NW (just kidding ~_~  my idol).

I test the same one web page on chrome and NW.
the memory changes on chrome:
page loaded frist time memory is  45.4MB, and reload 30 times, memory changed from 46 MB to 68 MB and at last to 46.7MB

when I test on NW, memory changed from 112MB to 318MB and aways keep 318MB.

**Comment by rogerwang** [comment] 2016-06-01 05:08
Could you please provide the sample web page so I can reproduce it here?

**Comment by renemarty** [comment] 2017-01-13 02:04
Any news on this? It's a serious bug of nw... I'm analysing to migrate a huge app to electron only due to this memory issue.  Any advice or comment will be appreciated.

**Comment by pageborn** [comment] 2017-07-31 11:41
I also find a solution for this issue, not yet.  if there is a function like global.gc(), and can really trigger garbage collector, will be the best way. Hope NW can fixed this issue. 
And i find minimize window can release memory,  some methods get together it works, like these: 

var gui = require('nw.gui');
var win = gui.Window.get();
if(process.memoryUsage().rss > 1024 * 1024 * 200) { //200MB
  win.minimize();
  win.maximize();
}

**Comment by bq-hentai** [comment] 2017-08-18 09:30
@pageborn I test ur mtd just now. But it doesn't effect all the time. maybe 5%.

**Comment by bq-hentai** [comment] 2017-08-18 09:30
@pageborn I test ur mtd just now. But it doesn't effect all the time. maybe 5%.
