### ISSUE TITLE
Developer Window

### ISSUE THREAD

**Issue by PewienTyp** [nwjs/nw.js#2965] opened 2015-01-17 11:54 UTC
Please add paste and copy option in developer console.

**Comment by ghostoy** [comment] 2015-01-17 13:31
Duplicate of #2660. Please try this link http://dl.nwjs.io/live-build/01-17-2015/be29028-d8ecacd-9a15a52-f2f89e2-d9a9d39-cdd879e/.

**Closed by ghostoy** 2015-01-17 13:31 UTC

**Comment by PewienTyp** [comment] 2015-01-17 14:18
Copy and paste in rigth click menu

**Comment by ghostoy** [comment] 2015-01-18 01:56
Does `ctrl+c` and `ctrl+v` work for you?

**Comment by jakehh** [comment] 2015-01-18 02:17
If you're on OS X, adding a App Menu worked for me (adds the cmd+c/cmd+v shortcuts)

**Comment by PewienTyp** [comment] 2015-01-18 09:16
ctrl+c and ctrl+v works but this menu will be usable
