### ISSUE TITLE
OnNoMemory  in ImageDecodeTask

### ISSUE THREAD

**Issue by dalidong2009** [nwjs/nw.js#5453] opened 2016-11-09 07:59 UTC
when I upgrade nw version from 0.12.3 to 0.15.4, the probability of app crash happen frequently then the old version.
the crash ofter occur at display img (jpg, 3024px * 4032px). the crash not always happen, but with a certain probability.
here is my crash report 
[xx.txt](https://github.com/nwjs/nw.js/files/580097/xx.txt)
Operating system: Windows NT
                  6.1.7601 19135
CPU: x86
     GenuineIntel family 6 model 62 stepping 4
     4 CPUs

Crash reason:  EXCEPTION_BREAKPOINT
Crash address: 0x5db53bc1
Thread 5 (crashed)
 0  nw.dll!logging::LogMessage::~LogMessage() [logging.cc : 735 + 0x9]   
 1  nw.dll!base::`anonymous namespace'::OnNoMemory [memory.cc : 19 + 0x80]
 2  nw.dll!content::ChildDiscardableSharedMemoryManager::AllocateLockedDiscardableSharedMemory(unsigned int,int) [child_discardable_shared_memory_manager.cc : 312 + 0x8]
 3  nw.dll!content::ChildDiscardableSharedMemoryManager::AllocateLockedDiscardableMemory(unsigned int) [child_discardable_shared_memory_manager.cc : 187 + 0x11]
 4  nw.dll!cc::SoftwareImageDecodeController::DecodeImageInternal(cc::ImageDecodeControllerKey const &,cc::DrawImage const &) [software_image_decode_controller.cc : 406 + 0x2b]
 5  nw.dll!cc::SoftwareImageDecodeController::GetDecodedImageForDrawInternal(cc::ImageDecodeControllerKey const &,cc::DrawImage const &) [software_image_decode_controller.cc : 574 + 0x16]
 6  nw.dll!cc::SoftwareImageDecodeController::DecodeImageInternal(cc::ImageDecodeControllerKey const &,cc::DrawImage const &) [software_image_decode_controller.cc : 451 + 0x23]
 7  nw.dll!cc::SoftwareImageDecodeController::DecodeImage(cc::ImageDecodeControllerKey const &,cc::DrawImage const &) [software_image_decode_controller.cc : 353 + 0x13]
 8  nw.dll!cc::`anonymous namespace'::ImageDecodeTaskImpl::RunOnWorkerThread [software_image_decode_controller.cc : 75 + 0x10]
....

**Comment by ghostoy** [comment] 2016-11-09 08:10
Could you post a sample app, including the large image? And how much memory does you PC have?

**Comment by dalidong2009** [comment] 2016-11-09 10:30
thanks .
the crash report copy from my client's PC, and I couldn't reappear the crash at my PC.
maybe I locate the issue point isn't correct.
img :
https://cloud.githubusercontent.com/assets/8622414/20132693/1a515a3e-a69f-11e6-8c9a-2d38ed5ab454.jpg
PC memory : 4GB

**Comment by ghostoy** [comment] 2016-11-11 02:52
I can't simply reproduce this issue with a Windows 7 VM with dual core + 2G memory.

It looks like a bug from upstream. This crash log appears in upstream bug report in https://crbug.com/592823. However it's said to be included in another non-public issue regarding to no memory in https://crbug.com/577786.

**Comment by ghostoy** [comment] 2016-11-22 02:44
There were big refactors for images for software decodings in nw19 (Chromium 55). Please try if it fixed your issue.

**Comment by dalidong2009** [comment] 2016-11-30 09:35
@ghostoy  thank you
my English is not good.
in the issue #5487 , nw version is 0.12.3 , nw app will crash always .
in this issue , nw version is 0.15.4 , the crash not always happen, but with a certain probability.

now , I change the size of big image in  server, the app work well . 
when nw19  is released, I will try this again.

**Comment by ghostoy** [comment] 2016-12-01 04:48
@dalidong2009 We have 0.19.0-rc1 released recently. You can try it first https://dl.nwjs.io/v0.19.0-rc1/

**Comment by ghostoy** [comment] 2016-12-27 02:53
Close this issue since not receiving feedbacks for 3 weeks. Please reopen it if you still experience this issue.

**Closed by ghostoy** 2016-12-27 02:53 UTC
Labels: needinfo, upstream-chromium
