### ISSUE TITLE
NW crash on WebMIDI API sysex sending

### ISSUE THREAD

**Issue by g200kg** [nwjs/nw.js#6502] opened 2018-03-09 04:20 UTC
NWJS Version : nwjs-sdk-v0.29.0
Operating System : windows x64

In v0.29.0, https://github.com/nwjs/nw.js/issues/6492 is solved and it is now possible to acquire a MIDI port by specifying sysex on webMIDIAPI.

However, unfortunately when I actually try to output sysex data, NW will crash.

In the program below, the display of "requestMIDIAccess OK" works normally. After that, sendNoteOn has no problem, but when I run sendSysEx, the NW window closes.

(You need to connect some MIDI devices to test it)

```js
<script>
let midiout=[];
alert("requestMIDIAccess start");
navigator.requestMIDIAccess({sysex:true}).then(
    function(ma){
      alert("requestMIDIAccess OK");
      let it=ma.outputs.values();
      for(let o=it.next(); !o.done; o=it.next()) {
        midiout.push(o.value);
      }
      alert("midiout found : "+midiout[0].name);
    },
    function(e){alert("requestMIDIAccess Error");},
  );
alert("requestMIDIAccess end");

function sendNoteOn(){
  midiout[0].send([0x90,0,0]);  // note On
  alert("send noteOn");
}
function sendSysEx(){
  midiout[0].send([0xf0,0x7e,0x7f,0x09,0x01,0xf7]); // GM on
  alert("send sysex message");
}
</script>

<button onclick="sendNoteOn()">Send NoteOn : send([0x90,0,0])</button>
<button onclick="sendSysEx()">Send Sysex : send([0xf0,0x7e,0x7f,0x09,0x01,0xf7])</button>
```

**Comment by rogerwang** [comment] 2018-03-09 04:56
Could you please provide the [crash dump](http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file) ?

**Comment by g200kg** [comment] 2018-03-09 05:23
crash dump is here

[a494c7a8-1e21-4aac-9268-cb0b8548909a.zip](https://github.com/nwjs/nw.js/files/1795711/a494c7a8-1e21-4aac-9268-cb0b8548909a.zip)

**Comment by g200kg** [comment] 2018-03-09 05:26
And I got a message from Chrome WebMIDIAPI author that it may caused by browser process security check.  (may be this one in electron? : https://github.com/electron-archive/brightray/issues/138)

**Comment by rogerwang** [comment] 2018-03-09 05:53
I think we already permit that. Would you clear the user data directory and try again?

**Comment by g200kg** [comment] 2018-03-09 06:24
hmm, this is a crash dump generated right now. After clear the User Data/Crashpad/reports/

[f3319153-ff11-473d-9cfa-3859a9ca6e86.zip](https://github.com/nwjs/nw.js/files/1795828/f3319153-ff11-473d-9cfa-3859a9ca6e86.zip)

**Comment by rogerwang** [comment] 2018-03-09 06:36
I mean clearing the whole user data dir (the dir named after the `name` field in package.json), not just the crash report dire.

**Comment by g200kg** [comment] 2018-03-09 07:29
ok, I see. I delete the directory and tried it again
The phenomenon seemed to be the same.

This directory was created
[zoomnw.zip](https://github.com/nwjs/nw.js/files/1795931/zoomnw.zip)

**Comment by toyoshim** [comment] 2018-03-09 11:04
Chromium requires to register renderers' process id to the whitelist to permit the Web MIDI sysex correctly. Otherwise, the browser process kills the renderer who is going to send a sysex for security sanity check. I may send a patch to fix it though I haven't checked NW side code base yet.

**Comment by g200kg** [comment] 2018-03-09 11:18
for example, https://github.com/nwjs/nw.js/blob/nw29/src/browser/nw_extensions_browser_hooks.cc line 197 set the ChildProcessSecurityPolicy for file_scheme, but I am not sure where the right place for MIDI sysex.

**Comment by rogerwang** [comment] 2018-03-09 11:42
@toyoshim it may be registered here: https://github.com/nwjs/chromium.src/blob/nw29/chrome/browser/media/midi_sysex_permission_context.cc#L31

It's not clear that the crash is caused by this. But we could also try...

**Comment by rogerwang** [comment] 2018-03-12 02:48
I'm able to reproduce it here. Will fix it soon.

**Comment by rogerwang** [comment] 2018-03-12 05:29
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2018-03-12 05:29 UTC
Labels: bug, triaged

**Comment by toyoshim** [comment] 2018-03-12 06:58
Ah, you've already done the right thing.
Thank you for fixing the problem, and please feel free to ping me if you have a question on Web MIDI implementation in Chromium :)

**Comment by g200kg** [comment] 2018-03-13 00:38
I have now confirmed it works normally with latest nightly build. Thank you!

**Comment by g200kg** [comment] 2019-03-09 14:17
I confirmed that this problem was fixed when nw29, but unfortunately, now this problem has recurred (v0.37.0-beta1-win-x64).

I do not know when it happened, and it may be another problem.

crash dump:
[01e2678d-9378-4a0a-9680-19c6f3cb77a8.zip](https://github.com/nwjs/nw.js/files/2948455/01e2678d-9378-4a0a-9680-19c6f3cb77a8.zip)
