### ISSUE TITLE
under nw0.19.0 audio.play  Uncaught (in promise) DOMException:

### ISSUE THREAD

**Issue by Vincent2015** [nwjs/nw.js#5641] opened 2017-01-17 03:15 UTC
var audio = new Audio("src/audio/message.mp3");
    undefined
audio.play()
     Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: DOMException: The element has no   
     supported sources.}
    VM1005:1 Uncaught (in promise) DOMException: The element has no supported sources.

before i upgrade nw to 0.190.0. i try this under nw 0.12.3 and chrome bwoser all is ok.

**Comment by rogerwang** [comment] 2017-01-17 04:35
Please upload a full example.

**Comment by Vincent2015** [comment] 2017-01-17 05:00
<img width="659" alt="b8f297bb-e0c7-4990-b3f5-a3bd52d1857e" src="https://cloud.githubusercontent.com/assets/6760575/22008283/c9733b2c-dcb4-11e6-93e5-b72ad759bc01.png">
<img width="631" alt="479efc61-3f0c-46e9-976f-4ba195f29f63" src="https://cloud.githubusercontent.com/assets/6760575/22008286/caab64ba-dcb4-11e6-9a91-d90296ed5149.png">

different version of nw

**Comment by rogerwang** [comment] 2017-01-17 05:16
By "full example" I mean a sample app ready to run and reproduce your issue here. Not screenshots.

**Comment by Vincent2015** [comment] 2017-01-17 05:44
demo is too big。this is link https://pan.baidu.com/s/1i5x9hbB.

you could try . thanks.

**Comment by Blatman** [comment] 2017-01-17 07:36
Gidday,

just tried the test demo and it seems to work OK if the libffmpeg.dylib within the package is replaced with an mp3 capable version - see iteufel on github.
Cheers.

**Comment by rogerwang** [comment] 2017-01-17 07:37
Thanks for verifying @Blatman . Closing according to your comment since it's not a bug.

**Closed by rogerwang** 2017-01-17 07:37 UTC

**Comment by Vincent2015** [comment] 2017-01-17 07:43
@Blatman  where is the replacement.

**Comment by Blatman** [comment] 2017-01-17 07:48
https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases

just swap out the libffmpeg.dylib in the test package under nwjs Framework.framework

**Comment by Vincent2015** [comment] 2017-01-17 07:56
ok,it's very good.thanks very much.
