### ISSUE TITLE
How to run testing on NW.js with puppeteer

### ISSUE THREAD

**Issue by WinSpeiNe** [nwjs/nw.js#6912] opened 2018-12-26 11:34 UTC
I'm try to do testing with puppeteer in NW(node webkit) application.
and i need to get page to use it in puppeteer.
When i try to use with puppeteer 1.4 version and chromium 71:

```
const puppeteer = require('puppeteer');

(async () => { 
	const browser = await puppeteer.launch({
		headless:false,
		executablePath:"my\\folder\\nw.exe",
		ignoreDefaultArgs:true
});
	
const pages = await browser.pages();
console.log(pages);
```
**The appliaction launch and the result is: [] - empty array.**

But when I'm use in puppeteer 1.9 version and chromium 71:
the launch never stop and not returning nothing !

how can I run testing in NW.js with puppeteer ??? 

@rogerwang

**Comment by rogerwang** [comment] 2018-12-26 14:56
It looks like puppeteer is expecting 'browser' windows but the NW window is a Chrome App window, which is different from browser window internally. We have the plan to migrate the implementation to browser window. See #5875 . 

Before that is done you can use the chromedriver shipped within NW.js SDK to test NW applications. Or puppeteer might support Chrome App testing so that it would work with NW as well.

**Comment by rogerwang** [comment] 2018-12-27 04:44
Close as duplicate of #6350

**Closed by rogerwang** 2018-12-27 04:44 UTC
