### ISSUE TITLE
After upgrading to 0.19.3, debug.log appears in this error, the program crashed!

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#5588] opened 2016-12-24 16:07 UTC
`[1225/000301:ERROR:process_info.cc(608)] range at 0x8828587e00000000, size 0x187 fully unreadable
[1225/000301:ERROR:process_info.cc(608)] range at 0x8828589e00000000, size 0x187 fully unreadable
[1225/000301:ERROR:process_info.cc(608)] range at 0x0, size 0x187 fully unreadable
[1225/000301:WARNING:in_range_cast.h(38)] value 1681616540610 out of range
[1225/000301:WARNING:in_range_cast.h(38)] value 1681616540088 out of range
[1225/000301:WARNING:in_range_cast.h(38)] value 1681616542440 out of range
[1225/000301:WARNING:in_range_cast.h(38)] value 1681616539150 out of range
[1225/000301:ERROR:process_info.cc(608)] range at 0xe0f126c400000000, size 0x18f fully unreadable
[1225/000301:ERROR:process_info.cc(608)] range at 0xe0f126e400000000, size 0x18f fully unreadable
[1225/000301:ERROR:process_info.cc(608)] range at 0x0, size 0x18f fully unreadable
[1225/000301:WARNING:in_range_cast.h(38)] value 1717540523010 out of range
[1225/000301:WARNING:in_range_cast.h(38)] value 1717540522488 out of range
[1225/000301:WARNING:in_range_cast.h(38)] value 1717540524840 out of range
[1225/000301:WARNING:in_range_cast.h(38)] value 1717540521550 out of range
`

**Comment by phpjishu** [comment] 2016-12-25 16:33
I used iframe in the new window

**Comment by ghostoy** [comment] 2016-12-27 03:06
Please submit a sample app to reproduce this issue.

**Comment by ghostoy** [comment] 2017-01-16 08:41
Close it since not receiving feedback for more than 3 weeks. Please reopen it if you have any updates.

**Closed by ghostoy** 2017-01-16 08:41 UTC
Labels: needinfo
