### ISSUE TITLE
macOS Sierra: [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#5234] opened 2016-08-25 10:01 UTC
When application starts it shows several warnings in console:

`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

NWJS Version: 0.16.1
OS: macOS Sierra 10.12 Beta (16A304a)

**Comment by rogerwang** [comment] 2016-08-29 04:48
How can I reproduce this?

**Comment by oaleynik** [comment] 2016-08-29 04:56
@rogerwang you can run an example from the NWJS's Readme:

![Screen](https://i.gyazo.com/dfcc1c929b2bfaa642e6fd224696a742.gif)

**Comment by oaleynik** [comment] 2016-08-29 05:09
@rogerwang also application doesn't wanna close anymore using close button.

![Screen 1](https://www.dropbox.com/s/etv7fdqs12w01ww/Screenshot%202016-08-29%2008.07.22.png?dl=1)

It just hangs:

![Screen 2](https://www.dropbox.com/s/wbxyc0ijuol6fd9/Screenshot%202016-08-29%2008.08.37.png?dl=1)

**Comment by oaleynik** [comment] 2016-08-29 05:11
Found similar bug report in Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=626534

**Comment by rogerwang** [comment] 2016-08-29 05:12
looks like upstream fixed in in Chromium 53. Could you please try this build? http://dl.nwjs.io/live-build/08-29-2016/nw17-3b148c7-541e578-de19b1f-6c79a25/v0.17.0/

**Comment by oaleynik** [comment] 2016-08-29 05:15
@rogerwang yep, looks like that. Thanks!

**Comment by oaleynik** [comment] 2016-08-29 05:18
@rogerwang nodejs 6.5.0 is gonna to be publically available soon. Does this mean we will get 0.17.0 soon as well?

**Closed** 2016-08-29 05:17 UTC

**Comment by rogerwang** [comment] 2016-08-29 05:20
0.17.0 will be released soon with Chromium 53 stable in this week.

**Comment by oaleynik** [comment] 2016-08-29 05:21
Thanks!
