### ISSUE TITLE
Node server not reset on window reload

### ISSUE THREAD

**Issue by Yatterman** [nwjs/nw.js#7544] opened 2020-08-15 16:04 UTC
NWJS Version : 0.47.2
Operating System : Linux Mint 20

### Expected behavior

When a window reload happens (either with F5 on dev window or by using the win.reload() method, an open server should be reset, so that the new instance of the code can issue its own server.listen()

### Actual behavior

The server is not closed and the new instance of the code is not able to open a new listen on the same port, because the old instance is still listening there, but those requests fall into the void

### How to reproduce

Consider this simple server "hello world"

var http = require('http'),
  server = http.createServer(function(req, res) {
  console.log(req.url); // just to show that we are here
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.write('&lt;strong&gt;Hello World&lt;/strong&gt;');
  res.end();
});
server.listen(8080);

when you execute it, you can point your browser to localhost:8080 and watch the output.
a single slash is printed in the console (the url we typed is the "home" of the "website")

Now edit your code to change the Hello World message and issue a win.reload() or press F5 on the developer window to make the changes to the code effective
Go to the browser and refresh the page.
The old message gets shown in the browser window, nothing is printed to the console (showing the server was not listening or didn't get the request anyway)

If you issue a server.close() before the reload, the expected behaviour happens instead.
A temporary workaround is to have some code like the one below
function reLoad()
{
        var win = nw.Window.get();
	server.close();
	win.reloadIgnoringCache();
}
and use that function to reload the code during development phase.

**Comment by franck34** [comment] 2020-08-16 05:56
Not a bug. It's a feature. You have to deal with that.

If nwjs was closing your server, and if you want the server to stay up you will be in another blocking situation.

**Comment by Yatterman** [comment] 2020-08-16 09:02
Why would you want the server to stay up? (genuine question, I can't picture a scenario like that)
You are reloading the app to update it. If the old server stays up, the client gets non updated data. If the server is reset, there's not an interruption of service, because it's just because the app is reloaded.
BTW, if it is a feature, it should be documented in the win.reload() section http://docs.nwjs.io/en/latest/References/Window/#winreload
As I wrote, there is a simple workaround and dealing with it is not cumbersome, but you must know you need to do it.

**Comment by corwin-of-amber** [comment] 2020-08-20 08:55
Anything `require`d by Node.js is loaded in the context of the background page (believe I saw it documented somewhere).

If you app has one server and multiple windows, you would be quite annoyed if NW.js reloaded your server every time you refresh one of them. You really want to have control over what happens.

There is a much cleaner way to do it: if you have resources associated with your window (such as the server connection in your case), clean them up when the window is unloaded. E.g.
```
window.addEventListener('beforeunload', () => { server.close(); });
```
This even fires right before the window is reloaded.

**Closed** 2023-03-08 16:55 UTC
Labels: invalid
