### ISSUE TITLE
App won't quit on Mac

### ISSUE THREAD

**Issue by aliblackwell** [nwjs/nw.js#7355] opened 2020-02-05 14:39 UTC
NWJS Version : 0.44.0
Operating System : Mac OS Catalina 10.15.1

### Expected behavior

Quitting the app from the system menu or by right-clicking the dock icon should quit the app. Processes nwjs, nwjs Helper, nwjs Helper (GPU) and nwjs Helper (Renderer) should all disappear from the Activity Monitor and the tray icon and dock icons should disappear.

### Actual behavior

The icon remains in the dock and the tray menu remains. nwjs, nwjs Helper, nwjs Helper (GPU) and nwjs Helper (Renderer) are all still active in Activity Monitor. 

Calling the `nw.App.quit()` method manually does successfully close the app.

**Running with `--disable-features=nw2` does lead to expected behaviour.**

### How to reproduce

- Download the zip [nw2_quit_bug.zip](https://github.com/nwjs/nw.js/files/4160077/nw2_quit_bug.zip), unzip and navigate into `nw2_quit_bug` using your terminal
- Run `$ npm install` to install latest nwjs release: v0.44.0
- Run `$ npm start` to start the app. A paw icon will appear in system tray. 
- Try to quit the app using the nwjs System menu or by right-clicking the dock icon and choosing Quit.

**Comment by rogerwang** [comment] 2020-02-06 04:07
Thanks for reporting. But your sample works for me.

**Comment by Blatman** [comment] 2020-02-06 09:21
FWIW - I tried test app on 10.13.6 (0.44.0) and it will not quit without force-quit. OK with nw2 disabled. I tested by just dropping nwjs into the src folder and double-clicking (probably why the taskbar icon showed the nwjs icon rather than the paws). My apps with windows are OK so maybe this is only an issue if there is no window.

**Comment by panther7** [comment] 2020-02-06 12:29
I think, that it's similar to #7271.

**Comment by arudnev** [comment] 2020-02-06 20:58
I'm on macOS Catalina 10.15.3

This works as expected:

`./nwjs-sdk-v0.44.0-osx-x64/nwjs.app/Contents/MacOS/nwjs --disable-features=nw2 nw2_quit_bug`

This one quits when clicking Quit App in tray menu, but does not quit when clicking Quit after right-click on dock icon

`./nwjs-sdk-v0.44.0-osx-x64/nwjs.app/Contents/MacOS/nwjs nw2_quit_bug`

We observe the same with other app that has "main": "index.html" and opens a window.
In our app when you click Quit it just hides the window.
If you click on the dock icon after that it re-opens the app ("reopen" even is fired by App).
If you click on Quit after re-open one more time the window does not get hidden.
It does not seem to fire "close" event on the Window when Quit menu item is clicked, but command + Q does exit the app.

**Comment by arudnev** [comment] 2020-02-07 17:26
I did some more testing, it seems that all comes down to difference in how Quit action on dock icon menu and how `close` event are handled in `nw1` vs `nw2` modes.

First of all, if app does not have window then Quit on dock icon menu does not exit the app, if app has window and does not add handler for `close` event then the app will exit as expected.

Now, if app adds handler to `close` event it all works differently between `nw1` and `nw2` modes.

In `nw1` mode Quit on dock icon would simply exit the app without firing `close` event.

In `nw2` mode it fires `close` event, but with [quit](https://nwjs.readthedocs.io/en/latest/References/Window/#event-close) argument being `undefined`.

So, if logic for handling of `close` event relies on `quit` argument to decide if app should be exited or simply hidden (typical behavior for some app types, i.e. messaging apps) then in `nw2` mode it can not distinguish between Quit on dock icon menu vs close button in the window frame.

It can be demonstrated by running something like this in dev console in vanilla sdk install and then attempting Quit via dock icon menu:

`nw.Window.get().on('close', (q) => { alert(q ? 'quit' : 'hide'); q && nw.App.quit(); })`

Also, not that it matters, in `nw2` mode subsequent clicks on Quit in dock icon menu don't fire `close` event at all and some other listeners seem to be de-registered after first click on Quit as well, i.e. `command + Q` that would fire `close` with `quit='quit'` before clicking on Quit would not fire after `close` event triggered by Quit.

**Comment by rogerwang** [comment] 2020-02-10 04:03
This shares similar root cause with #7298

**Comment by rogerwang** [comment] 2020-02-10 04:07
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed** 2020-02-10 04:07 UTC

**Comment by aliblackwell** [comment] 2020-02-11 16:58
Thank you both (@rogerwang and @arudnev) so much! This is fantastic news.
