### ISSUE TITLE
app crashed after reload/refresh using web workers 

### ISSUE THREAD

**Issue by f3l1x** [nwjs/nw.js#7487] opened 2020-05-21 12:41 UTC
NWJS Version : 0.46.0-sdk
Operating System : OSX

### Expected behavior

Don't crash.

### Actual behavior

<img width="912" alt="Screenshot_2020-05-21_at_14_35_24" src="https://user-images.githubusercontent.com/538058/82559693-5b61cd00-9b70-11ea-95d8-140c9f8dc237.png">

### How to reproduce

1. Open app.
2. Register web worker. 
  ```
  self.onmessage = e => console.log(e);
  self.postMessage('OK');  
  ```
3. `nw.Window.get().reload()`
4. Wait 5-20s.

### More info

- tested on 0.45.4 - 0.46.0 with same result 
- `nw.Window.get().reloadDev()` => `TypeError: nw.Window.get(...).reloadDev is not a function`

**Comment by f3l1x** [comment] 2020-05-22 17:33
Today it just crashed using Web Worker without redirect. :-/

**Comment by elpeleq42** [comment] 2020-05-22 23:04
can reproduce on windows 10, also I had reported that before aswell(in an issue reporting crashes caused by worker threads)

**Comment by rogerwang** [comment] 2020-05-23 01:04
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by f3l1x** [comment] 2020-05-24 20:29
Hey @rogerwang. Here is MVP, https://github.com/webkitty/playground/tree/master/nwjs/bugs/7487-web-worker. 

1. `npm install`
2. `npm run dev`
3. Click to button until app crashed (about 3-5x times).

**Comment by rogerwang** [comment] 2020-05-30 10:06
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed** 2020-05-30 10:05 UTC

**Comment by f3l1x** [comment] 2020-06-09 14:10
Confirmed! It works now. Thank you.

**Comment by xland** [comment] 2022-02-17 06:05
This issue also happens on 0.61.0.0
@rogerwang
