### ISSUE TITLE
High CPU usage on OSX

### ISSUE THREAD

**Issue by kessiler** [nwjs/nw.js#4508] opened 2016-03-07 08:45 UTC
I'm running the porpcorntime.sh in their last version.
nwjs helper is using almost 100% CPU.

<img width="659" alt="screen shot 2016-03-07 at 2 30 56 am" src="https://cloud.githubusercontent.com/assets/4087757/13564117/d6fb79e0-e40c-11e5-9b06-2eb722da2adf.png">

What was I doing? I was just watching some tv series.
As you can see above to reproduce this issue you may need to wait a half hour. (take a look the CPU Time - it's the third column)

**Comment by ghostoy** [comment] 2016-03-08 07:41
@kessiler Which version of NW.js are you using?

**Comment by kessiler** [comment] 2016-03-08 08:22
v0.12.2

**Comment by ghostoy** [comment] 2016-03-08 10:39
It should be fixed in 0.12.3+.

**Comment by kessiler** [comment] 2016-03-11 19:00
thanks @ghostoy, will try to update and then bring a feedback!

**Comment by ghostoy** [comment] 2016-03-14 07:08
oh, it's said to be fixed in 0.12.2 in some cases. Not 0.12.3. Seems that it didn't fix for your case. I suggest you can try 0.13.0, which is totally re-implemented base on Chrome app and should not having such issue.

**Comment by Christywl** [comment] 2017-04-26 05:23
@kessiler , as ghostoy said, do you try the newer nwjs build, is this issue still reproduced on the latest nwjs ?

**Comment by Christywl** [comment] 2017-05-04 08:05
I can't reproduce your issue, my CPU usage:
<img width="1280" alt="4508" src="https://cloud.githubusercontent.com/assets/20039821/25694765/bc0fb4ec-30e2-11e7-8100-3aad5d289451.png">

**Comment by Christywl** [comment] 2017-10-11 04:29
@rogerwang , this is similar to #5152 , could we close this and track in #5152 ?

**Comment by rogerwang** [comment] 2017-10-11 04:34
Yes. They are duplicates. Thanks.

**Closed by rogerwang** 2017-10-11 04:34 UTC
Labels: needinfo
