### ISSUE TITLE
SSL and Client-Certificates

### ISSUE THREAD

**Issue by sinotitan** [nwjs/nw.js#893] opened 2013-07-19 03:07 UTC
Hi all, I'm using NW.I cannot access web pages(https,ssl) that request for a client certificate which on IE and Chrome would popup a window asking to choose the certificate to use if any and then the site loads, when I try to browse a https page like that on the nw it simply doesn't go anywhere, no errors, nothing.
Is what I'm trying to do supported at all?

Chrome says: "Select a certificate to authenticate yourself to {URL}"
IE Says: "Select a Certificate"

**Comment by ratones** [comment] 2015-01-12 12:06
I see that since v0.11.1 there is a new  option in package.json - 'additional_trust_anchors'. According to wiki, we can add a list of PEM-encoded certificates to allow connecting to services using a self-signed certificate. 
I converted my pfx file to PEM-encoded and copied the content of .pem file to package.json, but nothing happened. Am I missing something? Does anyone had some success using this new feature?
Or I am on a totally wrong track...

**Comment by fancycode** [comment] 2015-01-12 12:12
@ratones: how does your `package.json` look like? The PEM-encoded certificate should be added as

```
"additional_trust_anchors": [
    "-----BEGIN CERTIFICATE-----VeryLongBase64EncodedCertificateData-----END CERTIFICATE-----"
]
```

**Comment by ratones** [comment] 2015-01-12 13:06
well, i haven't noticed the brackets... In rest i just copied the content of the generated .pem file and added the line feed character wherever i found one, including in the base64encoded data. Since my pfx is password protected, It includes other stuff, like -----BEGIN RSA PRIVATE KEY----- and some other descriptions which i'm not sure are necessary...(Bag Attributes\n    localKeyID: 01 00 00 00\n, etc etc); Also, my .pem file contains two certificates, i guess one of them is the server certificate... 
I really feel like i'm going blind here...

**Comment by fancycode** [comment] 2015-01-16 08:52
You should only need to include the server certificate itself (between `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`, without line breaks).

**Comment by ratones** [comment] 2015-01-18 07:04
I tried every possible combinations, nothing seems to work... At the moment i'm using a proxy for my requests and it is working fine. The proxy is configured with all SSL options that I need. I was looking for a  "cleaner" solution...

**Comment by thojansen** [comment] 2015-02-03 20:25
@rogerwang any news here :smile: ?

**Comment by rogerwang** [comment] 2015-02-04 05:02
@thojansen, will try to fix this before 0.12.0 release.

**Comment by thojansen** [comment] 2015-04-24 15:31
still open @rogerwang, right?

**Comment by rogerwang** [comment] 2015-04-25 13:14
@thojansen yet and sorry to miss it in 0.12.0. I found it much easier to be supported in NW13 because we are migrating to a new architecture in v13. The first alpha version of it is expected to be released in early May. I'll see this feature in that version.

btw, do you happen to have a simple case to test this feature? Thanks in advance.

**Comment by thojansen** [comment] 2015-04-28 07:58
@rogerwang i have set up a repository to test everything https://github.com/thojansen/client-certificates 
- creates CA, signed server and client certificate
- manually import client certificate into system keystore (different on each OS)
- runs node.js server on https with validation of client certificate
- chrome shows popup to select relevant client certificate (popup can be avoided via specific rules or group policies, see http://scn.sap.com/community/windows/blog/2014/01/30/avoid-certification-selection-popup-in-chrome)

**Comment by rogerwang** [comment] 2015-04-28 09:36
@thojansen great. It should be very helpful.

**Comment by rogerwang** [comment] 2015-04-28 13:08
btw @thojansen what features of NW.js are you currently using? I'm asking because the NW12 features are being ported to a new architecture in NW13 and maybe we could use the first alpha version with the fix of this issue to test your application, see also https://groups.google.com/d/msg/nwjs-general/A7VpwOztU_s/Tg1L6nS2RBsJ

**Comment by thojansen** [comment] 2015-04-28 15:05
right now we are only running a client webserver and use NTLM authentication to our exchange server, but the plan would be to make our current web application native in case we can use client certificates. Therefore it should be quite easy for us to check out early version of NW13 and provide some feedback here.

**Comment by rogerwang** [comment] 2015-04-29 17:04
@thojansen I can confirm it's fixed in the nw13 branch. The binary & source code of the first alpha release will be available in early May.

**Comment by thojansen** [comment] 2015-04-30 07:11
sounds awesome, we will try this out and give you feedback. if we can render pages accepting client certificates, this would be huge for us (ideally without a popup).

**Comment by rogerwang** [comment] 2015-04-30 11:15
@thojansen if you want to hide the popup, then how should the client certificate to be selected?

**Comment by thojansen** [comment] 2015-04-30 11:23
@rogerwang having the option to specify rules would be awesome.. usually via issuer or cn .. http://www.chromium.org/administrators/policy-list-3#AutoSelectCertificateForUrls

**Comment by xland** [comment] 2015-05-07 10:42
我也在关注这个问题，再过几天就到五月中旬了，early may马上就要逝去了呢。

**Comment by Bryan-Turek** [comment] 2015-05-07 22:26
This will be great to have. Still waiting on that NW13 Release :+1: :)

**Comment by xland** [comment] 2015-05-10 08:36
嘿~王总~
@rogerwang 不知道什么时候更新到V0.13啊~
感激....

**Comment by rogerwang** [comment] 2015-05-11 02:19
Please see v0.13.0-alpha0 here https://groups.google.com/d/msg/nwjs-general/IqfH1RXNGlw/2PgeRGHO-B4J

It supports this feature now.

**Comment by rogerwang** [comment] 2015-05-11 02:19
@xland please use English only here, as the comment should be readable by most users.

**Comment by thojansen** [comment] 2015-05-11 03:49
Awesome :tada: .. the first test on our internal network already worked. I am now presented with the "select a certificate popup" and the content is loaded. This is really huge. Any chance to get the auto-selection working? We have some pages where this popup is now presented 5-10 times for each page load.

**Comment by xland** [comment] 2015-05-12 11:02
When I use google chrome to access a "https" website (wich require two way certificate),
google chrome ask me to select a  certificate.
When I select my certificate,google chrome ask me to "continue(not safe)"
![1](https://cloud.githubusercontent.com/assets/2980915/7585862/4df111ba-f8d9-11e4-8ce0-d1c460fd57b8.png)

When I use nwjs-v0.13.0-alpha0-win-ia32
"nwjs-v0.13.0-alpha0-win-ia32" only ask me to select a certificate
and then ...
![2](https://cloud.githubusercontent.com/assets/2980915/7585868/5af24f32-f8d9-11e4-99fb-1a30b1899237.png)



What can I do,Help me~

**Comment by thojansen** [comment] 2015-05-12 11:14
Generally, you would still need to sign the certificate using your own certificate authority (CA). This CA needs to be imported into your OS keychain and needs to be trusted. Then it should work.
https://github.com/thojansen/client-certificates

**Comment by xland** [comment] 2015-05-12 11:38
thank you 
but,I can't let my users to run "client-certificates" tools 
......

**Comment by wealeson** [comment] 2015-05-12 11:42
I used usbkey, and popup select a certificate, and input usbkey's password,BUT when I want to go next step,nwjs No response, and need positive closing.

use OS certificate, all is normal, what's wrong with use USBkey?

**Comment by thojansen** [comment] 2015-05-12 11:43
@xland did you try the "ignore-certificate-errors" switch from https://github.com/nwjs/nw.js/wiki/Command-line-switches?

**Comment by xland** [comment] 2015-05-12 12:07
@thojansen 
Thank You!!!
It works!!!
["chromium-args": "--ignore-certificate-errors",]

But not work with a USB Key
Just like @wealeson  said!

**Comment by wealeson** [comment] 2015-05-12 13:29
use certificate in usbkey nwjs no response,need positive closing.
some one help me~~@thojansen @rogerwang

**Comment by xland** [comment] 2015-05-13 00:36
I have the same question with @wealeson

**Comment by rogerwang** [comment] 2015-05-13 05:12
@thojansen the group policy should be supported. Note that the policy setting paths are the same with Chromium, not Chrome. e.g.  We only tested it with Linux.

Here lists the difference between Chromium and Chrome:

```python
  # The prefix of key names in config determines which writer will use their                                                                                                                   
  # corresponding values:                                                                                                                                                                      
  #   win: Both ADM and ADMX.                                                                                                                                                                  
  #   mac: Only plist.                                                                                                                                                                         
  #   admx: Only ADMX.                                                                                                                                                                         
  #   none/other: Used by all the writers.                                                                                                                                                     
  if '_chromium' in defines:
    config = {
      'build': 'chromium',
      'app_name': 'Chromium',
      'frame_name': 'Chromium Frame',
      'os_name': 'Chromium OS',
      'win_reg_mandatory_key_name': 'Software\\Policies\\Chromium',
      'win_reg_recommended_key_name':
          'Software\\Policies\\Chromium\\Recommended',
      'win_mandatory_category_path': ['chromium'],
      'win_recommended_category_path': ['chromium_recommended'],
      'admx_namespace': 'Chromium.Policies.Chromium',
      'admx_prefix': 'chromium',
      'linux_policy_path': '/etc/chromium/policies/',
    }
  elif '_google_chrome' in defines:
    config = {
      'build': 'chrome',
      'app_name': 'Google Chrome',
      'frame_name': 'Google Chrome Frame',
      'os_name': 'Google Chrome OS',
      'win_reg_mandatory_key_name': 'Software\\Policies\\Google\\Chrome',
      'win_reg_recommended_key_name':
          'Software\\Policies\\Google\\Chrome\\Recommended',
      'win_mandatory_category_path': ['google', 'googlechrome'],
      'win_recommended_category_path': ['google', 'googlechrome_recommended'],
      'admx_namespace': 'Google.Policies.Chrome',
      'admx_prefix': 'chrome',
      'linux_policy_path': '/etc/opt/chrome/policies/',
    }
```

**Comment by xland** [comment] 2015-05-13 06:28
I can not understand what @rogerwang said

**Comment by xland** [comment] 2015-05-13 06:28
I can not understand what @rogerwang said

**Comment by rogerwang** [comment] 2015-05-13 06:36
@xland , my previous comment is answering the question here in my conversation with Thomas (not yours) https://github.com/nwjs/nw.js/issues/893#issuecomment-100755996

**Comment by thojansen** [comment] 2015-05-13 07:54
ok, do you know where i could define the default group policy to be used by nwjs in an app?

**Comment by rogerwang** [comment] 2015-05-13 08:11
@thojansen in windows:  Software\Policies\Chromium\AutoSelectCertificateForUrls
in linux: /etc/chromium/policies/managed/

**Comment by rogerwang** [comment] 2015-05-19 06:31
close as fixed in 0.13.0-alpha0

**Closed by rogerwang** 2015-05-19 06:31 UTC

**Comment by hxzqlh** [comment] 2015-09-14 09:14
for my case, I tried this tutorial and it can successfully do a HTTPS POST request:

```
data = '{"protocols": ["5.2.6"], "user": "'+ $scope.user.name + '","password":"' + $scope.user.pwd +'"}'; 
 
var https = require('https');
var options = { 
          host: '192.168.10.113',
          port: 443,
          path: '/mediawise/auth',
          method: 'POST',
          rejectUnauthorized: false,
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Content-Length': data.length
          }   
};  

var req = https.request(options, function(res) {
    console.log("statusCode: ", res.statusCode);
    console.log("headers: ", res.headers);

    res.on('data', function(d) {
            process.stdout.write(d);
    }); 
}); 

req.on('error', function(e) {
     console.error(e);
}); 

req.write(data);
req.end();
```

**Comment by yaphone** [comment] 2019-05-09 16:52
+1 for Client-Certificates support
