### ISSUE TITLE
snapshot not load after refresh [$5]

### ISSUE THREAD

**Issue by withinthefog** [nwjs/nw.js#3388] opened 2015-04-20 09:28 UTC
Refresh page in nwjs 0.12.1 will Cause the snapshot to fail.

Here is the code to reproduce the Scenario:

package.json:

```json
{
  "name": "nw-refresh",
  "main": "index.html"
}
```

index.html:

```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<script src="app.js"></script>

</body>
</html>
```

app.js:
```javascript
require('nw.gui').Window.get().evalNWBin(null, 'snapshot.bin');
var lib = require('./lib');

try {
    console.log('calling snapshot function from web...');
    echoInSnapshot();
} catch (e) {
    console.error('error calling snapshot function:', e.stack)
}

lib.callSnapshot();
```

lib.js:

```javascript
exports.callSnapshot = function () {
    try {
        console.log('calling snapshot function from node...');
        echoInSnapshot();
    } catch (e) {
        console.error('call snapshot from node error:', e.stack);
    }
};
```

snapshot.js:
```javascript
function echoInSnapshot() {
    console.log('in snapshot function')
}
```

Compile the snapshot.js using the command:
```
nwjc snapshot.js snapshot.bin
```

Start the nw.app, the log from app.js is collect, but if I hit the refresh(or refreshDev) button, there will be a `RefrenceError` says `echoInSnapshot is not defined`.

Also, calling snapshot functions from node context(like the code in lib.js above) will cause a `RefrenceError echoInSnapshot is not defined`. But in previous version(0.11.x), the functions in snapshot can be called Directly from a node context.

**Comment by liyingzh** [comment] 2015-04-22 05:53
The refresh probelem is not reproducble on nwjs-v0.12.1-linux-x64.

nwjc uses code cache to write binary.bin, As v8 preserve code compiled in one context to use it in another context, the code has to be context-independent.
While nwsnapshot uses custom start-up snapshot which is not much different than V8's native scripts executed to initialize Javascript globals, so the functions in snapshot can be called everywhere.

**Comment by mscreenie** [comment] 2015-05-06 09:56
+1 reproducible on windows 8.1 . Trying to reload the app while its open i can reproduce this error.

**Comment by mscreenie** [comment] 2015-05-07 20:08
I've reproduced this on Windows 7 btw. I'm wondering why its not reported by more people? I'll recheck my app code.

**Comment by withinthefog** [comment] 2015-05-08 02:50
@mscreenie @liyingzh thanks for reply. 

This issue also happened on OS X.

**Comment by mscreenie** [comment] 2015-05-09 21:09
No problem. I've noticed that the file is not loaded inside dev tools network tab, don't think it would show up in dev tools perhaps its loaded by io.js

**Comment by mscreenie** [comment] 2015-05-11 05:54
No problem.

 I've noticed that the file is not loaded inside dev tools network tab, don't think it would show up in dev tools perhaps its loaded by io.js 

perhaps @rogerwang has fixed this in nwjs 13 , ill check, but would be good to get a fix for 12.1 as its the preferred version of release right now.

**Comment by rogerwang** [comment] 2015-05-11 06:45
will fix this in next 0.12 version.

**Comment by mscreenie** [comment] 2015-05-11 13:31
Thanks roger! Also glad to see your decision on refracting code into sdk and distribution builds. Good decision. Any idea on an eta for 12.2? Cheers.

**Comment by mscreenie** [comment] 2015-05-11 13:31
Thanks @rogerwang ! Also glad to see your decision on refracting code into sdk and distribution builds. Good decision. Any idea on an eta for 12.2? Cheers.

**Comment by mscreenie** [comment] 2015-05-14 13:15
Thanks @rogerwang ! A bit off topic - glad to see your decision on refracting code into sdk and distribution builds for nw13. Good decision.

Any idea on an eta for 12.2? Cheers.

**Comment by rogerwang** [comment] 2015-05-19 06:42
It's expected to be released in this week.

**Comment by withinthefog** [comment] 2015-05-19 07:57
Thanks @rogerwang

**Comment by mscreenie** [comment] 2015-05-21 09:44
Excellent @rogerwang . Thanks for the update.

**Comment by rogerwang** [comment] 2015-05-21 14:11
I found that when you keep devtools closed the code works well. Change snapshot.js to something like: document.write(Date.now()) to workaround the windows console issue.

The reason is that v8 won't load the serialized code blob when debugger is attached: https://github.com/nwjs/v8/blob/nw12/src/compiler.cc#L1291

**Comment by mscreenie** [comment] 2015-05-21 15:13
I'll test this, but if I remember correctly it would not be called, ill see if having devtools closed makes a difference.

**Comment by mscreenie** [comment] 2015-05-21 15:29
Yep, when dev tools is closed snapshot is loaded. Makes debugging a little harder but then again I only compiled a snapshot when distributing the package.

**Comment by legionsra** [comment] 2015-07-09 18:48
this is still happening. i Thought it was a problem of loading pages via Javascript but is definitely this the problem.
Avoid the opening devtools should not be the final solution but a temporary workaround. Please consider a fix for the next version.
Tested today with nwjs v.12.2. I will test it without devtools soon.

**Comment by legionsra** [comment] 2015-07-10 01:22
Tested, that was exactly the problem. without devtools bin code runs perfectly.
This has to be fixed anyway for the next version.

**Comment by mscreenie** [comment] 2015-07-16 19:57
Demanding that the issue should be fixed for the next version isn't going to make it fix faster and it's not the right way to request bug-fixes.

Considering roger is the sole maintainer of this project and likely has other commitments. I would use a softer approach and maybe attach a bounty to this bug.

**Comment by fritx** [comment] 2016-01-10 09:08
Any progress on this?
Luckily this still works with devtools closed ;)

**Comment by rogerwang** [comment] 2016-01-15 04:42
The 'snapshot', which is the compiled binary code of JS, is now supported by a more flexible method: http://docs.nwjs.io/en/latest/References/Window/#winevalnwbinframe-path

It allows you load the compiled binary after reload.

**Closed by rogerwang** 2016-01-15 04:42 UTC
Labels: bounty
