### ISSUE TITLE
DevTools detached from target nw 0.11.x

### ISSUE THREAD

**Issue by nrako** [nwjs/nw.js#2738] opened 2014-12-03 19:19 UTC
When loading some very specific js script in nw 0.11.x, I always end-up with the Dev Tools "Detached from the target":
![screen shot 2014-12-03 at 20 04 47](https://cloud.githubusercontent.com/assets/425397/5286827/ebf4500a-7b27-11e4-8508-61069907e20e.png)

However that works in nw 0.10.5

I've made a zip which contains an minimal sample app. The script loaded is nothing special it's a browserify build of a file which load the moment lib. I had the same issue when requiring other lib like react, but others are just fine. I'm lost...

src: https://www.dropbox.com/s/evpdlcfm6oyqdie/debugnw.zip?dl=0

nw: 0.11.2
os : mac (darwin)
##

**Comment by tunderdomb** [comment] 2015-04-05 03:15
I've came across this numerous times before with various versions, but suddenly It doesn't seem to disappear anymore. The problem persists. 
I tried these versions, they all reproduce this issue: 

- node-webkit-v0.11.5-win-x64
- nwjs-v0.12.0-win-x64

also, there are no source maps in my code. Even when I run a pure html page, it happens.

**Comment by 1j01** [comment] 2015-05-23 23:17
+1 I have run into this at least one time even after [limiting](https://github.com/1j01/project-nexus/commit/91eb91544714d19259ae95b124a4820fe5baab5f#diff-f3969b6ef36ab0405c83f35b365ffe81R25) the number of instances of [an entire operating system's styles converted to browser CSS with inline source maps](https://github.com/1j01/elementary.css) to one.
(I forgot that the dark styles contain the light styles as a base!)
*nwjs v0.12.1 (win x64)*

**Comment by adam-lynch** [comment] 2015-05-24 18:52
+1. See #3501 and #3380

**Comment by jthrilly** [comment] 2015-07-10 14:35
:+1: Same issue here, caused by a large concatenated stylesheet. OSX 10.11, nwjs v0.12.2

**Comment by orther** [comment] 2015-08-21 14:33
Same issue here caused by inline source maps of large concatenated stylesheet. If I create separate source map files it works. OSX 10.10.4, nw.js v0.12.3

**Comment by tshinnic** [comment] 2015-10-07 00:14
Thank you for figuring out the problem point.   Deleting the last source line containing the inline source map allowed me to run nw.js again (v0.12.3/Win10).  Difference in size of .js was not that much - was 200kb now 71kb - kinda hard to believe that is so fatal.  Have tried again now generating a separate .map file and that at least starts...

I'm seeing a bunch of Chromium bug reports starting May about slow startup...  but I can't find any "it just stopped working" bugs.

Interesting is that nw.js v0.13.0-alpha3 using Chromium 44.0.2303 didn't have the same problem?!  At least not with the same files.

**Comment by zhaowweny** [comment] 2015-10-15 03:13
I saved some images by localStorage, and have the same issue. Now I clear my localStorage, it's fine. These images's url format is data:image/png;base64,.....

**Comment by YahyaElharony** [comment] 2016-11-04 06:44
I have this problem too.
Actually, I am a fairly new in NodeJS and I didn`t make anything complicated, just wanna open a simple index.js contains some basics to create a server.
Can anyone help me please? :D

**Comment by rogerwang** [comment] 2016-11-04 12:11
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.

**Closed by rogerwang** 2016-11-04 12:11 UTC

**Comment by naffan2014** [comment] 2016-12-07 12:47
not sovle yet on node-7.2.1, on mac
