### ISSUE TITLE
0.23.7/0.24.0 - app will crash on start with improper child_process spawn path

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6056] opened 2017-07-25 23:34 UTC
OSX -
Crash on start occurs whereas earlier builds would give an error but stay alive.
eg: 0.17.6 gives  Uncaught Error: spawn C:\sqlite\sqlite3.exe ENOENT
Obviously for OSX this path is a Windows path but later build will just crash rather than give an error.

Win -
Had this happen on Win as well (seems to occur from 0.18.0 onward) when following was used -
C:\sqlite\\sqlite3.exe - again a rubbish path but nwjs should at least give some error handling.

Test project attached for OSX.

[crashy.zip](https://github.com/nwjs/nw.js/files/1175077/crashy.zip)

**Comment by Christywl** [comment] 2017-07-26 01:42
I can reproduce this issue on Mac with nwjs-sdk-v0.23.7. Crash happens when the app starts.

**Comment by rogerwang** [comment] 2017-07-26 04:42
Will fix this in 0.24.1 since it's not a regression in 0.24.0.

**Comment by rogerwang** [comment] 2017-08-31 05:48
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-08-31 05:48 UTC
Labels: bug, P1, test-todo, triaged
