### ISSUE TITLE
macos api error

### ISSUE THREAD

**Issue by Hua-King** [nwjs/nw.js#7880] opened 2022-05-10 03:43 UTC
![lQLPDhtoTQBcXY_Mgs0DT7CuvwkRudUWxgJ7j0LogD4A_847_130](https://user-images.githubusercontent.com/103172877/167538270-38d707ef-61ce-41dc-ba3e-5d50f5c179d9.png)
please help me. how to fixed?
on windows, the api is ok.
but on macos, the api is bad.
app build with nw.js on windows and macos.

**Comment by bluthen** [comment] 2022-07-27 21:05
- Does it have the same issue with chrome?
- Is the clock on the mac accurate, I think you can get this with bad clock.
-  what versions of nw are you using?
  - I believe it uses certificate authorities that are in the OS. There might be a certificate authority or two that are different. I think this is changing starting in chromium 105.

- https://www.chromium.org/Home/chromium-security/root-ca-policy/

**Comment by ayushmxn** [comment] 2022-08-05 21:01
Closing this since unable to reproduce your issue. Ping me here with steps to reproduce and I'd be happy to reopen this.

**Closed by ayushmxn** 2022-08-05 21:01 UTC
Labels: needinfo
