### ISSUE TITLE
[nw13] user-agent field in package.json is being ignored.

### ISSUE THREAD

**Issue by bgSosh** [nwjs/nw.js#3882] opened 2015-10-09 12:54 UTC
We have user-agent set to a custom value in package.json, however the user agent string sent to the server remains as: 

     Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36

Version nw0.13.0 alpha3

**Comment by dogancelik** [comment] 2015-10-15 10:02
Possibly a duplicate of #2850

**Comment by bgSosh** [comment] 2015-10-15 11:43
Strange - it's working fine for us on 0.12.3.

**Comment by rogerwang** [comment] 2015-11-10 02:50
Thanks for reporting. This is just fixed in git. Will be available in the next alpha release or live build.

**Closed by rogerwang** 2015-11-10 02:50 UTC
