### ISSUE TITLE
Random crash involving boundsKey_

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#6553] opened 2018-04-05 16:01 UTC
NWJS Version : 0.28.1
Operating System : Windows 7 64-bit

### How to reproduce

We've had reports from users, and seen in our crash analytics, some unhandled exceptions involving "boundsKey_". This affects the desktop download for Construct 3, which uses NW.js. Unfortunately the crash doesn't have a very helpful stack - it just looks like this:
```
TypeError: Cannot read property 'boundsKey_' of undefined
at Bounds.get [as left] (extensions::app.window:55:40)
at NWWindow.get (extensions::nw.Window:548:43)
```
I presume this corresponds to a `nw.Window.get()` call, but it's not clear why this call would crash. Our own source code does not use a property named `boundsKey_`. It only appears to be in the Chromium source here: https://github.com/nwjs/chromium.src/blob/45be0261c5a04cc38dead115740a8a6f7e6958a7/extensions/renderer/resources/app_window_custom_bindings.js#L55
This line also corresponds to the "as left" and line 55 parts of the stack.

So presumably `nw.Window.get()` internally retrieves some window bounds which in some edge case can fail. Perhaps this could be worked around? We've only seen this in NW.js 0.28.1, we'll distribute an update soon to check the latest version.

**Comment by Christywl** [comment] 2018-04-09 03:03
Please provide a ready sample to reproduce this. And could you please upload the dump file?

**Comment by AshleyScirra** [comment] 2018-04-09 11:09
I'm afraid I can't reproduce it myself, it's a report from one of our users.

**Comment by AshleyScirra** [comment] 2018-05-24 23:31
We're still getting reports of this, e.g.: https://www.scirra.com/forum/construct-3-desktop-build-error_t204010

Can you not at least try to add some extra guards based on the error message? i.e. check whatever object reference is valid before accessing `boundsKey_`.

**Comment by rogerwang** [comment] 2018-05-25 01:43
Yeah, will workaround it like that.

**Comment by drg8** [comment] 2018-05-25 04:50
@AshleyScirra,
I just installed latest version of Node.js and even copied latest version of nwjs libraries in the Construct 3 desktop folder, but the error is still there. 

**Solution**
I ran Construct a couple of times with and without running the game, so I found that the issue is related to "Dialog" Preview option under Construct 3's settings. so I changed it back to "Popup window" and I no longer have that error :D 

**To reproduce the error:**

- select "Dialog" option for preview under Construct settings.
- preview the game.
- close preview window and then close Construct.

p.s. idk if this will work for you guys, but I tried it 4-5 times and Construct crashed and I got the error message.

**Comment by AshleyScirra** [comment] 2018-05-25 15:57
I can reliably reproduce this now using the steps at https://github.com/Scirra/Construct-3-bugs/issues/1631
You can use our NW.js app to reproduce it: https://www.scirra.com/forum/construct-3-desktop-build-beta-currently-win64-only_t199344

I've tried to debug it but even with "pause on caught exceptions" it doesn't break on the exception. I guess it's because the NW.js code is extension code or something. It does however point out this code:

```js
Object.defineProperty(Bounds.prototype, 'left', {
  get: function() {
    return appWindowData[privates(this).boundsKey_].left;  // <-- exception
  },
  set: function(left) {
    this.setPosition(left, null);
  },
  enumerable: true
});
```

So presumably there is some edge case where `appWindowData[privates(this).boundsKey_]` returns undefined.

**Comment by rogerwang** [comment] 2018-05-25 23:09
We worked around it in git. Please try https://dl.nwjs.io/live-build/nw30/05-25-2018/a8197eb-27e602c-b58e580-00b3abb/v0.30.6/

**Comment by AshleyScirra** [comment] 2018-05-29 12:09
Now it crashes with a different error:
```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (extensions::nw.Window:145)
    at Object.handleRequest (extensions::binding:64)
    at Object.<anonymous> (extensions::binding:377)
    at NWWindow.get (extensions::nw.Window:592)
```
It looks like we're accessing `zoomLevel` in order to save the current zoom level on exit, since our app lets the user adjust it. The crashing method appears to be the `[0]` read here:
```js
apiFunctions.setHandleRequest('getZoom', function() {
    return sendRequest.sendRequestSync('nw.currentWindowInternal.getZoom', arguments, this.definition.parameters, {})[0];
  });
```
The steps to reproduce this in our app involves changing the settings so it creates an iframe instead of a popup window. So this may be related to creating and then removing an iframe leaving the NW window methods in a bad state.

**Comment by AshleyScirra** [comment] 2018-11-06 15:11
We are still getting reports of the previously noted error (e.g. https://github.com/Scirra/Construct-3-bugs/issues/2258).

**Comment by AshleyScirra** [comment] 2018-11-20 11:41
We are still getting reports of the previously noted error, e.g. https://github.com/nwjs/nw.js/issues/6553

Users are reporting this happens when closing the app, so maybe it's something to do with the closing code.

**Comment by rogerwang** [comment] 2018-12-04 12:32
Closing this as the original error is fixed. See #6881 for the new issue.

**Closed by rogerwang** 2018-12-04 12:32 UTC
Labels: needinfo

**Comment by zaggerj** [comment] 2019-05-07 04:02
can you solved this problem?
