### ISSUE TITLE
window close event doesn't fire

### ISSUE THREAD

**Issue by Gimmeaphatbeat** [nwjs/nw.js#4972] opened 2016-06-13 14:42 UTC
OS: Windows 8.1
Version: 0.15.2

This event has stopped working. 
Used to work in 0.15.0
Haven't tested 0.15.1.

http://nwjs.readthedocs.io/en/latest/References/Window/#event-close

**Comment by ghostoy** [comment] 2016-07-11 02:11
@Gimmeaphatbeat I can't reproduce the issue with 0.15.2 and latest 0.15.4. Could you post a sample app for reproduction?

**Comment by ghostoy** [comment] 2016-07-25 05:01
Close it since not receiving feedbacks in 2 weeks. Please reopen it if you have further comments.

**Closed by ghostoy** 2016-07-25 05:01 UTC
