### ISSUE TITLE
DesktopCaptureMonitor: only screens being monitored when specify both screens and windows

### ISSUE THREAD

**Issue by JakeLoo** [nwjs/nw.js#6437] opened 2018-02-01 04:11 UTC
NWJS Version : nw27.1 
Operating System : windows 10 x64

### Expected behavior

when using DesktopCaptureMonitor.start(screens: true, windows: true),
I'd expect seeing both screens and windows being monitored.

### Actual behavior

only screens being monitored and not windows.

![image](https://user-images.githubusercontent.com/2171134/35660754-c697abac-06c2-11e8-8a47-14e81e7955d3.png)

### How to reproduce

```
var dcm = nw.Screen.DesktopCaptureMonitor;
nw.Screen.Init()
dcm.on("added", function (id, name, order, type) {
  console.log(id, name, order, type);
});

dcm.on("removed", function (id) { });
dcm.on("orderchanged", function (id, new_order, old_order) { });
dcm.on("namechanged", function (id, name) { });
dcm.on("thumbnailchanged", function (id, thumbnail) { });
dcm.start(true, true);
```

we've a patch, if you're interested:
https://github.com/bebo/nwjs/commit/9859e11d6774d1cd1ce929342bb4ef42c92a6266

**Comment by Christywl** [comment] 2018-02-01 06:37
close as duplicate of #6417.

**Closed by Christywl** 2018-02-01 06:37 UTC
