### ISSUE TITLE
nwjc protect javascript and crash when devtools open

### ISSUE THREAD

**Issue by kkm** [nwjs/nw.js#6001] opened 2017-07-01 17:10 UTC
Hello,

Compile in `nwjc.exe --future index.js index.bin` then index.html:
`<script>nw.Window.get().evalNWBin(null, 'index.bin');</script>`
run in `nw --js-flags='--future' V:\Desktop\app_release .`

index.js:
`alert("XXX")` -->works well!

it crash and figure out.
index.js:
`function test(){}` --> CRASH!

cool its run but if I open in devtool then crash and log says
debug.log from nw:
> [0701/185819.647:WARNING:chrome_main_delegate.cc(569)] final extension: 
[0701/185825.361:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol.  (0x2ee6)

what does mean?

in nwjc sdk from 18.3 works very good in protect snapshot.

**Comment by Christywl** [comment] 2017-07-04 06:49
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.23.5. The app crashes after the devtools opens(`function test(){}` in `index.js`). But the log is different from the reporter's. The log on Linux:

```
[0704/144636.418227:WARNING:chrome_main_delegate.cc(569)] final extension:

(nw:5562): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Could not connect: Connection refused


#
# Fatal error in ../../v8/src/inspector/v8-debugger-script.cc, line 127
# Check failed: lineEnds.size().
#
#0 0x7fd819a42dc7 <unknown>
```

**Comment by kkm** [comment] 2017-07-04 12:27
it starts from 22.0 version until 23.5

**Comment by rogerwang** [comment] 2017-07-05 02:02
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-07-05 02:02 UTC
Labels: bug, P1, test-todo, triaged

**Comment by rogerwang** [comment] 2017-07-06 00:46
Please try this version: https://dl.nwjs.io/live-build/07-06-2017/nw23-ef6d067-faf54f4-bdcc2a7-759a6e8/v0.23.6/

**Comment by kkm** [comment] 2017-07-06 15:56
yeah finally works well thank you very much.

**Comment by dstiq** [comment] 2017-08-18 08:32
looks like this crash i have in my project
with logs 
[0818/112232.505:WARNING:chrome_main_delegate.cc(586)] final extension:
[0818/112254.137:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol.  (0x2ee6)

But its not about devtools. Its crash when i clicked some buttons, wich have onclick handlers, one of those have this:
 nw.Window.get().reloadIgnoringCache();
nwjs - v0.24.0

**Comment by dstiq** [comment] 2017-08-18 08:47
Actually that is changeLocation buttons and i have a func
