### ISSUE TITLE
the app crash when display big img

### ISSUE THREAD

**Issue by dalidong2009** [nwjs/nw.js#5487] opened 2016-11-17 07:05 UTC
nw version is 0.12.3
when display image bigger then 7000*5000, the app crash .
here is my test  image
![2014120107280906](https://cloud.githubusercontent.com/assets/8622414/20379411/21b6b632-acd7-11e6-9e9d-ea61c4cf8ab4.jpg)

**Comment by ghostoy** [comment] 2016-11-18 02:04
Does it crash with latest stable 0.18.7? And what's your OS?

**Comment by ghostoy** [comment] 2016-11-18 08:24
It might be related to #5453.

**Comment by ghostoy** [comment] 2016-11-23 03:01
Closed this issue as duplicate of #5453. Please reopen it if you see different.

**Closed by ghostoy** 2016-11-23 03:01 UTC
