### ISSUE TITLE
[0.24.0:DevTools] Uncaught Error during filtering network requests

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#6060] opened 2017-07-27 12:33 UTC
[16507:775:0727/152912.786924:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (109)

Steps to reproduce:

1 Open DevTools > Network Tab
2 Start typing in Filter input

Error is triggered only if there is a change in filtered list.

**Comment by Christywl** [comment] 2017-07-28 02:21
I can reproduce this issue on Linux with nwjs-sdk-v0.24.0. 
`./nwjs-sdk-v0.24.0-linux-x64/nw -url=https://google.com`, and open devtools, when click Network Tab, you will see this error in the terminal.
```

[7390:7390:0728/101819.596901:ERROR:desktop_window_tree_host_x11.cc(1159)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)

(nw:7390): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown or unsupported transport 'disabled' for address 'disabled:'
[7390:7390:0728/101825.447461:ERROR:CONSOLE(0)] "XMLHttpRequest cannot load https://chrome-devtools-frontend.appspot.com/serve_file/@c43eb10509d7219dc8a7f93c7fd8b7844d86601b/product_registry_impl/product_registry_impl_module.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-devtools://devtools' is therefore not allowed access. The response had HTTP status code 404.", source: chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@c43eb10509d7219dc8a7f93c7fd8b7844d86601b/&dockSide=undocked (0)
[7390:7390:0728/101825.447501:ERROR:CONSOLE(22)] "Empty response arrived for script 'https://chrome-devtools-frontend.appspot.com/serve_file/@c43eb10509d7219dc8a7f93c7fd8b7844d86601b/product_registry_impl/product_registry_impl_module.js'", source: chrome-devtools://devtools/bundled/inspector.js (22)
[7390:7390:0728/101825.447829:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (109)
[7390:7390:0728/101825.447846:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (109)
```
Can't reproduce on nwjs v0.23.7.

**Comment by rogerwang** [comment] 2017-07-28 07:14
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-07-28 07:14 UTC
Labels: bug, P2, triaged
