### ISSUE TITLE
0.12.0  Uncaught ReferenceError

### ISSUE THREAD

**Issue by icode** [nwjs/nw.js#2955] opened 2015-01-16 11:39 UTC
Uncaught ReferenceError: stream is not defined node.js:478 
 createWritableDummyStream   node.js:478
 (anonymous function)    node.js:573
 afterWrite net.js:756 

windows xp

0.12.0 

0.11.5 is ok

**Comment by rogerwang** [comment] 2015-01-16 12:10
This is duplicate of #2933

**Closed by rogerwang** 2015-01-16 12:10 UTC
