### ISSUE TITLE
App.dataPath returns default profile path instead of application path

### ISSUE THREAD

**Issue by vzamanillo** [nwjs/nw.js#4998] opened 2016-06-17 09:02 UTC
Nwjs 0.15.2
Ubuntu Linux 64 bit

In nw.js == 0.12.3 App.dataPath returned ~/.config/<name-in-manifest>
In nw.js > 0.12.3 App.dataPath returned ~/.config/<name-in-manifest>/Default (the default profile folder)

Is this intentional or it is a bug?

**Comment by vzamanillo** [comment] 2016-06-17 21:15
Related to #4696

**Comment by rogerwang** [comment] 2016-06-21 09:46
close as duplicate of #4696

**Closed by rogerwang** 2016-06-21 09:46 UTC
