### ISSUE TITLE
I use the nw.js 22.3 Windows32 program to open and will generate a temporary file on the C program almost hit. Every time you open it. Open C will be filled with many times.

### ISSUE THREAD

**Issue by gendew** [nwjs/nw.js#6246] opened 2017-10-30 11:57 UTC
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 22.3
Operating System : windows7

### Expected behavior

<!- What do you think should happen? ->

### Actual behavior

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by Christywl** [comment] 2017-10-31 01:18
Could you please provide a sample and steps to reproduce it?

**Comment by gendew** [comment] 2017-10-31 01:39
Because I have a relatively large package, I don't provide samples. Specific steps are, first of all, index.html, package.json and noede_modules these two files and a folder packaged into compressed packets, and then modify the suffix name changed to.Nw. Then use windows CMD to combine the nw.exe and the compressed package into a program. Finally, using Enigma Virtual Box, the nw.js file and all the programs are packaged into a program. I translated this passage through the translation software, and English is not very good.
![9w8k5r235x8 _twjg bsf](https://user-images.githubusercontent.com/24712645/32203608-60ff8eea-be1f-11e7-993d-571fd1858d45.png)

**Comment by gendew** [comment] 2017-10-31 02:16
What's wrong with this? Look at the picture
![f700e9ce7fb9ffdba89911a0f2691b7](https://user-images.githubusercontent.com/24712645/32204312-65d1bc8c-be23-11e7-9a17-765000479643.png)

**Comment by Christywl** [comment] 2017-11-01 01:48
Maybe you used the newer version than 0.22.3. Please update to the latest nwjs build. And you could also delete the app data folder in /User/<use name>/AppData/Local/<app name>.

Could you please post your package.json and index.html here?

**Comment by gendew** [comment] 2017-11-01 02:53
[index.zip](https://github.com/nwjs/nw.js/files/1432929/index.zip)

I downloaded and used the highest version of nw.js, but it turned out to be the same as the low version. Every time I open the program will take up C of disk space, the program shut down will release C of disk space, but not normally closed for example without closing the program directly close windows, restart the windows C disk is the memory will never be released. Please wrap up a program and observe the storage space of the C disk, and you will know the result.

我下载并使用了最高版本的nw.js ，但是结果还是和低版本一样。我每次打开程序将会占用C磁盘空间，程序正常关闭将会释放C磁盘空间，但是不正常关闭例如没有关闭程序直接关闭windows ，重新启动windows之后C磁盘被占用的内存永远不会被释放。请你打包一个程序然后观察C磁盘的存储空间你将会知道结果。

**Comment by Christywl** [comment] 2017-11-01 03:16
> Maybe you used the newer version than 0.22.3. Please update to the latest nwjs build. And you could also delete the app data folder in/User/<use name>/AppData/Local/<app name>.

This explains the error in your posted picture, not for this issue.

I'll check on my device with your sample.

**Comment by Christywl** [comment] 2017-11-03 08:27
It's a bug, and duplicate of #5208, close this. See https://github.com/nwjs/nw.js/issues/5208#issuecomment-341633712

**Closed** 2017-11-03 08:27 UTC
Labels: needinfo
