### ISSUE TITLE
OSX - 0.19 Flash needs manual intervention and control-click not working

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5548] opened 2016-12-13 22:18 UTC
0.19 (Chrome 55) will no longer run flash from HTML via embed or object tags (webview disappeared on Chrome 54 - 0.18) and requires control-click however I can not get this to happen.
Have attached a wee test app to demonstrate.
Tried dragging index.html onto browsers and got - 

Safari - said Click to use Flash. OK with embed/object tags.
Chrome 55 - just worked. OK with embed/object tags.
Chrome 56 (Canary) - just worked. OK with embed/object tags.
Chrome 57 (Canary) - got blocking/update dialogs. OK  with embed/object tags after update of flash. (23.0.0.185 to 24.0.0.186 - just worked thereafter)

![ccflash](https://cloud.githubusercontent.com/assets/11089335/21158733/474bfb24-c176-11e6-8d59-e148a2401796.jpg)

[PepperFlashTest.zip](https://github.com/nwjs/nw.js/files/650340/PepperFlashTest.zip)

**Comment by rogerwang** [comment] 2016-12-14 01:36
Interesting. We have a test case to make sure this feature works and it passed... https://github.com/nwjs/nw.js/tree/nw19/test/sanity/issue5068-flash-permission

Will see your case.

**Comment by ghostoy** [comment] 2016-12-16 02:34
The test case was run under `http:` protocol, because `chrome-extension:` was limited and can not be tested automatically.

**Comment by rogerwang** [comment] 2016-12-16 04:20
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment] 2017-11-20 07:11
This is a regression at least in 0.26. Reopen it.

**Comment by rogerwang** [comment] 2017-11-20 07:30
Ref #6216

**Comment by rogerwang** [comment] 2017-11-22 02:51
Close as the last comments are false alarm. And the test case was covered.

**Closed by rogerwang** 2017-11-22 02:51 UTC
Labels: bug, regression, test-todo
