### ISSUE TITLE
X-Cross-Origin is being enforced 

### ISSUE THREAD

**Issue by danielsokolowski** [nwjs/nw.js#7049] opened 2019-05-10 03:58 UTC
NWJS Version : nwjs-sdk-v0.39.0-beta1-win-x64, nwjs-sdk-v0.38.3-win-x64, nwjs-sdk-v0.37.5-win-x64
Operating System : Windows 2008 R2

### Expected behavior

Site referenced in <iframe> would load without being blocked.

### Actual behavior

www.thecse.com refused to connect, console error: 

	Refused to display 'https://www.thecse.com/en/listings/mining/generation-mining-limited' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Adding following to package.json does not help: 

	"chromium-args":" --disable-site-isolation-trials --disable-web-security --user-data-dir=./nwjs-user-data-dir --disable-sync --disable-background-networking --disable-component-update --enable-spell-checking"

### How to reproduce

- create a hello world nwjs app
- include `<iframe id='oQuoteIFrame' src='https://www.thecse.com/en/listings/mining/generation-mining-limited'></iframe>`
- load app, iframe is being blocked. 

![iframe blocked](https://user-images.githubusercontent.com/273413/57501737-a3d88080-72b6-11e9-8f7c-eab112e34200.png)

**Comment by danielsokolowski** [comment] 2019-05-10 04:06
I have tested with https://www.aequitasneo.com/en/single-security/ETHC which sends `X-Frame-Options: Deny` and that one does work, whereas https://www.thecse.com/en/listings/mining/generation-mining-limited which sends `X-Frame-Options: SAMEORIGIN`  fails. Full header dump below:

	Accept-Ranges: bytes
	Age: 0
	Cache-Control: public, max-age=1800
	Content-Encoding: gzip
	Content-Language: en
	Content-Type: text/html; charset=utf-8
	Date: Fri, 10 May 2019 04:05:32 GMT
	Etag: "1557460946-1"
	Expires: Sun, 19 Nov 1978 05:00:00 GMT
	Last-Modified: Fri, 10 May 2019 04:02:26 GMT
	Link: <https://www.thecse.com/en/listings/mining/generation-mining-limited>; rel="canonical",<https://www.thecse.com/en/node/216196>; rel="shortlink"
	Server: Apache
	Transfer-Encoding: chunked
	Vary: Cookie,Accept-Encoding
	Via: 1.1 varnish-v4
	X-Content-Type-Options: nosniff
	X-Drupal-Cache: HIT
	X-Frame-Options: SAMEORIGIN
	X-Generator: Drupal 7 (http://drupal.org)
	X-Powered-By: PHP/5.6.40
	X-Varnish: 427328969

**Comment by ffanny** [comment] 2019-05-11 02:06
I can reproduce it with nwjs-sdk-win-v0.38.1. 
With code `<iframe id='oQuoteIFrame' src='https://www.thecse.com/en/listings/mining/generation-mining-limited'></iframe>` and whether using `"chromium-args":" --disable-site-isolation-trials --disable-web-security --user-data-dir=./nwjs-user-data-dir --disable-sync --disable-background-networking --disable-component-update --enable-spell-checking"`,
the log is `Refused to display 'https://www.thecse.com/en/listings/mining/generation-mining-limited' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by danielsokolowski** [comment] 2019-05-14 20:04
Could core devs kindly confirm my sanity that this is indeed a bug?

**Comment by danielsokolowski** [comment] 2019-05-28 20:43
Humble Ping

**Comment by danielsokolowski** [comment] 2019-06-04 18:59
Ping

**Comment by rogerwang** [comment] 2019-06-05 01:04
Yes. This is a bug and will look to fix it soon.

**Comment by Dimtime** [comment] 2019-08-23 22:41
> 
> 
> Yes. This is a bug and will look to fix it soon.
maybe this can help:
https://github.com/electron/electron/issues/18940
for me this work: "chromium-args": "--disable-site-isolation-trials"

**Comment by Haris-Jamil** [comment] 2019-09-19 13:52
@rogerwang any update on this issue?

**Comment by rogerwang** [comment] 2019-11-13 10:42
The `X-Frame-Options` workaround should be used in an iframe with the `nwfaketop` property. So I'm closing this issue as it works as expected.

**Closed by rogerwang** 2019-11-13 10:42 UTC

**Comment by Andrew-Gee** [comment] 2022-12-03 10:31
This still happens for me, even with `nwfaketop nwdisable` attributes set on the iframe...

**Comment by hthetiot** [comment] 2022-12-06 08:30
> This still happens for me, even with `nwfaketop nwdisable` attributes set on the iframe...

Using webview instead of iframe, I believe is the solution here. Like that iframe behavior is respected.
