### ISSUE TITLE
Silent printing with win.print() for pdfs

### ISSUE THREAD

**Issue by juanchel** [nwjs/nw.js#5036] opened 2016-06-27 21:47 UTC
When I use win.print() it successfully prints silently in most cases, but when I try to print a pdf displayed in chrome's basic pdf viewer, the print dialog shows up - it is no longer silent and none of the options passed in are passed through.

nw.js version: v0.15.2, v0.15.4
OS: osx 10.11.4

**Comment by rogerwang** [comment] 2016-06-28 04:43
close as duplicate of #5002

**Closed by rogerwang** 2016-06-28 04:43 UTC

**Comment by rogerwang** [comment] 2016-06-28 12:34
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment] 2016-06-28 23:13
http://dl.nwjs.io/live-build/06-29-2016/nw15-cc83171-b33fad2-3ee2c58-8655cb9/v0.15.5/
