### ISSUE TITLE
don't work frameless and border-radius

### ISSUE THREAD

**Issue by marrokin** [nwjs/nw.js#7256] opened 2019-12-04 14:23 UTC
![image](https://user-images.githubusercontent.com/7069586/70149502-3a66f780-1676-11ea-8d2c-c58feca609de.png)

NWJS Version: 0.42.6
Operating System: Windows 10 1903

Rounded corners in the window

I tried to make an application with nwjs with rounded corners but what you see in the image appears, it does not work and a border appears in the window

```javascript
"js-flags": "--harmony_proxies",
   "window": {
     "width": 960,
     "height": 600,
     "frame": false,
     "toolbar": false,
     "transparent": true,
     "position": "center",
     "icon": "src / assets / icon.png"
   },
   "webkit": {
     "page-cache": true
   },
```
```css
html,
body {
   font-size: 16px;
   margin: 0;
   display: flex;
   flex-direction: column;
   width: 100vw;
   height: 100vh;
   flex: 1;
   border-radius: 2rem;
   overflow: hidden;
   background: transparent;
   -webkit-app-region: drag;
}

#app {
   flex: 1;
   margin: 0;
   padding: 0;
   background: silver;
}
```
```html
<html>
  <body>
    <div id="app">
      <span>WINDOWS 10 VER : 1903</span>
      <span>NWJS VERSION : 0.42.6</span>
    </div>
  </body>
</html>

**Comment by rogerwang** [comment] 2019-12-04 14:43
Does `--disable-features=nw2` make any difference there?

**Comment by marrokin** [comment] 2019-12-04 17:49
> Does `--disable-features=nw2` make any difference there?

that works! 😄 👍

**Comment by rogerwang** [comment] 2019-12-15 23:37
cc #7230

**Comment by rogerwang** [comment] 2019-12-30 12:01
close as duplicate of #7221

**Closed by rogerwang** 2019-12-30 12:01 UTC
