### ISSUE TITLE
When entry window minimized or hidden then application is slow

### ISSUE THREAD

**Issue by aretias-kr** [nwjs/nw.js#2928] opened 2015-01-14 09:07 UTC
I am making a notification application. 
So in the window is minimized or hidden state I need to create a notification window.

The notification window creation and animation works well.
But when the window is minimized or hidden works very slowly.

Exhibit different symptoms, depending on the version,
0.10.5 is slow when the minimum. It works well hidden.
0.11.5 is slow In both minimized and hidden.
##

**Comment by WolfspiritM** [comment] 2015-01-14 13:45
Can reproduce.
Having the same issue and can't find a workaround.
Have to use version 0.10.5 until this is fixed.

**Comment by aretias-kr** [comment] 2015-01-15 05:08
@WolfspiritM 
I will release app using version 0.10.5 with prevent minimize.
To prevent minimize, when minimize event occurs insert the following code.

```javascript
if (isWin()) {
    wind.on("minimize", function () {
        setTimeout(function () {
            wind.restore();
            wind.hide();
        }, 100);

        wind.hide();
    });
}
```
It makes minimize action works like "hidden"

**Comment by tommoor** [comment] 2015-01-15 06:58
I have also seen this issue on Mac, which platform are you working on?

**Comment by aretias-kr** [comment] 2015-01-15 07:07
@tommoor Actually I support multi-platform but, I've seen issue on only Windows 7 64bit. not also mac

**Comment by rogerwang** [comment] 2017-11-22 05:21
This should be working with latest version now. 

In 0.13 and later versions we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. This issue is closed as we believe it should be fixed. Please leave a message if it isn't and we'll reopen it.

**Closed by rogerwang** 2017-11-22 05:21 UTC
Labels: bug, regression, triaged

**Comment by victorcid** [comment] 2018-04-13 16:40
hi i´m having this issue with in the 0.29.4 this hapen when i tray to use a module tha has been compiled when is on plain js it works fine i´m guesing it has to do meabe with the frame 
  win.evalNWBinModule(null, './some.bin', './some.js');
this because i have inside a function on loop thrug setTimeout and when i do consol.log it sows where is coming from in the script but after minimize it displays the massage but not wher is coming from and also the interval time chanche a lot
