### ISSUE TITLE
Disable Window Snapping on Windows 10

### ISSUE THREAD

**Issue by thoughtspacewebsites** [nwjs/nw.js#4280] opened 2016-01-19 18:52 UTC
I'm using these instructions to set up a frameless window, and I made a separate "drag handle" that allows you to reposition the window wherever you want on the screen. 

https://github.com/nwjs/nw.js/wiki/Frameless-window

I'd like to disable the window snapping feature on Windows machines, because currently, if the user drags the window too close to the top of the screen, it snaps into place and can't be recovered. Any suggestions?

**Comment by ghostoy** [comment] 2016-01-22 07:32
Does resizable false work for you? http://docs.nwjs.io/en/latest/References/Manifest%20Format/#resizable

**Comment by thoughtspacewebsites** [comment] 2016-01-23 19:41
No, it doesn't seem to. The window still tries to snap to the top and blow up to full size.

**Comment by ghostoy** [comment] 2016-01-23 22:21
I will look into this issue.

**Comment by thoughtspacewebsites** [comment] 2016-03-07 19:19
Hey @ghostoy, just wanted to follow up here to see if you've managed to find any solutions to this issue.

**Comment by ghostoy** [comment] 2016-03-09 05:55
@thoughtspacewebsites Do you still see this issue in latest RC1 build? Make sure you set `resizable` to `false` in `package.json`.

**Comment by ghostoy** [comment] 2016-03-28 02:57
@thoughtspacewebsites Close it since I can't reproduce this issue since RC1 build. Please reopen it if you still see this issue.

**Closed by ghostoy** 2016-03-28 02:57 UTC
