### ISSUE TITLE
Window title and icon misisng and taskbar is blocked

### ISSUE THREAD

**Issue by Kriknos** [nwjs/nw.js#4559] opened 2016-03-13 04:01 UTC
For the rc1 I figured ok they'll get this issue fix asap. But it is still a problem in rc2. It all worked fine in beta 7.

The Window title and icon are not shown. Also I have my taskbar set to auto hide so I can not select anything on my taskbar with the nw.js app maximized, which is the default I have it set to at startup. As it maybe important I am running on windows 7. For now I have to stick with the beta 7 till this is fixed.

**Comment by rogerwang** [comment] 2016-03-13 12:44
The title and icon issue is a duplicate of #4486 and it was just fixed in live build.

**Comment by Christywl** [comment] 2017-04-26 02:20
@Kriknos , is this issue still reproduced on your test with the latest nwjs build?

**Comment by Christywl** [comment] 2017-10-11 07:58
close until there is more information.

**Closed by Christywl** 2017-10-11 07:58 UTC
Labels: needinfo
