### ISSUE TITLE
Random crashes on RPG Maker v1.6.1 with nwjs v0.29.0

### ISSUE THREAD

**Issue by Gobla** [nwjs/nw.js#6910] opened 2018-12-25 12:39 UTC
NWJS Version : 0.29.0, 0.29.4, 0.31.5, 0.35.3
Operating System : Windows 10 x64

Tried to contact RPG Maker support about this issue and they directed me to you because they think it's a nwjs issue. 

I encountered strange behavior with the game I make. It has random crashes during gameplay not tied to a specific action or time - it may happen after 20 minutes of playing or 6 hours. Battle/Map changes don’t affect this occurrence in any visible way, at least I didn’t detect a pattern during the testing.

The game folds with the console so I can't provide direct console output so the best I can get is debug.log after the crash. It has this error:

[1220/181051.502:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: The URL does not use a recognized protocol (0x2ee6)

Tried troubleshooting on my own and it didn't change much. First of all, I checked other issues and tried to sideline the error to see if it's critical with this code:

`process.on('uncaughtException', function (e) {
	console.error('uncaughtException:', e);
	console.error(e.stack);
});`

The crash still killed the game process with the console. So, no changes at all.

I tried switching between different nwjs versions. RPG Maker v1.6.1 uses 0.29.0 so I tried changing it to  0.35.3, 0.29.4, 0.31.5. Didn't change anything at all, the game still crashes and debug.log has the same error type.

Finally, I tried making a memory dump. Sorry, I can't provide the whole thing but the error code is 0xE0000008. Saved only the error code for googling but it didn't give me anything useful. Also, if I remember it correctly exception field info was blank. 

Windows error journal doesn't have anything about the problem or at least I don't see any matching entries when I get a crash.

Can provide the game itself if you need it for testing.

Thanks!

**Comment by TheJaredWilcurt** [comment] 2018-12-25 16:09
Without any code to test this or attempt to reproduce the issue, my assumption is that you have some type of performance issue with your app that is causing the crash and that it probably is not related to NW.js or RPG Maker directly.

If you can open the Chromium dev tools, there are many options for profiling the application's performance and memory usage.

* https://developers.google.com/web/tools/chrome-devtools/

**Comment by rogerwang** [comment] 2018-12-26 14:58
@Gobla you could provide the game so we can try to reproduce it here.

**Comment by rogerwang** [comment] 2019-01-07 11:34
close until more information is available.

**Comment by Gobla** [comment] 2019-01-10 12:38
Sorry, my motherboard died and I was out of the loop for quite some time. A fair warning - it's an NSFW game. Download links: [Windows](https://drive.google.com/open?id=1rQBkWIz0BQn0DDXeKWKBLcnZu8JSsBms) - [MacOS](https://drive.google.com/open?id=1GPc_0FoGjMmUEYw0aRSW81BgA9unJ0dl) - [Linux](https://drive.google.com/open?id=1Hn1UfhavRhvmF0S93xmi8sVNw-doBet1)

**Comment by TheJaredWilcurt** [comment] 2019-05-19 17:34
Played your game, could not reproduce issue. Closing until a more information is provided, ideally a means to consistently reproduce the issue.

**Closed by TheJaredWilcurt** 2019-05-19 17:34 UTC
