### ISSUE TITLE
Full screen flickering (to black) in nw.js 0.15.1

### ISSUE THREAD

**Issue by chadams77** [nwjs/nw.js#4947] opened 2016-06-06 16:07 UTC
Short clip showing the issue: https://www.youtube.com/watch?v=NsoY18LtVBU

I didn't have this problem with nw.js 0.12.3, however I upgraded because 0.12.3 was leaking memory.

I'm running windows 10, have a 7870 GHZ edition graphics card.

I'm using both a 2d canvas (over top, for text) and a webgl canvas (underneath), both are going black when it flickers.

This doesn't happen in windowed mode, even after switching back and forth a few times. 

Disabling canvas hardware acceleration makes the flickering worse.

**Comment by rogerwang** [comment] 2016-06-07 06:50
Does the same code run well in Chromium browser v51?

**Comment by chadams77** [comment] 2016-06-07 13:44
I get the same flickering problem in Chrome v51 and v50 as well

**Comment by chadams77** [comment] 2016-06-07 13:46
In nwjs 0.13.1 I don't get flickering, and there's no memory leak, but my game runs considerably slower.

**Comment by rogerwang** [comment] 2016-06-08 02:03
@chadams77 so I'm closing this since it's upstream issue. Please refer to crbugs.com.

If there is any performance regression, please file another issue.

**Closed by rogerwang** 2016-06-08 02:03 UTC
