### ISSUE TITLE
one click nw.exe,appears four nw.exe processes.

### ISSUE THREAD

**Issue by mustapha-wang** [nwjs/nw.js#3311] opened 2015-03-30 05:26 UTC
mouse click on nw.exe,launched four nw.exe processes.wrong or design as?
windows 7 64bit
node-webkit 0.12.0
##

**Comment by justinmchase** [comment] 2015-03-30 21:00
I believe it's by design.

**Comment by baconface** [comment] 2015-04-01 23:33
Design. I believe because of different processes/treads for different things like your app, WebKit/blink, node.js/io.js, etc.

**Comment by mustapha-wang** [comment] 2015-04-02 10:39
But,If i use a cloudTag control in html,three of four processes cpu loading are over 20%.

**Comment by Christywl** [comment] 2017-07-27 07:00
Any problems for this? Could we close it?

**Comment by rogerwang** [comment] 2017-07-27 07:28
close as it's intended under Chromium's multi-process architecture.

**Closed by rogerwang** 2017-07-27 07:28 UTC
Labels: needinfo
