### ISSUE TITLE
[Feature Request] Allow resizeTo() (and other resize functionality) to work on windows where "resizable" is false

### ISSUE THREAD

**Issue by sysrage** [nwjs/nw.js#7694] opened 2021-03-11 19:40 UTC
NWJS Version : 0.52.0
Operating System : Windows 10 (I assume also Linux)

### Expected behavior

When using `win.resizeTo()` (or any other NW.js API calls that resize windows) on a window that's set as `resizable: false`, it should still resize the window.

### Actual behavior

The window is not resized.

If `win.setResizable(true)` is called before calling `win.resizeTo()`, the window will be properly resized. One can then call `win.setResizable(false)` to "freeze" the window again.

While it's understandable to not resize when resizable is false, I recommend modifying behavior so that setting resizable to false only impacts user interaction with the window (manual resizing, minimizing, or maximizing). Programmatically resizing should still be possible when using `win.resizeTo()`, `win.resizeBy()`, `win.height`, and other related NW.js API methods.

This is purely a QOL feature request, so we don't have to build a wrappers to enable/disable resizing before/after changing the window size.

### How to reproduce

1. Open a window with the `resizable` property set to false.
2. Attempt to call `nw.Window.get().resizeTo(1000,1000)`.
3. Note that the window doesn't resize unless `nw.Window.get().setResizable(true)` is called first.

**Comment by ayushmxn** [comment] 2022-10-22 00:51
Isn't the point of `resizable: true` for not to be able to resize the window?

**Comment by sysrage** [comment] 2022-10-22 00:56
> Isn't the point of `resizable: true` for not to be able to resize the window?

I suppose that depends on your opinion! Personally, I believe `resizable: false` should mean that the **user** is not able to manually resize the window. We should still be able to resize the window programmatically, since we can do it anyway by manually setting it to `false`, resizing, and then setting it back to `true`.

**Comment by tharatau** [comment] 2023-04-21 19:36
Duplicate of #7685

**Closed by tharatau** 2023-04-21 19:36 UTC
Labels: bug
