### ISSUE TITLE
Concatenating the zipped archive to nw.exe does not work when started with arguments

### ISSUE THREAD

**Issue by jonathan-roy** [nwjs/nw.js#4903] opened 2016-05-27 08:11 UTC
I built an executable that only writes nw.App.argv.toString() to the document, and appended the archive containing the app to nw.exe using `copy /b nw.exe+test.nw test.exe`:

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
        <script type="text/javascript">
            window.addEventListener("load", function (event)
            {
                document.write("[" + nw.App.argv.toString() + "]");
            });
        </script>
    </head>
    <body></body>
</html>
```

Now when I start the executable for the first time using the command "test.exe hello world", the application works well showing "[hello,world]" and I also notice that a blank file called "hello" is created in the same folder than test.exe. When I start the application again with the same arguments, it does not work anymore, no window is showing, until I delete the file "hello" and run it again.

Tested using NW.js v0.14.5 on Windows 7 32bit.

**Comment by jonathan-roy** [comment] 2017-01-04 10:05
Any news on this issue?

**Comment by ghostoy** [comment] 2017-01-18 07:52
It should be fixed in latest 0.19.5.

**Comment by Christywl** [comment] 2017-04-10 03:15
I can't reproduce this issue on Windows with nwjs-sdk-v0.21.5.

**Comment by Christywl** [comment] 2017-10-24 05:23
close until there is more information

**Closed by Christywl** 2017-10-24 05:23 UTC
Labels: needinfo
