### ISSUE TITLE
NW.jS Custom build

### ISSUE THREAD

**Issue by NegativeIQ** [nwjs/nw.js#4984] opened 2016-06-15 17:53 UTC
Guys, how about some way of making custom builds of NW.js? Mainly chromium.
At the moment its a hude library (~90mb on windows), and for some simple apps its overkill.
So if we could strip down everything we dont need that would be awesome.

**Comment by rogerwang** [comment] 2016-06-21 09:58
close as duplicate of #3955

**Closed by rogerwang** 2016-06-21 09:58 UTC

**Comment by frankhale** [comment] 2016-06-21 14:19
I think people commonly forget what they are actually getting in those 90 megabytes. You are getting a complete platform in order to develop apps and it's a very small price to pay for such raw power. Put your app on a thumb drive. I recently bought a 32 gigabyte thumb drive for $11 US dollars. Space is cheap.
