### ISSUE TITLE
nw18 and nw19 block when https website with cert. error is loaded

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#5544] opened 2016-12-12 19:47 UTC
Tested with:
 nwjs SDK win 32 and 64 18.7 and 19.2. 
To reproduce: 
run nw.exe, pres F12 to open dev console and load some website with ssl cert error, e.g. https://play.composed.com. It will completelly block nwjs, and show the blank screen. Even the console won't work propperly anymore. On nw16 it just shows warning.

@rogerwang can you please take a look at this. Is there a chance for fix on nw18 branch?

**Comment by rogerwang** [comment] 2016-12-13 03:01
Thanks for reporting. Will fix it soon. And I'm afraid there is no 0.18.x releases any more since the stable branch is at 0.19.

**Comment by krneticz** [comment] 2016-12-13 10:47
@rogerwang thank you very much for quick response!

**Comment by rogerwang** [comment] 2016-12-14 02:54
It should be a regression in 0.17.4.

**Comment by rogerwang** [comment] 2016-12-14 06:11
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-12-14 06:11 UTC
Labels: bug, test-todo
