### ISSUE TITLE
Spawned child process fails due to stdout & stderr filling up with no way to read from parent

### ISSUE THREAD

**Issue by jobeninc** [nwjs/nw.js#6390] opened 2018-01-17 02:20 UTC
### Please post a workaround if one is known.  Thanks!

NWJS Version : 0.27.4 
Node Version : 9.3.0
Operating System : Windows 7

## Expected behavior

Message traffic between parent and spawned child should continue uninterrupted

Verified expected behavior with - NWJS Version : 0.19.4, Node Version : 7.2.0

## Actual behavior

The spawned child process exits with error code: 3221225477

### Sub problems:
 - maxBuffer config parameter does not appear to change the buffer size for spawn or fork
 - Unable to consume stdout or stderr on the parent side
 - The more that spawned processes that leverage third party products that print to stdout, the faster the error occurs

## How to reproduce

Run the following code with a helloWorld.html of your choice. 

### package.json
`
{
  "name": "scratch",
  "version": "0.0.1",
  "main": "index.js"
}
`

### index.js
`
const path = require('path');
const gui = require('nw.gui');
const spawn = require('child_process').spawn;

gui.Window.open('helloWorld.html', {}, function(win) {});

//Create spawned process
var child = spawn(process.execPath, ['./child.js'], {
  stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
  execPath: process.execPath
});

//Message sent back from child
child.on('message', function(m) {
  console.log('[Child message] ' + m.msg);
});

//Continually send messages to child (simulates typical IPC traffic)
setInterval(function() {
  console.log('ping')
  child.send('ping');
}, 50);

process.on('uncaughtException', function (err) {
  console.error(err);
});
`

### child.js
`
//Respond to pings with pongs
process.on('message', function(m) {
  setTimeout(function() {
    //Add a little bit of print litter to stdout to speed up the errors
  
process.stdout.write('stdout111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111');
    process.send({msg: 'pong'});
  });
});
`

**Comment by Christywl** [comment] 2018-01-17 06:35
I try it on Windows 8.1 with nwjs-sdk-v0.27.4, an error occurs:
![image](https://user-images.githubusercontent.com/20039821/35028883-2a630af4-fb93-11e7-925e-6e0456c6488c.png)

This doesn't happen on Linux with nwjs-sdk-v0.27.4.

**Comment by rowenbuzz** [comment] 2018-01-23 20:22
I am running into the same issue in an application with multiple spawned processes.  The application is currently unusable with the same upgrade as the OP.  I'm also on Windows 7 as well.

**Comment by skaughtx0r** [comment] 2018-01-29 19:55
Not sure if this is related, but I'm using the fork command to spawn a nodejs process and it seems to die immediately on Windows 10 using NW.js 0.27.5.

The only error that prints out is ```events.js:136 Uncaught NodeError: Channel closed``

When running with NW.js 0.26.6 it works fine.

**Comment by rogerwang** [comment] 2018-01-30 08:31
Yeah this seems to be a regression in 0.27

**Comment by rogerwang** [comment] 2018-01-30 13:14
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2018-01-30 13:14 UTC
Labels: P2, WIP, bug, triaged

**Comment by rogerwang** [comment] 2018-01-31 01:02
Please try https://dl.nwjs.io/live-build/nw28/01-31-2018/6d34eb9-c73bf1a-19c0659-668ffc5/v0.28.1/

**Comment by skaughtx0r** [comment] 2018-01-31 04:22
Thanks, that 28.1 build appears to be working in my case.

**Comment by jobeninc** [comment] 2018-01-31 23:13
That worked for my original issue. Thank you for addressing it so quickly.
