### ISSUE TITLE
NW.js crashes and returns status_access_violation when opening specific page

### ISSUE THREAD

**Issue by UtterDonkey** [nwjs/nw.js#7829] opened 2022-01-05 13:36 UTC
my game runs `var login = nw.Window.open('https://pixelbulb.online/login-API', {frame: false, show: true, width: 500, height: 700, always_on_top: true, position: "center"})` to create a login window, but it crashes the entire app! (Returns a status_access_violation on the SDK). When I open the window in a new instance, it doesn't do this but I need to be able to use post message. It's only that page.

NWJS Version : works in 0.54.1, so 0.55.0 was the first version that this issue occurs
Operating System : windows 11

### Expected behavior

It should open the window and not crash
### Actual behavior

It crashes
### How to reproduce
To reproduce, just run the js code at the top of the issue. There is nothing in the console or a crash report.

**Comment by sysrage** [comment] 2022-01-05 13:42
I helped @UtterDonkey reproduce this:

- It also fails/crashes in Windows 10.
- It fails/crashes with versions 0.55.0 through present (0.59.1).

This may be a duplicate of #7828.

**Comment by Nabeelhassan** [comment] 2022-01-05 13:46
yp i guess it might be a duplicate. I helped @FahadQurashi49 on his ticket #7828. I can also confirm that it does open on new instance and we are having the same problem of communication via postmessage.

**Comment by kr4ssi** [comment] 2022-01-07 06:15
>postmessage
I think reCaptcha uses this too #7810

**Comment by UtterDonkey** [comment] 2022-01-07 12:50
Wow thanks! That's it! I'll just remove Captcha for now. But this really must be fixed

**Comment by UtterDonkey** [comment] 2022-01-07 17:58
Nope, still occurs

**Comment by rogerwang** [comment] 2022-01-08 05:07
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2022-01-08 05:07 UTC

**Comment by UtterDonkey** [comment] 2022-01-08 12:11
Thanks
