### ISSUE TITLE
Crash dump file gets created inside C:\Users\<Username>\AppData\Local\Chromium\User Data\Crashpad\reports folder

### ISSUE THREAD

**Issue by ShobanaV** [nwjs/nw.js#5585] opened 2016-12-23 13:20 UTC
Hi,

I am using node-webkit 0.19.3 in Windows 7. When the app crashes, the crash dump files are getting created inside "C:\Users\<Username>\AppData\Local\Chromium\User Data\Crashpad\reports" folder, instead of app-specific path.

Is this expected?

**Comment by ghostoy** [comment] 2016-12-27 03:09
Close as duplicate of #5248.

**Closed by ghostoy** 2016-12-27 03:09 UTC
