### ISSUE TITLE
nw.exe eats a lot of shared memory! Is there any  solution for this problem?

### ISSUE THREAD

**Issue by sorty** [nwjs/nw.js#4536] opened 2016-03-10 02:51 UTC
nw.exe 0.13.0 rc2 
win7 64bit

I run both nw.exe and chrome.exe to open the following web site "http://www.craftymind.com/factory/html5video/CanvasVideo.html" 
one mintue later, the shared momory used by nw.exe up to  400M,while the chrome.exe is 70M.
![memory](https://cloud.githubusercontent.com/assets/172805/13657748/a16f91a6-e6ac-11e5-93b6-a58fc35fea4c.png)

it seems nw.exe eat too much shared memory! Is there any  solution for this problem?
I think the memory accquired by such as CreateFileMapping api in nw.exe is not recycled in time

**Comment by rogerwang** [comment] 2016-03-10 05:02
close as duplicate of #4520

**Closed by rogerwang** 2016-03-10 05:02 UTC
