### ISSUE TITLE
crash on reuse MenuItems on Mac

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6195] opened 2017-10-07 09:04 UTC
NWJS Version : 0.24.4
Operating System : Mac OSX 10.12.6

### Expected behavior

when assigning already created MenuItem object that is assigned to other menu it should work fine.
It works well on Windows but crashes on Mac

### Actual behavior

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Application Specific Information:
**Crashing on exception: Item to be inserted into menu already is in another menu**

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff869a657b __exceptionPreprocess + 171
1   nwjs Framework                      0x000000010ec9db7b _ZN2v88internal29InterpreterDispatchDescriptor26InitializePlatformSpecificEPNS0_27CallInterfaceDescriptorDataE + 2718411

**Comment by gpetrov** [comment] 2017-10-08 14:34
@rogerwang can you please help? This is really annoying crash and I really want to reuse the menu items in various menus as we have many large menus containing similar items, so I want to cache and reuse them.

This works really fine on Windows and Linux - but not on Mac - there when an existing menu items gets assigned to a second menu - nwjs crashes with the error above.

Is this an OS limitation or a bug in nwjs?

Hope it can be easily solved otherwise I have to rewrite the whole menu creation and it will be really slow on the mac due to this limitation.

Thanks!

**Comment by rogerwang** [comment] 2017-10-08 14:56
Will see it. Thanks.

On Oct 8, 2017 10:34 PM, "George Petrov" <notifications@github.com> wrote:

@rogerwang <https://github.com/rogerwang> can you please help? This is
really annoying crash and I really want to reuse the menu items in various
menus as we have many large menus containing similar items, so I want to
cache and reuse them.

This works really fine on Windows and Linux - but not on Mac - there when
an existing menu items gets assigned to a second menu - nwjs crashes with
the error above.

Is this an OS limitation or a bug in nwjs?

Hope it can be easily solved otherwise I have to rewrite the whole menu
creation and it will be really slow on the mac due to this limitation.

Thanks!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nwjs/nw.js/issues/6195#issuecomment-335010690>, or mute
the thread

**Comment by rogerwang** [comment] 2017-10-09 01:45
could you please provide a case so we can reproduce it?

**Comment by Christywl** [comment] 2017-11-03 07:38
close until there is more information

**Closed by Christywl** 2017-11-03 07:38 UTC
Labels: needinfo

**Comment by gpetrov** [comment] 2017-11-03 07:52
Problem was solved by just first detaching the menu items from the previous menu and then attaching them to the new one
