### ISSUE TITLE
win.isDevToolsOpen() not supported in v0.15.3?

### ISSUE THREAD

**Issue by kimhonoridez** [nwjs/nw.js#5063] opened 2016-07-01 08:45 UTC
I wanted to trigger this function but it is undefined:

```
var win = nw.Window.get();
win.isDevToolsOpen();
```

**Comment by Christywl** [comment] 2017-04-06 05:41
win.isDevToolsOpen() is still undefined on nwjs-sdk-v0.21.4. But I find that this is not supported for now in the docs(http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues). @rogerwang , am I right?

**Comment by rogerwang** [comment] 2017-04-25 06:18
close as duplicate of #4487

**Closed by rogerwang** 2017-04-25 06:18 UTC
Labels: regression
