### ISSUE TITLE
nwjc: segmentation fault 11 on macOS 10.3.3 using 0.30.2-sdk

### ISSUE THREAD

**Issue by troyibm** [nwjs/nw.js#6682] opened 2018-06-12 17:58 UTC
NWJS Version : nw@0.30.2-sdk
Operating System : macOS 10.13.3 (17D102)

### Expected behavior

nwjc should create app.bin

### Actual behavior

> node_modules/nw/nwjs/nwjc app/bundle.js app/app.bin

Received signal 11 SEGV_MAPERR 000000000000

==== C stack trace ===============================

 [0x0001037c20f3]
 [0x7fff6e535f5a]
 [0x7f9fd3c00000]
 [0x0001034ec50e]
 [0x000102ed08ac]
 [0x7fff6e2b4115]
 [0x000000000003]
[end of stack trace]
Segmentation fault: 11

### How to reproduce

I can provide my bundle.js and any other files you need, just let me know what and where I should put them.

**Comment by rogerwang** [comment] 2018-06-12 22:14
Yes, please provide bundle.js so we can reproduce it. Thanks.

**Comment by alxproject** [comment] 2018-06-16 06:56
the same happen to me on Linux, specific when use nwjc --nw-module lib.js lib.bin and the lib.js contains a dinamic es6 import
for example
if on the code appear import('./lib.js').then().catch();
the nwjc show the segmentation fault error
only with import() the segmentation fault error appear

**Comment by troyibm** [comment] 2018-06-17 15:35
@rogerwang here's the bundle.js

[bundle.js.zip](https://github.com/nwjs/nw.js/files/2109123/bundle.js.zip)

**Comment by rogerwang** [comment] 2018-06-18 07:31
There is a bug in nwjc that it crashes on compilation error. I just fixed that in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

Using the new local nwjc it shows an error in your script:
````
Unhandle exception: Uncaught SyntaxError: Identifier 'file' has already been declared @        const file = this.copiedFile;[461]
Failure compiling 'bundle.js' (see above)
````
So this looks like an error in your script.

**Comment by Christywl** [comment] 2018-06-29 05:19
@troyibm,  I try the latest nwjs, no crash happens, it also shows an error in the script. Please try the latest nwjs. If ok for you, please close this.

**Comment by alxproject** [comment] 2018-07-12 04:41
using lastest 0.31.6 show this error
~/nwjs-sdk-v0.31.6-linux-x64/nwjc --nw-module lib.js lib.bin
`Unhandle exception: Uncaught SyntaxError: Unexpected token import @        import(loadpath).then((status) => {[235]`
only using the function import() make the compiler faild
`Unhandle exception: Uncaught SyntaxError: Unexpected token import @        import();[235]`

the code works correctly

**Comment by alxproject** [comment] 2018-07-30 04:33
using latest nightly 0.32.1 show the same error
```
$ ~/nwjs-sdk-v0.32.1-linux-x64/nwjc --nw-module libimp.js libimp.alx
Unhandle exception: Uncaught SyntaxError: Unexpected token import @	return import(lib);[2]
Failure compiling 'libimp.js' (see above)
```
libimp.js
```
export function importar(lib) {
	return import(lib);
}
```
the code without compile works correctly

**Comment by alxproject** [comment] 2018-09-04 02:13
using latest release 0.32.4 show the same error
```
$ nwjc -nw-module libimp.js libimp.alx
Unhandle exception: Uncaught SyntaxError: Unexpected token import @  return import(lib);[2]
Failure compiling 'libimp.js' (see above)
```
libimp.js
```
export function importar(lib) {
	return import(lib);
}
```

**Comment by alxproject** [comment] 2018-09-06 03:38
using latest release 0.33.0-sdk show the error segmentation fault again
```
$ nwjc -nw-module libimp.js libimp.bin
Segmentation fault
```
libimp.js
```
export function importar(lib) {
	return import(lib);
}
```

**Comment by rogerwang** [comment] 2018-09-06 07:09
@alxproject I just pushed a fix for the crash. Now it should report an error on syntax error of import, which is an issue tracked in #6303 .  So I'm closing this issue. Thanks.

**Closed by rogerwang** 2018-09-06 07:09 UTC
Labels: needinfo
