### ISSUE TITLE
[0.15.2] new_instance doesn't work.

### ISSUE THREAD

**Issue by asinverse** [nwjs/nw.js#4971] opened 2016-06-13 12:41 UTC
Hello,

I've tested NW v.0.15.2 on Windows 8.1 and it seems `new_instance` option when opening new window doesn't work well: I can access all variables of parent window from its child.
Here's my code, it worked well on v0.12.3. Please tell me if I did something wrong.

> var opt = {
>         "width": 520, "height": 520, 
>         "new_instance": true
>     };
>     nwgui.Window.open("new.html" , opt, function(win) {
>         console.log(win);
>     });

**Comment by asinverse** [comment] 2016-06-13 13:06
Then, I try NW v0.14.6, I couldn't access variables of parent window (seem ok), but I get other errors:
>bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
main.js:11 Uncaught ReferenceError: $ is not defined

Here's `new.html`
```javascript
<!DOCTYPE html>
<html>
<head>
	<title>New window</title>
	<link rel="stylesheet" href="./css/bootstrap.min.css">
	<link rel="stylesheet" href="./css/style.css">

  <script type="text/javascript" src="./js/libs/jquery.min.js"></script>
  <script type="text/javascript" src="./js/libs/bootstrap.min.js"></script>
  <script type="text/javascript" src="./js/main.js"></script>
</head>
<body>
	<div class="container" style="margin-top: 20px;">
		<div id="createSession" class="col-md-12">
			<label for="sessionID">SessionID: </label>
			<input id="sessionID" type="text" />
			<button id="startNewSession" type="button" class="btn btn-primary">Start a new session</button>
		</div>
	</div>
</body>	
</html>
```
and, here's `main.js`
```javascript
$(document).ready(function() {
	console.log("Loaded !");
	
	$("#startNewSession").click(function(evt) {
		console.log("on new session click");
	});
});
```

All these are working fine on v0.12.3. Thank you for any suggestion.

**Comment by tolrtd** [comment] 2016-06-17 10:26
I'm having the same issue.  Seems to be a regression.

**Comment by tolrtd** [comment] 2016-07-20 01:34
Any updates on this? Not having new_instance on 0.15/0.16 is a pretty tough pill to swallow from 0.12.3 for people using the graphics capabilities of nwjs.

**Comment by rogerwang** [comment] 2016-07-20 01:43
Theoretically you cannot just access variables directly in another process. I'll check the example.

new_instance is for launching window in another process but the variables are not shared directly.

**Comment by tolrtd** [comment] 2016-07-20 01:47
Roger, I'm mainly interested in new_instance to create a new renderer thread.  I don't care so much about sharing variables.  In 0.15/0.16 I am not seeing a separate renderer process in Windows 8.1 x64 like I see with separate Chrome tabs.

**Comment by gpetrov** [comment] 2016-11-10 14:52
is this issue being addressed? We would really like to use new process instances for heavy duty rendering.
but we need be able to exchange message and that is currently not possible

**Comment by tolrtd** [comment] 2016-11-10 14:55
I got around this by using Broadcast Channel which is available in Chrome 54+.

https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

**Comment by gpetrov** [comment] 2016-11-10 15:04
@tolrtd WOW thanks! This was a life saver! Works great!

**Comment by Christywl** [comment] 2017-08-28 06:40
Is this issue still valid or we could close it?

**Comment by Christywl** [comment] 2017-10-24 05:17
close until there is more information

**Closed by Christywl** 2017-10-24 05:17 UTC
Labels: needinfo
