### ISSUE TITLE
[Linux] Videos are not playing on Twitter (maybe others)

### ISSUE THREAD

**Issue by justUmen** [nwjs/nw.js#6834] opened 2018-10-23 16:05 UTC
NWJS Version : 0.34.0
Operating System : Linux Mint

Message : 

> We cannot play the video in this browser. Please try a different web browser.

My code is a simple : ```<webview style="position:absolute;width:100%;height:100%;" id="app" src="http://twitter.com" allowtransparency></webview>```

Output errors.

```
[22274:22317:1023/224256.019061:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[22274:22274:1023/224256.020549:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
[22274:22317:1023/224257.629467:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio decoder initialization failed"}
[22274:22274:1023/224257.629880:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DECODER_ERROR_NOT_SUPPORTED
```

**Comment by TheJaredWilcurt** [comment] 2018-11-22 00:57
@justUmen 

This occurs because Twitter uses h.264 mp4 encoded video streams. Due to patent reasons, NW.js does not support this codec out of the box. You can follow these instructions to package the additional codecs manually:

* http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/

**Comment by TheJaredWilcurt** [comment] 2018-11-22 01:05
Confirmed that replacing the `ffmpeg.dll` with the prebuilt binary worked. Closing issue.

**Closed by TheJaredWilcurt** 2018-11-22 01:05 UTC
