### ISSUE TITLE
NWJS os.homedir not compatible with nodejs

### ISSUE THREAD

**Issue by gengshenghong** [nwjs/nw.js#5173] opened 2016-08-01 09:31 UTC
nwjs-v0.15.4-win-ia32.zip on windows 7

os.homedir() returns strings like "C:\Users\name", which should be: "C:\\\\Users\\\\name" instead.

This will affect "nwworkingdir" of <input>, it does not work using paths like "c:\xx\xx". I'll have to use string.replace() to handle the string manually. I was thinking it is correct behavior, but testing with official nodejs on same machine, os.homedir() returns "C:\\\\Users\\\\name" (tested with both nodejs v5.2 and v6.3.1). Thus, it seems like a bug of nwjs...

**Comment by rogerwang** [comment] 2016-08-04 08:02
I'm confused. In your report the return values are the same...

**Comment by gengshenghong** [comment] 2016-08-06 06:34
@rogerwang Sorry, it seems like github escaped  backslash(\), two backslash is same with one backslash....I've edit above using 4 backslash, please read it again.

Sorry for the confusing. :(

**Comment by ghostoy** [comment] 2016-08-17 02:37
@gengshenghong Did you get the result from Node.js CLI mode? Node.js CLI will try to output using valid JS string syntax, which escaped backslashes `\`. You can try `console.log(os.homedir())`, which returns `C:\Users\name`.

**Comment by gengshenghong** [comment] 2016-08-23 08:46
yes, I used CLI mode. Then maybe an issue of "nwworkingdir"? whatever, I have to use "string.replace()" to handle the strings to make it work if I save os.homedir() results to a variable and use it for "nwworkingdir".

example like:
var a = os.homedir();
var b = "<input...." + "nwworkingdir" + a + ...;
it does not work directly.

**Comment by ghostoy** [comment] 2016-08-24 01:48
In HTML, you have to escape it by replacing `\` with `\\`. Not an issue of `nwworkingdir`.
BTW, it should be `"nwrokdingdir=\"" + escapedHomeDir + "\""`. `=` and `"` are needed for a valid HTML attribute.
Closing this issue as not a bug.

**Closed by ghostoy** 2016-08-24 01:48 UTC
