### ISSUE TITLE
Slow https server creation on Windows

### ISSUE THREAD

**Issue by lynxtaa** [nwjs/nw.js#6470] opened 2018-02-15 12:59 UTC
NWJS Version : 0.28.2 (issue also present in previous releases)
Operating System : Windows 10, Windows 7

`require('https').createServer()` command takes ~1 second to run. 

### How to reproduce

package.json:
```json
{
  "name": "HTTPS",
  "node-main": "node-main.js",
  "main": "index.html"
}
```

node-main.js:
```js
const https = require('https')
console.time()
const server = https.createServer()
console.timeEnd()
server.listen(443)
```

You can observe in node devtools, that creating https server takes too long. In Ubuntu in takes ~10ms.

Simply running `node node-main.js` in cmd takes  10-20ms.

**Comment by Zuzon** [comment] 2018-02-15 13:50
move your server code to web worker. Running it in UI thread not best idea.

**Comment by cTn-dev** [comment] 2018-02-17 12:37
I can also confirm this, initially i haven't though much of it, but if you need to create multiple web servers on demand on windows, it does indeed take quite a while, about 1s.

**Comment by GnorTech** [comment] 2018-02-17 12:46
Thanks for reporting. Will definitely look to fix it.

**Comment by GnorTech** [comment] 2018-02-18 09:28
The delay is caused by openssl initialization code to walk the heap list as a source of entropy for the random number generator. It's delayed only in the first time for initialization. 
https://github.com/nwjs/node/blob/nw27/deps/openssl/openssl/crypto/rand/rand_win.c#L471

In Node the heap list is much shorter than NW so it takes shorter time to walk through. In NW it keeps walking through the heap list until MAXDELAY time is reached, which is 1s.
Now it's fixed in the latest nightly build: https://dl.nwjs.io/live-build/nw28/02-18-2018/5c35a0d-80813d9-ce48aed-6570a4b/v0.28.2/

**Closed by GnorTech** 2018-02-18 09:28 UTC
