### ISSUE TITLE
nw.window.open callback returns undefined when URL points to a site that doesn't exist

### ISSUE THREAD

**Issue by petsinho** [nwjs/nw.js#5105] opened 2016-07-14 12:24 UTC
*NWJS version : 0.14.5
*OS : Windows 10 64bit

How to reproduce : 
1. open nwjs console
2. run the following : 
 var WWin;
 var test = nw.Window.open('http://anotSoExistentSite.com', function(ww){WWin = ww})
3. a new window is dispatched but we have no reference on it

**Comment by walton007** [comment] 2016-10-20 09:14
I also meet this bug! Do you have any workaround?

**Comment by ghostoy** [comment] 2016-10-27 06:20
This issue should be fixed with #5294 in 0.17.4 or later. Please try with latest stable NW.js version. Be free to reopen it if it still doesn't work for you.

**Comment by Christywl** [comment] 2017-04-06 05:14
@petsinho @walton007  , do you mean the red box in the below screenshot ?
![image](https://cloud.githubusercontent.com/assets/20039821/24738699/0e523a1a-1aca-11e7-8146-318860c689d9.png)

**Comment by petsinho** [comment] 2017-04-06 10:11
hey @Christywl , no that is not the case, the snippet that you wrote makes perfect sense.

If I remember well, like I wrote above, it was getting a null handle sometimes, not every time (could not reproduce it but it was like 1 out of 15 times). I haven't use nw for some time and not sure if it was indeed fixed.
So in this case, in your snippet win would be `undefined` and win.width would break.

**Comment by Christywl** [comment] 2017-11-03 05:38
I use your codes, try 20+ times with nwjs-sdk-v0.26.3, can't reproduce this issue. The window object could be returned in` nw.Window.open` callback. Could you please try the latest nwjs build to check if it's still reproduced for you?

**Comment by Christywl** [comment] 2017-11-20 01:30
close until there is more information

**Closed by Christywl** 2017-11-20 01:30 UTC
Labels: needinfo
