### ISSUE TITLE
NW app not launching if RoamingProfileSupportEnabled registry key is set

### ISSUE THREAD

**Issue by dsomesh** [nwjs/nw.js#6621] opened 2018-05-15 11:38 UTC
Expected behavior
One of has the following key set to enable roaming profile for chromium
1.HKLM\SOFTWARE\Policies\Chromium\RoamingProfileSupportEnabled=1 (DWORD)
2.HKLM\SOFTWARE\Policies\Chromium\RoamingProfileLocation=C:\test (Or any other path in string)
It should launch successfully on launching.

(Please note that it is reproducible only if the machine is added to domain)

Actual behavior
On launching nw appears in task manager for a short time, but then goes off instantly. On removing those values it appears to launch properly.

NWJS Version :v0.25.4-win-x64
Operating System : Windows 7 64 bit

### How to reproduce

It is easily reproducible with following steps.(I reproduced in windows 7 64 bit)

Take a machine added to domain
Set the following Registry keys-
1.HKLM\SOFTWARE\Policies\Chromium\RoamingProfileSupportEnabled=1 (DWORD)
2.HKLM\SOFTWARE\Policies\Chromium\RoamingProfileLocation=C:\test (String)
Launch the application.

**Comment by dsomesh** [comment] 2018-05-15 11:38
This issue kinda important for us.Let us know if there are any work-arounds

**Comment by rogerwang** [comment] 2018-05-16 00:05
Will try to find a workaround. Could you try https://dl.nwjs.io/live-build/nw30/05-16-2018/29d01bf-df35f74-b58e580-00b3abb . It's helpful to pinpoint the root cause.

**Comment by rogerwang** [comment] 2018-05-16 02:56
The workaround would be add the argument: `--disable-sync` . And this is fixed in git (0.30.5)

**Closed by rogerwang** 2018-05-16 02:56 UTC

**Comment by dsomesh** [comment] 2018-05-16 09:03
We have a wrapper that launches nw.exe, as per an immediate fix (as we cant upgrade the nw version now)we are thinking of setting the value of RoamingProfileSupportEnabled to 0,launch nw and set the value back to 1 using the wrapper. My initial testing says that it works fine. Can you confirm if this would work for older versions for nw if only during launch the value is not effective?

**Comment by rogerwang** [comment] 2018-05-16 11:30
It's better to just add --disable-sync

**Comment by dsomesh** [comment] 2018-05-16 12:13
But that is present in 0.30 as part of your recent fix. Right? We are still using nw 0.25. So planning to go with this. Let me know if this is not the case.

**Comment by rogerwang** [comment] 2018-05-16 12:42
No. The fix is to disable reading that registry key.

The switch has been in Chromium. It should be in 0.25 as well.

**Comment by dsomesh** [comment] 2018-05-16 15:08
Thanks!!!That's all I needed for now.
