### ISSUE TITLE
Right click inside devtools crashes app

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#5659] opened 2017-01-24 20:52 UTC
Using SDK 20 rc1 in Win7 x64, when trying to right-click inside the devtools crashes the application instantly.

**Comment by zachm93** [comment] 2017-01-30 16:41
Any right-click in the app while devtools are open crashes the app for me.

[10408:14440:0130/104007.332:FATAL:window_impl.cc(138)] Check failed: atom. 87
Backtrace:
	v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFCD1C3C241+366209]
	v8::internal::compiler::InstructionOperand::Compare [0x00007FFCD1BC51DA+109674]
	v8::ResourceConstraints::set_max_executable_size [0x00007FFCD20273E4+742916]
	v8::ResourceConstraints::set_max_executable_size [0x00007FFCD2026E5E+741502]
	v8::ResourceConstraints::set_max_executable_size [0x00007FFCD2026F90+741808]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42FF65F+390607]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42E9169+299225]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42C4348+148152]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42B10C0+69680]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42FB548+373944]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42E1EC7+269879]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42E5C26+285590]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42E5AD4+285252]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42E379F+276239]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42E6C15+289669]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42E62FF+287343]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42F4F18+347784]
	v8::internal::compiler::JSCreateLowering::common [0x00007FFCD42B342D+78749]
	v8::internal::interpreter::Register::operator!= [0x00007FFCD31A9C1C+86828]
	v8::internal::compiler::LoadElimination::zone [0x00007FFCD303C965+590517]
	v8::internal::compiler::LoadElimination::zone [0x00007FFCD2FEAB69+255161]
	v8::internal::compiler::LoadElimination::zone [0x00007FFCD2FEAB17+255079]
	v8::Extension::dependency_count [0x00007FFCD1579E39+1458457]
	v8::Extension::dependency_count [0x00007FFCD15754C9+1439657]
	v8::internal::compiler::InstructionOperand::Equals [0x00007FFCD136F381+127649]
	v8::internal::compiler::InstructionOperand::Equals [0x00007FFCD136567D+87453]
	v8::internal::compiler::InstructionOperand::Equals [0x00007FFCD137103C+135004]
	v8::Extension::dependency_count [0x00007FFCD14A6A2B+593163]
	v8::internal::ParseInfo::is_eval [0x00007FFCD23F4EBC+628428]
	v8::internal::GCIdleTimeHandler::GCIdleTimeHandler [0x00007FFCD1C5CBA9+48553]
	v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFCD1C10247+185991]
	v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFCD1C0F25A+181914]
	v8::internal::GCIdleTimeHandler::GCIdleTimeHandler [0x00007FFCD1C5DB71+52593]
	v8::internal::GCIdleTimeHandler::GCIdleTimeHandler [0x00007FFCD1C5E104+54020]
	v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFCD1C2C1CE+300558]
	v8::internal::compiler::Linkage::GetStubCallContextParamIndex [0x00007FFCD19EC4B0+78528]
	v8::internal::compiler::InstructionSequence::instructions [0x00007FFCD12ACA4E+1031102]
	v8::internal::compiler::InstructionSequence::instructions [0x00007FFCD12AE08B+1036795]
	v8::internal::compiler::InstructionSequence::instructions [0x00007FFCD12A8910+1014400]
	v8::internal::interpreter::Register::operator= [0x00007FFCD18D0E9E+120750]
	v8::internal::interpreter::Register::operator= [0x00007FFCD18D0D90+120480]
	v8::internal::interpreter::Register::operator= [0x00007FFCD18D0204+117524]
	ChromeMain [0x00007FFCD0766B5C+236]
	(No symbol) [0x00007FF736285924]
	(No symbol) [0x00007FF736282CFF]
	IsSandboxedProcess [0x00007FF7362DCFC3+126739]
	BaseThreadInitThunk [0x00007FFD17A48364+20]
	RtlUserThreadStart [0x00007FFD1AAA70D1+33]

[0130/104007.406:ERROR:process_info.cc(608)] range at 0x6b142cec00000000, size 0x25c fully unreadable
[0130/104007.406:ERROR:process_info.cc(608)] range at 0x6b142d0c00000000, size 0x25c fully unreadable
[0130/104007.406:ERROR:process_info.cc(608)] range at 0x0, size 0x25c fully unreadable

Process finished with exit code -2147483645

**Comment by GnorTech** [comment] 2017-01-30 16:58
Could you please provide a sample app? The default app or a simple app here works for me.

**Comment by alphasdev** [comment] 2017-02-01 17:34
SDK 20 also crashes nwjs apps. What is the reason?

**Comment by zachm93** [comment] 2017-02-01 17:52
I created a small sample app and did not experience the issue. 

I removed the bootstrap init code from my real app and the issue went away. So something in there is probably creating the conflict but I haven't had time to dig into it any further.

**Comment by Yonezpt** [comment] 2017-02-01 19:19
Can anyone provide a sample app displaying the problem so that they can test it on their end? Haven't got the chance to do it myself for a few days, otherwise I'd done it already.

**Comment by PavelSapachev** [comment] 2017-02-07 20:42
I have the same problem on 0.20.1 version (SDK - win32 and win64). The following package.json is crashed application (after right click in DevTools or main application window):

```
{
  "name": "Test",
  "main": "index.html",
  "window": {
    "icon": "./icon.png"
  }
}
```

The icon property is important in this case. I have used 32x32 icon.

**Comment by rogerwang** [comment] 2017-02-07 22:15
Could you please upload all the files? Thanks.

**Comment by PavelSapachev** [comment] 2017-02-08 08:14
> Could you please upload all the files? Thanks.

Yes, i can. The link for archive with all files: https://dl.dropboxusercontent.com/u/5903127/Temp/nwjs5659.zip

**Comment by josendf** [comment] 2017-02-08 09:33
The crash also happens if you press the context menu key on a windows keyboard.

**Comment by Yonezpt** [comment] 2017-02-08 10:42
Sounds like NWJS is trying to build the custom context menu (http://docs.nwjs.io/en/latest/References/Menu/) as if the right click was being done inside a NWJS window, but since the devtools do not share the same environment (as far as I can tell) it crashes the app.

**Comment by rogerwang** [comment] 2017-02-08 11:29
@josendf unfortunately I cannot reproduce any crash with your sample.

Could anyone upload the crash dump? http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file

**Comment by PavelSapachev** [comment] 2017-02-08 12:04
@rogerwang my sample is too not reproducible?

**Comment by rogerwang** [comment] 2017-02-08 13:49
@PavelSapachev yeah I meant your sample. typo in my last comment.

**Comment by fearlesspixel** [comment] 2017-02-08 15:24
A crash dump is not being generated on my machine.

**Comment by PavelSapachev** [comment] 2017-02-08 15:28
@rogerwang ah, ok. But i have a little problem with crashdump - it is not created. I have only debul.log, similar as in second post of this thread. My sample i've checked in Windows 10 and 8.1 - in both cases the NW is crashed.

**Comment by PavelSapachev** [comment] 2017-02-08 15:42
@rogerwang  One more instersing thing: the app crash only if DevTools opened by F12 key. If DevTools opened from context menu - app is not crash.

**Comment by Yonezpt** [comment] 2017-02-08 15:48
@PavelSapachev even more interesting, if you open devtools via context menu, then it never crashes when you right click on it, even if you open it again after via F12.

But, if the first time you open it is using F12 then right-click = app crash. Nice find, I usually open it with F12, never remembered opening it via context menu to see if the crash still occurred.

**Comment by PavelSapachev** [comment] 2017-02-08 16:46
The issue #5669 helped to me find crash dump location. Here is my dump: https://dl.dropboxusercontent.com/u/5903127/Temp/iss5659.dmp

**Comment by Yonezpt** [comment] 2017-02-11 01:26
This problem goes even further. If F12 is pressed to open the devtools for the first time and then right-click inside the app (not inside the devtools) the app crashes just as well.

Something is breaking normal behavior when F12 is pressed or when the devtools are opened via F12.

**Comment by rogerwang** [comment] 2017-02-13 02:44
I can reproduce the issue now with F12 hotkey. So if the context menu is created after opening devtools it will crash, and it won't when the context menu is created before opening devtools.

Will look to fix it soon.

**Comment by rogerwang** [comment] 2017-02-13 04:28
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-02-13 04:28 UTC
