### ISSUE TITLE
New window created using window.open not honouring height and width

### ISSUE THREAD

**Issue by silentsakky** [nwjs/nw.js#5517] opened 2016-12-01 13:35 UTC
When creating new window using window.open it opens window with fixed height/width and doesn't honour passed height/width

* State which version are you using - 0.14.7 SDK
* State which OS version are you running with - OSX El Capitan
* Provide a reproducible case if possible - code attached here
[window-open.zip](https://github.com/nwjs/nw.js/files/624691/window-open.zip)

**Comment by leyaya** [comment] 2016-12-27 03:46
I met the same problem, your problem has been solved? How do you solve?

**Comment by HUN73R13** [comment] 2017-01-03 10:16
I have the same Issue
**Version** 0.19.4 (both sdk and production)
**OS** Windows 10 Pro 64-bit, tried with ia32 and x64
**Code**
`    nw.Window.open('index.html', {
        title: 'Title Goes Here',
        position: 'center',
        focus: true,
        min_width: 1024,
        min_height: 768,
        fullscreen: true
    }, function(win) {});`
using` min_width` & `min_height` or just ` width` & `height` or even using both have no effect on the issue.
created window in my case is 1024px × 799px.
as you can see width seems to be respected in my case but the height is not.

**Comment by ghostoy** [comment] 2017-01-17 04:59
@HUN73R13 Your issue is Windows specific upstream bug. See #5337.

**Comment by silentsakky** [comment] 2017-01-17 06:37
I don't think so, I am able to reproduce issue in Mac OS also
and upstream bug is related to height/width is off by some pixels then the passed height/width, but my issue is that whatever height/width you are passing it is showing popup with fixed height/width only, it is just ignoring the passed sizes

**Comment by ghostoy** [comment] 2017-01-17 06:55
@silentsakky I was responding to @HUN73R13.

**Comment by silentsakky** [comment] 2017-01-17 06:57
@ghostoy Oops :)

**Comment by Christywl** [comment] 2017-03-15 02:07
Still reproduced on Linux/Windows with nwjs-sdk-v0.21.2.

**Comment by silentsakky** [comment] 2017-03-23 13:44
any updates on when this is going to be fixed?

**Comment by xzhan96** [comment] 2017-04-06 06:38
@rogerwang are you working on this? if not, I'd like to investigate it.

**Comment by xzhan96** [comment] 2017-04-06 09:02
@silentsakky your sample has the same issue in chrome, did you try it on chrome?

**Comment by silentsakky** [comment] 2017-04-06 09:35
Just checked with Chrome  V57.0.2987.133 (64-bit) in mac, it is opening with proper window size

**Comment by xzhan96** [comment] 2017-04-07 01:32
@Christywl please help to run the test on Chrome on Linux, Mac and Windows.
 Note that the issue is:

> whatever height/width you are passing it is showing popup with **fixed** height/width only, it is just ignoring the passed sizes

**Comment by xzhan96** [comment] 2017-04-07 03:03
Ok, I can reproduce now.

**Comment by xzhan96** [comment] 2017-04-11 09:00
https://github.com/xzhan96/chromium.src/commit/78b21e7e6e2d2882503d19215dbc74a53489e1fe

**Comment by rogerwang** [comment] 2017-04-12 05:39
This is fixed in git and will be available in the next nightly build.

**Comment by xzhan96** [comment] 2017-04-12 09:54
The fix was reverted temporarily for new issue

**Comment by silentsakky** [comment] 2017-04-12 12:16
Should we reopen the issue then?

**Comment by rogerwang** [comment] 2017-04-13 05:36
It is merged into nw22 branch since 0.22.0 is to be released soon and there is no further releases for 0.21.

**Closed by rogerwang** 2017-04-13 05:36 UTC
Labels: bug, P2, triaged
