### ISSUE TITLE
NWJS 0.18.0 - Renaming nw.exe

### ISSUE THREAD

**Issue by edelciomolina** [nwjs/nw.js#5373] opened 2016-10-17 23:56 UTC
In this version, if try to change the nw.exe filename to another will stop to open and no shows any error or log message.

**Comment by jiangjianping** [comment] 2016-10-18 00:55
me too

**Comment by rogerwang** [comment] 2016-10-18 01:22
Thanks. This is duplicate of #5362

**Closed by rogerwang** 2016-10-18 01:22 UTC
