### ISSUE TITLE
Cannot build node gyp module for nwjs 0.39+

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7145] opened 2019-08-28 09:38 UTC
Hi, from Nwjs version 0.39 we can't builds sqlite3. This is critical stopper for releasing newer NWjs.

Issues:
* https://github.com/nwjs/nw-gyp/issues/130
* https://github.com/mapbox/node-sqlite3/issues/1179

**Comment by panther7** [comment] 2019-08-28 09:38
^ @rogerwang

**Comment by rogerwang** [comment] 2019-09-02 01:56
This should share the same root cause with #7104

**Comment by panther7** [comment] 2019-09-03 15:37
Hm, and any progress fix this issue?

This is really stopper for use new nwjs with sqlite

**Comment by gpetrov** [comment] 2019-09-11 14:31
any progress @rogerwang ? We would really like to build or native node modules in NWJS 0.40+ - but are stuck now in 0.38 because of this problem

**Comment by panther7** [comment] 2019-09-18 08:19
I think, some progress: https://github.com/nwjs/v8/commit/bf62c4681425c89225fbc5216bc1bf1a42485adc ?

**Comment by rogerwang** [comment] 2019-09-18 14:41
Fixed in #7104

**Closed by rogerwang** 2019-09-18 14:41 UTC

**Comment by gpetrov** [comment] 2019-11-10 19:32
@rogerwang is this something we can also integrate? As compiled node modules are really fat now

https://github.com/electron/electron/pull/20614
