### ISSUE TITLE
17.0 window.open the callback's parameter is null

### ISSUE THREAD

**Issue by liufangfang** [nwjs/nw.js#5271] opened 2016-09-06 05:58 UTC
```
gui.Window.open("presenter-view.html", {
                                new_instance: true,
                                focus: true,
                                //x: 0,
                                //y: 0,
                                "icon": "resources/img/axeslide.png"
                            }, function (new_win) {
                                    new_win.moveTo(0, 0);
                                    new_win.focus();
                                    new_win.enterFullscreen();
                                });
```
after using 0.17 the new_win is null  @rogerwang @ghostoy

**Comment by rogerwang** [comment] 2016-09-06 06:03
This is duplicate of #4418

**Closed by rogerwang** 2016-09-06 06:03 UTC

**Comment by liufangfang** [comment] 2016-09-06 06:10
@rogerwang  16.1 has no this problem.  I update my app project to 0.17.0 just now.  When resolve this problem?
