### ISSUE TITLE
Opening/Closing Windows is using/leaking memory - any ideas?

### ISSUE THREAD

**Issue by shrewdlogarithm** [nwjs/nw.js#3095] opened 2015-02-15 23:01 UTC
To demonstrate this (tested with 11.6 and 12.0) I made a quick demo

package.json
```javascript
{
  "name": "MemTest",
  "main": "index.html"
}
```

index.html
```javascript
<html>
<head>
<script>
    var wins = []
	var gui = require('nw.gui');
	var win = gui.Window.get();
	function opensome() {
		for (var i = 0; i < 10; i++)
			wins.push(gui.Window.open("test.html")) 
	}
	function closesome() { 
		for (var i = 0; i < wins.length; i++)
			wins[i].close(true)
		wins = [] 
	}
	function movealong() {
		gui.Window.open("index.html")
		win.close(true)
	}
</script>
</head>
<body>
<input type=button value="Open 10 Windows" onClick="opensome()"></input>
<input type=button value="Close All Opened Windows" onClick="closesome()"></input>
<input type=button value="Close this and open another" onClick="movealong()"></input>
</body>
</html>
```

test.html
```javascript
Hello World
```

To test this (Windows 64bit here) - open taskmgr, run the app (it should start 2 processes using about 15-20Mb of memory) - hit 'Open 10 Windows' a few times - should now be using 100s of Mbs of memory - that's fine.

Hit "Close all opened windows" and memory usage will drop but not to the earlier values - 10s of Mbs will have 'leaked'.  This also seems to be a percentage of the memory the windows used and NOT a constant - e.g. opening/closing more complex documents leaks more memory each time.

The last button opens a new 'index.html' and closes the current window just to rule-out 'references' being held somehow.

Note: I've tried running with --expose_gc/using gc() and gui.App.clearCache() - neither helps

I'm guessing this is probably Chromium cache or history-releated?- but it's also a quick way to run out of memory when you have larger documents loaded into Windows 

Any ideas?

**Comment by RIAEvangelist** [comment] 2015-02-17 19:09
This could be the heap allocation from chromium. Memory is allocated to each window for JS to use.

Does begin to reduce after a few min?

I think this should be a non issue if so because an app that requires >4 windows seems like a bad architecture that could be redone in tabs or some other form of layout within a single window.

IMHO.

**Comment by shrewdlogarithm** [comment] 2015-02-17 20:51
I've never seen the memory be released - at least not in normal PC usage (I didnt try filling-up the PC's memory or anything of that nature)

The App wouldn't have more than 1/2 windows open at a time (10 was just to speed the example along) but it will open dozens (they're reports/analyses combining web and local data) over the course of a working day and as most users have laptops (which are slept rather than powered-off) it will do so for days at a time without a restart (e.g. it will end-up using HUGE amounts of memory)

One of the base requirements of this application is an 'idle' footprint of no more than 50Mb of memory - so right now I can't even put nw.js forward as a solution because it reaches than after just a few windows have been open/closed...

**Comment by shrewdlogarithm** [comment] 2015-02-19 14:56
Looking for alternative solutions/fixes - I came across atom-shell, which appears to be what would have happened if most of the major design decisions for node-webkit had gone the other way!

https://github.com/atom/atom-shell

It couples node and chromium loosely with your application being just JS which opens/closes windows as required.  I assumed that might be less memory-hungry so I test it.

It's nowhere near as polished as node-webkit - yet - distribution and packaging are a bit messy in particular, but it is going to knock node-webkit into a cocked-hat for applications which aren't "open one window and keep it forever" if my results are typical.

Using a version of my test-app (above) opening just 10 windows and closing them, node-webkit held-onto 135Mb at the end wheras atom-shell had just 43Mb.  Repeating the trick left 160Mb and 45Mb and that just continued.

I'd really like to see a solution (or even a reason) for node-webkit's memory hunger given that closed windows should be completely destroyed/purged/gone - but I'm guessing from the lack of replies that there isn't one right now?

I think this is a problem which will have to be addressed at some point - I know it's down to how Chromium works (it's obvious from testing Chrome that it "Likes a drink of memory") but is atom-shell can avoid it - I think node-webkit can too?

p.s. OSX users might be cheered by the fact that atom-shell seems quite well developed on that platform - moreso than node-webkit if I'm honest??

**Comment by rogerwang** [comment] 2015-02-19 15:18
It's a known issue because the residing Node context hold some reference to the window object in the *first* DOM context so it uses more memory. But the memory shouldn't increase when you keep opening/closing window. This was verified by an issue report in the past.

Regarding the extra memory usage we're in a discussion to change this in nw13, please see #3107

**Comment by shrewdlogarithm** [comment] 2015-02-19 17:52
That's an interesting read (if a bit over my head in places)

Memory usage does increase over time tho - even if you open just one window to the same page/close it/open it/close it - even if you give the GC time to do it's thing - even if you close and reopen the last window (as in my example above), the memory footprint of one of the node.exe processes just keeps growing (this is on WIn7-64 using Node 11.6 or 12 and using taskmgr because that's what users tend to look at)

An app growing from 50Mb to 150Mb and creeping slowly upwards might not seem like a big deal given the specs of modern PCs but there are situations where that's going to be an issue - thin clients with limited memory at one end of the problem, gamers who are paranoid about everything which they run in resource terms at the other

I'm intrigued by atom-shell's ability to run "just Node" as a base process too - it means you could deploy apps which are just tray icons/background servers/listeners/proxies waiting for the user to open a window (or even just access their content via their normal browser) - there currently isn't a way of deploying a simple cross-platform desktop server like that (that I'm aware of) and not having the overhead of a browser active is a bonus to it's footprint

I'm guessing that's something which has never been on the node-webkit roadmap/intended purposes list?

**Comment by rogerwang** [comment] 2015-02-20 15:47
@shrewdlogarithm welcome to submit a case that reproduces that memory keeps increasing.

Regarding the ability of "just Node" as a base process, their API is designed in that way so you think it's just running Node. But it's actually not -- still running in a Chromium (browser) process.

btw, starting from 0.12.0-alpha1 we support an additional start point of the application with 'bg_script' which might let developers feel the similar.

**Comment by shrewdlogarithm** [comment] 2015-02-20 16:57
The hardest part of making a good test-case for memory increase is that I suspect using setTimeout or setInterval (to schedule windows opening/closing) stops the Chromium GC from operating (as JS is active??)

The Chromium GC seems a reluctant beast at the best of times - there are situations where it seems to never trigger (I've pushed an App well beyond 1Gb of memory usage - zero free RAM - no sign of GC going on) and other situations where it's more frequent.

There used-to-be a cmd-line-switch to add a 'purge memory' button in Chrome (Task Manager) but it disappeared a while ago - certainly something of that nature in Chromium would be nice - the unlock-GC/GC() approach only seems to work for the current Window

**Comment by shrewdlogarithm** [comment] 2015-02-20 21:16
I'm not an expert on this stuff, but I was browsing a Heap Dump for my App earlier and noticed it contained objects which were created by code loaded into Windows since closed.

They appeared to relate to jQuery (loaded into every window via a SCRIPT tag in the HEAD of the html) and they were around 2.5Mb in size - so one thought is that this might be part of the problem!?

I therefore added a win.close event to every window which assigns $ and jQuery to null.  Checking the heap dump for that version, the objects remains however they no longer refer to $ - they refer to an anonymous reference from a call to $.toJSON - and I don't use that anywhere in my code!

The only occurences of that are in nw.exe and nw.pak - which makes me wonder if I'm using jQuery wrongly and/or if references are being overwritten and leading to closures being retained?

I really don't understand JS at this level but it seemed odd that the Heap Debugger would point into code which should have been removed entirely when I close the window which contained it??

**Comment by jaymes-bearden** [comment] 2015-04-02 19:47
We're having the exact same issue. When profiling with timeline, we notice a consistent increase in documents as they are never removed (even after closing the window, adding a handler and nulling it all out).

Checking against the heap snapshot containment, we've noticed that they all have a reference to a global object (ie: object on window) called nwDispatcher. Maybe the windows can't be gc'd due to this common object?

**Comment by shrewdlogarithm** [comment] 2015-04-02 19:54
Roger said something along those lines earlier (perhaps in another thread?) but it was only supposed to be the first Window you opened, not any additional ones.

I tried pretty-much everything I could think of to avoid leaking memory but the fact is that an nw.js application will hold-on to every bit of memory a window consumes, even if you close it.

I switched the app I was working on to atom-shell - simply because it's architecture allows me to open/close windows without the memory leak.  It's not as 'mature' as nw.js in other areas memory management was high on the requirements list and nw.js couldn't do that...

**Comment by Yimiprod** [comment] 2015-04-09 14:21
I put my experience in this ticket, when in dev environment, i don't close then reload the app, i use the reload button.
Don't know if it came from angularjs or node-webkit, but each time i reload like this, the app became more and more slow at a point the app can't even run properly.

In production environment, the reload button for this specific app is hidden so the memory leak will probably not appear. Still, this issue should be up.

**Comment by jaymes-bearden** [comment] 2015-04-09 18:16
For our usage, we did exactly that early on to attempt to reclaim memory. Problem being that for whatever reason, the documents are retaining a reference to some sort of parent object and thus cannot be totally reclaimed.

As a temporary work around, we maintain a hidden window state and more-or-less reuse the windows as much as possible, ie, we don't really ever "close" them just hide.

**Comment by shrewdlogarithm** [comment] 2015-04-09 18:24
It's been said before - in many places - that Chromium is very memory-hungry and VERY reluctant to release memory.  I'm guessing that the structure of nw.js is such that fully releasing a Window is difficult, but that does run the risk of apps using ENORMOUS amounts of memory.

nw.js wouldn't be alone in this - Steam (the gaming client) uses Chromium and some people have issues with it consuming MASSiVE amount of memory (in some cases several Gbs)!!

Since I switched our 'many windows' app to atom-shell I've not looked more deeply at this - atom-shell can 'fully release' a Window on-demand, although it still has issues with existing Windows using more and more memory over time (that's just Chromium I guess)

nw.js will need to address this at some point tho, not everyone just wants to open a single Window - there are many use cases for opening and discarding content over the app lifetime?

**Comment by ataylor09** [comment] 2016-04-05 00:20
I'm noticing this same problem with my app too.
In my application, the user can open a PDF document - which opens a new window running the PDF.js viewer - which can be quite heavy.

I've found that if you open -> close, open -> close etc. etc.... It doesn't take too long before the memory size is in the GB's... which for me is a big issue!
I've also noticed the same problem if you refresh the page several times.

I think I'm too far down the track with NW.js to make a switch to atom shell or similar. Is there an easy work around for this issue?

If I was to open the document in an iframe that lives within the main window - rather than in a new window, would that fix the problem?

**Comment by rogerwang** [comment] 2016-04-05 01:43
@ataylor09 which version are you using?

**Comment by ataylor09** [comment] 2016-04-05 02:54
@rogerwang I'm using version 12.3

**Comment by rogerwang** [comment] 2016-04-05 02:55
Please try latest 0.13.3.

**Comment by ataylor09** [comment] 2016-04-05 03:43
@rogerwang with 0.13.3 I can see the memory usage in windows task manager go up and down each time I open and close a window... so appears to be working correctly so thanks for that.

The issue is still present when using window.reload however... Not really an issue for release version of app, as reload won't be exposed to the user. But for development and testing purposes, I use this to refresh the page when I've made changes to my code.

Is there another way to achieve this without using window.reload()

**Comment by rogerwang** [comment] 2016-04-05 05:39
@ataylor09 window.reload shouldn't have leak, unless you're storing objects in Node context/background page, which is not supposed to be cleared like the DOM context.

You can use the "reload app" feature in the context menu in SDK build, or use '--mixed-context' in the command line argument which enables a mode that Node and DOM objects reside in a same context.

**Closed by rogerwang** 2016-04-05 05:39 UTC
