### ISSUE TITLE
[NW13-alpha6] Does not contain the scrollbar

### ISSUE THREAD

**Issue by zhenlovezhen2012** [nwjs/nw.js#4048] opened 2015-12-09 08:43 UTC
[NW13-alpha6] Does't contain the scrollbar,but nw-12.3 working fine;

Windows and MAC is the same;
<img width="229" alt="13" src="https://cloud.githubusercontent.com/assets/6262638/11680502/ae0e5110-9e93-11e5-9608-6d215d0dadff.png">
<img width="165" alt="12" src="https://cloud.githubusercontent.com/assets/6262638/11680539/df6e903a-9e93-11e5-8fc1-4e8277610a81.png">

**Comment by Mithgol** [comment] 2015-12-09 19:31
I am closing this issue as an exact duplicate of a previously reported issue (#3834).

**Closed by Mithgol** 2015-12-09 19:31 UTC
