### ISSUE TITLE
Content-scripts are not injected correctly

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7597] opened 2020-10-16 15:40 UTC
NWJS Version: 0.49.x, 0.50.x
Operating System: Win 10

### Expected behavior

Insert content-scripts correctly, works fine in NWjs 0.47.3 and NWjs 0.48.4

### Actual behavior

Sometimes, after init/load webview and injection content-scripts (via `webview.addContentScripts`).
  

### How to reproduce

1. [Example.zip](https://github.com/nwjs/nw.js/files/5529676/Example.zip)
    * contentscript.js - injected to webview, easy example for chrome.runtime communictaion, example showing command message `hello-world` from webview to window.
      ```js
      connection.command('hello-world', null, (returnData) => console.log(returnData));
      ```
   * window2.js - chrome.runtime.onMessage, return to webview 'Hi!', if receive `hello-word` message.
1. Run with NWjs, check devtools (shown automatically)
1. Some startup, incialized wrong, missing contentscript.js
   ![2020-10-16 14 21 43](https://user-images.githubusercontent.com/3808250/96258239-fcd43a00-0fbb-11eb-8524-20d1ae18b30c.png)
1. Some startup, incialized ok
   ![2020-10-16 14 22 33](https://user-images.githubusercontent.com/3808250/96258244-fd6cd080-0fbb-11eb-8ab6-d8c268ce64c8.png)

**Comment by panther7** [comment] 2020-10-21 08:02
@rogerwang Could you help me with? Or can i help you with this issue?

**Comment by panther7** [comment] 2020-10-27 12:11
This is blocker for our project. Is anything, which i can help resolve with this issue?

**Comment by panther7** [comment] 2020-11-01 15:37
Still broken in v0.49.2

**Comment by rogerwang** [comment] 2020-11-12 00:49
Hello. It works for me -- here is what I got after I run your sample in 0.49.2:

<img width="369" alt="1" src="https://user-images.githubusercontent.com/165401/98880968-ea1e2980-24c3-11eb-8c70-b8605c44928b.png">

**Comment by panther7** [comment] 2020-11-12 01:09
Try run it several time please, it is works to 50%. It is strange.

**Comment by rogerwang** [comment] 2020-11-12 03:06
I tried it for 10 times and it always works...

**Comment by panther7** [comment] 2020-11-12 09:43
It is very strange, now i tested several times. Recorded to gif.

![aaa](https://user-images.githubusercontent.com/3808250/98923360-d7abec00-24d3-11eb-9969-3cc7e1d77095.gif)

**Comment by TheJaredWilcurt** [comment] 2020-11-12 16:42
**Reproduction Attempt Process:**

1. On Windows 10 64-Bit
1. Download the latest NW.js SDK (0.49.2 64-Bit)
1. Download provided example zip
1. extract both
1. Put files from example into a `package.nw` folder next to `nw.exe`
1. Open task manager
1. Run NW.js > Application launches > Console shows correct output > close NW.js
1. Wait for all `nw.exe` process to be removed from the list of running processes in Task Manager
1. Repeat the last two steps 10 times

My results are the same as Roger's. Cannot reproduce.

**Comment by bluthen** [comment] 2020-11-12 17:02
Maybe race condition and dependent on the hardware or system load? I usually get around these type of issues by finding right spot to split the task with a timeout. Hate doing it but seems unavoidable sometimes.

**Comment by panther7** [comment] 2020-11-13 08:19
I tested on 3 differents PC and all has same issue. In NWjs 0.47.3 and below I never seen this issue (v0.48 was skipped).

**Comment by corwin-of-amber** [comment] 2020-11-13 14:47
@panther7 Also could not reproduce, but I would suggest deferring the creation of the Connection object until the page has loaded; i.e. instead of:
```js
const connection = new Connection();
```

which occurs at initialization time, you may try:
```js
document.addEventListener('DOMContentLoaded', () => {
    window.connection = new Connection();
});
```

Or any other event that is appropriate, e.g. `'load'` or `'readystatechange'`.

**Comment by panther7** [comment] 2020-11-13 14:54
@corwin-of-amber Thanks for suggest, but it still is not fixed.

![2020-11-13 15 52 40](https://user-images.githubusercontent.com/3808250/99085381-67cb5d80-25c8-11eb-80ff-3806777d86b1.png)

**Comment by corwin-of-amber** [comment] 2020-11-13 14:57
Actually @TheJaredWilcurt, I have tested it a bit more (on macOS) and indeed when I *reload* the window (that is, Ctrl+R in the devtools window) rather than quit & relaunch, the `generated_script_file` (the one that holds `params`) is missing about one out of three times.

When quitting & relaunching, it is always there.

**Comment by panther7** [comment] 2020-11-15 12:58
@TheJaredWilcurt Still *cant-reproduce*? Last test from @corwin-of-amber confirmed my issue.

Btw, I tested today in Chromium v86.0.4240.198 and it works properly.

**Comment by panther7** [comment] 2020-11-15 16:34
Tested on latest [nwjs0.50](https://github.com/nwjs/nw.js/tree/0630f073fa62818cabff0bc0d70ba7fba87106b2), still broken.

**Comment by corwin-of-amber** [comment] 2020-11-15 16:38
@panther7 it does seem like the only missing thing is `params`. Your content script is loaded correctly in all the reloads. Can you perhaps work around this by using something else instead of `params.extensionId` and `params.frameId`? E.g. you can generate id's in the main page and send them to the webview via `postMessage`.

**Comment by panther7** [comment] 2020-11-15 21:27
@corwin-of-amber hmm, it seem, that nwjs after v0.47 has more "async" loading content-scripts.
Now, i tested merge array content-scripts to one and seems works:
```js
            js: {
                code: `var params = { test: true, frameId: '${uuid}', extensionId: '${location.hostname}' };`,
                files: ['contentscript.js']
            },
```

**Comment by panther7** [comment] 2020-11-18 15:24
Sometimes, i have this error:
> Uncaught TypeError: Error in invocation of runtime.connect(optional string extensionId, optional object connectInfo): chrome.runtime.connect() called from a webpage must specify an Extension ID (string) for its first argument.

"String extensionId is optional", but error say, that must be present... there is something broken in NWjs.

![2020-11-18 16 21 20](https://user-images.githubusercontent.com/3808250/99549596-1c46f400-29ba-11eb-8884-e74d6619961b.png)

**Comment by panther7** [comment] 2020-11-18 16:40
I created [new example](https://github.com/nwjs/nw.js/files/5561379/Example2.zip), it is more simple. It use only `chrome.runtime.sendMessage` and `chrome.runtime.onMessage`. Example opens 20 webviews and trying communication, if something fails, do you shows error alert.

Test in NWjs:
- 0.47.3, 0.48.4: ok, [screenshot](https://user-images.githubusercontent.com/3808250/99559358-fecb5780-29c4-11eb-8c6e-6f14938661c9.png)
- 0.49.2, 0.50.0 (today build): fail, [screenshot](https://user-images.githubusercontent.com/3808250/99559362-01c64800-29c5-11eb-951a-b2bbd1f90a23.png)

**Comment by rogerwang** [comment] 2020-11-24 00:33
@panther7 I don't think you are using the chrome API correctly -- as error message reported from your example, it prompts that you are missing a parameter 'extension id'. Please check https://developer.chrome.com/extensions/runtime#method-sendMessage

**Comment by panther7** [comment] 2020-11-24 07:35
@rogerwang What is  wrong? API is same over years. Works correctly to NWjs 0.48. Param `extensionId` is optional. Last example is simply extreme and illustrates, that NWjs sometimes "calls/includes/execs/whatever" wrong with `chrome.runtime` API.

**Comment by rogerwang** [comment] 2020-11-24 11:24
According to the doc, the param is required when the API is called from web pages, that is what the sample is doing from a webview. So it's expected to fail.

It may "work" for you in previous versions, but that was a bug and is fixed now. Please do not rely on it.

**Comment by panther7** [comment] 2020-11-24 11:51
@rogerwang `chrome.runtime` and `extensionId` are not truly issue.

[Next example](https://github.com/nwjs/nw.js/files/5589591/R.zip) is without them. Only define content-script `code` with variable `params`. The *contentscripts.js* trying read `params.extensionId`, like:

*window.js*:
```js
webview.addContentScripts([
    {
        name: 'params',
        js: {
            code: `
                var params = {};
                params.extensionId = '${location.hostname}';
            `,
        },
        matches: ['<all_urls>'],
        all_frames: true,
        run_at: 'document_start',                
    },
]);
```

*contentscript.js*:
```
try {
    console.log(params.extensionId);
} catch (err) {
    console.error(err);
    alert(`Broken, check devtools > console > error \n\n ${err}`);
}
```
[R.zip

**Comment by panther7** [comment] 2020-11-27 11:25
[Another Example](https://github.com/nwjs/nw.js/files/5607579/Example5.zip) without contentscript.js, all is in `code`. Broken too...

![2020-11-27 12 24 28](https://user-images.githubusercontent.com/3808250/100444312-8abb3e80-30ab-11eb-95d6-6b5ba8e3fff5.png)

```js
{
    name: 'scripts-1',
    js: {
        code: `
            function sendMessage(data) {
                let extensionId = '${location.hostname}';
                return new Promise(resolve => {
                    chrome.runtime.sendMessage(extensionId, data, resolve);
                });
            }

            (async () => {
                if (window.top === window) {
                    try {
                        const response = await sendMessage({ greetings: 'hello' });
                        console.log(response.greetings);
                    } catch (err) {
                        console.error(err);
                        alert(\`Broken, check devtools > console > error \\n\\n $\{err\}\`);
                    }
                }
            })();
        `,
    },
    matches: ['<all_urls>'],
    all_frames: true,
    run_at: 'document_start',
}
```

@rogerwang

**Closed** 2020-11-28 02:52 UTC
Labels: cant-reproduce

**Comment by panther7** [comment] 2020-11-28 06:57
Wow! Works! Thanks @rogerwang 

It was very difficult to come up with more and more examples. :)

**Comment by rogerwang** [comment] 2020-11-28 08:02
Fix available in https://dl.nwjs.io/live-build/nw50/20201128-025700/1b058a3a2/v0.50.2/

**Comment by panther7** [comment] 2020-11-30 11:53
@rogerwang Thanks, when is scheduled release v0.50.2?

**Comment by gpetrov** [comment] 2020-12-09 07:12
It is already released
