### ISSUE TITLE
App.on('reopen') is not fired after win.hide()

### ISSUE THREAD

**Issue by Saravanan90** [nwjs/nw.js#5262] opened 2016-09-02 15:16 UTC
**Version used: 0.17.0** (also faced in 0.16.1 as well)

**OS: El Capitan**

**Script:**

var win = nw.Window.get();
var tray = new nw.Tray({ icon: 'myicon.png', iconsAreTemplates: false });

  tray.on('click', function() {
    win.show();
  });

win.on('close', function(event) {
    this.hide();
});

nw.App.on('reopen', function() { // Clicking on the Mac dock or Windows task bar icon
  win.show();
});

**Issue faced:**
- After window close, tapping on dock icon doesn't open the window whereas clicking on tray icon works, which implies reopen is not fired.
- The above issue happens after a while on closing the window.

Is there any alternative to win.hide()? 

Even tried win.show(false), but didn't work.

**Comment by Saravanan90** [comment] 2016-09-07 05:59
Can someone kindly help me in fixing this issue?

**Comment by FiatPax** [comment] 2016-09-09 12:25
Not sure but did you try win.restore() instead of win.show()

**Comment by ghostoy** [comment] 2016-11-24 08:28
I can't reproduce this issue on my Mac with 0.17.0, 0.17.6 and 0.18.7. When I "close" the window and click the dock, the window show up.

**Comment by ghostoy** [comment] 2016-12-27 02:54
Close this issue since not receiving feedbacks for a long time. Please reopen it if you still experience this issue.

**Closed by ghostoy** 2016-12-27 02:54 UTC
Labels: needinfo
