### ISSUE TITLE
NW Crash when opening a page

### ISSUE THREAD

**Issue by pchuong** [nwjs/nw.js#6247] opened 2017-10-30 14:50 UTC
NWJS Version : v0.26.1
Operating System : Windows7

### Expected behavior

NW.exe shouldn't crash

### Actual behavior

NW.exe crash every time when I open a page on my local server.

### How to reproduce

I am getting this error in the log file when the process crashed. Perhaps if the error message prints the request url, it can help to track down which request is causing this crash.

[1030/103616.838:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol  (0x2ee6)

Attached is a zip file contains a bunch of .dmp files when I tried to set the url from the dev tool or from the command argument when starting nw.exe.

[reports.zip](https://github.com/nwjs/nw.js/files/1427591/reports.zip)

**Comment by Christywl** [comment] 2017-11-01 01:41
I can't reproduce this issue on Windows 7/8.1 with nwjs-sdk-v0.26.2-x64.

   ` <a href="http://127.0.0.1:8080/1.html">link</a>`

Could you please try it on win64 devices to check if it's a win32 specific issue? And you could please upload your sample here, I'll check on my device.

**Comment by pchuong** [comment] 2017-11-01 13:27
At first, I thought it was a 32bit vs 64bit issue and I did download and tried on 64bit. 64bits also crashed.
You can reproduce the crash with this url. https://dev.ti.com/gc. This is where my application is hosted online. With this url, nw.exe crash.

**Comment by Christywl** [comment] 2017-11-03 08:44
How should I do with this url? I just try `nw.exe --url=https://dev.ti.com/gc`, it works fine. Could you please provide the detailed steps to reproduce this?

**Comment by pchuong** [comment] 2017-11-03 13:22
Hi Christy, that is exactly how I launch nw.exe. Did you login? It will crash after the you login and goto the application.

**Comment by call-me-bk** [comment] 2017-11-04 09:40
#6001 it will crash every time you login. Did you login?

**Comment by call-me-bk** [comment] 2017-11-04 09:41
Check error tree

**Comment by Christywl** [comment] 2017-11-06 01:11
I can reproduce this issue on Widnows 8.1/Linux with nwjs-sdk-v0.26.3 after I login. Here is crash dump file.
[7ff22a59-7ff6-49be-b770-d4da47d8cfce.zip](https://github.com/nwjs/nw.js/files/1444631/7ff22a59-7ff6-49be-b770-d4da47d8cfce.zip)

**Comment by rogerwang** [comment] 2017-11-06 02:11
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-11-06 02:11 UTC
Labels: bug, P1, triaged

**Comment by dobriai** [comment] 2018-04-25 20:27
OK - now this seems **broken again** in versions `0.30.0` and `0.30.1`.
Works fine in `0.29.4` and I don't have a handy copy of `0.29.5` to check.
All this for `win64` - both sdk and normal builds. Happens on Win7 and Win10 machines.
```
[0425/120529.493:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: The URL does not use a recognized protocol (0x2ee6)
```
and then the app closes or crashes - hard to tell.

Should this be reopened or should I create another Issue? If a call stack is needed ... I'll need a quick reminder how to get it :-)

**Comment by Christywl** [comment] 2018-04-26 03:11
`nw.exe --url=https://dev.ti.com/gc` works fine with nwjs-sdk-v0.30.0/v0.30.1 on Windows. If you meet another crash issue, please file a new issue and provide your sample to reproduce it.
