### ISSUE TITLE
NW crashes when nw.Window.open set icon as png format images.[0.21.x]

### ISSUE THREAD

**Issue by sean220** [nwjs/nw.js#5770] opened 2017-03-13 06:57 UTC
````javascript
nw.Window.open("index.html",{frame:false,icon:"logo.png"});
````
This issue exists only in the 0.21.x version on MacOS[10.12],Every time it crashes when open new window. Maybe any image format as icon has this problem,I only tested the png image format.

**Comment by Christywl** [comment] 2017-03-13 07:25
Reproduced on Linux and Mac with nwjs-sdk-0.21.0.

**Comment by rogerwang** [comment] 2017-03-13 07:48
close as duplicate of #5767

**Closed by rogerwang** 2017-03-13 07:48 UTC
Labels: bug, P1, triaged
