### ISSUE TITLE
Autocomplete= "off" this attribute is invalid in nw!

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#5590] opened 2016-12-26 06:38 UTC
Autocomplete= "off" this attribute is invalid in nw!
Code and effect screenshot!

http://pan.baidu.com/s/1boTscvd

**Comment by ghostoy** [comment] 2016-12-27 03:04
Close as duplicate of #5184.

**Closed by ghostoy** 2016-12-27 03:04 UTC
