### ISSUE TITLE
nw12 crash channel.cc(553)

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#3342] opened 2015-04-06 22:59 UTC
hi

got some crash with 

```
[5562:0406/002742:WARNING:channel.cc(553)] Failed to send message to remove remote endpoint (local ID 3, remote ID 2147483649)
 [5562:0406/002742:WARNING:channel.cc(553)] Failed to send message to remove remote endpoint (local ID 1, remote ID 1)
```

then app crash (linux ubuntu 14.10 x64)

an idear why ? 

thanks 
##

**Comment by polpo** [comment] 2015-04-20 17:16
I am getting a similar message even upon normal application exit (SIGINT, closing application window, calling gui.App.quit()).

```
[11142:0420/101333:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 2147483649, remote ID 3)
[11142:0420/101333:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
Failed to tell parent about crash.
```

Also on Linux x64.

**Comment by uggrock** [comment] 2015-08-04 12:23
we have the same issue even with v0.12.3

**Comment by SchizoDuckie** [comment] 2015-08-05 20:38
Same here. v0.12.3 
```
[18639:0100/000000:FATAL:child_shared_bitmap_manager.cc(112)] Check failed: false. 
Failed to tell parent about crash.
```
```
[18712:0805/223800:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
[18712:0805/223800:WARNING:channel.cc(320)] RawChannel write error
```

**Comment by Christywl** [comment] 2017-07-14 07:24
I can't reproduce this issue on nwjs-sdk-v0.23.6. Please try the latest nwjs build.

**Comment by Christywl** [comment] 2017-10-09 08:18
close until there is more information.

**Closed by Christywl** 2017-10-09 08:18 UTC
Labels: needinfo
