### ISSUE TITLE
On OSX, dragging window doesn't work with multiple <div>s with -webkit-app-region: drag;

### ISSUE THREAD

**Issue by elisee** [nwjs/nw.js#3360] opened 2015-04-11 15:17 UTC
In the following example, one should be able to drag the green regions and unable to drag the red one:

index.html:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf8">
    <title></title>
    <style>
        body { -webkit-user-select: none; }
    </style>
</head>

<body>
    <div style="-webkit-app-region: drag; background: green; height: 100px">
        Draggable
    </div>
    <div style="background: red; height: 100px">
        Non-draggable
    </div>
    <div style="-webkit-app-region: drag; background: green; height: 100px">
        Draggable
    </div>
</body>

</html>
```

package.json:

``` json
{
    "name":"nw_multiple_drag_window",
    "main":"index.html",
    "window":{
        "toolbar":false,
        "frame":false
    }
}
```

This works correctly on Windows but on Mac OS X, most of the window is undraggable and a tiny portion at the center of the red region is draggable.

If one removes `-webkit-app-region: drag;` on either of the green regions, then the other region becomes correctly draggable. I believe it is likely caused by the fact that there are two separate codepaths for dealing with single vs. multiple drag regions: https://github.com/nwjs/nw.js/blob/51300afa76f4f916ec80c3ae8e70082b5f267bbe/src/browser/native_window_mac.mm#L921, implying multiple regions are incorrectly merged in UpdateDraggableRegionsForCustomDrag (https://github.com/nwjs/nw.js/blob/51300afa76f4f916ec80c3ae8e70082b5f267bbe/src/browser/native_window_mac.mm#L1039)
##

**Comment by shaynem** [comment] 2015-04-12 05:00
This has always been an issue.

I ended up adding and removing drag regions via javascript depending on
window states to get around this. Might not work for your situation tho.

That or you could make a transparent image position it at the top above all
layers z-index to make that drag

On 12 Apr 2015 1:17 am, "Elisée" <notifications@github.com> wrote:
>
> In the following example, one should be able to drag the green regions
and unable to drag the red one:
>
> index.html:
>
> <!DOCTYPE html>
> <html>
> <head>
>     <meta charset="utf8">
>     <title></title>
>     <style>
>         body { -webkit-user-select: none; }
>     </style>
> </head>
>
> <body>
>     <div style="-webkit-app-region: drag; background: green; height:
100px">
>         Draggable
>     </div>
>     <div style="background: red; height: 100px">
>         Non-draggable
>     </div>
>     <div style="-webkit-app-region: drag; background: green; height:
100px">
>         Draggable
>     </div>
> </body>
>
> </html>
>
> package.json:
>
> {
>     "name":"nw_multiple_drag_window",
>     "main":"index.html",
>     "window":{
>         "toolbar":false,
>         "frame":false
>     }
> }
>
> This works correctly on Windows but on Mac OS X, most of the window is
undraggable and a tiny portion at the center of the red region is draggable.
>
> If one removes -webkit-app-region: drag; on either of the green regions,
then the other region becomes correctly draggable. I believe it is likely
caused by the fact that there are two separate codepaths for dealing with
single vs. multiple drag regions:
https://github.com/nwjs/nw.js/blob/51300afa76f4f916ec80c3ae8e70082b5f267bbe/src/browser/native_window_mac.mm#L921,
implying multiple regions are incorrectly merged in
UpdateDraggableRegionsForCustomDrag (
https://github.com/nwjs/nw.js/blob/51300afa76f4f916ec80c3ae8e70082b5f267bbe/src/browser/native_window_mac.mm#L1039
)

**Comment by AdamCanady** [comment] 2015-04-16 07:10
I'll confirm this as an issue. In my example, the regions are bounded to the top, but are not draggable. Instead, regions bounded to the bottom of the same size (but without the background-color) are draggable.
![screen shot 2015-04-16 at 2 10 48 am](https://cloud.githubusercontent.com/assets/2141945/7175762/cf7bd71c-e3dd-11e4-8873-c758206a3b62.png)

**Comment by Christywl** [comment] 2017-07-14 06:29
I can't reproduce this issue on Mac with nwjs-sdk-v0.23.6.

**Comment by Christywl** [comment] 2017-10-09 08:17
close until there is more information.

**Closed by Christywl** 2017-10-09 08:17 UTC
Labels: needinfo
