### ISSUE TITLE
Node-webkit Helper has CPU running at 100%

### ISSUE THREAD

**Issue by ersatzryan** [nwjs/nw.js#2372] opened 2014-09-20 17:36 UTC
This happens in multiple node-webkit apps

https://github.com/LightTable/LightTable/issues/1475

http://forum.time4popcorn.eu/viewtopic.php?f=6&t=537

**Comment by tommoor** [comment] 2015-02-19 19:04
@rogerwang the problem is that node-webkit provides no way to get more information... is there a way we can debug what's going on inside node-webkit Helper? I'd be more than happy to do so as this is killing our current app.

As a side note Lighttable is now moving to atom because of this issue: https://github.com/LightTable/LightTable/issues/1088

**Comment by adam-lynch** [comment] 2015-02-19 19:14
+1, CPU usage seems abnormally high at least.

**Comment by xenyou** [comment] 2015-03-12 05:03
+1 nwjs Helper makes my Mac very very heavy

**Comment by xenyou** [comment] 2015-03-12 05:20
FYI, Just running nw.js in not archived directory does not reproduce this issue.
Running foo.app (i.e. after build) causes the issue.

**Comment by shaynem** [comment] 2015-03-12 06:18
To get around this issue I created and install file that extracts the
contents of the application to /etc/folder and used platypus to create and
application in /Applications that launches the nwjs instance from /etc so
that way the application isn't packaged.

Rough work around but it works.

Using package maker I can have pre scripts that check and clear the
/etc/app dir upon install if required.

**Comment by stephan-nordnes-eriksen** [comment] 2015-03-15 11:22
I am also seeing high cpu usage of the nwjs helper. I suspect it has to do with some logging or something else because that process shoots high when I start using the profiler and other things in the Dev Tools.

**Comment by keitha-cakewalk** [comment] 2015-04-14 02:21
I'm also having the same problem.  We have an app for which nwjs seemed suited.
However, upon trying to simply download files from our server, we're hit with crazy high CPU heating up the Mac and causing the download the drop.  Have seen as high as 160%, sometimes 115% sustained.
I made a basic test app with nothing in it but download code and that goes from 50-70%.  This is even using io-buffer with large file buffer blocks.   I have the same download code in a .js file which when run from node doesn't have these issues.

I'd like to send the test project for debugging.  Like others, I tried the built in tools to find any javascript issues, but alas that's around 95% idle.  Even tried the flame graph but the widest parts of the graph were simply mwjs helper with no other info.  So I'm blocked by this issue and concerned that it's been a fair amount of time with no progress on this.  Happy to help provide whatever info needed.

Using the latest 12.0.1 nwjs.  OSX Yosemite 10.10.2.

The basic code is like this:
var ioBuf = require('io-buffer');
var fs = require("fs");  // includes the Filesystem for Node
var url = require('url');
var http = require('http');

	// 1 GB
	var size = 1 * 1024 * 1024 * 1000;
	var file_url = 'http://mirror.internode.on.net/pub/test/1000meg.test';

	var file = fs.createWriteStream('test.data');

	// Write data to a file in 256k chunks 
	var buffered = ioBuf.createBufferedStream(256 * 1024);
	buffered.pipe(file);
	
	var srcUrl = url.parse(file_url);
	var options = { headers: { 'user-agent': 'test' }, hostname: srcUrl.hostname, path: srcUrl.path };
	var req = http.get(options, function(res) {
		if (res.statusCode < 200 || res.statusCode > 299) { 
			// clearInterval(pGress); // stop the download progress
			console.log("bad http status code:" + res.statusCode);
		}
		else {
			var fsize = res.headers['content-length'];
			if ( fsize != size ) {
				size = fsize;
				sizeRecip100 = 100 / size; // recalc size recip.
			}		
			res.on('data', function(data) {
				buffered.write(data);				
			});		
			res.on('error', function(err) {
				if (err != null ) {
					alert(err.message);
				}
			});	
			res.on('end', function() {
				console.log("done dl");
				buffered.end();			
				//clearInterval(pGress); // stop the download progress
				alert("done with download");
			});
		}
	});

**Comment by rogerwang** [comment] 2015-04-14 05:20
@keitha-cakewalk could you please send the project to me? we've been trying hard here to reproduce this issue. cc @xueeinstein

**Comment by xueeinstein** [comment] 2015-04-14 08:18
+1, It's reproducible. `nwjs Helper` went to 80+% CPU usage on iMac. Noticeably, at that time, network speed is up to 8~9MB/s. But when the network down to 200~300KB/s, `nwjs Helper` CPU usage is only about 6%. Maybe some bugs in node.js I/O in nw.js. I have built a debug version of `nwjs-v0.12.1`, trying to figure it out.

**Comment by rogerwang** [comment] 2015-04-14 13:41
@xueeinstein thanks. but the bug reports are about 100% CPU when app is idle...

**Comment by xueeinstein** [comment] 2015-04-14 14:04
@rogerwang , but with 8~9MB/s network speed, directly running in node.js only takes about 30% CPU usage.

**Comment by keitha-cakewalk** [comment] 2015-04-14 16:40
Retrying, with google drive attachments this time...

On Tue, Apr 14, 2015 at 11:50 AM, Keith Albright <keithalbright@cakewalk.com
> wrote:

> Hi Roger and Bill,
>
> Nice to meet you.  I’m relatively new to nwjs via a contractor we worked
> with.  However, I’ve been a long time developer in c++ and have done a lot
> of deep debugging.
> Let me know if you all are interested in checking out any of our music
> products, or if you would find mac spin dumps helpful.
>
> Here’s the app.nw for the test app.  Is that sufficient?
>
> ​
 app.nw
<https://docs.google.com/a/cakewalk.com/file/d/0Bwg8gZEGmcuBM0ZQMTZVdDZIem8/edit?usp=drive_web>
​

> Yes, I’ve seen node directly be lower.  I've also seen the CPU be lower
> when downloading say on a bus with limited wifi.
>


> Interesting I see a kernel component in the activity for Safari, node and
> nwjs, but not for example if doing curl from cmd line.
>
>
>
> I had generated a flame graph when we were seeing high cpu, but it may not
> be that helpful.  It was run against 12.0.0
> Attached
>
​
 graph2.svg
<https://docs.google.com/a/cakewalk.com/file/d/0Bwg8gZEGmcuBWXhnOVZRdFdkZ1E/edit?usp=drive_web>
​


>
>

**Comment by rogerwang** [comment] 2015-05-21 01:46
merge with #2723 which is fixed now.

**Closed by rogerwang** 2015-05-21 01:46 UTC
Labels: needinfo

**Comment by keitha-cakewalk** [comment] 2015-05-21 12:56
Awesome, thanks.  So this is in 13?  Will it be brought to say a 12.2?

**Comment by rogerwang** [comment] 2015-05-21 13:38
yes. it'll be released with 0.12.2 soon.
