### ISSUE TITLE
nwjs 0.16 developer (SDK) Crash and forced to close

### ISSUE THREAD

**Issue by oknoorap** [nwjs/nw.js#5144] opened 2016-07-23 16:09 UTC
On earlier version of nwjs this code 100% working if any error occured, but in 0.16 it forced my app to close, I don't know how to debug where is error.

```process.on('uncaughtException', function (e) {
	console.log(e)
})```

is there any alternative method to debug errors?

**Comment by rogerwang** [comment] 2016-07-25 01:09
could you please submit a minimal case to reproduce?

**Comment by oknoorap** [comment] 2016-07-25 03:14
@rogerwang I don't know, what is error. I can't see error in devtools, it was too fast to close, I knew there is an error.

**Comment by fragrans** [comment] 2016-07-29 15:12
I think I have got same problem here.
If there is any error within JavaScript code, nwjs crashes.

I tested with 0.15.* SDK and Normal, both crash.

**Comment by RohitSharma27** [comment] 2016-07-30 05:29
window.on("error",function(err){})
can help you out in capturing the JavaScript errors, if there is any.

**Comment by oknoorap** [comment] 2016-07-30 07:41
@RohitSharma27 so process.on('uncaughtException', function (e) { console.log(e) }) not working anymore?

**Comment by RohitSharma27** [comment] 2016-07-30 17:08
I fear so. Well, 'uncaughtException' event is emitted when an exception bubbles all the way back to the event loop and it looks like NW captures it before, it propagates to the event loop and logs it to console instead.

**Comment by rogerwang** [comment] 2016-08-04 07:59
It should be the duplicate of #5148

**Closed by rogerwang** 2016-08-04 07:59 UTC
