### ISSUE TITLE
Kiosk printing does not work

### ISSUE THREAD

**Issue by HappyStriker** [nwjs/nw.js#6773] opened 2018-08-23 08:58 UTC
NWJS Version : 0.32.1
Operating System : macOS High Sierra 10.13.6

### Expected behavior

I have been reading into the issues #1263 and #4911 to find a solution to print a website to a pdf without the chromium print dialogue to pop up, but I did not succeed with the provided solutions of those issues.

According to the solutions mentioned there one should be able to print a website silently without the chromium print popup to be shown.

### Actual behavior

The print dialogue pops up for a few seconds, prints to pdf and then disappears.

### How to reproduce

_package.json:_
```
{
  "name": "main",
  "main": "main.html",
  "window": {
    "printPreview": false
  },
  "chromium-args": "--kiosk-printing"
}
```

also applying the chromium arg --kiosk does not help.

_main.html:_
```
<!DOCTYPE html>
<html>
  <head>
    <script>
      const win = nw.Window.get();

      function printMeToPDF() {
        win.print({
          "autoprint": true,
          "pdf_path": `/Users/Username/Desktop/printed.pdf`,
        })
      }
    </script>
  </head>
  <body>
    <h1>Hello printer world!</h1>
    <input type="button" onclick="printMeToPDF();" value="print me to pdf">
  </body>
</html>
```

### Final words

Thank you for looking into these issues and also for developing nwjs, which is a great tool!
Happy Striker

**Comment by rogerwang** [comment] 2018-08-23 11:15
This should be the duplicate of #6269

**Closed by rogerwang** 2018-08-23 11:15 UTC
