### ISSUE TITLE
0.57.1 webview crash

### ISSUE THREAD

**Issue by ostwindli** [nwjs/nw.js#7928] opened 2022-07-29 07:17 UTC
With nwjs v0.57.1, there is a chance of crashing when destroying and creating a webview.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/17735161/181704385-9b2a2aa5-7484-451a-a1fb-d88e34ca7a84.png">

At the same time, I found that this problem started from v[0.51.0](https://github.com/nwjs/nw.js/blob/nw67/CHANGELOG.md#0510--01-22-2021)

**Comment by ostwindli** [comment] 2022-07-29 11:43
ps: v0.51.0  crash log

<img width="847" alt="image" src="https://user-images.githubusercontent.com/17735161/181751733-5c8c61d8-6e0b-495c-9a69-e1fda3deb1a3.png">

**Comment by ayushmxn** [comment] 2022-07-31 21:30
@ostwindli Could you provide a small repro or steps to reproduce?

**Comment by ayushmxn** [comment] 2022-08-05 15:39
Closing this for now since don't have steps to reproduce. Ping me here once you're able to and I'll reopen this.

**Closed by ayushmxn** 2022-08-05 15:39 UTC
Labels: needinfo
