### ISSUE TITLE
`window.icon` of `package.json` does not work

### ISSUE THREAD

**Issue by AlttiRi** [nwjs/nw.js#7858] opened 2022-03-25 13:33 UTC
NWJS Version: 0.62.1
Operating System: Win 10

I use:
```
{
  "name": "nw-demo",
  "version": "0.0.1",
  "main": "index.html",
  "window": {
    "icon": "icon.png"
  }
}
```
But the application's icon in Task Bar and and the window's icon are default:

![Screenshot](https://user-images.githubusercontent.com/16310547/160129900-eca0fdb6-587a-402b-a13e-1e01c76e4888.png)

![Screenshot_1](https://user-images.githubusercontent.com/16310547/160129914-74a01119-6ef3-4e5c-a59d-a588190c99bb.png)

I run the demo app with `../nwjs-sdk-v0.62.1-win-x64/nw .` command.

---
```html
<link rel="icon" href="icon.png">
```
Even this does not work when I open the app with NW.js.

---

As well as
```json
    "icons": {
        "16": "icon.png",
        "48": "icon.png",
        "128": "icon.png"
    }
```

**Comment by UtterDonkey** [comment] 2022-05-21 08:36
try 
`{
  "name": "nw-demo",
  "version": "0.0.1",
  "main": "index.html",
  "icon": "icon.png",
  "window": {
    "icon": "icon.png"
  }
}`

**Comment by NicoLB22** [comment] 2022-05-30 08:08
Hello,

I'm facing the same problem after migrating from v0.58.0 to v0.64.1 on Win 10.
My app is now rendering the NW default icons, ignoring the one that was previously displayed.
Did you manage to make it work again with the latest NWJS version ?

Thanks

**Comment by AlttiRi** [comment] 2022-05-30 09:03
I just checked, it works now.
The same code as from my first message:  [app.zip](https://github.com/nwjs/nw.js/files/8797054/app.zip) (`icon.png`, `index.html`, `package.json`)

With v0.64.1.

**Comment by NicoLB22** [comment] 2022-05-30 09:16
Ok, thank you.
For me it still doesn't work on my development environment, but everything is fine in production !
With v0.64.1.

**Comment by ayushmxn** [comment] 2022-08-05 18:13
Duplicate of #7556

**Closed by ayushmxn** 2022-08-05 18:13 UTC

**Comment by jerson-arch** [comment] 2023-02-17 06:41
> Lo acabo de comprobar, ahora funciona. El mismo código que en mi primer mensaje: [app.zip](https://github.com/nwjs/nw.js/files/8797054/app.zip) ( `icon.png`, `index.html`, `package.json`)
> 
> Con v0.64.1.

It also helped me and it worked for me.
size: 64px x 64px
format: PNG
v0.72.0

Resize images (this may help)
https://picresize.com
