### ISSUE TITLE
Focusing a parent window

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#5286] opened 2016-09-08 20:56 UTC
I've got one window that opens another window. I would like to then, have a function on the new window on a click event that re-focuses the parent window. Here are some things that I've tried:
```
parent.window.opener.focus()
parent.window.focus();
window.opener.focus();
window.blur();
var newWindow = window.open('','_parentName');newWindow.focus();
parent.win.focus();
```

According to the old window docs, `window.opener.focus()` should work, according to the new window docs, `win.focus()` should work. So I would think `parent.win.focus()` should work. But it doesn't. Anyone have a work around?
http://docs.nwjs.io/en/latest/References/Window/#winfocus

Edit: on an old version of webkit (`0.12.2` I believe) this works: `window.open('', '_parentWindowName');` however in `0.13` this does not work anymore.

**Comment by RohitSharma27** [comment] 2016-09-09 01:51
This is what you're looking for.
Window.open('.../link/...', {optional parameters}, function(win){
win.on('focus',function(){
win.opener.focus();
});
});

**Comment by RohitSharma27** [comment] 2016-09-09 01:51
I meant 
win.on('click',....

**Comment by joshterrill** [comment] 2016-09-09 02:30
I'm sorry I don't understand, could you please post the full example? I saw
that you said "I meant..." But I don't understand where that fits into the
code.

**Comment by RohitSharma27** [comment] 2016-09-09 10:03
Replace focus in win.on('focus'... with click. This means that when you'll click your child window, your parent window will come into focus... You may want to bind this click event on a button or something in your child window. It was just meant to tell you how you can use and access these windows. I hope it helps. And please close the issue as it's not a bug.

**Comment by FiatPax** [comment] 2016-09-09 12:14
[focusParentSample.zip](https://github.com/nwjs/nw.js/files/463898/focusParentSample.zip)

Here's my implementation, tested with nwjs v0.17.1

**Comment by joshterrill** [comment] 2016-09-09 19:39
When I try the implementation on my code, I get `VM2139:1 Uncaught TypeError: Cannot set property 'parentWin' of undefined(…)`. @RohitSharma27  I don't understand what you mean by a click. I am not doing anything to click the newly opened window. I'm trying to focus the parent window in an `onclick=` attribute.

**Closed** 2016-09-14 00:10 UTC
