### ISSUE TITLE
transparent error on win10

### ISSUE THREAD

**Issue by oliverlife** [nwjs/nw.js#6275] opened 2017-11-07 07:02 UTC
when I run this demo [transparency-5989.zip](https://github.com/nwjs/nw.js/files/1168696/transparency-5989.zip) using nw 0.26.2，my computer can't show the demo's main window.
My os is win 10 
![image](https://user-images.githubusercontent.com/17264532/32480897-95776e4a-c356-11e7-8a73-9d0b56c461a4.png)
When I change the "transparent" value (in package.json) to false，the demo run well.
When using nw 0.26.0，the demo run well.

**Comment by jtg-gg** [comment] 2017-11-07 07:35
@oliverlife can you check if NW.js v0.26.0 works ?

**Comment by oliverlife** [comment] 2017-11-07 07:55
@jtg-gg Yes, v0.26.0 works well.

**Comment by rogerwang** [comment] 2017-11-07 07:59
close as it's working in the latest version.

**Comment by rogerwang** [comment] 2017-11-07 08:01
closed in mistake. reopening...

**Comment by jtg-gg** [comment] 2017-11-07 09:53
this issue caused by WS_EX_COMPOSITED style that I enable to fix https://github.com/nwjs/nw.js/issues/6217, so I guess I'll need to revert WS_EX_COMPOSITED style

similar issue also reported on win7 (https://github.com/nwjs/nw.js/issues/6265)

**Comment by jtg-gg** [comment] 2017-11-07 11:50
@oliverlife I manage to reproduce on my other machine
but in my case, I can display the transparent window after I minimize then restore the window
can you try this work-around ?

**Comment by oliverlife** [comment] 2017-11-07 12:16
I can't display the window on my computer, so I can't minimize then restore the window.
But when I run the demo, there is a program icon of the demo on the taskbar.
I try to click the icon, but the window is still invisible.

**Comment by jtg-gg** [comment] 2017-11-07 14:47
@oliverlife, click the taskbar several times, i think you can minimize by using right click on taskbar

**Comment by oliverlife** [comment] 2017-11-08 03:33
@jtg-gg , menu, that showed by using right click on taskbar,  isn't include minimize option.

**Comment by oliverlife** [comment] 2017-11-08 03:34
@jtg-gg , menu, that showed by using right click on taskbar, doesn't have minimize option.

**Comment by jtg-gg** [comment] 2017-11-09 02:46
@oliverlife can you try using alt+spacebar for the minimize menu

**Comment by oliverlife** [comment] 2017-11-09 03:19
@jtg-gg I show the minimize menu using your method, I select the minimize item then restore, but the windows is still invisible.Maybe we have different win10 version between us,my win10 version is 1709.

**Comment by jtg-gg** [comment] 2017-11-09 03:35
@oliverlife I've 3 machine win10 version 1709
on the VM works from the time application started
the other 2 machine. needs to minimize then restore

anyway can you try my sample app here:
[transparency-5989.zip](https://github.com/nwjs/nw.js/files/1456203/transparency-5989.zip)

the sample app, runs as "show": false
then after the html doc is loaded, it will minimize / show, this workaround works on my "other 2 machine"

**Comment by jtg-gg** [comment] 2017-11-10 05:12
@oliverlife  I've made a pull request https://github.com/nwjs/chromium.src/pull/100
@rogerwang please accept it, and please also patch nw27

**Comment by rogerwang** [comment] 2017-11-13 15:16
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-11-13 15:16 UTC
Labels: needinfo
