### ISSUE TITLE
Pinning app in taskbar is creating an incorrect shortcut target

### ISSUE THREAD

**Issue by sumit6b** [nwjs/nw.js#5991] opened 2017-06-28 09:09 UTC
NW.js v0.21.6 
Windows 7 Professional

I am running my app by executing a command `<directory-nw>/nw.exe <directory-package.json>` .
Now from the task bar when I right click and choose "pin this program to taskbar" I get a shortcut whose target does not contain the first parameter which I used to start the process, i.e, target only has `<directory-nw>/nw.exe`. So when I try to open my app using this shortcut, default window of nwjs gets displayed.

I tried using [--nwapp](http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-nwapp) argument but it is not opening the app whose directory I am passing as the value of this argument.

**Comment by taher** [comment] 2017-07-10 07:38
@rogerwang The issue is specifically when the app package is in a different folder than the nwjs binary ... and the path to app (folder which has package.json) is passed as command line argument.

On pinning to taskbar, the shortcut target doesnt have path to app argument, which makes the app broken. Since this is the most visible shortcut for the users... they are not able to launch the app again once they pin shortcut to taskbar. 
![image](https://user-images.githubusercontent.com/79488/28007367-c1b78722-6570-11e7-9415-24734d9d7bfb.png)

**Comment by semmel** [comment] 2017-10-12 20:45
With NWJS v. 0.25.5 this issue may be fixed partly. I *can no longer confirm* that when pinned to the taskbar the exe parameters are missing.

When running the app from the pinned taskbar icon I find in the array `nw.App.argv` the *same parameters* which were given to `MyApp.exe` on the *initial launch* from a desktop shortcut or by console command.
However the `nw.App.argv` array contains additional items (`--profile-directory` and `--app-id`) which should just show in `nw.App.fullArgv`. So I guess taskbar pinning is still a little buggy here.

In my case I employ the `--user-data-dir=%APPDATA%\MyApp` parameter to direct the user data to the Windows `Roaming` folder. Previously this did not work when the user pinned my app to the taskbar, but with nwjs `0.25.5` it works now fine.

@Christywl Regarding the app title in the taskbar I *cannot confirm* this either. It looks ok now for me:
![Pinned Icon](https://docs.visisoft.de/data/public/739261?dl=true&ct=true&file=%2F9f3dda7c8c%2FPin%20to%20taskbar.png)
In my manifest: `"name": "TestApp"`

Test System:
* Win 10 x64
* nwjs 0.25.5 (nightly)
* MyApp.exe is nw.exe glued with package.nw (html sources zip file) via `copy /b`

**Comment by tphalp** [comment] 2018-05-07 19:25
Same issue here. On v0.29.3 of nwjs. 

When pinning to taskbar, lunching the app results in the NWJS window only. Same situation as @taher. App package (folder) is in a different location that the nwjs binary. The original shortcut that we install with the app passes the location to the binary, but when pinning, the shortcut for the pinned app doesn't have have the package location in the shortcut.

**Comment by rogerwang** [comment] 2018-06-02 01:34
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2018-06-02 01:34 UTC
Labels: EFK, P2, WIP, bug, triaged
