### ISSUE TITLE
process_info.cc probable access violation?

### ISSUE THREAD

**Issue by Yannicked** [nwjs/nw.js#4628] opened 2016-03-24 23:09 UTC
I'm using version 13.0.0 on windows 10 64 bit
When executing a function using the node-ffi library (it does work in nodejs), the application abruply closes without any error. It produces the following log entries:
`[0324/235841:ERROR:process_info.cc(608)] range at 0x5531453200000000, size 0x265 fully unreadable
[0324/235841:ERROR:process_info.cc(608)] range at 0x5531455200000000, size 0x265 fully unreadable
[0324/235841:ERROR:process_info.cc(608)] range at 0x0, size 0x265 fully unreadable
`

This is the application I'm trying to run: https://github.com/Yannicked/nw-cue-effects
It uses node-ffi to interface with a dll api provided by my keyboard manufacturer to controll the rgb leds of keyboard.

It also produces a crash dump using crashpad [Crash Dump.zip](https://github.com/nwjs/nw.js/files/188825/10961360-8ea1-4739-90cb-0d957884ce9a.zip)

**Comment by Yannicked** [comment] 2016-03-28 14:18
I've fixed it for me.
The crash was caused by returning a node::Buffer form a native module (which does work in plain node.js). I've rewritten my own module to return a array as a workaround.

**Comment by rogerwang** [comment] 2016-03-28 14:43
That's interesting. Will fix it with your case.

Yannick de Jong <notifications@github.com>于2016年3月28日周一 下午10:19写道：

**Comment by rogerwang** [comment] 2016-03-29 06:14
I hit some error when installing the sample provided by you: error downloading CUESDK.

Since you have pinpoint the root cause, could you please provide another minimal sample? Thank in advance.

**Comment by rogerwang** [comment] 2016-04-02 14:41
@ghostoy please try to reproduce.

**Comment by Yannicked** [comment] 2016-04-02 19:14
The module that crahsed nwjs was (it only works on windows): https://github.com/Yannicked/node-win-gdigrab/tree/3939bcf01345da4126578ae8db9f3007b357a619

small example on how to use it:

    var gdigrab = require('node-win-gdigrab');
    var gdi = new gdigrab();
    function parsedata(a) { // a is a array which contains the rgb values of your display 
      console.log('The top left pixel of your display has the values R: '+a[0][0]+' G: '+a[0][1]+' B:'+a[0][2]);
    }
    gdi.grab(parsedata);

**Comment by ghostoy** [comment] 2016-04-05 06:26
@Yannicked I cannot reproduce this on my Windows 7/8/10 with the minimal sample above. BTW the argument passed to `parsedata(a)` was a linear array, not a two-dimensional array.

**Comment by ghostoy** [comment] 2016-04-19 07:55
@Yannicked Do you still see this issue in latest 0.13 and 0.14 releases?

**Comment by ghostoy** [comment] 2016-05-23 05:25
Closed this issue since not receiving feedbacks for more than 4 weeks.

**Closed by ghostoy** 2016-05-23 05:25 UTC
Labels: nw13
