### ISSUE TITLE
iframe memory leak on nw 0.12.3 to 0.14.x

### ISSUE THREAD

**Issue by mangaga** [nwjs/nw.js#4866] opened 2016-05-19 02:27 UTC
this is a serious problem， all my customers could not endure it. 

#[nwjs/nw.js#3069]
#[nwjs/nw.js#1931]

**Comment by rogerwang** [comment] 2016-05-19 05:12
There is no need to submit issue which is duplicate of existing issue. You can just leave a message in the previous one.

**Closed by rogerwang** 2016-05-19 05:12 UTC
