### ISSUE TITLE
Windows snap is lost with frameless transparent window and webkit-app-region drag

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#6219] opened 2017-10-20 02:20 UTC
NWJS Version : SDK 0.26.0
Operating System : Win7 x64

### Expected behavior

Window snap should stay working as normal with frameless transparent window

### Actual behavior

Window snap is completely lost

### How to reproduce

Window snap behavior can be previewed here for better understanding: http://i1-news.softpedia-static.com/images/news2/snap-in-windows-10-overview-and-enhancements-489110-4.gif

Using a basic app, move the window against top or side edges of the screen, it should display the snap preview and letting it go will cause it to resize the app on its own to the preview size.

![aero](https://user-images.githubusercontent.com/8498057/31802187-39dd54f0-b53c-11e7-8bff-cefc3534d46d.png)

Instead there is no recognition of window snap and the described behavior is absent, the window never resizes

![noaero](https://user-images.githubusercontent.com/8498057/31802166-177f1ae2-b53c-11e7-9eaa-c203997357a2.png)

App sample using `package.nw` folder:

````html
<!DOCTYPE html>
<html style="background:white;height:100%;-webkit-app-region:drag">
    <head>
    </head>
    <body></body>
</html>
````

````json
{
    "author": "test",
    "description": "test",
    "main": "index.html",
    "name": "test",
    "version": "1.0.0",
    "window": {
        "frame": false,
        "transparent": true
    }
}
````

I don't know if this is expected behavior, meaning that this is meant to be like this when using a transparent frameless window, but thought it should be reported in case it is a bug.

**Comment by Christywl** [comment] 2017-10-20 06:32
I can reproduce this issue on Windows with nwjs-sdk-0.26.0.

**Comment by rogerwang** [comment] 2017-10-20 06:36
CC @jtg-gg , please take a look. Thanks in advance.

**Comment by kapilmoondra** [comment] 2017-10-23 16:02
Looks like this is an issue with smaller window size. We are developing a snapping application and facing same issue on windows platform. Window size is pretty much same as shown in problem here. Even elctron is facing similar issue and they have left it to Chromium and closed this issue as won't fix (https://github.com/electron/electron/issues/2170)

**Comment by Yonezpt** [comment] 2017-10-23 19:34
@kapilmoondra Sounds like a very different problem. This one appears to be just a botched window size calculation, leaving the width equal to the screen minus the resize border. If the mouse cursor didn't change then I would consider these being related, but they are not.

**Comment by jtg-gg** [comment] 2017-10-25 11:28
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/98
please also patch nw27

**Comment by rogerwang** [comment] 2017-10-26 01:47
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-10-26 01:47 UTC
Labels: bug, P3, triaged
