### ISSUE TITLE
nwdirectory attribute behaves like webkitdirectory in Win32 version of nw.js v0.12alpha2

### ISSUE THREAD

**Issue by stereoplegic** [nwjs/nw.js#3054] opened 2015-02-05 03:36 UTC
I didn't see an existing bug on this, so here's mine:

I'm writing an app that stores the path of the directory selected via HTML5 file input (with the nwdirectory attribute set) to a variable. This works as intended in v0.11.5 and 0.11.6 (I honestly can't recall whether it worked in v0.12alpha1).

As the title suggests, when building with nw.js v0.12alpha2, the value of an <input type="file" nwdirectory> is the file path of every file within the selected directory, a la the webkitdirectory attribute. I'm only building for Win32 and Linux64, and of the two only Win32 seems to be affected.

**Comment by felicienfrancois** [comment] 2015-02-05 08:11
This seems to be a duplicate of #2961

**Comment by felicienfrancois** [comment] 2015-03-09 09:55
Can be closed now fixed in 0.12.0)

**Comment by rogerwang** [comment] 2015-03-09 12:37
thanks for the reminder!

**Closed by rogerwang** 2015-03-09 12:37 UTC
