### ISSUE TITLE
Application crashes at startup on "certain" network configurations

### ISSUE THREAD

**Issue by mpunktcpunkt** [nwjs/nw.js#5078] opened 2016-07-05 08:58 UTC
Hi,

nw.js seems to crash at startup on certain network and pc configurations.
After some time i figured out that this line "require('http')" causes the crash.

Tested with versions: 0.14.6 64 bit, 
                               0.15.4 64 bit, 
                               0.14.6 sdk 64 bit (used for the crash dump)
Network Config:
The PC is connected via crossover cable to another host. Wifi is enabled but no network is connected.
OS: 
Windows 7 64 bit. I do not know which extra software might cause the crash. The app runs fine on another pc with the same network config

The attached crash dump is from a hello world example were i typed "require('http')" via the console

[app_crash_at_require_http.zip](https://github.com/nwjs/nw.js/files/347354/app_crash_at_require_http.zip)

Please let me know if i can provide any more information or should try something out. I do not have constant access to that machine but i can access it fairly often.

**Comment by ghostoy** [comment] 2016-07-07 08:07
It's wired because the crash shows it run out of memory when allocating memory for rendering.

Could you post the log file when you run into this issue? Run `nw --enable-logging --v=1 path/to/your/app` and you will find the log file in your app's data folder.

**Comment by mpunktcpunkt** [comment] 2016-07-07 10:00
Hi, 
tanks for your reply.Here is the log: 
[chrome_debug_crash.txt](https://github.com/nwjs/nw.js/files/351862/chrome_debug_crash.txt)

Memory is interesting. That machine has 8gb. Around half of it was "Available" but almost nothing was "Free". The App does not crash when started directly after PC reboot. 

Starting the nodeJs server via a node installation (V5.11.1) directly also always works.

Still, the only thing that is crashing is nwjs with the network settings mentioned above

**Comment by mpunktcpunkt** [comment] 2016-07-14 07:50
Hi,
could you find anything. Can i provide you with more information?

**Comment by ghostoy** [comment] 2016-07-14 08:10
@mpunktcpunkt No progress so far.  There is not fatal errors recorded in the log, but only some warnings. But shouldn't them fail NW in my opinion.

Did you tried to remove the data folder and restart your app? The data folder is located in `%LOCALAPPDATA%\<your-app-name>`.

**Comment by mpunktcpunkt** [comment] 2016-07-14 08:33
Hi,
I deleted the folder and restarted the app. Sadly it still crashes.

**Comment by Christywl** [comment] 2017-08-18 07:26
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by mpunktcpunkt** [comment] 2017-08-21 08:44
Sadly i cannot give you any updated information. This issue forced us to stop using NWjs

**Comment by Christywl** [comment] 2017-10-25 07:34
Close it.
If someone meets this issue again, please reopen it.

**Closed by Christywl** 2017-10-25 07:34 UTC
Labels: needinfo
