### ISSUE TITLE
Transparent frameless window with id gets smaller each time it is closed while minimized

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#6280] opened 2017-11-10 06:23 UTC
NWJS Version : SDK 0.27.0-beta1 and SDK 0.26.5
Operating System : Win7 x64

### Expected behavior

The window size should remain the same size the window had before being closed while it was minimized.

### Actual behavior

The window size is being reduced or saved with less size each time the window is closed while it was minimized.
Each time this happens it loses 64px in width and height.

### How to reproduce

Sample app with window **with an id** set to transparent frameless.
Minimize the window and close it via the task bar.
Open app again, window size is smaller by 64x64 in width and height.

Using `package.nw` method, sample can be found below

`package.json`
````json
{
    "author": "test",
    "description": "test",
    "main": "index.html",
    "name": "test",
    "version": "1.0.0",
    "window": {
        "id": "testWindow",
        "frame": false,
        "transparent": true
    }
}
````

`index.html`

````html
<!DOCTYPE html>
<html style="background:rgba(0,0,0,0.5);height:100%">
    <head>
    </head>
    <body>
        <div id="size-message" style="color:white"></div>
        <script>
                document.getElementById("size-message").textContent = "my window size is " + window.innerWidth + "px by " + window.innerHeight + "px";
        </script>
    </body>
</html>
````

Short recording showing the problematic behavior. Each time the window is being minimized, closed and opened again.

![ss](https://user-images.githubusercontent.com/8498057/32645511-1bad0006-c5d7-11e7-9d4d-965237a6d2aa.gif)

**Comment by Yonezpt** [comment] 2017-11-10 06:23
This does not happen if the window is closed while it is **not** minimized.

**Comment by Christywl** [comment] 2017-11-13 05:24
I can reproduce this issue on Windows 8.1 with nwjs-sdk-v0.26.5. This issue doesn't happen on Linux.

**Comment by jtg-gg** [comment] 2017-11-29 04:44
i am a bit busy now, will look into this once i am "free"

**Comment by Yonezpt** [comment] 2018-01-18 08:07
Any update on this one?

**Comment by jtg-gg** [comment] 2018-01-24 05:07
@Yonezpt just now I test with nw27.6 (latest from live build)
I can't reproduce this on win10

**Comment by Yonezpt** [comment] 2018-01-24 07:16
I just tested this on Windows 7 with SDK 0.27.5 and SDK 28 beta 1, the problem is still clearly there.

Make sure that you are really following the steps I provided; open app, minimize, close the app while it is minimized, open it again and the size is smaller than when you opened it before.

**Comment by rogerwang** [comment] 2018-01-24 07:25
0.28.0-beta1 was released before the fix. You could try this build:
https://dl.nwjs.io/live-build/nw28/01-23-2018/d70c598-f4f8fdb-4f1f894-3b59d35

**Comment by Yonezpt** [comment] 2018-01-24 07:35
@rogerwang I just tested on that linked build. the problem is still there unfixed.

**Comment by jtg-gg** [comment] 2018-01-24 07:55
@Yonezpt ok I can reproduce it on my win10, I didn't notice the "close" and "open" the app part

**Comment by Yonezpt** [comment] 2018-01-24 07:58
@jtg-gg No problem, it's not like it wasn't in the title of the issue either ;P

Take into consideration that this can be a consequence of these fixes:

#6248
#6221
#6219
#6204

Just saying so that the fix for this problem doesn't revert either of them.

**Comment by jtg-gg** [comment] 2018-01-26 07:50
@Yonezpt I've made the fix here: https://github.com/nwjs/chromium.src/pull/105
waiting @rogerwang  to patch nw28/29

**Comment by rogerwang** [comment] 2018-01-28 12:34
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2018-01-28 12:34 UTC
Labels: P2, bug, triaged
