### ISSUE TITLE
[v0.79.1 - arm64] libnode.dylib is missing

### ISSUE THREAD

**Issue by nebular** [nwjs/nw.js#8111] opened 2023-08-25 12:36 UTC
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x ] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior

The library "libnode.dylib" is missing in nwjs Framework/Versions/xxx (normal version) - however it is present on the SDK version.

This causes a crash when starting the normal version.

### Expected/Proposed Behavior

Add the libnode.dylib to the 0.79.1 normal flavor package.

### Additional Info

- Operating System:
- NW.js Version: v0.79.1 arm64
- Repro Link:
- Code snippet:
- Crash report:

```
82487:259:0825/142727.702754:FATAL:nw_content_renderer_hooks.cc(53)] Failed to load node library (error: dlopen(/Volumes/git.root/obscene-studio-project/core/cache/0.79.1/nwjs-v0.79.1-osx-arm64.zip-extracted/nwjs-v0.79.1-osx-arm64/nwjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/116.0.5845.96/libnode.dylib, 0x0001): tried: '/Volumes/git.root/obscene-studio-project/core/cache/0.79.1/nwjs-v0.79.1-osx-arm64.zip-extracted/nwjs-v0.79.1-osx-arm64/nwjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/116.0.5845.96/libnode.dylib' (no such file))
```

**Comment by KOSHACHIJ** [comment] 2023-08-27 03:45
Not only libnode ( libffmpeg also missed ), and not only on arm64 ( x64 has same issue ), on all 0.79.x builds ( 0, 1 and 2-nightly ).
Copying both ( libffmpeg / libnode ) from 0.78 build solves problem.

**Comment by nebular** [comment] 2023-08-27 19:16
I would suggest to copy them from the SDK version (in arm64 at least they are available), because 0.79.1 include a NodeJS upgrade - so if you copy it from 0.78.x you will miss the update. Regarding libffmpeg I have seen it is dangerous to use libraries from another version, the library seems quite coupled with the rest of the Chromium Core, and I sometimes got Segmentation Faults when loading videos by doing that. You can also get the version with proprietary codecs for 0.79.1 from https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases/tag/0.79.1 .

**Comment by ayushmanchhabra** [comment] 2023-10-23 00:16
@rogerwang can this be closed as duplicate of 8123?

**Comment by rogerwang** [comment] 2023-10-24 19:18
yes, thanks.

**Closed by rogerwang** 2023-10-24 19:18 UTC
Labels: needinfo
