### ISSUE TITLE
Mac builtin edit menu: can't remove last two items

### ISSUE THREAD

**Issue by donaldpipowitch** [nwjs/nw.js#3036] opened 2015-01-30 20:30 UTC
When using ´createMacBuiltin` with `edit` menu it seems I can remove every submenu item, but the last separator and the following two items ("Start Dictation...", "Special Characters...").

**Comment by mrfabbri** [comment] 2015-01-31 16:51
Closing as duplicate of #2812

**Closed** 2015-01-31 16:51 UTC
