### ISSUE TITLE
If the NWJS is set to be transparent, it will clash with the transparent theme of Windows 7, and the upper right side will not be able to click

### ISSUE THREAD

**Issue by onlyou** [nwjs/nw.js#6176] opened 2017-09-26 05:47 UTC
If the NWJS is set to be transparent, it will clash with the transparent theme of Windows 7, and the upper right side will not be able to click。
package.json-->"transparent": true,

Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
Operating System :

### Expected behavior

<!- What do you think should happen? ->

### Actual behavior

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by onlyou** [comment] 2017-09-26 05:52
If Windows7 sets the theme to a basic theme, it can be resolved

**Comment by onlyou** [comment] 2017-09-27 17:16
There are pictures to show the effect
![snipaste20170928_011306](https://user-images.githubusercontent.com/2231544/30927242-6e13352c-a3ea-11e7-917b-53a869dd67fd.jpg)

**Comment by jtg-gg** [comment] 2017-09-28 01:48
@onlyou can you send your sample app? I can't reproduce it

**Comment by onlyou** [comment] 2017-09-28 02:17
The green area can be clicked normally
In the red area, if there is a function button, the background layer of the program will be clicked directly
I've tried a lot of Windows 7, and that's how it works
Close the "package.json" transparently, and then it's normal
But the program has no effect

thanks for your help!


![666](https://user-images.githubusercontent.com/2231544/30946373-3a9a2a38-a436-11e7-8dce-fd5b7856fc99.gif)

**Comment by jtg-gg** [comment] 2017-09-28 02:26
@onlyou , I can reproduce it, looks like after certain width or height, then the problem occurs

**Comment by rogerwang** [comment] 2017-09-30 01:53
reassign to @jtg-gg since it's in the transparency feature.

**Comment by jtg-gg** [comment] 2017-10-02 13:13
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/96
please also patch nw26

**Comment by rogerwang** [comment] 2017-10-02 13:33
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-10-02 13:33 UTC
Labels: bug, P2, triaged
