### ISSUE TITLE
nwworkingdir not working

### ISSUE THREAD

**Issue by MikeNerevarin** [nwjs/nw.js#2948] opened 2015-01-15 20:04 UTC
v0.11.5 x64 Linux

```javascript
var input=document.createElement('input');
input.type='file';
input.setAttribute('nwworkingdir','/home/');
input.click();
```

File dialog appears, but in current nw directory.

**Comment by jonwwilkes** [comment] 2015-02-19 19:58
Can confirm bug with 0.12.0-alpha3 on
Windows 7 Professional

Can also confirm bug with alpha2 on:
Debian Jessie (testing) amd_64

**Comment by jonwwilkes** [comment] 2015-02-19 20:03
Oops, I neglected to use forward slashes on Windows.  So nwworkingdir actually works there with 0.12.0-alpha3.

I'll try later on Debian with alpha3.

**Comment by rogerwang** [comment] 2015-02-19 23:57
will be fixed before the next beta release.

**Comment by chrisJohn404** [comment] 2015-07-01 17:55
I assume this bug did not get fixed in the "next beta release" as it is not fixed in nwjs 0.12.2, windows 32bit.  I tried both "C:\Users" and "C:\Users\" and neither were working, the default directory kept showing up as the cwd, process.cwd().  I can go through other nwjs OS releases and check those if needed.  Any idea when this will be fixed?

**Comment by jonwwilkes** [comment] 2015-07-21 15:21
Hi Roger,
Can you please fix this?  It's an important feature for any app that saves or reads a file (which I assume would be many apps).

Right now I'm essentially relying on the "Recent Files" item that is part of Gnome's open/save dialog.  But that's generally an extra click (or, many clicks on first use).

**Comment by jonwwilkes** [comment] 2015-07-24 21:26
Can confirm it doesn't work on GNU/Linux 32-bit (running some relatively recent version of Ubuntu, can't remember which)

**Comment by zhaojunmo** [comment] 2015-08-06 01:52
Win 7, I tried v0.12.0, v0.12.1, v0.12.2, v0.12.3, all of them were not working, please help to fix it, thank you very much.

**Comment by matthew-dean** [comment] 2015-10-14 03:24
Oh. This isn't fixed nor has a workaround?

**Comment by matthew-dean** [comment] 2015-10-14 16:08
See #3372 for a possible workaround.

**Comment by jonwwilkes** [comment] 2015-10-14 17:02
That workaround has only been tested on Windows.  What happens under Linux or OSX?
But the bigger problem is communication.  The github issues are littered with reports that nwworkingdir is broken.
Kevin Fan even wrote to the list asking for financial support for his work on nw.js, and I told him to name a price for fixing this issue.  Still haven't heard back.
-Jonathan
 


     On Wednesday, October 14, 2015 12:09 PM, Matthew Dean <notifications@github.com> wrote:
   

 See #3372 for a possible workaround.—

**Comment by matthew-dean** [comment] 2015-10-14 17:12
@jonwwilkes OSX already worked fine for me. I tested it on OSX and it didn't break anything. Not sure about Linux. Who is Kevin Fan?

**Comment by jonwwilkes** [comment] 2015-10-14 18:11
Hi Matthew,Here's a link to the relevant post:https://groups.google.com/forum/#!topic/nwjs-general/WjP5lbixm9g

I'll test this workaround later tonight on a Debian machine.  Of course if it works I'll use it.  Still, the devs' lack of communication is a bit frustrating.
-Jonathan 


     On Wednesday, October 14, 2015 1:13 PM, Matthew Dean <notifications@github.com> wrote:
   

 @jonwwilkes OSX already worked fine for me. I tested it on OSX and it didn't break anything. Not sure about Linux. Who is Kevin Fan?—

**Comment by jonwwilkes** [comment] 2015-11-01 05:11
Some more details about this:
when using the nwworkingdirectory with nwsaveas, I can confirm that the convoluted (and dangerous) workaround does indeed work.

When using nwworkingdirectory _without_ nwsaveas (i.e., an "Open" file dialog) the workaround doesn't work.

@matthew-dean: can you confirm that you tested the workaround with both "Save" and "Open" dialogs?

**Closed** 2016-09-19 06:43 UTC

**Comment by smolleyes** [comment] 2016-09-23 10:18
hi

i reopen it since it s still not working on windows (nwjs 14.7 / 17.4 / 18 ... ) when i try to open a mapped drive like Z:\2016\CA\EIFFAGE\Paris\16CA091 or \\Myserver\something\blabla it s not working (pasting the same link in the opened file dialog works normally)

no problems on osx/linux

thanks
