### ISSUE TITLE
OS X:Unable to load the extension source

### ISSUE THREAD

**Issue by caopc01** [nwjs/nw.js#5292] opened 2016-09-10 08:48 UTC

**Comment by ghostoy** [comment] 2016-09-14 05:52
@caopc01 Please post a full description of the issue including NW.js versions, your OS & version, sample app and steps to reproduce.

**Comment by ghostoy** [comment] 2016-12-27 02:54
Close this issue since not receiving feedbacks for a long time. Please reopen it if you still experience this issue.

**Closed by ghostoy** 2016-12-27 02:54 UTC
Labels: needinfo
