### ISSUE TITLE
Can't to close widow after redirected 

### ISSUE THREAD

**Issue by lyaskovec** [nwjs/nw.js#5345] opened 2016-10-05 07:22 UTC
**version:** nwjs-sdk-v0.14.7-win-ia32 
**os:** win10 x64

```
nw.Window.open("https://vk.com/away.php?to=https%3A%2F%2Fgoogle.com.ua", {}, function(win){
    setTimeout(function(){
        console.log("Try close")
        win.close()
    }, 3000)
})
```

When I create a window which is redirected on another page, after redirect being completed I cant close the window programatically.

**Comment by Christywl** [comment] 2017-03-22 03:09
@lyaskovec , I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.21.3. The second window could be closed by `win.close()`.

**Comment by lyaskovec** [comment] 2017-03-22 09:06
@Christywl I was reproduce on version 0.14.7 TLS . And now I can reproduce again this issue
In newest version working as expected

**Comment by RohitSharma27** [comment] 2017-03-23 02:29
You should wait for loaded event on win(window object) before using it.

**Comment by lyaskovec** [comment] 2017-03-23 07:39
@RohitSharma27 loaded event fired before I call method close

**Comment by rogerwang** [comment] 2017-09-25 02:47
close until more information is available.

**Closed by rogerwang** 2017-09-25 02:47 UTC
Labels: needinfo
