### ISSUE TITLE
0.35.0b1 - OSX - App will crash if using menu or click outside window

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6852] opened 2018-10-31 14:24 UTC
MacOS 10.13.6 High Sierra

Using test app from #6850 - run app and click outside window and app will crash. It will also crash if any menu options are used (eg: Preferences). It was noted that if the Dev Tools window was open then the crash would not occur. No problem with builds up to 0.34.2
Screenshot -

<img width="1291" alt="crashreport" src="https://user-images.githubusercontent.com/11089335/47794442-5fbd5f80-dd18-11e8-922b-1d1f678374e9.png">

All tests done with prior deletion of app profile.

**Comment by rogerwang** [comment] 2018-11-02 06:15
I can't reproduce the crash here -- when I click outside of the window it just switches to the other application underneath. And menu items seems ok (no Preferences found with the sample)

**Comment by rogerwang** [comment] 2018-11-02 11:56
This is fixed in git and will be available in the next [build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2018-11-02 11:56 UTC
