### ISSUE TITLE
No access to devtools when package.json > main point to http URL

### ISSUE THREAD

**Issue by metalfox6383** [nwjs/nw.js#6672] opened 2018-06-06 22:16 UTC
Hi:

I can't access to DevTools when package.json file point to http URL:

{
  "name": "Balanza",
  "main": "http://192.168.1.241:7777/habacuc",
  "window": {
	"toolbar": true
  },
  "dependencies": {
    "serialport": "^6.2.0"
  }
}

How I enable it?

Thanks.

**Comment by Christywl** [comment] 2018-06-07 00:44
Duplicate of #6648 , and you could oepn DevTools with keyboard shortcut F12 on Windows and Linux or ⌘+⌥+i on Mac.

**Closed** 2018-06-08 00:33 UTC
