### ISSUE TITLE
v0.20.0 right button click in Developer Tools crash

### ISSUE THREAD

**Issue by josendf** [nwjs/nw.js#5668] opened 2017-01-30 08:27 UTC
We are testing NW.js v0.20.0 (sdk version) and noticed that in some circumstances the application crashes when right clicking in the Developer Tools window. Tested under Window 10 x64, steps to reproduce:

1. Start the app
2. Press F12
3. Right click in the Developer Tools window
4. The app crashes.

If you open the Developers Tools through the app context menu (not using the F12 key), the crash does not happens. Follows the console log and attached the crash dump:

[11480:11268:0130/092116.153:FATAL:window_impl.cc(138)] Check failed: atom. 87
Backtrace:
        v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFDA0D5C241+366209]
        v8::internal::compiler::InstructionOperand::Compare [0x00007FFDA0CE51DA+109674]
        v8::ResourceConstraints::set_max_executable_size [0x00007FFDA11473E4+742916]
        v8::ResourceConstraints::set_max_executable_size [0x00007FFDA1146E5E+741502]
        v8::ResourceConstraints::set_max_executable_size [0x00007FFDA1146F90+741808]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA341F65F+390607]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA3409169+299225]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA33E4348+148152]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA33D10C0+69680]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA341B548+373944]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA3401EC7+269879]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA3405C26+285590]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA3405AD4+285252]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA340379F+276239]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA3406C15+289669]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA34062FF+287343]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA3414F18+347784]
        v8::internal::compiler::JSCreateLowering::common [0x00007FFDA33D342D+78749]
        v8::internal::interpreter::Register::operator!= [0x00007FFDA22C9C1C+86828]
        v8::internal::compiler::LoadElimination::zone [0x00007FFDA215C965+590517]
        v8::internal::compiler::LoadElimination::zone [0x00007FFDA210AB69+255161]
        v8::internal::compiler::LoadElimination::zone [0x00007FFDA210AB17+255079]
        v8::Extension::dependency_count [0x00007FFDA0699E39+1458457]
        v8::Extension::dependency_count [0x00007FFDA06954C9+1439657]
        v8::internal::compiler::InstructionOperand::Equals [0x00007FFDA048F381+127649]
        v8::internal::compiler::InstructionOperand::Equals [0x00007FFDA048567D+87453]
        v8::internal::compiler::InstructionOperand::Equals [0x00007FFDA049103C+135004]
        v8::Extension::dependency_count [0x00007FFDA05C6A2B+593163]
        v8::internal::ParseInfo::is_eval [0x00007FFDA1514EBC+628428]
        v8::internal::GCIdleTimeHandler::GCIdleTimeHandler [0x00007FFDA0D7CBA9+48553]
        v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFDA0D30247+185991]
        v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFDA0D2F25A+181914]
        v8::internal::GCIdleTimeHandler::GCIdleTimeHandler [0x00007FFDA0D7DB71+52593]
        v8::internal::GCIdleTimeHandler::GCIdleTimeHandler [0x00007FFDA0D7E104+54020]
        v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale [0x00007FFDA0D4C1CE+300558]
        v8::internal::compiler::Linkage::GetStubCallContextParamIndex [0x00007FFDA0B0C4B0+78528]
        v8::internal::compiler::InstructionSequence::instructions [0x00007FFDA03CCA4E+1031102]
        v8::internal::compiler::InstructionSequence::instructions [0x00007FFDA03CE08B+1036795]
        v8::internal::compiler::InstructionSequence::instructions [0x00007FFDA03C8910+1014400]
        v8::internal::interpreter::Register::operator= [0x00007FFDA09F0E9E+120750]
        v8::internal::interpreter::Register::operator= [0x00007FFDA09F0D90+120480]
        v8::internal::interpreter::Register::operator= [0x00007FFDA09F0204+117524]
        ChromeMain [0x00007FFD9F886B5C+236]
        (No symbol) [0x00007FF78A6E5924]
        (No symbol) [0x00007FF78A6E2CFF]
        IsSandboxedProcess [0x00007FF78A73CFC3+126739]
        BaseThreadInitThunk [0x00007FFDE8488364+20]
        RtlUserThreadStart [0x00007FFDE85970D1+33]

[0130/092116.271:ERROR:process_info.cc(608)] range at 0x4d5b31e600000000, size 0x225 fully unreadable
[0130/092116.271:ERROR:process_info.cc(608)] range at 0x4d5b320600000000, size 0x225 fully unreadable
[0130/092116.271:ERROR:process_info.cc(608)] range at 0x4d5b320800000000, size 0x225 fully unreadable

[c718a201-3c26-4e2c-963c-2427562a1906.zip](https://github.com/nwjs/nw.js/files/738383/c718a201-3c26-4e2c-963c-2427562a1906.zip)

**Comment by conceptualspace** [comment] 2017-01-30 19:46
duplicate of #5659

**Comment by rogerwang** [comment] 2017-02-06 07:15
close as duplicate.

**Closed by rogerwang** 2017-02-06 07:15 UTC
