### ISSUE TITLE
v0.15.4   couldn't  load plugin....

### ISSUE THREAD

**Issue by lipan** [nwjs/nw.js#5041] opened 2016-06-28 15:18 UTC
Windows: 32bit  

PeperFlash 

help!

**Comment by lipan** [comment] 2016-06-28 16:08
{
    "description": "Pepper Flash Player", 
    "name": "Flapper", 
    "version": "21.0.0.216", 
    "x-flapper-revision": "45688", 
    "x-ppapi-arch": "ia32", 
    "x-ppapi-os": "win",

**Comment by rogerwang** [comment] 2016-06-29 02:38
close as duplicate of #4979

**Comment by RohitSharma27** [comment] 2016-06-29 02:38
Please refer the comment on #4979 and see if it helps.

**Closed by rogerwang** 2016-06-29 02:38 UTC

**Comment by lipan** [comment] 2016-06-29 05:52
@RohitSharma27   thanks !
