### ISSUE TITLE
[NW15/16] Using arg "--in-process-gpu" avoids a game (on Steam) runs on windows 7 

### ISSUE THREAD

**Issue by MadSpyxFR** [nwjs/nw.js#5178] opened 2016-08-02 07:52 UTC
Hi,

When you use the arg "--in-process-gpu" in package.json (or in command line),run the app through Steam,  2 nw.exe process are created and nothing else happens; neither other nw.exe process nor gameoverlay.exe. Everything works as intended on windows 8.1

The app can run the 1st time (sometimes)

Tested with a "hello world" project with nw 0.15 and 0.16 on windows 7 pro 64b

Regards,

**Comment by ghostoy** [comment] 2016-08-03 01:23
@MadSpyxFR Could you upload the "hello world" project and post step-by-step guide of running it in Steam?

**Comment by MadSpyxFR** [comment] 2016-08-03 22:38
@ghostoy I will post 2 examples tomorrow

**Comment by MadSpyxFR** [comment] 2016-08-08 21:47
@ghostoy sorry for the delay.

[https://www.dropbox.com/s/ve0r519i23xogza/Nw.js%20bug.zip?dl=0](url)
What you need to reproduce:
- A windows 7 pro 64b with all updates and steam client.
- A valid steamworks account ( or at least a game using nodewebkit with an exe named nw.exe)

Step to reproduce:
1/ upload on your steam depot the content of folder nw15 (or copy it in the app you choose)
2/ run the app via steam client
3/ if you are lucky the app runs the 1st time, close the app and try to restart the app via steam client.
4/ 2 nw.exe are created and nothing else
5/ kill nw.exe process
6/ open package.nw
7/ remove "--in-process-gpu" arg from package.json
8/ save and run again via steam client
9/ you should be able to run each time you click on run via steam client (with 4 nw.exe process).

Do the same with nw16 folder content.

**Comment by ghostoy** [comment] 2016-08-17 05:12
@MadSpyxFR I'm trying to register an account of steamworks. There are two kinds of partner accounts. Which should I choose: 

* Ready to register your Cyber Cafe or VR Arcade locations with the Steam Site License program?
* Looking for the SteamVR Tracking License?

**Comment by MadSpyxFR** [comment] 2016-08-17 07:05
@ghostoy , if you don't have a greenlit game, you can't register... but if you have a steam account (as player), I can find a way for you to test (maybe send you via mail a steam key for a nw.js game)

**Comment by ghostoy** [comment] 2016-08-22 05:32
@MadSpyxFR Sorry for the late response. My account on steam: ghostheaven. And please send me the steps to run your app in steam client. Thank you :)

**Comment by MadSpyxFR** [comment] 2016-08-23 21:11
@ghostoy  I send you a mail with all info and steam key. 
Regards,

**Comment by ghostoy** [comment] 2016-08-24 08:21
@MadSpyxFR I tested on a Windows 7 32bit VM and could not reproduce your issue. Both 0.15.0 or 0.16.0 can be started by Steam client. I copied your `package.nw` to my NW downloads and launch it with Steam, since your nw.exe is 64bit.

**Comment by MadSpyxFR** [comment] 2016-08-24 17:16
@ghostoy yes the bug occurs only for windows 7 pro 64b

**Comment by ghostoy** [comment] 2016-08-29 06:32
@MadSpyxFR I'm still not able to reproduce this issue on my Win7 x64 pro VM. I tried to launch with desktop icons or within Steam client. The hello word app can always be launched without exceptions.

**Comment by Anonymitet** [comment] 2016-08-29 22:09
I can reproduce this problem when I run it thorugh Steam. It leaves ghost NW processes behind after closing the application which makes steam think it is still running and nothing happens when I try to run it again.

**Comment by rogerwang** [comment] 2017-11-29 02:01
This should be fixed now. See #6059

**Closed by rogerwang** 2017-11-29 02:01 UTC
Labels: bug, triaged
