### ISSUE TITLE
Window and modal boxes features changed witn nw2 enabled

### ISSUE THREAD

**Issue by nwOkido** [nwjs/nw.js#7217] opened 2019-11-15 19:09 UTC
======== TEMPLATE BUG FORM ========

NWJS Version : 0.42.4
Operating System : Linux Mint 18.3 Cinnamon 3.6.7, kernel 4.15.0-66-generic

### Expected behavior

1. Window resizing with the mouse cursor on the edged of the window is possible,
2. The window opens in the center of the screen,
3. Modal dialog boxes boxes open in the center of the screen.

### Actual behavior

1. Window resizing with the mouse cursor is not possible,
2. The window does not open in the center of the screen, it is shifted to left,
3. Modal dialog boxes open at the top center of the screen.

### How to reproduce
When "chromium-args" is set to "--disable-features=nw2", the listed three items show expected behavior, set to "--enable-features=nw2" gives the actual behavior.
 

Have a nice day, Okido

**Comment by Luzzifus** [comment] 2019-11-19 08:47
> Window resizing with the mouse cursor is not possible

To elaborate on that, resizing is only not possible (at least for me), when the window is frameless.

**Comment by DimPaDev** [comment] 2019-11-20 11:15
I can confirm this bug with the latest version too (0.42.5) , Hopefully it will be fixed soon , I cant enable nw2 features in my apps with frameless windows because of this.

**Comment by cyantree** [comment] 2019-12-09 18:37
I experience similar problems with `nw2` and `0.42.6`. In my case the window state won't be stored and restored when specifying an `id`. Maybe this is related to your findings.

@rogerwang Should I open a separate issue for this?

**Comment by nwOkido** [comment] 2020-01-01 11:22
NWJS Version : 0.43.3
Operating System : Linux Mint 18.3 Cinnamon 3.6.7, kernel 4.15.0-66-generic
I can confirm that with "chromium-args" set to "--enabled-features=nw2" the behavior is:

1. Window resizing with the mouse cursor on the edged of the window is possible, the handles appear, **solved**
2. The window opens in the center of the screen, with "window.position": "center" in package.json the window is centered, **solved**
3. Modal dialog boxes boxes open in the center of the screen, dialog boxes open at the top of the screen, **not solved**

Have a nice day, Okido

**Comment by cyantree** [comment] 2020-01-01 13:47
Yes, `0.43.3` also fixed resizing for my. However it didn't fix storing/restoring the window state.

**Comment by rogerwang** [comment] 2020-01-02 03:35
@nwOkido could you provide a sample for Modal dialog boxes?

**Comment by nwOkido** [comment] 2020-01-02 19:58
NWJS Version : 0.43.3
Operating System : Linux Mint 18.3 Cinnamon 3.6.7, kernel 4.15.0-66-generic
Example is in the zip, nw.js SDK files are in the modal-example folder, the file in /data is the target referenced in package.json.
[2020-01-02-modal-example.zip](https://github.com/nwjs/nw.js/files/4017173/2020-01-02-modal-example.zip)

Have a nice day, Okido

**Comment by rogerwang** [comment] 2020-01-04 07:58
I started your sample, but didn't find any 'edit' button as described in the instruction.
<img width="1091" alt="Screen Shot 2020-01-04 at 3 56 18 PM" src="https://user-images.githubusercontent.com/165401/71762484-e2d4d980-2f0a-11ea-9f95-aaa32cc3bcff.png">

**Comment by nwOkido** [comment] 2020-01-04 09:31
In a clean install during the first load the software "thinks" that it is loaded over http while it actually is loaded form the system, depending on this origin a different view template is loaded, this is something that I need to fix.
If you click Reload in the menu on the right the edit button will become visible and you can do the 3 steps to get a modal box warning.

Have a nice day, Okido

**Comment by rogerwang** [comment] 2020-01-04 09:35
There is no "Reload" to click here...

**Comment by nwOkido** [comment] 2020-01-05 12:01
That is odd, I tried on 2 Linux machines before posting.
Anyway there is a more simple example, a modal alertbox shows the same behavior.
File is attached, remove the txt extension from the file.

Have a nice day, Okido
[modalbox.html.txt](https://github.com/nwjs/nw.js/files/4023349/modalbox.html.txt)

**Comment by rogerwang** [comment] 2020-01-05 13:28
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed** 2020-01-05 13:27 UTC
Labels: nw2

**Comment by nwOkido** [comment] 2020-01-05 14:15
Thanks.

**Comment by rogerwang** [comment] 2020-01-06 06:26
A nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200105-162000/69c924066. Please try it.
