### ISSUE TITLE
Missing Line Numbers and Source Mapping in DevTools w/ NW.js 0.66.0+

### ISSUE THREAD

**Issue by djmisterjon** [nwjs/nw.js#7936] opened 2022-08-05 14:26 UTC
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
devtool not work anymore,  line number is missing, vscode debbuger not work anymore

### Expected/Proposed Behavior
devtool should work,  line number should work, vscode debbuger should work.

### Additional Info

- Operating System:
- NW.js Version: 0.66.0
- Repro Link: https://github.com/djmisterjon/nwjsvitedevtool-issue-0.66/issues/2
- Code snippet: none
- Crash report: none

---

0.66
log and maybe related to sourceMappin ? this make impossible to debug in 0.66
![image](https://user-images.githubusercontent.com/24865815/183096821-d987aac7-d007-46f6-8b00-36f792c9557c.png)

0.65
![image](https://user-images.githubusercontent.com/24865815/183097237-74d42314-0535-4dd0-a15b-f874ab6c18aa.png)

plz see branch to test 
![image](https://user-images.githubusercontent.com/24865815/183097463-48bb602e-4f92-42fc-ba64-15c464eb426f.png)

`npm i`
than 
`npm run start-nw`

**Comment by sysrage** [comment] 2022-08-05 14:46
No need to clone the repro. Any simple NW.js app reproduces this behavior (missing line numbers and other mapping in DevTools). I have confirmed this also happens on NW.js 0.67.0. The issue is present in both Windows and Linux.

**Comment by sysrage** [comment] 2022-08-05 14:47
@rogerwang, this breaks a great deal of the development/debugging process. If you could give it attention, we'd all appreciate it.

**Comment by sysrage** [comment] 2022-08-05 14:48
May be related to:
- #7927

**Comment by rogerwang** [comment] 2022-08-05 15:30
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2022-08-05 15:30 UTC
Labels: test-todo, regression
