### ISSUE TITLE
About nw.exe remain after close

### ISSUE THREAD

**Issue by kscorpio** [nwjs/nw.js#6588] opened 2018-04-27 02:59 UTC
NWJS Version : nwjs-sdk-v0.14.7-win-ia3 &  nwjs-sdk-v0.30.1-win-ia3 
Operating System : win64

 I use NWJS to developt a app ，use serial port，
1 . When i want to close app , use window.close or app.quit., the widow really close
but there are many nw.exe processes remain， need kill manually . if not, app can not restart 

2 sometime  , to open app just start some precesses ,window can not start

**Comment by Christywl** [comment] 2018-04-27 06:13
I can't reproduce this issue on Windows 10 x64 with nwjs-sdk-v0.30.1-ia32/x64.  All nwjs processes end if closing the nwjs app with `win.close()` or `App.quit()`.

**Comment by Christywl** [comment] 2018-05-11 07:51
close until there is more information

**Closed by Christywl** 2018-05-11 07:51 UTC
Labels: needinfo

**Comment by rtimmortal** [comment] 2018-09-04 12:39
you should try to clear your cache in appdata
