### ISSUE TITLE
Issue using nwdirectory property

### ISSUE THREAD

**Issue by jminnick** [nwjs/nw.js#3020] opened 2015-01-29 14:55 UTC
EDIT: After doing more testing. This is not a build issue. It is a regression issue. My local NW version is v0.11.5 and my app was building with v0.12 bits. So it looks to me like an issue isolated to v0.12.

After performing a build using node-webkit-builder the file input field implemented with the nwdriectory property is returning all the files as opposed to the directory that was selected.

This happens on both OSX and Windows. This is easily reproduced with a basic file input field using the nwdirectory property.

Pre-build the FileList looks like this:

![nwkbug1](https://cloud.githubusercontent.com/assets/3810135/5959453/70d15a84-a79c-11e4-933a-885aeb57edec.PNG)

Post-build the FileList looks like this:

![nwkbug2](https://cloud.githubusercontent.com/assets/3810135/5959490/c2e37cd0-a79c-11e4-9ffe-4ff97970c798.PNG)

**Comment by floydpink** [comment] 2015-02-03 13:12
This seems to be a duplicate of #2961

**Comment by felicienfrancois** [comment] 2015-03-09 09:56
Can be closed now (fixed in 0.12.0)

**Closed** 2015-03-09 12:38 UTC
