### ISSUE TITLE
nwsaveas removing extention

### ISSUE THREAD

**Issue by ognb** [nwjs/nw.js#3702] opened 2015-07-23 00:28 UTC
nwsaveas="filename.txt" it will be "filename" why?
##

**Comment by conceptualspace** [comment] 2017-01-30 04:47
try adding an accept attribute to your input (http://www.w3schools.com/tags/att_input_accept.asp) and just provide the extension, ex, `accept=".txt"`

**Comment by Christywl** [comment] 2017-05-24 01:09
should be duplicate of #4460

**Comment by Christywl** [comment] 2017-10-10 04:53
close until there is more information.

**Closed by Christywl** 2017-10-10 04:53 UTC
Labels: needinfo
