### ISSUE TITLE
NWJS not supported for Mac M1?

### ISSUE THREAD

**Issue by tufik2** [nwjs/nw.js#8073] opened 2023-05-21 02:56 UTC
There is any plan to support Mac with an M1 chip directly from NWJS stable channel. I see that when we download Mac, that point directly to x64 and need rosetta to run, that is a big performance issue to create apps. Thanks...

**Comment by rogerwang** [comment] 2023-05-21 03:40
Close as duplicate of #7620

**Closed by rogerwang** 2023-05-21 03:40 UTC
