### ISSUE TITLE
Right Click Closes nwjs

### ISSUE THREAD

**Issue by Kriknos** [nwjs/nw.js#5531] opened 2016-12-08 05:42 UTC
Version 0.19.0 sdk
Windows 7 professional 64bit

If I start my app and then start the Developer Tools, if I right click anything in my app window, nwjs crashes. But if I start my app, and right click before I open the Developer Tools, everything works just fine. Also right clicking in the Developers Tools does not cause any problem.

Is not a huge deal, but is bit aggravating when I am testing some of the more complex components of my app and have to resetup my test case.

**Comment by ghostoy** [comment] 2016-12-08 06:35
I can't reproduce this issue. Would you please submit a sample app?

**Comment by fritx** [comment] 2016-12-08 13:07
@ghostoy same here.. related issue comments: https://github.com/nwjs/nw.js/issues/4697#issuecomment-262419775

**Comment by Kriknos** [comment] 2016-12-09 04:08
Nothing fancy about my app it just loads a url and the entire app is html, css, and javascript.

Here's what my package.json looks like
```
{
	"main": "http://www.my-site.com/index.php",
	"name": "my-app",
	"window": {
		"title": "My App",
		"icon": "my-icon.png",
		"width": 1000,
		"height": 800
	},
	"node-remote": "http://www.my-site.com",
	"chromium-args" : "--enable-experimental-web-platform-features"
}
```
Here's the first few lines of my javascript (my-site.com/main.js) that uses a few nwjs features
```
if (typeof(require) == "function")
{
	var gui = require('nw.gui');

	var win = gui.Window.get();

	win.maximize();

	win.title = 'My App';

	var clipboard = gui.Clipboard.get();
}
```
After that nothing that would be related to nwjs. My app can run in a browser just fine.

**Comment by ghostoy** [comment] 2016-12-27 02:50
I still cannot reproduce this issue with the sample app provided. @Kriknos 
Could you share a full app?

**Comment by ghostoy** [comment] 2017-01-16 08:43
Close it since not receiving feedbacks for more than 3 weeks. Please reopen it if you have any updates.

**Closed by ghostoy** 2017-01-16 08:43 UTC
Labels: needinfo
