### ISSUE TITLE
node-webkit incompatible with Mac OS X - CPU usage goes to 100% and system hangs

### ISSUE THREAD

**Issue by Emasoft** [nwjs/nw.js#2723] opened 2014-12-01 15:25 UTC
Node webkit-helper is frequently using more than 100% of cpu on OS X, heating up the system and stopping all other processes, and making the system unresponsive until the webkit-helper process is killed manually from system monitor. This happens with almost all nw based applications I tried. It seems that node-webkit has a problem with the underling OS X. Upgrading to Yosemite didn't solved the issue.

**Comment by chino23** [comment] 2015-01-08 09:38
any progress on the performance issues on mac?

**Comment by shrewdlogarithm** [comment] 2015-01-15 00:26
I have no idea if this is related but I have almost the polar-opposite issue (in 0.11.5)

On OSX (Mavericks - updated to latest), my app frequently hangs/freezes - it becomes totally unresponsive to any events or inputs and there's no messages/warnings or pattern to when it happens...

Oddly, it also disappears from the 'Force Quit' list when this happens (as if the processes are no longer 'mine'?)  The window remains visible and can be dragged-around but I'm forced into Activity Monitor to kill the 'node webkit' and 'node webkit helper' processes before I can re-run it (wherein it will work for a while before crashing again)

Note: in Activity Monitor, the processes are shown using a small amount of CPU - around 1% - which grows over time (but would take days to reach 100%)

Given I'm running on a VM - my issues COULD just be down to that (it's hardly a supported approach) but I could also be seeing a similar issue but the VM is preventing a CPU race condition?

**Comment by AndryBray** [comment] 2015-02-01 18:44
Testing nwjs 0.12.0 alpha2 I have the same problem with webkit CSS3 animation.
Tested on MacOS 10.6.8 and 10.8.5 (both 64bit).
On the oldest, the CPU reaches 150%, on the new one 30/40%.
This is a test case: http://codepen.io/anon/pen/jEGbdZ

Using nodewebkit 0.10.5 the CPU usage is less but in my opinion still too much (about 10% of a i7 quad core 2,8GHz)

PS: Testing the same on Chrome 40.0.2214.94 and the chrome process reaches 20 - 25 % of CPU usage.

**Comment by tommoor** [comment] 2015-02-24 17:10
@rogerwang is there some way we can debug this, get inside the node-webkit process? This is happening every single day in our app and it's driving us up the wall :wink:

**Comment by rogerwang** [comment] 2015-02-24 19:06
@tommoor I'll check it with @AndryBray 's case asap.

**Comment by tommoor** [comment] 2015-02-24 22:15
@rogerwang I'm not sure whether the CSS3 issue is the same one or not, we're having this occur with the app completely idle - it will just gradually keep getting worse until it's using 100%+ of the CPU.

I want to help here - let me know how to debug the node-webkit Helper process and we'll probably find the problem in hours :wink:

**Comment by rogerwang** [comment] 2015-02-25 01:32
tried the case here with Macbook Pro (10.10.1):
Chrome 41: 40-45%
NW.js 0.12.0-alpha3 live build: 40-45%

So still cannot reproduce it here. Will find another OSX system to try.

**Comment by rogerwang** [comment] 2015-02-25 01:54
@tommoor can you send me your app and steps to reproduce it?

**Comment by tommoor** [comment] 2015-02-25 02:58
@rogerwang our app requires multiple users to work and only reproduces often after being open for many hours. It's going to be a lot easier if I can do the debugging on my end...

**Comment by felicienfrancois** [comment] 2015-02-25 08:49
May be related to #3030 (CSS3 transitions not smooth on Mac OS X)

**Comment by kamesh-a** [comment] 2015-02-25 11:16
Reproducible snippet. issue#2899

```

var http = require('http');
var fs = require('fs');
var path = require('path');

function download(url, callback) {

    var dest;

    if(/darwin/.test(process.platform))
        dest = path.join(process.env.HOME,'Downloads',path.basename(url));
    else if(/^win/.test(process.platform))
        dest = path.join( process.env.HOMEDRIVE, process.env.HOMEPATH,'Downloads',path.basename(url));
    else{
        console.warn('Platform is not Win/Mac');
        return;
    }

    var file = fs.createWriteStream(dest);

    var request = http.get(url, function(response) {

        response.pipe(file);

        var len = parseInt(response.headers['content-length'] || response.headers['x-goog-stored-content-length'], 10);
        var total = len / 1048576;
        var cur = 0;

        response.on("data", function(chunk) {
            cur += chunk.length;
            console.log("Downloading " + (100.0 * cur / len).toFixed(2) + "% " + (cur / 1048576).toFixed(2) + " mb\r" + " Total size: " + total.toFixed(2) + " mb")
        });

        file.on('finish', function() {
            file.close(); // close() is async, call callback after close completes.
            if (callback)
                callback('success');
        });

        file.on('error', function(err) {
            fs.unlink(dest); // Delete the file async. (But we don't check the result)
            if (callback)
                callback(err.message);
        });
    });
}

download('http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-osx-ia32.zip',function({console.error(arguments)});


```

**Comment by tommoor** [comment] 2015-02-26 16:46
Another day... 

![screen shot 2015-02-26 at 8 45 34 am](https://cloud.githubusercontent.com/assets/380914/6396541/dc8316b6-bd93-11e4-9fd0-829c07523312.png)

![screen shot 2015-02-26 at 8 45 18 am](https://cloud.githubusercontent.com/assets/380914/6396542/dc97072a-bd93-11e4-9611-e0ea734d07ef.png)

**Comment by shrewdlogarithm** [comment] 2015-02-26 17:19
33 threads! - what does that read when you first start the app?

Are you using setTimeout or (particularly bad) setInterval within your code?

**Comment by tommoor** [comment] 2015-02-26 17:34
setTimeout and setInterval are used in the code, yep.

**Comment by shrewdlogarithm** [comment] 2015-02-26 17:46
It's a long-shot, but I've found that swamping setTimeout/setInterval with
jobs can lead to high cpu usage and even a system lockup (on WIndows here)
 - I'd assumed, being single threaded, you could use those as a 'job stack'
but but it seems that might not be a wise choice in some cases...

As I said tho, it's a longshot.

**Comment by tommoor** [comment] 2015-02-26 18:08
I see, thanks - I don't think that's the case here, as you can see in the profiler our JS is doing no work and the app is sat idle. There are a couple of intervals but usually a max of ever 1000ms.

**Comment by rogerwang** [comment] 2015-02-27 05:36
@tommoor I'll add some tracing support so it would be helpful to know what's happening there. Before that is there something usual in devtools?

**Comment by bebejane** [comment] 2015-03-07 22:26
i can report the same issues here. our app needs to run 24/7 so its frustrating having to restart it all the time. it seems to happen when the app is idle for a long time...

**Comment by kennyhk** [comment] 2015-03-23 04:45
＠bebejane, @rogerwang 
Yes, my app is same issues here.
Must idle it for at least 800 sec.  
idle it for 10000+ sec is good to reproduce this issue.

**Comment by kennyhk** [comment] 2015-03-25 09:57
@rogerwang 
https://www.youtube.com/watch?v=HjTTxEtwTwE&feature=youtu.be

This demo show how to trigger the nwjs cpu issue by the following steps :

1. Open an app that base on nwjs
2. Idle it about 2 hours
3. keep shake the app windows
4. at 01:03, CPU usage is more then 100%!

**Comment by felicienfrancois** [comment] 2015-03-25 12:04
Is it related to App Nap ?
What  happens if you disable App Nap ?

**Comment by dannykok** [comment] 2015-03-26 14:04
@felicienfrancois tested with my app with the same issue. Problem wasn't resolved by disabling App Nap. CPU goes way higher after idling the app for around 2-3 hours. 

I am running it on Yosemite 10.10.2 macbook pro 15" retina 2013. End users reported similar findings on Macbook Air as well so I guess it may not be hardware dependent.

**Comment by rogerwang** [comment] 2015-03-27 13:36
@kennyhk could you please send your app to me, or extract a case from it? That would be helpful for me to reproduce it here.

**Comment by kennyhk** [comment] 2015-03-27 14:20
@rogerwang 
yes, but that is not my app in demo video : 
https://popcorntime.io

**Comment by MarcFowler** [comment] 2015-04-20 15:02
I get the same thing (OSX 10.10.3, iMac). I don't know if it's caused by CSS3 animations, though I have some running. Even if I remove those nodes, it doesn't go back down again. Even if I quit the window with them in, it doesn't seem to go down.

I'm using `process.nextTick` and a couple of ~30,000ms `setTimeout/setInterval` calls but nothing that I'd have expected to cause this.

**Comment by kennyhk** [comment] 2015-04-30 05:19
@rogerwang 
hi, i done some test result, just for your information :


**test case 1 -  simple apps (no internet apps) with 10 hours idle**
 - code : https://github.com/zcbenz/nw-sample-apps
 - build : nwjs v0.12.0, 64bit
 - env : iMac (Mid 2011), OSX 10.10.2 , intel core i5 2.5GHz, 4GB 1333 MHz DDR3
 - result : no any problem. low CPU usage and fast GUI response.



**test case 2 - file download without idle**
 - code : https://github.com/nwjs/nw.js/issues/2899
 - build : nwjs v0.12.0, 64bit
 - test file : http://ipv4.download.thinkbroadband.com/512MB.zip
 - env : iMac (Mid 2011), OSX 10.10.2 , intel core i5 2.5GHz, 4GB 1333 MHz DDR3
 - result : high CPU usage (over 100%) when downloading


**test case 3 - simple CSS3 animation with 3 hours idle**
- code : http://www.w3schools.com/css/tryit.asp?filename=trycss3_animation_direction2
- build : nwjs v0.12.0, 64bit
- env : iMac (Mid 2011), OSX 10.10, intel core i5 2.5GHz, 4GB 1333 MHz DDR3
- result : no any problem. low CPU usage and fast GUI response.


**test case 4 - complex app with 3 hours idle on OSX 10.10**
- app : https://popcorntime.io
- env : iMac (Mid 2011), OSX 10.10.2 , intel core i5 2.5GHz, 4GB 1333 MHz DDR3
- result : high CPU usage (over 100%), GUI response slow like hang**


**test case 5 - complex app with 3 hours idle on OSX 10.9**
- app : https://popcorntime.io
- env : MacBook Pro (Early 2011), OSX 10.9.4, intel core i5 2.5GHz, 4GB 1333 MHz DDR3
- result : high CPU usage (over 100%), **but GUI response still smooth and fast!**

**Comment by rogerwang** [comment] 2015-04-30 06:22
@MarcFowler could you please share your app to me? I'm eager to reproduce it here.

@kennyhk thanks for your effort and the information. Regarding test case 4, can it be reproduced every time? and what's the version inside the app? I'll check it.

**Comment by kennyhk** [comment] 2015-04-30 08:35
@rogerwang 

sorry for i don't know what is the version because that is not my app. 

But I have another complex app, the result is same as test case 4, via v0.11.6 and v0.12.0
it can be reproduced every time with idle.

**Comment by MarcFowler** [comment] 2015-04-30 09:59
Sorry @rogerwang, it's a really complex app (i.e. with a lot of other stuff going on with it) and I've not got the ability right now to replicate it in a contained app. I'll do my best as soon as I can though. I have a very similar Mac (iMac 2011, though I have more RAM) to @kennyhk there and I get the same results. I can replicate the issue he outlined in case 4 too, which says something at least?

**Comment by rogerwang** [comment] 2015-04-30 11:11
@kennyhk I'll check with popcorntime. Could you please share your "another complex app" to me?

**Comment by kennyhk** [comment] 2015-04-30 13:04
@rogerwang
i has been send an email to you (roger@nwjs.io) about my app.
one more discovery, slow GUI response problem can trigger by minimize(hide to dock)/restore the app after idle.

**Comment by rogerwang** [comment] 2015-04-30 13:47
@kennyhk regarding "one more discovery", does it apply to your app, or popcorntime, or any other NW apps? And does it mean minimize/restore after 3hrs idling, or minimize/restore after a short idle time after launching the app?

**Comment by lealife** [comment] 2015-04-30 18:04
I have the same problems with nwjs-0.12.0 & 0.12.1 on mac ox
![image](https://cloud.githubusercontent.com/assets/1699428/7419225/5911cb52-efa6-11e4-9c30-12ffcbf04f09.png)
I just open a link with nwjs

**Comment by rogerwang** [comment] 2015-05-01 07:26
@kennyhk I downloaded popcorntime 3.7 beta (newest version) but cannot reproduce it here. It's running  on NW 0.9.2 btw.

**Comment by rogerwang** [comment] 2015-05-01 07:28
I'll try to add some log here and make a special build for you to collect some information hopefully. That will happen soon after nw 0.13.0-alpha1 release. It's still best if it can be reproduced here.

**Comment by ersingencturk** [comment] 2015-05-12 03:55
Same here, can it be related to graphic card ?
Any chance if any having this problem have a mac with this card: Intel Iris Pro 1536 MB

![screen shot 2015-05-12 at 06 53 13](https://cloud.githubusercontent.com/assets/280623/7579901/b4dc745c-f873-11e4-896a-9ab5c6b1c3c5.png)

**Comment by eabovsky** [comment] 2015-05-14 19:57
Can confirm. CSS3 animations seem to be the cause of the CPU consumption spike.

I had a small animated element in my app which used CSS keyframes, which would run at ~30% cpu according to the activity monitor. After removing the animated element, average CPU consumption went from ~30% to 10%.

**Comment by rogerwang** [comment] 2015-05-17 02:42
please try this build for the fix:

http://dl.nwjs.io/live-build/05-17-2015/0038f72-296de67-be948af-459755a-2bdc251-1764a45/nwjs-v0.12.1-osx-x64.zip

btw, It's supposed to fix the cpu hog while idling, not high utilization under load.

**Comment by rogerwang** [comment] 2015-05-18 15:18
Thanks to @kennyhk for working with me closely on the issue. He verified the issue is fixed.

For issue similiar with this one (100% while idle), e.g. higher CPU utilization than Node, please submit separate issue. Thanks.

**Closed by rogerwang** 2015-05-18 15:18 UTC
Labels: bug, mac-only

**Comment by kennyhk** [comment] 2015-05-19 03:09
Thanks to @rogerwang!  We wait in hope for the new release. NWJS the best!

**Comment by chino23** [comment] 2015-05-19 03:14
Thanks a lot @rogerwang . Really appreciate it!

**Comment by eabovsky** [comment] 2015-05-20 18:23
Hey guys, another observation I just made on OSX:

If I use the "--disable-gpu-vsync " chromium flag, it will make my "nwjs Helper" process spike to 100%+ CPU.

**Comment by stephan-nordnes-eriksen** [comment] 2015-06-05 03:04
In my case I had a simple d3.js animation (spinning thing) which, when removed, fixed the issue for me.
