### ISSUE TITLE
How to get image from clipboard

### ISSUE THREAD

**Issue by comptron** [nwjs/nw.js#4654] opened 2016-03-30 09:51 UTC
Hi, 

I am using NW.js v.0.13, on windows 7
And i would like to know if there is  a way to get image from clipboard.
As you mention in the documents, for now it is supported for string type only.
When this option will be supported?
Is there another way to achieve this result?

Thanks,

**Comment by rogerwang** [comment] 2016-04-02 06:43
we'll see this. Close as duplicate of #2677

**Closed by rogerwang** 2016-04-02 06:43 UTC
