### ISSUE TITLE
webview's "beforeunload" event do'nt work

### ISSUE THREAD

**Issue by a379933101** [nwjs/nw.js#8056] opened 2023-04-10 06:11 UTC
<webview id="foo" src="test.html" style="width:100%;height: 100%;" partition="trusted" allownw></webview>

test.html:
<body>
        <a href="test2.html" >test2</a>
        <script>
             window.addEventListener('beforeunload', (event) => {
                event.preventDefault();
                event.returnValue = '';
            });
        </script>
    </body>
 
the code ' window.addEventListener('beforeunload' .. '  have no effect

**Comment by a379933101** [comment] 2023-04-10 06:13
<webview id="foo" src="test.html" style="width:100%;height: 100%;" partition="trusted" allownw></webview>

**Comment by a379933101** [comment] 2023-04-10 06:13
webview id="foo" src="test.html" style="width:100%;height: 100%;" partition="trusted" allownw>

**Comment by panther7** [comment] 2023-04-10 08:54
It did not ever worked... #6945

**Comment by tharatau** [comment] 2023-04-17 22:23
Duplicate of #6945

**Closed** 2023-04-17 22:23 UTC
