### ISSUE TITLE
evalNWBin() not working in 0.16.1?

### ISSUE THREAD

**Issue by alexandervrs** [nwjs/nw.js#5236] opened 2016-08-25 13:23 UTC
I wanted to update the NW.js version in my app to make use of the new Chrome App functions, so I replaced the NW.js SDK and converted my .js files to bin using the new nwjc

When I ran the app though, no error or problems but seemed like Javascript was... disabled or something. So with further tests, I saw that evalNWBin() was simply not working.

I made a small sample to make sure that was the case and it seems the line,
    nw.Window.get().evalNWBin(null, "bins/test.bin");
is never executed

[Here is the file](https://www.dropbox.com/s/r8pcp9gv5k01cux/testNW.zip?dl=1), just drop it in your 0.16.1 SDK folder and run nw.exe

**edit**: Googling the issue seems I've found another user with the same issue too [here](https://groups.google.com/forum/#!topic/nwjs-general/qJ03mWrZJNU)

**Comment by ghostoy** [comment] 2016-08-26 05:21
@alexandervrs Did you see this issue when DevTools is open? It's a known issue #3388.

> The reason is that v8 won't load the serialized code blob when debugger is attached: https://github.com/nwjs/v8/blob/nw12/src/compiler.cc#L1291

**Comment by alexandervrs** [comment] 2016-09-03 19:38
I am using the SDK version of NW.js. I am not sure if the Dev Tools were open, but I believe it didn't work even if they were closed. I've since, just loaded the scripts with regular <script src> and then it works.

**Comment by ghostoy** [comment] 2016-09-14 05:16
@alexandervrs I can't reproduce this issue with both 0.16.1 or 0.17.0 on both Mac and Windows. I'm closing this bug until we can figure out a way to reproduce.

**Closed by ghostoy** 2016-09-14 05:16 UTC
