### ISSUE TITLE
🐞 [BUG] Multi-screen Maximized Transparent Window, Click Throughable -wrong reseted Clickable Bounds

### ISSUE THREAD

**Issue by wesamco** [nwjs/nw.js#4888] opened 2016-05-24 13:46 UTC
* which version are you using: Newest nightly build 24/5/2016 
http://dl.nwjs.io/live-build/05-24-2016/nw15-9833156-678e4d4-eec6faf-3233243/v0.15.0/nwjs-sdk-v0.15.0-win-x64.zip
* OS version are you running: Windows 10 Build 14332
* Provide a reproducible case if possible: Not needed
* crash dump file if it's a crash: there is no crash

[@jtg-gg #4846](https://github.com/nwjs/nw.js/issues/4846#issuecomment-221145760) I installed the latest nightly build, and tried it, the issue wasn't fixed.

here is a 10 Seconds video with explanation https://www.youtube.com/watch?v=0Y8MwzwIFUc
- the bug is not in my code, the window covers all the screens, I can drag the yellow rectangle to the far left of the second monitor and the white 50 px thick solid border is to prove that the window extends to all the screens.

- the new clickable bounds of the window gets reseted to wrong clickable bounds, which seems to be the bounds of the primary screen, but the bounds of the window does not change, see the white border, in the Screen shot. I had some guesses of the bug origin, [guess 1 ::ResetWindowRegion](https://github.com/jtg-gg/chromium.src/blob/cdeae7658e12fea2d3a2ff9b1dd719a0064d3b6f/ui/views/win/hwnd_message_handler.cc#L1157 ) || [guess 2]( https://github.com/jtg-gg/chromium.src/blob/cdeae7658e12fea2d3a2ff9b1dd719a0064d3b6f/ui/views/win/hwnd_message_handler.cc#L1777) ||  [guess 3](https://github.com/jtg-gg/chromium.src/blob/cdeae7658e12fea2d3a2ff9b1dd719a0064d3b6f/ui/views/win/hwnd_message_handler.cc#L2380 ) || [guess 4](https://github.com/jtg-gg/chromium.src/blob/cdeae7658e12fea2d3a2ff9b1dd719a0064d3b6f/ui/views/win/hwnd_message_handler.cc#L2405-L2408)

- see the screenshot and explanation, <img src="http://i.imgur.com/bC085Bs.jpg">
the horizontal red line seperates the two monitors, and the blue line marks the far right end of the updated clickable bounds, they are the exact same bounds of the primary screen of the system, I counted the pixels with the Paint select tool..
- the clickable bounds update seems to happen on mouse up event, because I can drag the yellow rectangle to the far far right with only one drag and then I can't click it.

**Comment by rogerwang** [comment] 2016-05-25 01:03
CC @jtg-gg

**Comment by jtg-gg** [comment] 2016-05-27 02:52
@wesamco I'm a bit busy now, will look into it next or next next week

**Comment by jtg-gg** [comment] 2016-05-31 12:14
@wesamco I can't access the youtube video, it is private, can you make it public ?

**Comment by wesamco** [comment] 2016-05-31 12:29
@jtg-gg  Done.

**Comment by jtg-gg** [comment] 2016-06-02 12:57
@wesamco I think I'll need you sample code.
I was using testing the test app from https://github.com/nwjs/nw.js/issues/4846, resizing the window size to extend 2 monitor when i click, I was able to click the button and right end my 2nd monitor

**Comment by wesamco** [comment] 2016-06-03 14:49
@jtg-gg to reproduce the bug, don't resize the window, it should be unresizeable,

### package.json
```
{
  "name": "App",
  "version": "1.0.0",
  "description": "",
  "chromium-args" : "--enable-transparent-visuals --disable-gpu --force-cpu-draw --enable-touch-events --enable-logging=stderr",
  "main": "App/dist/index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "window": {
    "title": "App",
    "toolbar": false,
    "frame": false,
    "transparent": true,
    "resizable": false,
    "show_in_taskbar": false,
    "width": 10000,
    "height": 10000
  },
  "author": "",
  "license": "ISC"
}
```

### Index.js
```
var gui = require('nw.gui');
var win = gui.Window.get();

gui.Screen.Init();
var screens = gui.Screen.screens;

function initWindowState() {
  var fartop = 0;
  var farleft = 0;
  var totalwidth = 0;
  var totalheight = 0;

  for (var i = 0; i < screens.length; i++) {
    var screen = screens[i];
    var rect = screen.bounds;
    totalwidth += rect.width;
    totalheight += rect.height;
    if (rect.x < farleft) {
      farleft = rect.x;
    }
    if (rect.y < fartop) {
      fartop = rect.y;
    }
  }
  win.moveTo(farleft, fartop);
  win.resizeTo(totalwidth, totalheight);
}

initWindowState();
```

### index.html
```
<html>

<head>
  <meta charset="utf-8">
  <title>App</title>
  <style>
html {
    width: 100%;
    height: 100%;
}

body {
    background-color:rgba(0,0,0,0);
    width: 100%;
    height: 100%;
    margin: 0;
    /*border: 50px solid white;*/
    overflow: hidden;
    position: relative;
}
</style>
  <script src="jquery-2.1.3.min.js"></script>
  <script src="jquery-ui.js"></script>
  <script type="text/javascript" src="index.js"></script>
  <script>
$(function () {
    $(".resizeable").resizable({
        containment: "#background",
        stop: function (event, ui) {

        }
    });

    $(".draggable").draggable({
        cursor: "crosshair",
        containment: "#background",
    });
});
 </script>

</head>

<body>

  <div class="draggable-resizable" style="background-color:yellow;">
  </div>
  


</body>

</html>
```

**Comment by jtg-gg** [comment] 2016-06-06 02:24
@wesamco I've these error when running your sample code
chrome-extension://anaelpolhngelhbmhepmjcfmmkjdngid/index.html:26
$(function () {
^

ReferenceError: $ is not defined
    at chrome-extension://anaelpolhngelhbmhepmjcfmmkjdngid/index.html:26:1

**Comment by wesamco** [comment] 2016-06-06 02:44
@jtg-gg  the $ is the Jquery javascript framework object, 
download the jquery libraries I linked from the offical jquery website,  
this error is caused because they are not being imported to index.html with the script tags 
```
<script src="jquery-2.1.3.min.js"></script>
  <script src="jquery-ui.js"></script>
```
because you didn't download the libraries and put them in the project folder, with package.json.

**Comment by jtg-gg** [comment] 2016-06-06 02:45
I'm using
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.11.4/jquery-ui.min.js"></script>

now the error is gone, but I don't see any yellow box to drag ?

**Comment by wesamco** [comment] 2016-06-06 02:48
add this css styling
```
draggable, resizable {
    display:block;
    background-color:rgba(0,0,0,0);
    overflow: hidden;
}

draggable:hover { 
    border-radius: 20px;
    border: 20px solid white;
    cursor: pointer;
}
```

**Comment by jtg-gg** [comment] 2016-06-06 02:50
still nothing

**Comment by wesamco** [comment] 2016-06-06 02:57
I am making a repro project repo, will be ready in minutes.

**Comment by wesamco** [comment] 2016-06-06 03:13
here is a repro https://github.com/wesamco/nwrepro
```
git clone https://github.com/wesamco/nwrepro
npm install
nw
```

**Comment by jtg-gg** [comment] 2016-06-06 03:25
thx @wesamco I can see and drag the yellow box
but, I can't reproduce your bug, I can drag the yellow box on both end of my monitor
can you share your monitor configuration ?

my main screen 1st is on left side, my 2nd is on right side
the 1st monitor is 1920x1200
the 2nd monitor is 1920x1080

well I'm running windows on VM, so I can't swap the left and right to test :(

**Comment by wesamco** [comment] 2016-06-06 03:33
![image](https://cloud.githubusercontent.com/assets/9993663/15811338/578f696e-2bb0-11e6-84bf-baebd684dabc.png)
working like in the video

**Comment by wesamco** [comment] 2016-06-06 04:01
@jtg-gg is it really vital to debug it and step in code?  I described what caused it the bug in all details, can't you guess what might have caused it?
are you running Windows 10? could it be Desktop Window Manager (dwm) related?

**Comment by jtg-gg** [comment] 2016-06-06 04:20
@wesamco I still can't reproduce your bug =( have you try it on another machine ?
I can drag the yellow box on both end of the screen
yes I'm using win10, I've changed my resolution and display configuration like yours

**Comment by jtg-gg** [comment] 2016-06-08 02:34
@wesamco have you tried on another machine?

**Comment by jtg-gg** [comment] 2016-06-10 03:45
closing this issue since I can't reproduce the bug

**Closed by jtg-gg** 2016-06-10 03:45 UTC
