### ISSUE TITLE
nw2: transparency not working as intended

### ISSUE THREAD

**Issue by Luzzifus** [nwjs/nw.js#7221] opened 2019-11-19 08:44 UTC
NWJS Version : 0.42.5
Operating System: Win10 (1903)

### Expected behavior

Setting the window subfield "transparent" to true should yield a transparent window with the desktop or whatever window is behind it shining through.

### Actual behavior

There is a Windows 95 style window in the background of my transparent window. When opening the window, sometimes the actual window content shows the that background window (as in the screenshot below), sometimes it is transparent to whatever is behind it as expected. But the (too large) border around it is always visible.

![display_error](https://user-images.githubusercontent.com/431996/69130392-bc6cf300-0ab0-11ea-8e67-b68a9fc08778.png)

### How to reproduce

Only happens in NW2 mode, works as expected with "chromium-args": "--disable-features=nw2".
Just run nw.Window.open() with transparency parameters: 

    let windowOptions = {
      show: true,
      title: 'test',
      width: 250,
      height: 100,
      min_width: 100,
      min_height: 50,
      position: 'center',
      frame: false,
      transparent: true
    };
    nw.Window.open('html/widget.html', windowOptions);

The background window seems to disappear when "transparent" is set to false. Or at least it is not too large anymore, can't really tell.

#7230

**Comment by gpetrov** [comment] 2019-11-20 13:59
@rogerwang - got this as well. Transparent windows on Windows do not work:

When opened I get:

![transparent_bug_nw2_42 5_result](https://user-images.githubusercontent.com/504730/69244883-24513580-0ba6-11ea-9959-bce17ab1c990.png)

While it should be:
![transparent_bug_without_nw2_42 5_result](https://user-images.githubusercontent.com/504730/69244905-2c10da00-0ba6-11ea-81f5-4046c89a63fb.png)
(when opened with --disable-features=nw2)

Here is my test project:
[transparent_title_42.5.zip](https://github.com/nwjs/nw.js/files/3869571/transparent_title_42.5.zip)

**Comment by Blatman** [comment] 2019-11-23 13:08
Tried the above test on Win10 1803 in Parallels 13 got -

![nwdiff](https://user-images.githubusercontent.com/11089335/69479142-0841d400-0df2-11ea-8953-a5a232ef3807.jpg)

Note: I added --disable-gpu-compositing --force-cpu-draw to the manifest.

**Comment by TheRealDannyyy** [comment] 2019-12-03 15:24
Can't reproduce issue on Windows 7. This seems to be Windows 10 exclusive.

**Comment by rogerwang** [comment] 2019-12-30 11:58
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed** 2019-12-30 11:57 UTC
Labels: nw2
