### ISSUE TITLE
In Windows 11, if you set frame to false in fullscreen, it will capture the mouse at the edge of the screen.

### ISSUE THREAD

**Issue by wangzhuxing12** [nwjs/nw.js#7941] opened 2022-08-12 23:13 UTC
In Windows 11, if you set frame to false in fullscreen, it will capture the mouse at the edge of the screen.

**Comment by ayushmxn** [comment] 2022-08-24 04:27
Duplicate of #7873

**Closed by ayushmxn** 2022-08-24 04:27 UTC
