### ISSUE TITLE
Cannot load NPAPI plugins in new versions of NW (0.11.2 & 0.11.5)

### ISSUE THREAD

**Issue by firebbs** [nwjs/nw.js#2923] opened 2015-01-11 16:49 UTC
Upgraded nw from *0.9.2* to *0.11.5* (tried also *0.11.5*) and any plugins in same application stoped load.
I tried to put libraries (e.g. libflashplayer.so) in "plugins" sub-folder of project (same directory with nw executable), but with no results...
with 0.11.5 *navigator.plugins* - lenght 0, with 0.9.2 - length 5

**OS:** Linux 3.17.4-1-ARCH #1 SMP PREEMPT Fri Nov 21 21:14:42 CET 2014 x86_64 GNU/Linux

**Comment by shennan** [comment] 2015-01-14 14:11
@firebbs I think you're putting the wrong file into the plugins directory. Node-webkit doesn't support the Pepper API plugins that Chrome uses. I'm on a Mac (not Linux), but I got it to work by including a 'Flash Player.plugin' file into the 'plugins' directory. The 'libflashplayer.so' didn't work for me either.

**Comment by dtauschke** [comment] 2015-01-17 06:25
I have the same problem and found:

"Known issues:
- NPAPI plugins not working on Linux; We'll enable PPAPI plugins soon. " 

in the release notes of version 0.11.0."

Is there a timeline for PPAPI support on Linux?

**Comment by rogerwang** [comment] 2015-01-17 14:45
@dtauschke it will be supported in nw12

**Comment by ncannasse** [comment] 2015-02-15 17:13
@rogerwang any ETA for nw12 ? I need PPAPI for one of my projects (requires Flash Stage3D Linux support, only available through PPAPI)

**Comment by rogerwang** [comment] 2015-02-15 22:56
The final version will be released in the same time frame with Chrome 41 release. I'll try to fix this in the next beta release. Thanks for your patience.

**Comment by rogerwang** [comment] 2015-02-18 05:59
build available here, use it with
`--ppapi-flash-path=/opt/google/chrome-beta/PepperFlash/libpepflashplayer.so --ppapi-flash-version=15.0.0.152`

http://dl.nwjs.io/live-build/02-17-2015/37585d5-4aad9fe-b1a5bb9-add523e-2bdc251-c114bb7/

will be released with the next version.

**Closed by rogerwang** 2015-02-18 05:59 UTC

**Comment by KYSergey** [comment] 2015-03-18 11:26
I was successful when I used it in package.json
```"chromium-args": "--ppapi-flash-path=plugins/libpepflashplayer.so --ppapi-flash-version=17.0.0.134" ``` for linux
```"chromium-args": "--ppapi-flash-path=plugins/pepflashplayer.dll --ppapi-flash-version=17.0.0.134" ``` for windows
@rogerwang Can I defined this args in runtime according to platform instead of having different copies of package.json for each platform?

**Comment by AlexandreSousa** [comment] 2015-04-24 12:12
could post an example of package.json file

**Comment by plashenkov** [comment] 2015-04-30 19:52
I can confirm it works with pepflashplayer.dll and NW.js 0.12.1 32bit on Windows.
Nevertheless, a console window appears and disappears quickly on executing nw.exe.
When using NPAPI there is no such issue.

**Comment by plashenkov** [comment] 2015-04-30 20:18
Is it necessary to specify --ppapi-flash-version parameter? Looks like it works without it.

**Comment by siddhartha-gupta** [comment] 2015-05-07 12:01
@plashenkov I'm also facing the similar issue for pepflashplayer.dll, i.e console window appears and disappears quickly on executing nw.exe. Have you found a fix for the same?

**Comment by plashenkov** [comment] 2015-05-07 12:05
@siddhartha-gupta No, I have not found a fix.

**Comment by siddhartha-gupta** [comment] 2015-05-12 06:15
Seems quite relevant - https://bitbucket.org/chromiumembedded/cef/issue/1606/unwanted-console-window-displayed-when
