### ISSUE TITLE
AlwaysOnTop does not work with Fullscreen or kiosk

### ISSUE THREAD

**Issue by wmbaum** [nwjs/nw.js#4554] opened 2016-03-11 16:31 UTC
In 0.13-rc1, on at least Windows, AlwaysOnTop does not work with fullscreen or even almost fullscreen windows.

AlwaysOnTop works correctly for small windows, but not for windows that cover most or all of the monitor. For example, on a 1920x1080 monitor, a 1920x1040 AlwaysOnTop window successfully prevents other windows from being diplayed on top of it, but a 1920x1060 or larger window will not.  Both claim success (win.isAlwaysOnTop()==true), but only the smaller window is actually always on top.  Above a certain size, some property of the window doesn't actually get set and other apps can be focused on top of it.

**Comment by krneticz** [comment] 2016-03-13 15:59
I'm experiencing the same issue, with rc1 and rc2.

**Comment by krneticz** [comment] 2016-03-18 11:28
This issue is significant because, when you run some content in your app that have Flash, Windows terminal window flashes over the app for a moment. That is happening with nwjs 12 and 13 with PPAPI Flash. Is there a way to avoid that window to flash? If not, then fixing this is critical for our application to be able to go to production with nw13, since when always on top works as it should, that does not happen.

**Comment by krneticz** [comment] 2016-04-08 12:20
@rogerwang is this planed to be fixed anytime soon? This is very important to us (SeeYouLink).

Thanks,
Zoran

**Comment by rogerwang** [comment] 2016-04-08 12:36
Will fix this soon. Thanks.

**Comment by rogerwang** [comment] 2016-04-09 01:28
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-04-09 01:28 UTC

**Comment by rogerwang** [comment] 2016-04-10 00:08
http://dl.nwjs.io/live-build/04-10-2016/723bab6-897a464-c2a3dcf-65b297d/

**Comment by rogerwang** [comment] 2016-04-10 00:09
It was caused by an upstream measure that not letting window covering task bar becomes always-on-top: https://bugs.chromium.org/p/chromium/issues/detail?id=320107
