### ISSUE TITLE
My client always collapses, gui.App.setCrashDumpDir(dir)Can not be used

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#5568] opened 2016-12-17 02:30 UTC
My client always collapses, I would like to know through some error log to what is the problem, but according to the document on the introduction of this link can not be used!
[https://github.com/nwjs/nw.js/wiki/crash-dump]

**Comment by phpjishu** [comment] 2016-12-17 02:30
@rogerwang [https://github.com/nwjs/nw.js/wiki/crash-dump](url)

**Comment by phpjishu** [comment] 2016-12-17 02:31
@rogerwang 
What should i do?

**Comment by phpjishu** [comment] 2016-12-17 02:34
@ghostoy What should i do?I use the 0.19.2

**Comment by phpjishu** [comment] 2016-12-17 02:42
This is a screenshot of errors that Google Chrome has collected!
http://f.xinyisoft.org/3bbc00f5ac0d8e694d845b97b714db1a

**Comment by phpjishu** [comment] 2016-12-17 05:53
@rogerwang 
NW err log 👍 
[1212/131025:ERROR:process_reader_win.cc(233)] ReadMemory at 0x9ffff8a of 512 bytes failed: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (0x12B)
[1212/131025:ERROR:crash_report_exception_handler.cc(98)] WriteEverything failed
[1216/233712:ERROR:process_reader_win.cc(233)] ReadMemory at 0xebec72d of 512 bytes failed: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (0x12B)
[1216/233712:ERROR:crash_report_exception_handler.cc(98)] WriteEverything failed
[1216/233727:ERROR:process_reader_win.cc(233)] ReadMemory at 0xaffff8b of 512 bytes failed: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (0x12B)
[1216/233727:ERROR:crash_report_exception_handler.cc(98)] WriteEverything failed

**Comment by ghostoy** [comment] 2016-12-22 05:37
`setCrashDumpDir` was deprecated long time ago. Currently crash dumps on Windows are generated in `%LOCALAPPDATA%\Chromium\User Data\Crashpad\reports`.

Please post your NW.js version, OS version and crash dumps in the issue. And it's even better if you can post your app and the steps to reproduce the crash.

**Comment by ghostoy** [comment] 2017-01-16 08:43
Close it since not receiving feedbacks for more than 3 weeks. Please reopen it if you have any updates.

**Closed by ghostoy** 2017-01-16 08:43 UTC
Labels: needinfo
