### ISSUE TITLE
CORS Requests failing from v0.41.0 onwards

### ISSUE THREAD

**Issue by Connum** [nwjs/nw.js#7182] opened 2019-10-17 08:15 UTC
NWJS Version : 0.41.0 and later
Operating System : Windows 10 64bit

I tried updating a project I haven't worked on in a while to the latest nwjs version. However, requests to my local dev server using `window.fetch` fail with the following errors visible in the console:

> Access to fetch at 'https://localhost:8080/some/url/' from origin 'http://localhost:9090' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

> :8080/some/url/:1 Failed to load resource: net::ERR_FAILED

The maximum version I can use with the requests still working is 0.40.2, with 0.41.0 up to even 0.41.3 it will result in these errors. Did I breaking changes?

**Comment by Connum** [comment] 2019-10-17 08:31
It's not only requests to the local dev server that fail, but any other CORS requests, too. I think it may have something to do with these changes in Chromium: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches
But is that really something that should apply to nwjs, too? Or wouldn't it be better to revert these changes for nwjs?

**Comment by rogerwang** [comment] 2019-10-17 08:43
Could you please post your package.json?

**Comment by rogerwang** [comment] 2019-10-17 09:12
I think you'll need "localhost:9090" in "node-remote" field, otherwise it's just a normal browser frame and subject to browser security model.

**Comment by Connum** [comment] 2019-10-17 09:15
Unfortunately, changing `node-remote` didn't help. But another solution to adding the CORS headers on the server-side of things is to open chrome://flags/#out-of-blink-cors and set the out-of-blink-cors flag to disabled, but I haven't found a way to set this via `chromium-args` yet.

**Comment by sadikyalcin** [comment] 2019-11-08 10:58
Have the same issue. It has been fine previously. Currently using 0.41.2.

`"chromium-args": "--disable-web-security --allow-file-access-from-files --allow-file-access --user-data-dir --allow-running-insecure-content --enable-local-file-accesses",`

**Comment by rogerwang** [comment] 2019-11-09 06:36
Could you please provide a full sample so I can reproduce it here?

**Comment by WesSouza** [comment] 2019-12-13 19:49
@rogerwang I just stumbled upon this problem.

Here's a reproduction setup with both 0.40.1 and 0.41.0:
https://github.com/WesSouza/nwjs-7182-cors-sample

Let me know if this is clear enough and helpful.

**Comment by rogerwang** [comment] 2019-12-16 02:28
Thanks for the sample. It works in the latest 0.43.0. Looks like it got fixed in that version. Closing for now.

**Closed by rogerwang** 2019-12-16 02:28 UTC

**Comment by FPChris** [comment] 2020-07-01 15:13
404 on that link now :/
