### ISSUE TITLE
Any plan about MacBook TouchBar support?

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#5756] opened 2017-03-08 21:54 UTC
Hello, 
do you have any plan about TouchBar interface for macbook?

I just saw in electron they made it! 
https://electron.atom.io/blog/2017/03/08/touch-bar-support

Thank you

**Comment by rogerwang** [comment] 2017-03-09 01:15
I'll put this on our TODO list. Thanks.

**Comment by fujunwei** [comment] 2017-03-25 04:56
I will investigate this feature.

**Comment by fujunwei** [comment] 2017-03-27 02:09
Touch bar support has been added to Chromium according to https://bugs.chromium.org/p/chromium/issues/detail?id=660126.
@Christywl Could you please help to verify it?

**Comment by Christywl** [comment] 2017-03-27 02:35
@fujunwei , my Mac device doesn't support Touch Bar, it's not the newer MacBook Pro.

**Comment by strowbeary** [comment] 2017-07-13 13:06
@fujunwei @rogerwang if you need the new macbook pro to test, tell me

**Comment by zdol** [comment] 2017-10-06 19:17
You don't need a Macbook Pro to test this. While in Xcode, Window>Show Touch Bar.

**Comment by smotaal** [comment] 2017-12-02 12:56
Any progress here? is there effort on this front at all?

**Comment by rogerwang** [comment] 2017-12-05 01:58
close as duplicate of #5501

**Closed by rogerwang** 2017-12-05 01:58 UTC
Labels: core-team, feature-request, P3
