### ISSUE TITLE
Closing a child window from document-start/-end event handler in bg script causes "extension context invalidated" exception

### ISSUE THREAD

**Issue by Luzzifus** [nwjs/nw.js#7293] opened 2020-01-02 08:03 UTC
NWJS Version: 0.43.2 + latest nightly
Operating System: Win 10

### Expected behavior

The main window opens a child window and stores a handle to that window in the global context. The background script listens to the close and document-start (or -end) events of the main window and closes the child window before the main window is a) closed for good (close event) or b) reloaded via dev-tools (document-start event). All these event handlers should be able to close the child window.

### Actual behavior

a) works. 
b) raises an "extension context invalidated" exception.

### How to reproduce

Demo:
[testCloseChildWinInBgScript.zip](https://github.com/nwjs/nw.js/files/4015203/testCloseChildWinInBgScript.zip)

**Comment by rogerwang** [comment] 2020-01-03 11:57
In the sample the child window is to be closed by `global.childWin.close();` in init.js. Unfortunately the object childWin and the context defined for it is in the main window which was destroyed on reload.

Consider allocating the childWin object in the context of background page so it won't be destroyed by the reload:
adding the following to init.js:
```js
function add(win) {
  global.childWin = nw.Window.get(win.window);
}
```
and 
use `global.add(childWin)` rather than `global.childWin = childWin` in index.html.

**Comment by rogerwang** [comment] 2020-01-04 01:24
closing as this is not a bug.

**Closed by rogerwang** 2020-01-04 01:24 UTC
