### ISSUE TITLE
the transparent not work on v0.23.5!

### ISSUE THREAD

**Issue by xingyuzhe** [nwjs/nw.js#5989] opened 2017-06-27 14:48 UTC
the transparent not work at all event after the release of 0.23.5!
version: 0.23.5-sdk-ia32
os: win7

![qq 20170627104220](https://user-images.githubusercontent.com/3498363/27593678-539ed91a-5b8a-11e7-9b7a-4c708cc6887d.jpg)

The whole window change from tranparent to black when i week up my pc! i can produce this all the time. 

to produce this bug, follow these steps:
- minimize your nw window
- lock your pc
- week up your pc
- restore your nw window
- the window's bg color change to black!

**Comment by rogerwang** [comment] 2017-06-27 14:50
Did 0.23.4 work for you?

**Comment by rogerwang** [comment] 2017-06-27 14:50
CC @jtg-gg

**Comment by xingyuzhe** [comment] 2017-06-27 15:03
@rogerwang this bug happens since 0.22.3

**Comment by EdvaldoLima** [comment] 2017-06-28 15:18
I have a similar problem, my case appears a menu inactive inside the window, which makes it impossible to work with totally transparent windows, to minimize the window it "disappears" but it is like flashing in the process of restoring the window.

Windows 10 x64 system.
Test in nwjs 0.23.4 and 0.23.5.

![transparent](https://user-images.githubusercontent.com/12137008/27645156-cfe82870-5bfb-11e7-994b-095ab821ec73.jpg)

**Comment by jtg-gg** [comment] 2017-07-05 03:28
@xingyuzhe @EdvaldoLima may I have the sample app?
I can't reproduce it with mine

**Comment by EdvaldoLima** [comment] 2017-07-05 14:21
@jtg-gg 

> Project.
> [AppTest.zip](https://github.com/nwjs/nw.js/files/1124957/AppTest.zip)

I made a short video so that you can better understand the application's implementation when executed.

[](https://www.youtube.com/watch?v=YqXaYGXQiJ8) see in HD

**Comment by Christywl** [comment] 2017-07-06 03:42
I can reproduce EdvaldoLima's issue with nwjs-sdk-v0.23.5.
1. transparent doesn't work, it's same as #5973. Maybe the patch isn't merged in nw 0.23.5? Please help check.
```
"window": {
  "frame": false,
  "transparent": true
}
```
2.  EdvaldoLima's  https://github.com/nwjs/nw.js/issues/5989#issuecomment-311692687
> to minimize the window it "disappears" but it is like flashing in the process of restoring the window.

The following issue only happens on Windows 10, doesn't happen on Windows 8.

And why does transparent work if add `"resizable": false` in package.json, maybe another issue?
```
  "window":{
    "frame": false,
    "transparent": true,
    "resizable": false
  },
```
@rogerwang @jtg-gg , please help check.

The bug reporter's issue may be different. @xingyuzhe , could you please provide a sample? And could you try other platforms to check if win7 32 specific issue? It works fine for me on Windows 7 x64 and Windows 8(I have no win7 32 PC).
`<body style="background-color: transparent">`

**Comment by jtg-gg** [comment] 2017-07-06 08:31
@EdvaldoLima have you tried to use these "--disable-gpu --force-cpu-draw" params as described in http://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/Transparent%20Window/

**Comment by xingyuzhe** [comment] 2017-07-06 08:51
@jtg-gg  --disable-gpu --force-cpu-draw  works  for me.  And we use version sdk-ia32 for all x64 system.

**Comment by EdvaldoLima** [comment] 2017-07-06 16:12
@jtg-gg 

The "--disable-gpu --force-cpu-draw" works perfectly, but with this flag I can reproduce another problem, the window becomes deficient to the event "focus" leaving practically the whole window with this problem.

See [--disable-gpu --force-cpu-draw](https://youtu.be/h4dOq71hhgc)

**Comment by jtg-gg** [comment] 2017-07-10 05:15
@EdvaldoLima I've just made a pull request https://github.com/nwjs/chromium.src/pull/87
@rogerwang please accept my pull request, and also patch nw24

**Comment by rogerwang** [comment] 2017-07-10 07:12
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-07-10 07:12 UTC
Labels: needinfo
