### ISSUE TITLE
Right click on Tray.menu and the menu window will appear in the taskbar.

### ISSUE THREAD

**Issue by gxdyxh** [nwjs/nw.js#6978] opened 2019-02-19 12:43 UTC
Running on Windows10 64bit, code source: https://github.com/zcbenz/nw-sample-apps/tree/master/Better-Tray-Menu

![11111](https://user-images.githubusercontent.com/33820361/53015792-e001ff00-3486-11e9-9715-77876cc2223a.png)
![22222](https://user-images.githubusercontent.com/33820361/53015796-e42e1c80-3486-11e9-9466-60b2aca23fd1.png)

**Comment by TheJaredWilcurt** [comment] 2019-02-19 21:49
Closing as duplicate of #6859.

**Closed by TheJaredWilcurt** 2019-02-19 21:49 UTC
