### ISSUE TITLE
nw.js ffi load dll error

### ISSUE THREAD

**Issue by jackieron** [nwjs/nw.js#6546] opened 2018-04-02 07:32 UTC
Hello, I want to load the DLL with nw.js, indicating the following error.

It is normal for me to call directly with node.js. But with nw. JS, how can I solve this problem?

E:\DemoTest\node_modules\bindings\bindings.js:83 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\E:\DemoTest\node_modules\ref\build\Release\binding.node
    at Object.Module._extensions..node (module.js:721)
    at Module.load (module.js:586)
    at tryModuleLoad (module.js:526)
    at Function.Module._load (module.js:518)
    at Module.require (module.js:618)
    at require (internal/module.js:11)
    at bindings (E:\DemoTest\node_modules\bindings\bindings.js:76)
    at Object.<anonymous> (E:\DemoTest\node_modules\ref\lib\ref.js:5)
    at Module._compile (module.js:674)
    at Object.Module._extensions..js (module.js:691)

**Comment by Christywl** [comment] 2018-04-02 07:41
Could you please try to use nw-gyp to rebuild node modules? See http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules

**Comment by jackieron** [comment] 2018-04-03 08:14
I tried to compile version 0.29.3 with nw-gyp.
Nw - gyp rebuild -- target = 0.29.3 - arch = x64
The following error is prompted.

E:\DemoTest\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call'
..\src\ffi.cc(111): error C2039: 'ForceSet': is not a member of 'v8::Object' [E:\DemoTest\node_modules\ffi\build\ffi_bi
ndings.vcxproj]
  C:\Users\Jackieron\.nw-gyp\0.29.3\deps\v8\include\v8.h(3070): note: see declaration of 'v8::Object'
..\src\ffi.cc(114): error C2039: 'ForceSet': is not a member of 'v8::Object' [E:\DemoTest\node_modules\ffi\build\ffi_bi
ndings.vcxproj]
  C:\Users\Jackieron\.nw-gyp\0.29.3\deps\v8\include\v8.h(3070): note: see declaration of 'v8::Object'
..\src\ffi.cc(123): error C2039: 'ForceSet': is not a member of 'v8::Object' [E:\DemoTest\node_modules\ffi\build\ffi_bi
ndings.vcxproj]
  C:\Users\Jackieron\.nw-gyp\0.29.3\deps\v8\include\v8.h(3070): note: see declaration of 'v8::Object'
..\src\ffi.cc(124): error C2039: 'ForceSet': is not a member of 'v8::Object' [E:\DemoTest\node_modules\ffi\build\ffi_bi
ndings.vcxproj]
  C:\Users\Jackieron\.nw-gyp\0.29.3\deps\v8\include\v8.h(3070): note: see declaration of 'v8::Object'
..\src\ffi.cc(125): error C2039: 'ForceSet': is not a member of 'v8::Object' [E:\DemoTest\node_modules\ffi\build\ffi_bi
ndings.vcxproj]
  C:\Users\Jackieron\.nw-gyp\0.29.3\deps\v8\include\v8.h(3070): note: see declaration of 'v8::Object'
..\src\ffi.cc(126): error C2039: 'ForceSet': is not a member of 'v8::Object' [E:\DemoTest\node_modules\ffi\build\ffi_bi
ndings.vcxproj]
  C:\Users\Jackieron\.nw-gyp\0.29.3\deps\v8\include\v8.h(3070): note: see declaration of 'v8::Object'
..\src\ffi.cc(132): error C2039: 'ForceSet': is not a member of 'v8::Object' [E:\DemoTest\node_modules\ffi\build\ffi_bi
ndings.vcxproj]

However, I can pass the previous version of NW 0.25, but require('ffi') will make the following error:
E:\DemoTest\node_modules\bindings\bindings.js:83 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\?\E:\DemoTest\node_modules\ref\build\Release\binding.node
at Object.Module._extensions..node (module.js:721)
at Module.load (module.js:586)
at tryModuleLoad (module.js:526)
at Function.Module._load (module.js:518)
at Module.require (module.js:618)
at require (internal/module.js:11)
at bindings (E:\DemoTest\node_modules\bindings\bindings.js:76)
at Object. (E:\DemoTest\node_modules\ref\lib\ref.js:5)
at Module._compile (module.js:674)
at Object.Module._extensions..js (module.js:691)

**Comment by rogerwang** [comment] 2018-04-03 08:18
This should be duplicate of https://github.com/node-ffi/node-ffi/issues/465

**Closed by rogerwang** 2018-04-03 08:18 UTC
Labels: needinfo
