### ISSUE TITLE
autocomplete="off"Property not supported

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#5836] opened 2017-04-10 07:15 UTC
autocomplete="off" Property not supported

**Comment by DinkoMiletic** [comment] 2017-04-10 08:10
duplicate of #5184?

**Comment by Christywl** [comment] 2017-04-12 05:52
`autocomplete="off"` works well for me on Linux with nwjs-sdk-v0.21.5 (code: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_input_autocomplete). @phpjishu , could you please provide your sample and nwjs version?

**Comment by rogerwang** [comment] 2017-04-20 04:46
close until more information is available.

**Closed by rogerwang** 2017-04-20 04:46 UTC
Labels: needinfo
