### ISSUE TITLE
how to get new-instance window

### ISSUE THREAD

**Issue by wildcatking** [nwjs/nw.js#3005] opened 2015-01-26 09:57 UTC
in nw: node-webkit-v0.11.5-win-ia32
I use new-instance window option open a new window,but cannot access this window,code below:

```
var docWindowOptions = {
  "new-instance": true,
  "show_in_taskbar":false,
  "show": true
};

var newWin=gui.Window.open("http://www.baidu.com",docWindowOptions);
```

   I use newWin.window visiti this open window content,find newWin.window.document.URL equal
   this script in window addr,but not "http://www.baidu.com" why?
##

**Comment by rbfowler9** [comment] 2015-02-13 01:47
It's not clear exactly what you're trying to accomplish, but if you launch a new window as a new instance, it runs as a separate process/thread down to the operating system level, so you won't be able to modify or access any property or content of the new window from the launcher window. You'll have to resort to an IPC mechanism to exchange data between instances.

**Comment by RIAEvangelist** [comment] 2015-02-14 07:23
If you do implement IPC communication, I would love to know how my node-ipc module works in nw.js 
https://github.com/RIAEvangelist/node-ipc

**Comment by felixSchl** [comment] 2017-03-09 22:38
@rbfowler9 is it possible to know when that window has finished loading though? so that the spawning window can close itself, for example. I want show a window that loads instantly and load the main window in a separate thread since our app can take about half a minute to load on older devices.

**Comment by Christywl** [comment] 2017-11-06 06:53
Duplicate of #4418, close this, and please see #4418.

**Closed by Christywl** 2017-11-06 06:53 UTC
