### ISSUE TITLE
Is there a plan to support AArch64

### ISSUE THREAD

**Issue by huangjunchao** [nwjs/nw.js#8052] opened 2023-04-04 07:15 UTC
### Issue Type

Before opening an issue, please search and see if it has already been raised.
- [x] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
Error in executing nw script on AArch64 architecture computer, unable to start demo correctly

### Expected/Proposed Behavior
Successfully executed nw on the AArch64 architecture computer and can successfully display demo
### Additional Info

- Operating System:
- NW.js Version:0.74.0
- Repro Link:
- Code snippet:
- Crash report:

**Comment by tharatau** [comment] 2023-04-17 05:46
Duplicate of #1151

**Closed by tharatau** 2023-04-17 05:46 UTC
