### ISSUE TITLE
The main page is not displayed in Windows7 system

### ISSUE THREAD

**Issue by onlyou** [nwjs/nw.js#6265] opened 2017-11-01 07:03 UTC
NWJS Version :0.26.2
Operating System :
Windows7 32

### Expected behavior

<!- What do you think should happen? ->

The main page is not displayed in Windows7 system
It can only be displayed in the toolbar

### Actual behavior
It can be shown in 0.26.0 before the upgrade
It might be related to the bug I've been offering to fix, the code is #6217

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by onlyou** [comment] 2017-11-01 07:03
![qq 20171101145948](https://user-images.githubusercontent.com/2231544/32263636-c59eb4ba-bf15-11e7-8d2d-f4f9fa5b4386.png)

**Comment by onlyou** [comment] 2017-11-01 07:05
My package. Json has no problem,
The program main screen in Windows10 shows normal

**Comment by Christywl** [comment] 2017-11-01 08:19
I try a simple test on Windows 7 x64 with nwjs-sdk-v0.26.2. It works fine. The transparent window displays.
package.json:
```
{
  "name": "test",
  "main": "index.html",
  "window": {
"toolbar": true,
"frame": false,
"show":true,
"transparent": true,
"resizable": false,
"show_in_taskbar":true
}
}
```


I also try ExamManager.zip you provided in https://github.com/nwjs/nw.js/issues/6217#issuecomment-338101369, the screenshot is:
![6265](https://user-images.githubusercontent.com/20039821/32265932-352470d6-bf20-11e7-9975-2bc27a90e298.png)

**Comment by onlyou** [comment] 2017-11-01 09:13
I used the same file, and in Windows 7's 32-bit operating system, the main page was not displayed
![ss](https://user-images.githubusercontent.com/2231544/32267944-f87a66a6-bf27-11e7-8f5b-985b880b0a44.gif)

**Comment by onlyou** [comment] 2017-11-01 09:16
The SDK I used was ‘nwjs-sdk-v0.26.2-win-ia32.zip’

**Comment by jtg-gg** [comment] 2017-11-01 09:35
@onlyou does it run on other 32 bit win7 system ? you might want to clean the nwjs appdata folder
I can't reproduce on 64bit win7, I don't have 32bit win7

**Comment by onlyou** [comment] 2017-11-01 10:06
I've cleaned up the appdata folder, it's not working

**Comment by onlyou** [comment] 2017-11-01 10:07
@jtg-gg I've cleaned up the appdata folder, it's not working

**Comment by onlyou** [comment] 2017-11-02 03:25
0.26.0 including previous versions can start the main interface
![snipaste20171102_112417](https://user-images.githubusercontent.com/2231544/32308355-69f06784-bfc0-11e7-92fe-5f5373705c5c.jpg)

**Comment by onlyou** [comment] 2017-11-02 03:26
@jtg-gg 
0.26.0 including previous versions can start the main interface

![snipaste20171102_112417](https://user-images.githubusercontent.com/2231544/32308395-9ef4301e-bfc0-11e7-954d-7bcee5451392.jpg)

**Comment by jtg-gg** [comment] 2017-11-02 04:33
@onlyou can you test on win7 64bit using nwjs 32bit ?

**Comment by onlyou** [comment] 2017-11-02 05:10
@jtg-gg 
I use 64bit Windows7, too. I don't know why there is no problem with the version with 0.26.0

**Comment by onlyou** [comment] 2017-11-02 05:39
@jtg-gg 
I tested a problem with the packag.json setting
When I set this value "transparent": false, I can display the main page
I think this might be related to the 2 questions I submitted earlier
The code is: #6217 and #6176

**Comment by jtg-gg** [comment] 2017-11-02 05:41
@onlyou run with this arguments "--enable-logging --v=1"
send me the chrome_debug.log in the appdata folder

**Comment by onlyou** [comment] 2017-11-02 05:59
I'm going to take the log of that path：AppData\Local\nwjs\User Data
[chrome_debug.zip](https://github.com/nwjs/nw.js/files/1436622/chrome_debug.zip)

**Comment by onlyou** [comment] 2017-11-02 05:59
@jtg-gg 
I'm going to take the log of that path：AppData\Local\nwjs\User Data
[chrome_debug.zip](https://github.com/nwjs/nw.js/files/1436623/chrome_debug.zip)

**Comment by jtg-gg** [comment] 2017-11-02 10:59
hmm nothing in the log, are you sending the correct one ?
the appdata for your sample app should be "iDH_ExamManager"

**Comment by onlyou** [comment] 2017-11-02 13:58
@jtg-gg 
I'm sorry I rerun the order
Two different log files are generated
Now I'll resubmit it to you
[chromeDebug.zip](https://github.com/nwjs/nw.js/files/1438012/chromeDebug.zip)

**Comment by jtg-gg** [comment] 2017-11-03 03:14
@onlyou I've just read the log, not much information in there regarding the window
I can't fix if I can't reproduce the bug on my machine
might be some GPU / Windows theme configuration / setting

**Comment by onlyou** [comment] 2017-11-03 03:18
@jtg-gg 
Is there any way to capture some useful information
I can try my best

**Comment by jtg-gg** [comment] 2017-11-03 03:22
@onlyou that enable logging is already the best, I'll need to debug on the machine to fix it
unless you can find the machine / windows setting that causing the bug that reproduce-able on any machine

**Comment by onlyou** [comment] 2017-11-03 03:27
@jtg-gg 
Thank you. I'm trying to find a few different Windows7 systems to try
If there is any new discovery, I will submit it to you in time

**Comment by onlyou** [comment] 2017-11-03 06:05
@jtg-gg 
I've switched to a different computer and I tried it, and the log looks like it's almost there, but you can see it again
But I found that it was related to the Windows7 theme,
If I set the Windows7 theme to basic, then "transparent": false, the main page can also be started
This is the equivalent of code #6176 and there is no real solution
[Debug.log.zip](https://github.com/nwjs/nw.js/files/1440193/Debug.log.zip)

**Comment by onlyou** [comment] 2017-11-03 06:06
@jtg-gg 
I've switched to a different computer and I tried it, and the log looks like it's almost there, but you can see it again
But I found that it was related to the Windows7 theme,
If I set the Windows7 theme to basic, then "transparent": true, the main page can also be started
This is the equivalent of code #6176 and there is no real solution
[Debug.log.zip](https://github.com/nwjs/nw.js/files/1440195/Debug.log.zip)

**Comment by jtg-gg** [comment] 2017-11-03 08:41
@onlyou hmm you can try "--disable-gpu-compositing --force-cpu-draw" might work
but still I can't explain the same code works on my win7 and doesn't on yours

**Comment by onlyou** [comment] 2017-11-03 10:50
@jtg-gg 
After the two parameters of "-- disable-gpu-compositing -- force-cpu-draw",
Pancake. Json setting parameter "transparent": true,Windows7 theme is non-basic theme
It's working properly
[chrome_debug.log](https://github.com/nwjs/nw.js/files/1440778/chrome_debug.log)

**Comment by jtg-gg** [comment] 2017-11-07 09:55
@onlyou another uses is reporting similar thing (https://github.com/nwjs/nw.js/issues/6275)

this issue caused by WS_EX_COMPOSITED style that I enable to fix https://github.com/nwjs/nw.js/issues/6217, so I guess I'll need to revert WS_EX_COMPOSITED style

so you'll have issue https://github.com/nwjs/nw.js/issues/6275 back

**Comment by jtg-gg** [comment] 2017-11-07 11:50
@onlyou  I manage to reproduce this on my other win 10 machine
but in my case, I can display the transparent window after I minimize then restore the window
can you try this work-around ?

**Comment by jtg-gg** [comment] 2017-11-09 03:39
@onlyou can you try my sample app here:
https://github.com/nwjs/nw.js/files/1456203/transparency-5989.zip

the sample app, runs as "show": false
then after the html doc is loaded, it will minimize / show, this workaround works on my "other 2 machine"

**Comment by onlyou** [comment] 2017-11-09 03:47
@jtg-gg 
I'm trying to run this demo
There is no problem with my Windows10 system
But it still doesn't show up on Windows7

**Comment by jtg-gg** [comment] 2017-11-10 05:12
@onlyou I've made a pull request https://github.com/nwjs/chromium.src/pull/100
but https://github.com/nwjs/nw.js/issues/6217 will be back, I can workaround this, by hiding the app, then show it after the html body is loaded

@rogerwang please accept it, and please also patch nw27

**Comment by rogerwang** [comment] 2017-11-13 15:16
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-11-13 15:16 UTC
Labels: needinfo
