### ISSUE TITLE
NWJS 0.24.3 crashes on OSX 10.9

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#6108] opened 2017-08-18 16:05 UTC
Hi there!

We have two users reported that our latest app version has been crashing upon startup. Both users are on OSX 10.9.5. Not sure is that a real cause of the problem, but rollback to 0.21.6 has fixed the problem. Just wanna double check with the team behind NWJS is that still true that NWJS 0.24.3 can be used on OSX 10.9+

NWJS Version : 0.24.3
Operating System : OSX 10.9.5

### Expected behavior

App should start without crashing

### Actual behavior

App crashes before showing anything

### How to reproduce

Not sure.

**Comment by oaleynik** [comment] 2017-08-18 16:07
Attaching system report from one of our users:

https://gist.github.com/oaleynik/afc98ab339049961231f4020aa755d06

**Comment by Christywl** [comment] 2017-08-21 02:34
I try a simple case on Mac 10.12.6 with nwjs-sdk-v0.24.3. No crash happens. Maybe it's related to Mac version or the specific case. Is there a test case to reproduce this issue?

**Comment by Blatman** [comment] 2017-08-21 06:59
I think this needs to be tested on 10.9 (if it is still supported) - this is the same as #6051.
I have attached a simple project out of the nwjs suite. On my machine I built the app with 0.24.3-sdk and it runs fine on 10.11 and 10.10 but crashes on start with 10.9 with duplicate services error.
Cheers

[MavTest.zip](https://github.com/nwjs/nw.js/files/1238004/MavTest.zip)

**Comment by Christywl** [comment] 2017-08-21 07:22
The attached sample also works fine on my Mac 10.12.6, but I don't have 10.9 device to double check. If there are some crash dump files in your device, please upload here. Thanks.

**Comment by Blatman** [comment] 2017-08-21 07:41
Attached is the dmp file from Mavericks for MavTest ....

[fc756c7d-2963-455a-9162-c3c8d3762f13.dmp.zip](https://github.com/nwjs/nw.js/files/1238102/fc756c7d-2963-455a-9162-c3c8d3762f13.dmp.zip)

**Comment by rogerwang** [comment] 2017-08-21 13:30
@Blatman the dump file of yours shows that it crashes in system lib libxpc.dylib in an OSX 10.9.2 system. Could you please try with 10.9.5?

**Comment by Blatman** [comment] 2017-08-21 14:44
@Roger - 
just upgraded to 10.9.5 - new dump for MavTest

[130b595d-2539-48d5-b9ab-e8791b7255e5.dmp.zip](https://github.com/nwjs/nw.js/files/1239129/130b595d-2539-48d5-b9ab-e8791b7255e5.dmp.zip)

**Comment by rogerwang** [comment] 2017-08-22 02:44
@Blatman and all: I don't have 10.9 system for now. Does the official binary start and show the default NW.js screen without any app? (Just download the official binary, don't use any package tool). And make sure that there is symlink in directory `nwjs.app/Contents/Versions/60.0.3112.101/nwjs Framework.framework/Versions` (not 2 directories)

**Comment by Blatman** [comment] 2017-08-22 09:03
@rogerwang Well, tried the 0.23.3-sdk nwjs binary itself and it also fails in the same manner - have attached screenshots of the folder structure in the framework package.

 
[raw-nwjs.zip](https://github.com/nwjs/nw.js/files/1241425/raw-nwjs.zip)

**Comment by josh83abc** [comment] 2017-08-22 16:25
I just double checked, all 3 cases of this crash report we got from our users are with MacOS 10.9.x
[https://github.com/nwjs/nw.js/issues/6112](url)

**Comment by shamun** [comment] 2017-08-23 08:08
On OSX - 10.12.5 

- package.json is not getting used

![](https://user-images.githubusercontent.com/107349/29604675-8b6026bc-87e8-11e7-8282-58bd84c8c405.png)

```
$ --version
nwjs-v0.24.3-osx-x64
$ ls
nwjs.app	package.json
$ cat package.json 
{
  "name": "Hello!!!",
  "main": "https://codepen.io/matt-west/full/wGzuJ",
}
```

**Comment by rogerwang** [comment] 2017-08-24 02:11
@Blatman the error msg says about "duplicate service", so I guess there may be another app or NW binary in the system. Would you change the bundle ID from "io.nwjs.nwjs.*" to something else or make sure there is no other NW binaries in the system and try again? I found these files contain the official bundle ID in the binary:

```
./Contents/Info.plist
./Contents/Resources/io.nwjs.nwjs.manifest/Contents/Resources/io.nwjs.nwjs.manifest
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Resources/app_mode_loader.app/Contents/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Resources/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Versions/A/Resources/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Versions/Current/Resources/app_mode_loader.app/Contents/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Versions/Current/Resources/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/Versions/Current/XPCServices/AlertNotificationService.xpc/Contents/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Framework.framework/XPCServices/AlertNotificationService.xpc/Contents/Info.plist
./Contents/Versions/60.0.3112.101/nwjs Helper.app/Contents/Info.plist
Rogers-Mac-mini:nwjs.app roger$ vi Contents/Versions/60.0.3112.101/nwjs\ Helper.app/Contents/Info.plist
```

**Comment by rogerwang** [comment] 2017-08-24 04:26
@Blatman forget it. I just get a 10.9 system and will see it.

**Comment by rogerwang** [comment] 2017-08-24 14:20
A workaround is to add `--disable-features=NativeNotifications` to the command line.

**Comment by shamun** [comment] 2017-08-24 14:25
YES - it works by adding the parameter in OSX.

![image](https://user-images.githubusercontent.com/107349/29671084-e2e2178c-88e8-11e7-839d-82259fafd808.png)

**Comment by oaleynik** [comment] 2017-08-24 15:36
@rogerwang thanks for a hint to workaround this! Should we expect official fix for this? We were kinda excited for native notifications..

**Comment by rogerwang** [comment] 2017-08-25 01:04
Yeah. I'll try to workaround the system xpcd issue, which is apparently fixed in later macOS versions: from system.log you can see that the same XPC service from NW is scanned twice and reported as duplication...

**Comment by oaleynik** [comment] 2017-08-25 01:37
@rogerwang no prob. Just let us know if there is no quick fix for this. Thanks a lot!

**Comment by rogerwang** [comment] 2017-08-25 02:11
This is fixed in git and will be available in the next nightly build.

**Closed** 2017-08-25 02:11 UTC
Labels: bug

**Comment by neymar57** [comment] 2023-09-30 17:08
how and where to install nw.js?

**Comment by neymar57** [comment] 2023-09-30 17:08
how and where to install nw.js?

**Comment by neymar57** [comment] 2023-09-30 17:08
how and where to install nw.js for mac os x 10.9.5?

**Comment by ayushmanchhabra** [comment] 2023-09-30 17:11
https://dev.to/thejaredwilcurt/guide-to-nw-js-versions-5d38
@neymar57 this might help

**Comment by neymar57** [comment] 2023-09-30 17:17
@ayushmanchhabra and where to find the version available for download of nw.js for mac os x 10.9?

**Comment by ayushmanchhabra** [comment] 2023-09-30 17:57
@neymar57 As the article says, "OSX support is not well-documented". Start with v0.29.x, download and check if it runs. If it doesn't, try other versions.

Since this is a closed issue, could you ask further questions via Discord or Gitter?
