### ISSUE TITLE
nwjs 0.13 beta2 - popup not closable / xauth on google fails

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4131] opened 2015-12-31 17:13 UTC
@rogerwang 
google api login through xoauth popup fails... clicking "sign in" will reload the same page.
More the login popup window can't be closed.

OS: MacOS 10.10.5

**Comment by dogancelik** [comment] 2015-12-31 18:52
Afaik all Google logins fail and page reloads itself when you enter a password.

Here's a demo:
![test](https://cloud.githubusercontent.com/assets/486818/12067293/3e9345e2-b000-11e5-9bdf-d355430a9226.gif)

**Comment by ghostoy** [comment] 2015-12-31 22:30
node-remote is now using a different spec. See [Manufest
Format#node-remote](
http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote)

Doğan Çelik <notifications@github.com>于2016年1月1日周五 02:52写道：

**Comment by dogancelik** [comment] 2015-12-31 23:07
@ghostoy then we should redirect [wiki/Manifest-format](https://github.com/nwjs/nw.js/wiki/Manifest-format) to that page. Nevertheless, node-remote is not related here. node is not used in this example.

**Comment by ghostoy** [comment] 2016-01-01 05:05
Wiki won't be replaced by docs. It's open for everyone to edit without
approval. So you can contribute your thoughts any time :)

Doğan Çelik <notifications@github.com>于2016年1月1日周五 07:07写道：

**Comment by AndryBray** [comment] 2016-01-02 11:02
I can confirm this issue even on nwjs 0.13 beta3 (build of 01-02-2016)

**Comment by ghostoy** [comment] 2016-01-05 08:12
My further testing on this issue showed that NW.js always use **GET** instead of **POST** forms. This may be the problem.

Here is my sample: https://gist.github.com/ghostoy/28f6dcec8b4bfb18bc30 . When you click *submit* button, server always read **GET** method.

**Comment by rogerwang** [comment] 2016-01-06 05:21
The reason is that navigation is disabled in Chrome Apps in Chrome browser and we shared the same architecture for NW app.

Now it's fixed in git.

**Closed by rogerwang** 2016-01-06 05:21 UTC
Labels: bug, nw13, regression, test-todo

**Comment by rogerwang** [comment] 2016-01-06 05:22
btw, the fix is tested with @ghostoy 's case. If it doesn't work for you, please reopen this issue.

**Comment by vivekgaikwad** [comment] 2016-01-07 06:50
I have checked nightly build version form data is getting passed but it is passed forcefully through GET even if we set form method as POST.

I have tried following:
Main.html
<form name="upload" action="http://localhost/test.php" method="POST" enctype="multipart/form-data">
      <input id='uploadfile' type="file" class="file" name="Filedata" onchange="javascript:load();" />
      <input id="test" type="text" name="name"/>
      <input id="submit" type="submit" name="submit"/>
    </form>

PFA screenshot after click on form submit.
![capture](https://cloud.githubusercontent.com/assets/5575953/12164102/db9d331a-b538-11e5-8aa9-665a72e6ae86.PNG)

You can refer the files provided in issue-4168. Please reply me asap.

**Comment by rogerwang** [comment] 2016-01-07 07:04
@vivekgaikwad does the case in this comment work for you? : https://github.com/nwjs/nw.js/issues/4131#issuecomment-168931353

**Comment by vivekgaikwad** [comment] 2016-01-07 07:20
@rogerwang I am able to get form file data using GET method even if i mentioned method to be POST. In the screenshot above i have mentioned form method to be post still request method is passed as GET.

**Comment by vivekgaikwad** [comment] 2016-01-07 07:22
@rogerwang We have file upload functionality which is not working due to this.

**Comment by rogerwang** [comment] 2016-01-07 07:41
Could you please upload some case so I can reproduce it?
