### ISSUE TITLE
Temp file not properly deleted

### ISSUE THREAD

**Issue by Sytten** [nwjs/nw.js#5208] opened 2016-08-11 21:57 UTC
Hi,

My software is using NW 0.14.5 so that might have been fixed by now.
But with that version, the following problems occurs:
1- One of my user reported that the temp file created normally on Windows in the local/temp file are not properly deleted when the %temp% system variable is changed to another location. That means the temp file are not removed when the software closes.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/495
2- When the software crash, the temp files are not deleted and stay in the temp directory. I saw an old issue about it, but this is still an issue as 100mb is wasted each time if the user does not know how to clear its temp file... This is probably not fixable easily though...

Thanks!

**Comment by RohitSharma27** [comment] 2016-08-13 05:40
In the mean time you may try this approach. Everytime your app runs, add the name of currently created folder in the temp directory to an array that you will maintain in your local storage. Try to clean up this array element asynchronously. Read the temp directory, if you find the nw folder there(excluding your current folder) delete it and remove entry from the array. If you don't find it there that means it has already been deleted, so remove it as well from the array. This won't take much as this code will be run on every start-up of your app which will try to reduce the array length. The only time this won't work is when your app crashes without even running your code, which shouldn't happen, i assume. If you can come up with a better approach. Do let me know. Thanks amd cheers.

**Comment by ghostoy** [comment] 2016-08-15 08:01
@Sytten I tested on a hello world app and can't reproduce this issue. I will test with your messenger app.

**Comment by RohitSharma27** [comment] 2016-08-15 08:17
@ghostoy I haven't tried it with the LTS version but this used to be the case with 0.12.3 back then. If your app crashes then the temp folder is not deleted, if you will kill your app from task manager on windows then also it won't be deleted. I don't remember what happens in case your machine goes to sleep and comeback. I have been using the solution, i have suggested above. The folder gets deleted when your app closes normally. Hope it will help.

**Comment by ghostoy** [comment] 2016-08-15 08:56
@RohitSharma27 @Sytten I tested with the "messenger app" and the folder was automatically deleted when messenger is exited normally. When crashed, the temp folder was not deleted. The folder was used to store extracted app.

You may try @RohitSharma27 's workaround or do not use self-contained app. You can put all your code in the folder of `package.nw`, which is in the same folder of nw.exe. This will avoid temporarily extracting your code to this folder on each startup.

**Comment by ghostoy** [comment] 2016-08-15 08:57
@Sytten On Mac, you can put code in the folder of `app.nw` in `Resources` folder.

**Comment by Sytten** [comment] 2016-08-15 21:31
Thank you for the feedback @ghostoy!
I will certainly try this.
Did you try to reproduce the other issue?

**Comment by ghostoy** [comment] 2016-08-17 02:39
@Sytten Did you mean 2- extracted temp files left on crash? Yes, I can reproduce. @rogerwang

**Comment by RohitSharma27** [comment] 2016-08-17 03:56
@ghostoy yes!!! That's exactly what it is. Every time the app crashes, it's extracted folder will stay there in the temp directory on windows.

**Comment by ghostoy** [comment] 2016-08-17 05:37
@RohitSharma27 Currently you can try **not to zip your app** to avoid this. Just put all your code in `package.nw` folder in the same folder of `nw.exe` (or `app.nw` folder in `Resources` folder on Mac).

**Comment by RohitSharma27** [comment] 2016-08-17 06:59
@ghostoy i have been using grunt-nw-builder since nw0.12.3 and i have customised that. I know  that we don't need to zip our files anymore. It's a good move. Thanks for the efforts. :)
I have got other more important issues with the upgradation. So, i have been using the above workaround that i have suggested since nw0.12.3. The last time i checked, grunt-nw-builder was still zipping the files when building the exe. Do let me know if i can be of help in production of the issue. :)

**Comment by ghostoy** [comment] 2016-08-17 07:10
@RohitSharma27 `nw-builder` supported non-zipped app. But `grunt-nw-builder` seems not supporting it. Please open an issue or submit PR for grunt-nw-builder. @adam-lynch

**Comment by RohitSharma27** [comment] 2016-08-17 08:35
Will submit a PR when i get some bandwidth. :)

**Comment by Sytten** [comment] 2016-08-22 13:14
Sorry for the delay, no I was referring to 1- One of my user reported that the temp file created normally on Windows in the local/temp file are not properly deleted when the %temp% system variable is changed to another location
Thanks!

**Comment by ghostoy** [comment] 2016-08-23 02:22
@Sytten Tested on my laptop (Win8.1) and found that extracted files are properly deleted when exit normally. Only an empty folder was left there, which is supposed to be removed as well. But it doesn't waste the disk space much (a few bytes).

**Comment by Sytten** [comment] 2016-08-23 12:50
Ok, then maybe the problem is with a bad configuration from the user who reported that.

**Comment by Christywl** [comment] 2017-03-31 05:23
As ghostoy said, only an empty folder is left there when app exit normally, it doesn't waste the disk space much. I think we could close this issue now. @Sytten

**Comment by rogerwang** [comment] 2017-03-31 09:49
The empty folder need to be removed as well.

**Comment by Christywl** [comment] 2017-11-02 08:04
I checked on Windows with nwjs-sdk-v0.26.2. The temp folder in AppData\Local\Temp  was removed after the app closed normally. So close this issue.

**Comment by Christywl** [comment] 2017-11-03 07:04
Reopen this.
Actually, it's not fixed for the packaged app, the empty folder is still left. @rogerwang , please take a look at this issue.

**Comment by gendew** [comment] 2017-11-03 08:39
Has this problem been solved?. Now @Christywl

**Comment by Christywl** [comment] 2017-11-03 08:50
Please wait for Rogerwang's investigatation.

**Comment by gendew** [comment] 2017-11-03 09:01
well. thanks @Christywl

**Closed** 2017-11-05 13:28 UTC
Labels: bug, P3, test-todo, triaged
