### ISSUE TITLE
Application fails to start in the Steam Linux Runtime on Steam Deck

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#8032] opened 2023-02-27 23:33 UTC
When trying to run my app in the Steam Linux Runtime on Steam Deck, it fails to start.
Apparently, there's an error... libnw.so: undefined symbol: cupsEnumDests
It was suggested I report it here. I'm using nw.js v0.66.1
Steam has to run native apps in the Steam Linux Runtime for their Steam Deck. But this error is preventing it from running on the Steam Deck.
Any help is appreciated, thanks!

**Comment by tharatau** [comment] 2023-03-02 21:27
Have you tried using NW v0.73.0?

**Comment by prominentdetail** [comment] 2023-03-02 21:35
> Have you tried using NW v0.73.0?

I haven't, but I could probably switch to that version next time I update if you think it would change anything. Is there any specific reason why that version would handle this issue better or is it just a question of whether the issue still exists on the latest version?

**Comment by tharatau** [comment] 2023-03-02 21:43
> is it just a question of whether the issue still exists on the latest version

Fixes are deployed to the latest branch. If the issue exists in the latest version, it can be fixed and you can upgrade to that version.

**Comment by prominentdetail** [comment] 2023-03-02 21:52
Okay, next time I update my app, I will try to switch versions and I'll let you know how it goes.

**Comment by tharatau** [comment] 2023-03-02 21:56
This might be an upstream issue since I can't see [any changes in the diff](https://github.com/tharatau/idea-maze/blob/main/lib/nw/diff/0.73.x/chromium.patch) related to `cupsEnumDests`.

I can see that there were some related changes [made in upstream](https://chromium.googlesource.com/chromium/src/+log/110.0.5481.153..111.0.5563.49?pretty=fuller&n=10000) though. (Search for `printing/backend/cups` on the page). But this is just guesswork. Maybe @rogerwang can weigh in?

**Comment by tharatau** [comment] 2023-03-18 23:39
Closing for now. Ping here if it still persists in latest version

**Comment by prominentdetail** [comment] 2023-03-19 00:13
I haven't been able to test it on latest version, since it doesn't render the window correctly on linux. I need to work on putting an example project for that issue first. Then I'll get back to this once I can run the new version.

**Comment by tharatau** [comment] 2023-03-26 21:47
I am pretty sure you need to install the `libcups` shared library from you Linux package manager. I ran NW.js on a fresh Ubuntu install and found myself installing a bunch of shared libraries - one of them libcups.

**Comment by prominentdetail** [comment] 2023-03-26 22:12
Would that mean that anyone that wants to run nw.js apps on the steam deck would have to install that library? Or are you saying that it can be included with the nw.js app? Because if users have to install the library, that doesn't sound like a solution.

**Comment by insraq** [comment] 2023-03-27 12:27
I am faced with the exact same problem but I am not using nw.js (I am using Electron). I think the issue is from upstream (Chromium) and Steam Linux Runtime. AFAIK, Steam Linux Runtime uses Ubuntu 14.04 and the `libcups` in the runtime might be a bit too old. The relevant change in the upstream (Chromium) is this one: https://chromium.googlesource.com/chromium/src/+/d4672d5e5ea885aba941f0e98517e8201c1a7967 and it is introduced in Chromium 94.

I am not sure what NW.js (or Electron) could do in this case. I think it's more of a Steam Linux Runtime (Scout) issue. Maybe open an issue there https://github.com/ValveSoftware/steam-runtime ?

**Comment by dfabulich** [comment] 2023-03-27 20:37
I've filed a bug on this. https://github.com/ValveSoftware/steam-runtime/issues/579

The problem isn't that the Steam Linux Runtime `libcups` is "too old." The problem is that Steam Linux Runtime runs the app in a Docker container that doesn't even _have_ `libcups` in it.

And, of course it wouldn't! CUPS is for _printing_. Why would a Steam game need to communicate with a printer?? Except, NW/Electron uses Chromium, and Chromium won't start without `libcups`, so, here we are.

**Comment by tharatau** [comment] 2023-03-28 14:41
Should this be thosed?

**Comment by prominentdetail** [comment] 2023-04-03 13:17
> There's a workaround here: [ValveSoftware/steam-runtime#579 (comment)](https://github.com/ValveSoftware/steam-runtime/issues/579#issuecomment-1489541881)

Does that apply to nw.js as well? What would the steps be for an nw.js app?
It mentions solder and sniper.. What are those?

**Comment by dfabulich** [comment] 2023-04-03 16:08
I wrote the workaround, but I intend not to ship a game using it, and I'm not sure that I recommend that anyone else do so, either.

Basically, the problem is that the Steam Linux Runtime is running with an ancient version of `libcups2` (which supports printing documents to printers). Modern versions of Chromium require a newer version of `libcups2`.

Valve has announced in the bug thread linked above that they intend to add a new version of `libcups2` to SLR, and that this should be available in the "next beta" of SLR.

A Valve developer (smvc) explained:
> I can't promise anything about timing, but we generally aim for 1 or 2 betas a month, and if there are no bad regressions then changes in beta get promoted to stable alongside the next beta.

So, I intend to just sit tight for a month or so. Eventually, the new `libcups2` will be available in SLR, and, at least for Electron apps, this problem will be gone. I'd bet that nw.js will also be fixed, but I haven't tested that.

> It mentions solder and sniper.. What are those?

`scout`, `soldier`, and `sniper` are the codenames of three major versions of the Steam Linux Runtime.

`scout` and `soldier` are kinda documented here. https://github.com/ValveSoftware/steam-runtime

`sniper` is the new-new thing that isn't really out yet; the only way to get your game to use sniper is (apparently?) to write Valve an email asking them to enable it for you. It has documentation here: 

https://gitlab.steamos.cloud/steamrt/steamrt/-/blob/steamrt/sniper/README.md
https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md

smvc explains:
> The intention is that for modern native Linux games, we'll skip Steam Runtime 2 'soldier' and go directly to Steam Runtime 3 'sniper'. At the moment getting games to be run in Steam Runtime 3 'sniper' requires manual setup from a Valve developer, but the intention is that it will eventually be a self-service thing in the partner web interface, so that when you upload your game's Linux depot, you'll choose whether it's marked as compatible with scout, sniper, or some future runtime.

OK, but what if you _really really really_ want to try the workaround right now, just to make sure their fix will fix nw.js? Let me begin by saying this probably isn't for the faint of heart; you'd need to have a fair amount of Linux expertise to give this a try. But, with that said…

1. Follow the reproduction instructions at the top of the bug thread https://github.com/ValveSoftware/steam-runtime/issues/579 to reproduce the failure in a "hello, world" Electron app.
2. In the course of that work, you'll launch an `xterm` in the `run-as-soldier` environment. Try running your nw.js app that way; it'll presumably fail in exactly the same way.
3. Then, follow my workaround instructions here https://github.com/ValveSoftware/steam-runtime/issues/579#issuecomment-1489541881 to fix your "hello, world" Electron app, by copying three extra libraries into the Electron app folder.
4. Then, uh, do the same thing to your nw.js app. I don't use nw.js, but Electron builds an output folder with a bunch of `.so` files that Chromium needs to run on Linux. I imagine nw.js does the same? So, put the new versions of `libcups` and `libavahi` libraries in your nw.js output folder, and try it. I bet it'll work, if you put the files in the right place. (But, again, I don't know where that is for nw.js.)

If the workaround works for you, you have two options:

1. Wait another month or so for Valve to roll out their fix, safe in the knowledge that it's probably gonna fix your nw.js app, too.
2. Ship a build of your app including those libraries.

There is some peril in shipping your own copy of the libraries.

* Where should you get your copies of those libraries? (I got my copies from a Steam Deck. Do you trust me and my copies?) 
* I haven't tested that my versions actually work on popular Linux distros like Ubuntu and Fedora. You'll probably want to try it yourself.
* Will my copies conflict negatively with whatever Valve gets around to shipping?
* When you ship nw.js, you're shipping a lot of other people's code. Chromium includes a license file containing licenses for all of its embedded dependencies. You'll need to honor the license to distribute libcups and libavahi. On paper, that might require you to confirm with a lawyer that you've done it right. (I think most nw.js/Electron apps don't go out of their way to make licenses available for all of their dependencies, and I think many indie developers disregard this issue.)

These perils lead me to decide not to ship the workaround to end users, but instead to just wait for Valve to fix it. (My app has been broken in SLR for months now… what's another month or two, in the grand scheme of things?)

**Comment by prominentdetail** [comment] 2023-04-03 19:06
Thanks for the writeup/explanation. I guess I will also wait too and see if it starts working in a month or two. Good to know how to test it and workaround it if necessary- hopefully we won't need to do that though.

**Comment by tharatau** [comment] 2023-04-03 19:10
Closing since Stream Runtime issue

**Closed by tharatau** 2023-04-03 19:10 UTC
Labels: bug
