### ISSUE TITLE
0.30.0-beta1 http2.connect doesn't "work" inside node enabled worker

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#6539] opened 2018-03-26 09:16 UTC
NWJS Version : 0.30.0-beta1 SDK
Operating System : Windows 10 x64

This is a regression (worked fine in 0.29+)

### Expected behavior
Event should fire (it does fire correctly in regular context)

### Actual behavior
Event never fires.

### How to reproduce
```
const http2 = require('http2');
var connection = http2.connect('https://api.binance.com'); // returns http2session
connection.on('connect', () => {
    // this never fires, it will fire when used in non-worker context
    console.log('connected');
});

```

**Comment by Christywl** [comment] 2018-03-27 06:03
I can't reproduce this on Linux/Windows with nwjs-sdk-v0.30.0-beta1.
My steps:
1. Start this app and open the devtools, the log 'connected' is displayed
2. Start this app with the command line option '--enable-node-worker', open the devtools, the log 'connected' is also displayed

**Comment by cTn-dev** [comment] 2018-03-27 06:27
@Christywl Console by default is always in regular context, '--enable-node-worker' doesn't change that, you have to start a worker and execute the code in its context, either by providing the code directly in the worker file or by switching to a worker context inside the console.

Here is an example file that also includes the worker.

[example.zip](https://github.com/nwjs/nw.js/files/1850653/example.zip)

**Comment by Christywl** [comment] 2018-03-27 06:50
Thanks for your example, I can reproduce this issue now with nwjs-sdk-v0.30.0-beta1.

**Comment by rogerwang** [comment] 2018-03-27 13:22
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2018-03-27 13:22 UTC
Labels: P2, bug, regression, triaged

**Comment by rogerwang** [comment] 2018-03-28 04:47
https://dl.nwjs.io/live-build/nw30/03-28-2018/a3b2369-c51f71f-3997f5c-227a27b/v0.30.0-beta1/

**Comment by cTn-dev** [comment] 2018-03-28 07:02
Thanks @rogerwang , i can confirm its fixed now.
