### ISSUE TITLE
when is support for chrome extensions coming?

### ISSUE THREAD

**Issue by whatsdis** [nwjs/nw.js#3815] opened 2015-09-08 00:28 UTC
when can we expect support for chrome extensions?

**Comment by joshterrill** [comment] 2015-09-08 00:32
This seems to be a duplicate of https://github.com/nwjs/nw.js/issues/792 I do remember seeing a thread in the Google Group that was talking about this. Maybe you can find it here: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by julmot** [comment] 2016-03-08 15:41
For me it's a bit confusing to find out what kind of browser extensions are currently supported. The [documentation](https://github.com/nwjs/nw.js/wiki/Third-party-browser-plugins) describes how to implement NPAPI plugins. However, NPAPI plugins aren't supported in Chrome related to [this article](https://support.google.com/chrome/answer/6213033?hl=en) and will not listed in the Chrome Web Store:
![screen](https://cloud.githubusercontent.com/assets/8310677/13606519/7f4449c0-e54c-11e5-999d-91ec26e7db49.png)
Also there are other extension formats like web extensions. Is it supported too? @rogerwang Maybe you can help with clarification?

**Comment by rogerwang** [comment] 2016-03-08 16:25
@julmot Note the difference between browser plugin and extension -- totally different thing...

**Comment by rogerwang** [comment] 2016-03-08 16:26
extensions are supported now in nw13. Use '--load-extension' in the command line argument to load it.

**Closed by rogerwang** 2016-03-08 16:26 UTC

**Comment by julmot** [comment] 2016-03-08 19:52
@rogerwang Thank you for your answer.

Unfortunately this does not answer all of my questions. I try to summarize things together:

- Chrome NPAPI plugins are supported in nwjs, even if they are not supported in Chrome
- Chrome extensions will be supported in nwjs 13

Remaining questions:

- How to find out if a plugin is a NPAPI plugin, or how to find NPAPI plugins at all if they are not listed in the Chrome web store because of incompatibility?
- What kind of APIs are supported in chrome extensions? Everything that is supported in Chrome?
- What about other plugins that are no web extensions and no NPAPI plugins, like the category "Apps" (see Screenshot in my last comment)? Are they supported?
- If web extensions are supported, how will things behave if an extensions contains browser popups or icons that would normally be displayed in a toolbar?

Thank you for your help and your understanding.

**Comment by 0joshuaolson1** [comment] 2018-11-10 21:37
2.5 years later.
