### ISSUE TITLE
NWJS 0.30.4 crash when using Service Worker

### ISSUE THREAD

**Issue by suziwen** [nwjs/nw.js#6624] opened 2018-05-16 13:01 UTC
NWJS Version : 0.30.4
Operating System : linux, window

### Expected behavior

Service Worker start correct, and Application will not auto close

### Actual behavior

After Application started, waiting about  10s, then Application will auto shut down. 

### How to reproduce

[nwjs30serviceworker.zip](https://github.com/nwjs/nw.js/files/2009189/nwjs30serviceworker.zip)

**Comment by Christywl** [comment] 2018-05-17 02:37
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.30.4.

**Comment by rogerwang** [comment] 2018-05-18 00:35
@Christywl do we know what's the last working version?

**Comment by rogerwang** [comment] 2018-05-18 01:11
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2018-05-18 01:11 UTC
Labels: P1, bug, triaged

**Comment by Christywl** [comment] 2018-05-18 01:12
v0.29.4 works fine. This happens since v0.30.0.
