### ISSUE TITLE
nwjs 0.17 beta - crash at boot

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#5193] opened 2016-08-05 09:55 UTC
nwjs 0.17 crashes on Windows 7 if starting the app with window show = false (package manifest).

This bug is similar to this one but for Windows only: https://github.com/nwjs/nw.js/issues/4187 from which one you can take the test case

PS: after crash, no nwjs process is visible inside the task manager

**Comment by AndryBray** [comment] 2016-08-05 10:07
Tested without any app installed (just the empty package as after download) and it's the same crash.
So nothing to do with app configurations

**Comment by oaleynik** [comment] 2016-08-05 11:53
The same thing is on OS X

**Comment by Blatman** [comment] 2016-08-07 20:20
FWIW - Every build of 0.17.0 has crashed on OSX 10.11.5 when starting.
Screenshot error is a bit different to what oaleynik gets but 0.17.0 won't even start up in its own folder without an app. 0.16 and prior start fine.

![nwjs-0 17-beta1-sdk-crashonstart](https://cloud.githubusercontent.com/assets/11089335/17465051/61407eca-5ce4-11e6-88eb-7aa9079ac3ab.png)

**Comment by ghostoy** [comment] 2016-08-09 02:45
@Blatman I tested with 0.17 beta on Mac and it didn't crash. I'm on Mac OSX 10.11.6. Could you post corresponding crash dumps in `~/Library/Application Support/nwjs/Crashpad/completed`?

**Comment by ghostoy** [comment] 2016-08-09 02:56
@AndryBray I can confirm this bug on Windows without any application. It just crash after boot. I'll look into this issue.

**Comment by Blatman** [comment] 2016-08-09 19:32
@ghostoy - unfortunately it looks like nwjs crashes before the ~/Library/Application Support/nwjs folder is created  (it is created OK with 0.16.2). I tried upgrading the mini to 10.11.6 (El Capitan) and still the same and also tried 0.17 on a MBP running 10.10.5 (Yosemite) where it still failed with the same error as above screenshot.
Tested with NWjs-0.17.0-beta1-sdk-osx-x64 dated 08-05-2016 - console logs posted as screenshot.
![systemlog](https://cloud.githubusercontent.com/assets/11089335/17530644/590b3028-5e70-11e6-8022-50de268b2a17.jpg)

**Comment by Blatman** [comment] 2016-08-09 20:03
@ghostoy - just tried more of the builds from 08-05-2016.

nw17-5d3baf3-0d7f0fb-5dcd777-77640cb/		5th 06:39AM  WORKS!
nw17-9233164-0d7f0fb-5dcd777-77640cb/		5th 03:46AM  FAIL
nw17-9e337f4-0d7f0fb-5dcd777-77640cb/               4th 11:59AM  FAIL

The 5d3baf3 build works OK - the earlier ones fail so it looks like the problem was fixed on OSX.
I guess you were using the 5d3baf3 build.

**Comment by ghostoy** [comment] 2016-08-10 02:21
@Blatman I was using the released beta version at https://dl.nwjs.io/v0.17.0-beta1/

**Comment by ghostoy** [comment] 2016-08-17 02:49
@AndryBray Have you tried latest 0.17.0-beta1 release? It should be working on macOS.

**Comment by ghostoy** [comment] 2016-08-17 03:00
This issue should be Windows 7 only, which exited with `Illegal Instruction`. And it only happens on **some** Windows 7 systems.

And it works on Windows 8.1 and Windows 10

**Comment by rogerwang** [comment] 2016-08-18 00:46
It looks like the crash is on AVX instructions in the official binary and the hardware without AVX support in the CPU. Will investigate the build options.

**Comment by rogerwang** [comment] 2016-08-19 05:46
fixed in http://dl.nwjs.io/live-build/08-19-2016/nw17-9a9237d-feecff2-be02ea9-6c79a25/v0.17.0-beta2/

**Closed by rogerwang** 2016-08-19 05:46 UTC
Labels: bug
