### ISSUE TITLE
Question : How to restart my application?

### ISSUE THREAD

**Issue by lee99** [nwjs/nw.js#4505] opened 2016-03-07 03:50 UTC
HI:
In my application,I need a way to restart my application clearly.

I have tried "chrome.runtime.restart()",but the function available only for ChromeOS kiosk mode.

 "chrome.runtime.reroad()", that is not my need.

thank you!

**Comment by lee99** [comment] 2016-03-07 07:05
what i want just like it...
![qq 20160229170144](https://cloud.githubusercontent.com/assets/2275619/13562643/9fb27e52-e475-11e5-91dc-a80544ac05ab.png)

it is the ContextMenu item built in nwjs13.rc2

thank you!

**Comment by rogerwang** [comment] 2016-03-07 08:29
so can this issue be closed?

**Comment by lee99** [comment] 2016-03-07 08:38
sorry,what  I need is a  built-in function to restart my app. so that I call it in my way.

**Comment by porsager** [comment] 2016-03-07 17:10
Duplicate of https://github.com/nwjs/nw.js/issues/149

**Closed** 2016-03-08 05:09 UTC

**Comment by f3l1x** [comment] 2017-09-14 08:53
# Works

`chrome.runtime.reload()` works for me.

**Comment by jssuttles** [comment] 2019-03-27 15:37
chrome.runtime.reload() no longer seems to work. Broke when we updated from 0.30.0 to 0.37.0

**Comment by f3l1x** [comment] 2021-01-21 11:31
I am using 0.50.2 and `chrome.runtime.reload()` works for me.

**Comment by vankasteelj** [comment] 2024-11-09 11:26
Just for reference, since 0.93.0 `chrome.runtime.reload()` doesn't work (it load a google page, then reloads the app), I had to use `window.location.reload()`
