### ISSUE TITLE
Check `Share system audio` checkbox by default when calling `chrome.desktopCapture.chooseDesktopMedia`

### ISSUE THREAD

**Issue by giladgd** [nwjs/nw.js#7910] opened 2022-07-01 16:31 UTC
NWJS Version: `0.66.0`
Operating System: `Windows 11`

### Expected behavior
When making this API call:
```js
chrome.desktopCapture.chooseDesktopMedia(["screen", "audio"], console.log);
```
The checkbox called `Share system audio` should be _checked_ by default.

This aforementioned expected behavior was the original behavior in `NWJS 0.43.6`, and because of this change I can't upgrade to `NWJS 0.66.0`.

### Actual behavior
When making this API call:
```js
chrome.desktopCapture.chooseDesktopMedia(["screen", "audio"], console.log);
```
The checkbox called `Share system audio` is _unchecked_ by default.

### How to reproduce
Create a file called `app/package.json` with the following content:
```
{
  "name": "Test",
  "main": "index.js",
  "manifest_version": 2,
  "offline_enabled": true,
  "permissions": ["desktopCapture", "audioCapture"]
}
```

Create a file called `app/index.js` with the following content:
```js
chrome.desktopCapture.chooseDesktopMedia(["screen", "audio"], console.log);
```

Run the following commands:
```bash
npm init -y
npm install "nw@^0.66.0-sdk"
npx nw app
```

**Comment by ayushmxn** [comment] 2022-07-13 20:08
This seems to be a potential issue in Chromium, could you open it there in their [bug tracker](https://bugs.chromium.org/p/chromium/issues/list) and link that here?

**Comment by ayushmxn** [comment] 2022-07-18 06:25
@giladgd is this what you're referring to? I'm running `v0.66.1` on WSL.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/14110965/179454353-2c032714-990b-4e5d-8642-6cfe77822b30.png">

Clicking on it enables the `Share` button which should allow you to share your screen.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/14110965/179454424-c82b9978-34d8-45b5-a993-29b216b9f0da.png">

I don't see any checkbox called `Share system audio`.

**Comment by hthetiot** [comment] 2022-07-18 19:47
Audio is only available for tabs sharing on getDisplayMedia to my
knowledge.

Le lun. 18 juil. 2022, 08:25, Ayushman Chhabra ***@***.***> a
écrit :

**Comment by ayushmxn** [comment] 2022-07-29 04:07
I'm out of my depth here.

**Comment by ayushmxn** [comment] 2022-07-30 01:56
Maybe this can help:
http://docs.nwjs.io/en/latest/References/Screen/#screenchoosedesktopmedia-sources-callback

**Comment by ayushmxn** [comment] 2022-08-03 03:34
Closing this for now. Ping me here if the problem still persists. I tried to reproduce but without any success - my comments are above.

**Closed by ayushmxn** 2022-08-03 03:34 UTC
Labels: needinfo, cant-reproduce
