### ISSUE TITLE
Incorrect image obtained from clipboard.get("png")

### ISSUE THREAD

**Issue by DiegoScirra** [nwjs/nw.js#6366] opened 2018-01-03 17:02 UTC
NWJS Version : v0.27.3 SDK
Operating System : Windows 10

### Expected behavior

To be able to create the correct image from the data obtained from calling clipboard.get("png")

### Actual behavior

The image created is only correct in size, the content is all messed up.

### How to reproduce

1) Make sure there is an image in the system clipboard.

2) In the javascript of an app get the clipboard object with **nw.Clipboard.get()**

3) Get the image data with **clipboard.get("png")**

4) Use the result of the previous call to populate an **Image** object

5) When that is complete, append the image to the body of the document. The drawn image is wrong.

Note: This works fine when requesting a **"jpeg"** from the clipboard.

Here is a basic app demonstrating the problem [example-app.zip](https://github.com/nwjs/nw.js/files/1601040/example-app.zip). Just make sure there is an image in the clipboard and hit the **PASTE** button.

**Comment by Christywl** [comment] 2018-01-04 02:18
I can reproduce this issue on Windows and Linux with nwjs-sdk-v0.27.3.
![image](https://user-images.githubusercontent.com/20039821/34547767-85753878-f138-11e7-88d8-c374d247b533.png)

**Comment by rogerwang** [comment] 2018-01-04 08:44
I can't reproduce the jpeg case. Please give more information on this, e.g. the sample image.

**Comment by Blatman** [comment] 2018-01-04 09:36
Yup, here is the image - just tried with 0.27.4 and still fails. (note: iMac is Retina 5K 18,3)
Also tried on Yosemite (10.10.5) non-retina and still fails with 0.27.4-sdk.

![01](https://user-images.githubusercontent.com/11089335/34557364-e99b35fc-f131-11e7-8232-fc4331717391.jpg)

Cheers.

**Comment by rogerwang** [comment] 2018-01-04 10:19
@Blatman thanks. but it works for me. How did you put it into clipboard? I opened this issue page with Safari, right click on the image and click 'copy image'.

**Comment by rogerwang** [comment] 2018-01-04 10:21
@Blatman did you mean you are using a jpeg image or you are using 'jpeg' format parameter in the source code in index.html?

**Comment by DiegoScirra** [comment] 2018-01-04 10:47
To clarify, when I said

> This works fine when requesting a "jpeg" from the clipboard.

I meant it worked when using the **"jpeg"** paramenter when making a call to **clipboard.get** in the source code.

**Comment by Blatman** [comment] 2018-01-04 10:47
Whoops - sorry my mistake - code is set up expecting png and I used the jpg so it will fail - sorry for wasting time.

**Comment by rogerwang** [comment] 2018-01-04 10:51
@Blatman no problem and good to know it :) and thanks for help testing NW.

**Comment by rogerwang** [comment] 2018-01-04 10:52
btw, the source format shouldn't matter, it will be converted to the format requested.

**Comment by rogerwang** [comment] 2018-01-04 10:53
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2018-01-04 10:53 UTC
Labels: bug, P2, triaged
