### ISSUE TITLE
Window.open callback returns undefined for new window

### ISSUE THREAD

**Issue by eemi2010** [nwjs/nw.js#4188] opened 2016-01-08 14:01 UTC
nw.Window.open('https://github.com', {}, function(new_win) { 
   console.log(new_win);
});

new_win is randomly undefined. So if you run the code lets say 5 times. You might get undefined 2 times

**Comment by AndryBray** [comment] 2016-01-08 14:14
I can confirm this issue with latest nightly build (2016-01-08)

**Comment by AndryBray** [comment] 2016-01-13 11:53
@rogerwang I see this problem every time I execute this on latest nwjs 0.13 beta3 (Jan 12)
```
nw.Window.open('http://www.google.it', {}, function(w) {
   console.log('nw window', w);
});
```

any news about that?

**Comment by thib3113** [comment] 2016-01-22 22:53
same problem with beta4

**Comment by berlincount** [comment] 2016-02-14 00:05
same on beta4

**Comment by berlincount** [comment] 2016-02-14 00:10
aaaand beta5

**Comment by berlincount** [comment] 2016-02-14 00:11
oh, I'm using new_win = nw.Window.open(url, options), btw

**Comment by rogerwang** [comment] 2016-02-14 06:34
Does this happen only with remote sites? It should have been fixed in the nightly build.

**Comment by AndryBray** [comment] 2016-02-14 09:52
@rogerwang  I had this problem even with local pages. I will test next build ASAP

**Comment by AndryBray** [comment] 2016-03-24 08:10
Hello @rogerwang 
the bug is still there in latest 0.13 

Any workaround for the moment?

**Comment by AndryBray** [comment] 2016-03-30 10:10
tested on nwjs 0.14... bug is still there =(

**Comment by rogerwang** [comment] 2016-03-30 12:33
It works for me because we have a test case for this scenario: https://github.com/nwjs/nw.js/tree/nw13/test/remoting/open-remote

See test.py for the content of index.html it generates on the fly.

Is it different from yours?

**Comment by thib3113** [comment] 2016-03-30 12:38
I have the same problem with the version 0.13.0-rc3sdk , but it's not all time ... maybe one time for 10 tests .

**Comment by rogerwang** [comment] 2016-03-31 09:51
@thib3113 could you please upload a sample for the random error? Our test case 'open-remote' never fail so I cannot reproduce it.

**Comment by thib3113** [comment] 2016-03-31 09:59
I juste use this : 
```javascript
gui.Window.open('http://www.XXXXX.com/forum/notifications.html', {
      position: 'center',
      width: screen.availWidth,
      height: screen.availHeight,
      show : false,
  },
    function(cWindows){
        cWindows.on('error', function(a,b,c){
            debugger;
        });
});
```
With devtools open, and some time i see
> on is not a function of undefined
(not sure is the exact error message, but it is like the error)

But, i don't know if the problem is : the website, my connection (I use my phone connection, so lot of connection problems), or other ...

**Comment by AndryBray** [comment] 2016-04-11 17:35
@rogerwang any wane about this issue?
I see I have the param "node-remote" set to my domain inside the package.json.

I see in you test case you don't have any "node-remote". Maybe try to set it and test again.
The problem is still there even with latest of 0.14.
Thank you

**Comment by RohitSharma27** [comment] 2016-04-13 04:45
nw 0.13.0
@rogerwang I can see the same issue as commented by @thib3113 . And it happens in opening a new window and loading local html file in it. The callback in the
 `Window.open(... , ... , function(win){})` 
function says "win" is undefined and if I use
`win.on('loaded', function(){})`
then it sometimes work and sometimes don't by saying "win.on" is not a function of undefined. (Same as reported by @thib3113

**Comment by rogerwang** [comment] 2016-05-03 02:32
should be fixed within this build: http://dl.nwjs.io/live-build/05-03-2016/nw14-d154648-1208bce-756e507-24751d8/v0.14.3/

**Closed** 2016-05-03 08:57 UTC

**Comment by softoxy** [comment] 2016-05-12 12:04
In 0.14.4 the problem is still present.

**Comment by softoxy** [comment] 2016-05-12 12:26
I found the solution in 0.14.4, i am changed the approach:

window.opener.closeSplashscreen();

**Comment by AndryBray** [comment] 2016-05-13 09:55
https://github.com/nwjs/nw.js/issues/4844#issuecomment-218990338

**Comment by walton007** [comment] 2016-09-05 12:51
any update? I also meet this issue and don't know how to workaround?
my case is: 
1. first index.html open one sub_index.html 
2. in the sub_index.html, i open another sub_sub_index.html
then,  sub_sub_index.html is opened. but the Window.open(cb) returns undefined! I just lost control of the new created windows!
Any one know how to workaround??

**Comment by AndryBray** [comment] 2016-09-05 13:06
@walton007 what is your nwjs version?

**Comment by tiegeda** [comment] 2017-01-04 03:38
I reproduce it use remote url and set dns to invalid ip. nw.window.open callback a undefined
（when I was trying to deal with timeout， I want to redirect when timeout， but got a undefined）

**Comment by cyc0der** [comment] 2017-01-11 16:07
same problem for me on winddows
win is not defined!
`			 
			 	var gui = require('nw.gui');
						 
			  var win = gui.Window.open ('print.html', {
			  position: 'center',
			  width: 901,
			  height: 127
			  });

			  win.on ('loaded', function(){
				var parameters = {greeting: "Hello World"}
				win.emit("data", parameters);
			  });`

**Comment by timraasveld** [comment] 2017-05-18 10:14
For me, the undefined `win` was caused by loading a not-found HTML file. If you want to know if this is the cause of your problem as well, put `about:blank` as the first argument:
```javascript
nw.Window.open('about:blank', {}, function(win) {
  if(win) {
    console.log("win is no longer undefined!");
  }
);

**Comment by JonasT** [comment] 2018-01-13 22:29
I am having this problem, and it doesn't even work with `about:blank`...

**Comment by mamontov-cpp** [comment] 2018-10-26 13:08
Still the issue persists with about:blank in 0.34.1 version.
