### ISSUE TITLE
File & Folder dialogs of the wrong type and undraggable on MacOS

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7349] opened 2020-01-31 06:43 UTC
NWJS Version : 0.43.6
Operating System : MacOS 10.14.6

### Expected behavior

The file & folder dialogs - should open on the center of the app screen and can not be moved/dragged

### Actual behavior

Now it slides from the middle of the app, as a drawer and it is not possible to drag it.
If it should open as drawer then it should be from the top side of the app.
Probably just the popup type is wrong

<img width="979" alt="mac_selectFolder_name_upload" src="https://user-images.githubusercontent.com/504730/73517902-297bfd80-43fd-11ea-8811-9cf1c63380de.png">
### How to reproduce

Use the following test case:

[folder_picker_bug.zip](https://github.com/nwjs/nw.js/files/4137902/folder_picker_bug.zip)

**Comment by gpetrov** [comment] 2020-02-01 13:22
Actually this is even worse when the nwjs app is in full screen, the buttons for cancel and select of the file & folder dialog can go out of the screen! So this makes the file dialog completely unusable on MacOS @rogerwang 

See this video after the 26 secs:

https://community.wappler.io/t/file-manager-bug/17075/5?u=george

**Comment by gpetrov** [comment] 2020-02-01 13:49
Also tried to use the extensions API chrome.fileSystem, https://developer.chrome.com/apps/fileSystem
To open an folder like:

```
chrome.fileSystem.chooseEntry({type: 'openFile'}, function(readOnlyEntry) {    
    console.log(readOnlyEntry);
});
```

but get an error unfortunately:
```
Unchecked runtime.lastError: Invalid calling page. This function can't be called from a background page.
```

And it seems the new Chrome native file system api isn't also fully enabled https://github.com/nwjs/nw.js/issues/7351

**Comment by cheffe112** [comment] 2020-02-06 16:54
I can confirm that chrome.fileSystem seems unusable on nw.js since 0.42.4 with
```
Unchecked runtime.lastError: Invalid calling page. This function can't be called from a background page.
```
Using 0.42.3, this still works fine.

**Comment by gpetrov** [comment] 2020-02-09 09:04
Any news on this issue @rogerwang ? It is getting very urgent as we are getting more and more angry users on Mac that are unable to use the file and folder dialogs ...

Selection buttons fall off screen and the file & folder dialog makes the whole nwjs app jumping around ...

**Comment by rogerwang** [comment] 2020-02-09 12:46
I'll fix them soon. 

btw, please don't file multiple cases under one GitHub issue. Thanks.

**Comment by rogerwang** [comment] 2020-02-09 13:43
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed** 2020-02-09 13:42 UTC
