### ISSUE TITLE
Invisible eventless area around all sides of window

### ISSUE THREAD

**Issue by gorelics** [nwjs/nw.js#4749] opened 2016-04-20 11:35 UTC
![invis_clip_area](https://cloud.githubusercontent.com/assets/7573291/14673161/e95bebd6-0704-11e6-8c69-1e157ad3fbb5.gif)

Hi, have a problem, invisible eventless area around all sides. html and body padding and margin 0px.
OS Windows 7 x64, nwjs-sdk-v0.14.0-win-x64

**Comment by rdtsc** [comment] 2016-04-20 15:41
Confirming this as well. Reproducible with the latest x64 build on Windows 7 and 10 **only if DWM is running in non-basic/classic mode**. GPU acceleration doesn't seem to make a difference.

**Test case**: 
```bash
git clone https://gist.github.com/rdtsc/4ad3502f1835dbdfa66253e7775eb19f nwjs-4749
```

**package.json**:
```json
{
  "name": "nwjs",
  "main": "index.html"
}
```

**index.html**:
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NW.js</title>
    <style>
      html, body {
        margin: 0;
        padding: 0;
        height: 100%;
      }
      button {
        cursor: pointer;
        width: 100%;
        height: 100%;
      }
      button:active {
        background: #AAA;
      }
      button:active::before {
        content: 'Clicked';
      }
    </style>
  </head>
  <body>
    <button></button>
  </body>
</html>
```

---

The circle in the middle of the cursors below indicates that `VK_LBUTTON` is being pressed. 

**Windows 7 Aero (Fail)**:
<p align="center"><a href="https://cloud.githubusercontent.com/assets/6773893/14680278/bca6672a-06ea-11e6-8d38-20aa9a90c67d.gif"><img src="https://cloud.githubusercontent.com/assets/6773893/14680278/bca6672a-06ea-11e6-8d38-20aa9a90c67d.gif"></a></p>

**Windows 10 Stock (Fail)**:
<p align="center"><a href="https://cloud.githubusercontent.com/assets/6773893/14680315/de7e2a4a-06ea-11e6-99b0-709d4ed59e0d.gif"><img src="https://cloud.githubusercontent.com/assets/6773893/14680315/de7e2a4a-06ea-11e6-99b0-709d4ed59e0d.gif"></a></p>

**Windows 7 Basic/Classic (Pass)**:
<p align="center"><a href="https://cloud.githubusercontent.com/assets/6773893/14680336/f282b740-06ea-11e6-8478-7ed177e4a30a.gif"><img src="https://cloud.githubusercontent.com/assets/6773893/14680336/f282b740-06ea-11e6-8478-7ed177e4a30a.gif"></a></p>

**Linux (Pass)**:
<p align="center"><a href="https://cloud.githubusercontent.com/assets/6773893/14680241/a409707c-06ea-11e6-9c0c-c15bb257c764.gif"><img src="https://cloud.githubusercontent.com/assets/6773893/14680241/a409707c-06ea-11e6-9c0c-c15bb257c764.gif"></a></p>

**Comment by simonob** [comment] 2016-04-20 21:53
Same issue here on nwjs-v0.14.1-win-x64. Glad I found this issue, have been tweaking various bits of CSS thinking it was my fault!!

**Comment by rogerwang** [comment] 2016-04-21 01:56
@rdtsc The report and cases are very helpful to pinpoint the root cause! Thanks again.

**Comment by rogerwang** [comment] 2016-04-21 02:55
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-04-21 02:55 UTC
Labels: test-todo
