### ISSUE TITLE
crash opening window with icon option

### ISSUE THREAD

**Issue by conceptualspace** [nwjs/nw.js#5771] opened 2017-03-13 20:07 UTC
nw 0.21.1
osx 10.11.6

psuedo-code:

`Window.open(url, {icon: "myicon.png"}, cb)`

working fine on nw 0.20.3.

crash dump attached:

[f5564a4c-0295-44dc-95ff-b9d5e76fdf78.dmp.zip](https://github.com/nwjs/nw.js/files/839482/f5564a4c-0295-44dc-95ff-b9d5e76fdf78.dmp.zip)

**Comment by rogerwang** [comment] 2017-03-14 01:27
close as duplicate of #5767

**Closed by rogerwang** 2017-03-14 01:27 UTC
