### ISSUE TITLE
Can't use es6 classes

### ISSUE THREAD

**Issue by pyrokinetiq** [nwjs/nw.js#3076] opened 2015-02-11 05:38 UTC
I have installed io.js `iojs-v1.2.0` and nw `0.12.0-alpha2`.

I have the following in my `package.json`:
````json
{
    "name": "Magician",
    "version": "0.0.1",
    "author": "Damon Poole <pyrokinetiq@gmail.com>",
    "main": "index.html",
    "dependencies": {
        "bluebird": "^2.9.8",
        "bootstrap": "^3.3.2",
        "fs-extra": "^0.16.3",
        "jquery": "^2.1.3",
        "less": "^2.4.0",
        "lodash": "^3.1.0",
        "nw": "^0.12.0-alpha2"
    },
    "scripts": {
        "start": "nw"
    },
    "js-flags": "--harmony"
}
````

I have the following class which gets loaded through `index.html`:
````js
"use strict";
class Magician {
	constructor(lib, win){
		console.log('winning');
	}
};
module.exports = Magician;
````

If I run `node --harmony magician.js`, it executes without error, however when I run `npm start` I get an error:

````
Uncaught SyntaxError: magician.js:2
class Magician {
^^^^^
Unexpected reserved word", source:magician.js (2)
````

It seems `nw` isn't picking up me enabling es6 classes through the `--harmony` flag. I've also tried using the `--es_staging` flag with no luck.

**Comment by pyrokinetiq** [comment] 2015-02-11 06:44
I'm expecting to be able to use flags as specified here:

https://iojs.org/en/es6.html

**Comment by MaxSvargal** [comment] 2015-02-11 07:56
"js-flags": "--harmony --harmony_classes"

It's on progress and additional flag needed.

**Comment by Phoenixmatrix** [comment] 2015-02-11 13:51
Keep in mind the version of io.js you have installed doesn't matter. Its the version its built with. I think 0.12 alpha2 is built with some early version of 1.0.0 which was before they enabled basic ES6 features. Some work already though. You'll have to use flags as mentionned above.

**Comment by rogerwang** [comment] 2015-02-12 23:16
close as duplicate of #3045

**Closed by rogerwang** 2015-02-12 23:16 UTC
