### ISSUE TITLE
Switch to libudev.so.1 [$50]

### ISSUE THREAD

**Issue by damianb** [nwjs/nw.js#770] opened 2013-06-07 02:55 UTC
As per my comment in #701 and numerous comments in the related issue https://github.com/Kodowa/Light-Table-Playground/issues/161 about the problem and how symlinking is ***NOT*** a fix, and how distributions are no longer shipping with a stale version of libudev, the dependency needs to be updated to track changes to maintain support with modern distros.  

Additionally, claiming that distros "should ship with libudev.so.0" is a bad point; that version is on life support to allow currently-maintained software to adapt and move over to the new version.  That means this software needs to be updated to move over as well before the old version of the library is no longer maintained and removed entirely (which is *already* happening in stable distros).

**Comment by nitriques** [comment] 2015-02-26 23:02
+1 On this. Was not working on Ubuntu 14.

Linking .0 to .1 seems to does the trick. See http://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error

**Comment by sarciszewski** [comment] 2015-05-17 07:51
This is blocking adoption for me. :(

**Comment by shaynem** [comment] 2015-05-17 10:47
sed -i
's/\x75\x64\x65\x76\x2E\x73\x6F\x2E\x30/\x75\x64\x65\x76\x2E\x73\x6F\x2E\x31/g'
/path/to/nwjs

That works a treat for us and we run it on each deploy, it doesn't cause us
any troubles but best to test with your own.

The linking is allot harder because of different variations i386 / x86_64
plus different distribution paths.. sure you can write a install script to
handle all these scenarios however if you get can away with the above sed
command then you can skip all that.

On Sun, May 17, 2015 at 5:51 PM, Scott Arciszewski <notifications@github.com

**Comment by sarciszewski** [comment] 2015-05-17 17:44
The problem is more: I want to just be able to install the damn software and hit the ground running. Creating symlinks or rewriting binaries (either on disk or at runtime) is NOT an acceptable solution.

**Comment by baconface** [comment] 2015-05-17 20:25
Sorry this free software built with the hard work of many contributors working in their free time failed to meet your expectations.

**Comment by sarciszewski** [comment] 2015-05-17 22:09
You should be. Please `shred /dev/sda`

**Comment by sarciszewski** [comment] 2015-05-17 22:15
@baconface Fuck off with your passive aggressive attitude. It's not helpful.

@everyone else: I'm posting a bounty on actually solving this issue.

**Comment by damianb** [comment] 2015-05-18 01:54
@baconface Thank you for playing a key part in marketing Open Source software.  We'll definitely win over customers from proprietary software in no time with help like yours.

@sarciszewski From what I thought I noticed, electron (formerly atom shell) didn't seem to have this issue. If you need something ASAP, I'd suggest steering that way.

**Comment by sarciszewski** [comment] 2015-05-18 02:20
I'm going to muck with chromium and see if I can patch this upstream. It's kind of ridiculous that this is still broken 2 years later.

**Comment by ssokolow** [comment] 2015-05-18 06:30
As a temporary fix, it *is* possible to bundle a copy of `libudev.so.1` from an older Ubuntu .deb and write a launcher script which sets `LD_LIBRARY_PATH`, much like many games do for other libraries.

libudev is LGPL licensed and the source is tiny enough that bundling the source tarball in with the nw.js app is a perfectly reasonable way to satisfy said license.

**Comment by karolherbst** [comment] 2016-03-23 23:17
is there any status update on this? Because I might have some time to work on this.

**Comment by rogerwang** [comment] 2016-03-24 01:10
Chromium upstream has fixed it: https://bugs.chromium.org/p/chromium/issues/detail?id=415212

The fix is in 0.13.0.

**Closed by rogerwang** 2016-03-24 01:10 UTC
Labels: bounty
