### ISSUE TITLE
Overlay Not work on Mac OS X and is not clickable on Linux

### ISSUE THREAD

**Issue by mrdev023** [nwjs/nw.js#6692] opened 2018-06-15 14:06 UTC
I try Overlay in Windows and it work perfectly but on Mac OS X is not possible to Open It with Shift + Tab or with activateOverlay function and on Linux, i can open it and close it, the time is refreshed but is not possible to click on it.

NW.js : 0.29.4 (i try 0.30.4 also)
Greenworks : 0.13.0

**Comment by Christywl** [comment] 2018-06-19 06:52
Duplicate of #6628, please comment in #6628. Close this.

**Closed by Christywl** 2018-06-19 06:52 UTC
