### ISSUE TITLE
Frameless windows have a lot of issues  on Linux and Windows (With NW2 mode)

### ISSUE THREAD

**Issue by malisipi** [nwjs/nw.js#8153] opened 2023-12-27 19:18 UTC
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior

* The last update was broke (from 0.82.0 to 0.83.0) `-webkit-app-region:drag` CSS feature. (in Wayland, X11)
* Also in X11, frameless examples is working with a titlebar. (Also related with https://github.com/nwjs/nw.js/issues/8137)
![Ekran Görüntüsü - 2023-12-27 22-04-00](https://github.com/nwjs/nw.js/assets/87281783/329c1790-0c4a-4f0e-96a7-ff9431ad11bb)
* Transparency also is not working correctly with latest version. (in Wayland, X11)

### Expected/Proposed Behavior

* All frameless examples works without titlebar
* NW will respect `-webkit-app-region` property.
* Also transparency is working correctly.

### Additional Info

Those bugs is fixed when disabled NW2 mode. (`--disable-features=nw2`) #7230 

- Operating System: Ubuntu 23.10 x86_64
- NW.js Version: 0.83.0 (SDK)
- Repro Link: https://github.com/nwutils/frameless-example
- Code snippet:
- Crash report:

**Comment by ssnangua** [comment] 2024-01-01 00:56
Win10 the same issues.

**Comment by UtterDonkey** [comment] 2024-01-13 23:58
Same issue, Windows 11 rounded corners also disappear in frameless.

**Comment by UtterDonkey** [comment] 2024-01-13 23:59
@rogerwang Could you take a look at this please?

**Comment by UtterDonkey** [comment] 2024-01-17 18:04
This issue also blocks nw1 removal https://github.com/nwjs/nw.js/issues/7230

**Comment by UtterDonkey** [comment] 2024-01-20 11:07
Might I suggest you rename this issue so that it's more obvious it's an issue with frameless windows themselves and not with the frameless examples?

**Comment by UtterDonkey** [comment] 2024-01-25 19:08
I'm not able to reproduce this problem in v0.82.0.

**Comment by UtterDonkey** [comment] 2024-01-25 19:18
I think this may have something to do with it: https://github.com/nwjs/nw.js/compare/nw82...nw83#diff-52fe046e03b7bd92f94816d435f9ed44082d363c02741801391d796e720d2765

**Comment by rogerwang** [comment] 2024-02-13 01:16
The drag issue will be fixed and released in upcoming 0.85.0 with Chromium 122. Thanks.

**Comment by rogerwang** [comment] 2024-02-13 18:14
I was testing my local fix with OP's sample, which uses `-webkit-app-region: drag`.

**Comment by UtterDonkey** [comment] 2024-02-13 18:16
Have you managed to fix any other of the issues with frameless windows like transparency, rounded corners etc.?

**Comment by rogerwang** [comment] 2024-02-18 00:17
Please try this build:
https://dl.nwjs.io/live-build/nw85/20240217-223403/1c035e527/v0.85.0/nwjs-sdk-v0.85.0-linux-x64.tar.gz[
](https://dl.nwjs.io/live-build/nw85/20240217-163921/0782fe73e/v0.85.0/nwjs-sdk-v0.85.0-win-x64.zip)

**Comment by djmisterjon** [comment] 2024-02-18 02:24
> Please try this build: https://dl.nwjs.io/live-build/nw85/20240217-223403/1c035e527/v0.85.0/nwjs-sdk-v0.85.0-linux-x64.tar.gz https://dl.nwjs.io/live-build/nw85/20240217-163921/0782fe73e/v0.85.0/nwjs-sdk-v0.85.0-win-x64.zip

work for me thank for your time

**Comment by UtterDonkey** [comment] 2024-02-18 07:59
I will test it for my issues as soon as possible and get back to you.

**Comment by UtterDonkey** [comment] 2024-02-18 13:10
@rogerwang 

I get this weird effect after moving a window with `resizable: false` and then if I make it frameless, it removes the rounded corners.

https://github.com/nwjs/nw.js/assets/68461677/270e7cb5-2f52-4eba-94e4-481fece9dadb

**Comment by Sheepux** [comment] 2024-02-25 13:29
Fixed the issue for me as well (windows)

**Comment by UtterDonkey** [comment] 2024-02-26 07:01
> @rogerwang 
> 
> I get this weird effect after moving a window with `resizable: false` and then if I make it frameless, it removes the rounded corners.
> 
> https://github.com/nwjs/nw.js/assets/68461677/270e7cb5-2f52-4eba-94e4-481fece9dadb
> 
> 

@Sheepux Are you able to reproduce these problems?

**Comment by malisipi** [comment] 2024-02-26 20:52
> Please try this build: https://dl.nwjs.io/live-build/nw85/20240217-223403/1c035e527/v0.85.0/nwjs-sdk-v0.85.0-linux-x64.tar.gz https://dl.nwjs.io/live-build/nw85/20240217-163921/0782fe73e/v0.85.0/nwjs-sdk-v0.85.0-win-x64.zip

`-webkit-drag-region` CSS property and titlebar issues is fixed on `Ubuntu 23.10 x86_64`.

However there're still some problems about transparency. It would be a sync issue about Gnome' window manager. (Also it can be reproducible in XWayland and Wayland). Except that everything is fine for me.

**Comment by jonlepage** [comment] 2024-05-23 04:53
@rogerwang 
this one worked
https://github.com/nwjs/nw.js/issues/8153#issuecomment-1950614414
but **update** to `0.88.0` will broke app-region again !

**Closed** 2024-07-17 20:52 UTC
Labels: bug, regression, has-min-repro

**Comment by rogerwang** [comment] 2024-07-19 17:40
Please try this build: https://dl.nwjs.io/live-build/nw90/20240719-033120/32b360f54/v0.90.0/
