### ISSUE TITLE
Node-webkit windows7 package HTML, login page automatically remember the password, how can we not remember the password?

### ISSUE THREAD

**Issue by hnldlsjzt** [nwjs/nw.js#6617] opened 2018-05-15 02:03 UTC
NWJS Version :
Operating System : windows7

### Expected behavior

<!- What do you think should happen? ->
![image](https://user-images.githubusercontent.com/28916697/40032346-5b69f62c-5826-11e8-9ccd-c32195cb0a8f.png)

<!- What actually happens? ->

![image](https://user-images.githubusercontent.com/28916697/40032327-466d3874-5826-11e8-972e-d2ead0248f02.png)

<!- 

It's normal to open in a browser. If you log in with nw.js, you will permanently save your account password. I hope I can't save it. What should I do?

->

**Comment by rogerwang** [comment] 2018-05-15 02:13
close as duplicate of #5944

**Closed by rogerwang** 2018-05-15 02:13 UTC

**Comment by hnldlsjzt** [comment] 2018-05-15 03:39
chrome.passwordsPrivate.getSavedPasswordList(function (passwords) {
passwords.forEach((p, i) => {
chrome.passwordsPrivate.removeSavedPassword(i);
});
});
chrome.privacy.services.passwordSavingEnabled.set({
value: false
});

I used the undefined error in JS. How to use chrome API correctly

![image](https://user-images.githubusercontent.com/28916697/40035476-95dc3be0-5834-11e8-98ec-20b70158c7cf.png)

**Comment by rogerwang** [comment] 2018-05-15 04:50
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
