### ISSUE TITLE
Facebook - blacked screen

### ISSUE THREAD

**Issue by tarva** [nwjs/nw.js#4533] opened 2016-03-09 20:23 UTC
Facebook problem.
I was able to login, but after login whole screen has some black layer over site.
After few clicks this black layes dissapears.

I used  0.13 RC2 - live-build/03-08-2016/8376d68-2c53f2b-3d99a78-93e6ec5/v0.13.0-rc2/

![nw013-facebook](https://cloud.githubusercontent.com/assets/140406/13649239/fa4e43aa-e63c-11e5-8c9d-027441ab2e8c.png)

**Comment by cryptedco** [comment] 2016-03-09 20:38
Yup, same here... but that is so from the first release of 13xxx - I attributed it to the extensive JS use of facebook and just waited for the page to finish. 1 click is enough when you wait 20 seconds and then just click to an "empty" space of the greyed page....
![screenshot 2016-03-09 21 33 35](https://cloud.githubusercontent.com/assets/326428/13649710/38e4a3fa-e63f-11e5-9e42-439194acb342.png)

**Comment by krneticz** [comment] 2016-03-11 14:17
I believe this blacked screen has to do with Facebook's prompt for desktop notifications. If you open Facebook in Chrome browser you get similarly looking screen, with prompt to allow desktop notification. See attached screenshot from Chrome.

@rogerwang are desktop notifications supported in nwjs? 

<img width="1680" alt="screen shot 2016-03-11 at 3 14 11 pm" src="https://cloud.githubusercontent.com/assets/281657/13704435/3f6676a0-e79c-11e5-8d5a-049044fa54c4.png">

**Comment by tarva** [comment] 2016-03-11 15:33
I tested it again with RC2 (not nighly build) and it works same - blacked screen.
I also think that desktop notifications have something with that problem. 

Tibor.

**Comment by ghostoy** [comment] 2016-03-14 07:44
Probably duplicate of #4521

**Comment by rogerwang** [comment] 2016-03-14 08:59
@krneticz it's supported. Will fix this issue soon.

**Comment by krneticz** [comment] 2016-03-14 09:22
@rogerwang thank you!

**Comment by rogerwang** [comment] 2016-03-14 10:43
It should be the duplicate of #4521 . Now the question is should we just grant the permission to all origin first?

**Comment by rogerwang** [comment] 2016-03-15 01:16
merge with #4521 . please check the updates there.

**Closed by rogerwang** 2016-03-15 01:16 UTC

**Comment by tarva** [comment] 2016-03-15 09:33
I checked new RC3 and it works now fine with facebook.
Thank you!
