### ISSUE TITLE
HTML5 application cache doesn't work after node-webkit v0.11.6 including the latest v0.12.0

### ISSUE THREAD

**Issue by ghosert** [nwjs/nw.js#3361] opened 2015-04-12 02:33 UTC
Here is my package.json:
{
    "main": "https://localhost/test",  
    "name": "nw-demo",  
    "description": "demo app of node-webkit",    
    "version": "0.1.0",         
    "keywords": [ "demo", "node-webkit" ],     
    "window": {                                      
        "icon": "link.png",                          
        "toolbar": false,                              
        "min_width": 1280,                              
        "min_height": 768,
        "frame": true                           
    },
    "user-agent": "%name %ver %nwver %webkit_ver %osinfo"
}

The main entry is an url for example: "https://localhost/test",  it implemented application cache and works well in Chrome browser. Means after loading this url for the first time, even without internet connection, you could still visit this url by reloading the application cache.

But it seems not working for the latest nwjs v0.12.0, but works for the older node-webkit v0.11.6

**Comment by mscreenie** [comment] 2015-04-17 08:28
Have you tried page cache inside package.json?

#page-cache

(boolean) whether to enable page cache, default to false.
#

**Comment by Gimmeaphatbeat** [comment] 2015-04-18 00:24
+1

Basically nwjs doesn't attempt to reload cached files when the 'cache manifest file' changes (which it should).

"Browsers only update an application cache when the manifest file changes, byte for byte." from https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

**Comment by famov** [comment] 2015-05-07 10:36
+1

I need this working. I can't downgrade to 0.11.5 because my application uses ffi module and it seems not to be working with that version. Is there some progress on this?

**Comment by ghosert** [comment] 2015-05-07 11:22
Yes, please, otherwise, people have to stick to 0.11.6 or the older version.

**Comment by rogerwang** [comment] 2015-05-07 14:37
will look into it. Thanks for reporting.

**Comment by alex-min** [comment] 2015-05-08 10:20
I can confirm the bug. The application cache actually half-works. It caches things after loading the app. So if you request with ajax something that was in the manifest after running it, it works. But as soon as you reload the page, it doesn't. (the page-cache flag changes nothing to this)

I'm also sticking to 0.11.6 in the mean time.

**Comment by rogerwang** [comment] 2015-05-21 02:59
It's fixed in this build: http://dl.nwjs.io/live-build/05-21-2015/9e81217-296de67-be948af-459755a-2bdc251-1764a45/

**Closed by rogerwang** 2015-05-21 02:59 UTC

**Comment by famov** [comment] 2015-05-21 16:05
Thank you rogerwang. It seems to be working, but in one of my projects I am getting the same problem, however it works in 0.11.5. I will test it carefully and will report what the difference with other projects.

**Comment by famov** [comment] 2015-05-22 16:09
I have just found it. It is a very specific case. Look at this application structure:
![image](https://cloud.githubusercontent.com/assets/12294053/7774316/9beb281e-00aa-11e5-98a4-edf7f27449c8.png)
When package.json points to main index, it redirects to /nwjs/index.html and it caches all files required under that directory. However, if you take a look to "Entries" table in "Aplication Cache/Index" database, you can see that each url entrie is wrong because it is relative to main index, like this:

http://localhost/**demo**/appcache.manifest
http://localhost/**demo**/example.png
...

and it should be:

http://localhost/**demo/nwjs**/appcache.manifest
http://localhost/**demo/nwjs**/example.png
...

When you reload application in offline mode, it can't find cached files. I can solve this in my application by changing my files structure, so it is not a big problem for me, but I think it could be considered to fix to avoiding other people headaches.

Thank you!

**Comment by ghosert** [comment] 2015-06-06 10:57
Thanks for your time, that's awesome !
