### ISSUE TITLE
error when trying to create menu in mac yosemite

### ISSUE THREAD

**Issue by gitawego** [nwjs/nw.js#3018] opened 2015-01-29 14:43 UTC
I can't create menu using this code:
```js
 var gui = require('nw.gui');
 var win = gui.Window.get();
if (process.platform === 'darwin') {
                        var nativeMenuBar = new gui.Menu({type: "menubar"});
                        nativeMenuBar.createMacBuiltin("My App");
                        win.menu = nativeMenuBar;
                    }
```

it gives error:
![err](https://cloud.githubusercontent.com/assets/438120/5959331/9139a2aa-a7cd-11e4-9d7a-d9a94f2edecb.jpg)

I'm using v0.11.6

**Comment by mrfabbri** [comment] 2015-01-31 18:48
What operating system/version?

**Comment by gitawego** [comment] 2015-01-31 20:43
It's Mac OS X Yosemite. 
and I'm using webpack with flag node-webkit

**Comment by jakehh** [comment] 2015-02-01 05:46
The error is @ line 32 on menu.js, This might not be exactly related with the menu itself if you have more code in the menu than you provided.

I don't see anything wrong with your Code.

**Comment by mrfabbri** [comment] 2015-02-01 10:48
@gitawego I was unable to reproduce with `webpack` v1.5.3 with `node-webkit` target (also note that support for target node-webkit is marked as experimental) as Jake stated there is nothing wrong with the posted code, the issue lies somewhere else or in the "webpacked" code.

**Closed by mrfabbri** 2015-02-01 10:48 UTC
Labels: cant-reproduce
