### ISSUE TITLE
nw13alpha3 - "node-remote" problems

### ISSUE THREAD

**Issue by bgSosh** [nwjs/nw.js#3880] opened 2015-10-09 11:06 UTC
Hi,

In nw12, we were using a "node-remote" setting like this:

      "node-remote" : "somedomain.com,127.0.0.1:3000",

In nw13, that throws an "Invalid Scheme" error.  Adding http:// to the domains fixes this:

      "node-remote" : "http://somedomain.com,http://127.0.0.1:3000",

However, now I'm getting an "invalid port" error.  I thought that perhaps it might be our 3000 port.  But strangely, both these work ok individually:

      "node-remote" : "http://somedomain.com",

OR

      "node-remote" : "http://127.0.0.1:3000",

But when they are included together, the "invalid port" error is thrown.

Am I using the correct format here?

Thanks

**Comment by b1rdex** [comment] 2015-10-15 02:45
Dupe of #3571. It's confirmed bug.

**Comment by mscreenie** [comment] 2016-01-04 12:25
Any updates? This is quite a bug.

**Comment by liufangfang** [comment] 2016-04-11 05:30
I want to know a right scheme. I wirte it according to the document of "http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote", but it report error.

**Comment by rogerwang** [comment] 2016-04-11 05:45
An array for node-remote should be written like `"node-remote":["<all_urls>", "..."]`

**Closed by rogerwang** 2016-04-11 05:45 UTC

**Comment by liufangfang** [comment] 2016-04-11 06:06
why "file://*" is wrong?
![image](https://cloud.githubusercontent.com/assets/3468473/14418108/7bc28d04-ffee-11e5-8cb3-f6933fb9bb7f.png)

**Comment by RohitSharma27** [comment] 2016-04-11 06:15
@liufangfang file protocol is not supported anymore. See [http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/](url)

**Comment by liufangfang** [comment] 2016-04-11 06:45
@RohitSharma27  Oh, thanks. I just see it in "http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote"
![image](https://cloud.githubusercontent.com/assets/3468473/14418752/886c88ac-fff3-11e5-99ee-914fe670f55a.png)

And I config "node-remote": "<local>,file://*,http://accounts.axeslide.com" in the last version, then how to replace it now?

**Comment by RohitSharma27** [comment] 2016-04-11 06:54
@liufangfang you can write `"node-remote":"<all_urls>"` in your package.json as it matches any URL that uses a permitted scheme. "file and app" scheme are not permitted anymore.

**Comment by RohitSharma27** [comment] 2016-05-09 09:31
@liufangfang  file scheme is permitted. And `"file:///*"` is how you write it. It should work fine but it isn't somehow. File is getting rendered but there is no node context available.

**Comment by liufangfang** [comment] 2016-05-09 10:00
Yes, I know it. Thanks
