### ISSUE TITLE
nwjs-v0.13.0-alpha0-win-ia32   can not excute alert("1");

### ISSUE THREAD

**Issue by xland** [nwjs/nw.js#3508] opened 2015-05-25 05:37 UTC
package.json:
{
  "name": "nw-demo",
  "version": "0.0.1",
  "main": "index.html"
}

index.html:
![1](https://cloud.githubusercontent.com/assets/2980915/7792373/16c5daa8-02e4-11e5-98cf-5ba24a077cd3.png)

System Environment:
windows 8.1  x64
user: administrator

description:
alert box  does not show!
##

**Comment by rogerwang** [comment] 2015-05-26 01:26
It will be fixed in alpha1. Thanks.

**Comment by Christywl** [comment] 2017-06-02 08:30
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment] 2017-10-10 02:13
close until there is more information.

**Closed by Christywl** 2017-10-10 02:13 UTC
Labels: needinfo

**Comment by xland** [comment] 2017-10-11 11:53
ok！close it~
