### ISSUE TITLE
Nw.js package program will occupy the program size in the C disk space. Disappear after manual closing. But not manually shut down, but directly shut down, occupied space will never be released.

### ISSUE THREAD

**Issue by gendew** [nwjs/nw.js#6250] opened 2017-10-31 03:26 UTC
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : nwjs-v0.26.2-win-ia32
Operating System : windows 7

### Expected behavior

<!- What do you think should happen? ->

Packed program open C will not have any space occupied

<!- What actually happens? ->
Disk space is occupied, the size of the size of the program
<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by Christywl** [comment] 2017-11-01 01:23
Could you please upload a sample to reproduce this?

**Comment by Yonezpt** [comment] 2017-11-03 03:34
@Christywl I think this is a duplicate of #6246 which was opened by the same user too.

**Comment by rogerwang** [comment] 2017-11-03 04:31
Close as duplicate. Thanks.

**Closed by rogerwang** 2017-11-03 04:31 UTC
Labels: needinfo
