### ISSUE TITLE
0.57.1-sdk crashed at Mac

### ISSUE THREAD

**Issue by ostwindli** [nwjs/nw.js#7900] opened 2022-06-05 03:10 UTC
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.57.1-sdk
Operating System : Mac OS M1 and Intel cpu

Two Questions:

1、It will crashed on both Macs， m1 and intel cpu；
2、In the m1，do not generate crashed dump files.

**Here is the dump file generated on the intel cpu mac**

[crash.zip](https://github.com/nwjs/nw.js/files/8839254/crash.zip)

**Comment by ayushmxn** [comment] 2022-08-03 02:55
Duplicate of #7928

**Closed by ayushmxn** 2022-08-03 02:55 UTC
Labels: needinfo
