### ISSUE TITLE
nwjs 0.13 beta5 - Wrong "restore" window size after click on the app in the taskbar on windows 10

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#4323] opened 2016-01-28 12:20 UTC
Hi, here is a simple demo (if needed) https://dl.dropboxusercontent.com/u/31740/storage/demo.zip

In the package json the min_width and min_height properties for window are set to 600 and 300.
Start the app, check the dimensions (all is OK)

Minimize the app, click on the app in the task bar to restore its window, check dimensions (width = 744px)

Any specific reason why this is happening ?

**Comment by rogerwang** [comment] 2016-01-28 22:04
@ghostoy pls check this with high priority.

**Comment by ghostoy** [comment] 2016-01-29 06:27
Same for Windows 8.1. I'll look into this.

**Comment by ZoomDomain** [comment] 2016-03-17 02:05
CTN DEV STEPHAN I am trying to get hold of you because your eclipse to notepad parser has dissapeared, i was just writing one, i am on deviantart mrz00m plz thanks!!!

**Comment by cTn-dev** [comment] 2016-03-26 12:10
@ghostoy @rogerwang Was the fix accidentally reverted when releasing the 0.13 ? (The same buggy behavior is back), this is also present in the recent 0.13.1 release.

**Comment by rogerwang** [comment] 2016-03-28 02:57
@cTn-dev No the fix is not reverted. This is due to a similar reason as https://bugs.chromium.org/p/chromium/issues/detail?id=419355

Will look to fix it soon.

**Comment by rogerwang** [comment] 2016-03-28 03:06
This is a regression introduced in 0.13.0-rc2.

**Comment by rogerwang** [comment] 2016-03-29 15:20
Fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-03-29 15:20 UTC
Labels: bug, nw13, test-todo, windows-only
