### ISSUE TITLE
Some nw interfaces do not work for window returned from nw.Window.open(remote_url) without node-remote manifest option

### ISSUE THREAD

**Issue by vsemozhetbyt** [nwjs/nw.js#5053] opened 2016-06-29 17:43 UTC
NW.JS 0.15.4 on Windows 7.

`package.json`

``` json
{
  "name": "savepage",
  "main": "savepage.js"
}
```

`savepage.js`

``` js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fs = require('fs');
/******************************************************************************/
nw.Window.open('https://github.com/nwjs/nw.js', { id: 'savepage_win' }, nwWin => {
  nwWin.showDevTools();

  nwWin.on('loaded', () => {
    nwWin.window.console.log('Trying to save the page...');

    nwWin.capturePage(imgBuffer => {
      fs.writeFileSync(`page.png`, imgBuffer);
    }, { format: 'png', datatype: 'buffer' });
  });
});
/******************************************************************************/
```

Output:

```
Trying to save the page...

Error in response to nw.currentWindowInternal.capturePageInternal: ReferenceError: nw is not defined
    handler              @ extensions::uncaught_exception_handler:8
    (anonymous function) @ extensions::uncaught_exception_handler:100
    safeCallbackApply    @ extensions::sendRequest:23
    handleResponse       @ extensions::sendRequest:81
```

**Comment by RohitSharma27** [comment] 2016-06-30 01:56
Try adding "node-remote":"<all_urls>" in your package.json

**Comment by vsemozhetbyt** [comment] 2016-06-30 06:19
@RohitSharma27 With this `package.json`:
```json
{
  "name": "savepage",
  "main": "savepage.js",
  "node-remote": ""
}
```
I get this error:
![1](https://cloud.githubusercontent.com/assets/10393198/16478661/bc9cb95a-3ea3-11e6-9608-86ca730d53e5.png)

**Comment by vsemozhetbyt** [comment] 2016-06-30 06:25
I've tried `"node-remote": "<all_urls>"` and it works. Thank you.

Is there any explanations in the docs why we need this addition for such patterns?

**Comment by RohitSharma27** [comment] 2016-06-30 06:47
Why didn't it show the <all_urls>? Anyways, it's just that you are telling nw that you want node and nw objects in every permitted scheme. You can allow this for selected schemes as well. Please refer the documentation for more info and close this ticket. Cheers. :)

**Comment by vsemozhetbyt** [comment] 2016-06-30 07:04
But why `nwWin.window` works in the page context without `node-remote` and  `nwWin.capturePage` does not? It seems as an obscurity in the doc or design.

**Comment by rogerwang** [comment] 2016-06-30 07:13
This is a trick to workaround an issue for remote pages. Consider moving it into a webview in the new window for 3rd party contents.

**Comment by RohitSharma27** [comment] 2016-06-30 07:37
@rogerwang Do you have any explanation for this behaviour? Does`capturePage()` internally use nw object?

**Comment by rogerwang** [comment] 2016-06-30 11:48
capturePage() is a method of nw.Window so yes, it depends on nw object ...

**Comment by RohitSharma27** [comment] 2016-06-30 12:49
So, here is my understanding about what's happening over here.
-> If **we don't write** the `"node-remote"` property then, 
we don't get the node and nw objects when we load the above url with http scheme. You can try to load some local page, let us say some html file placed along side your package.json. NW will use chrome-extension protocol and it would work. You won't get any error.
Now, to answer @vsemozhetbyt's question. When the above page gets loaded, `nwWin` object is passed to the callback so, it's there. You can even do `nwWin.window,console.log()` or do the same with a `setTimeout()` and it will work. When you do nwWin.capturePage(), it looks that it calls `nw.currentWindowInternal.capturePageInternal` which won't work as `nw`'s context was never included without you telling NW to do so. Notice that it says, `nw` is undefined and not the `nwWin`
P.S. :  Please correct me if I am wrong.

**Comment by RohitSharma27** [comment] 2016-06-30 18:38
I think this is the intended behaviour and that's what node-remote property is for. I can raise a PR to update the docs with proper explanation but let's wait for roger to approve this explanation.

**Comment by Christywl** [comment] 2017-03-24 02:32
@rogerwang , mark as 'documentation bug' per above RohitSharma27's comments. If incorrect, please update.

**Comment by danschumann** [comment] 2017-06-20 19:18
It says nw is not defined.  I tried all the `<all_urls>`, chromium --files stuff, but to avail, then I was like.. well, what if I just give it nw?

HACK but works!
```
nwWin.window.nw = nw
nwWin.capturePage(/* now works */)
```

Just set a global `nw` to my child window from my parent. EZ

**Closed** 2022-10-22 04:52 UTC
Labels: documentation
