### ISSUE TITLE
website not openning in iframe

### ISSUE THREAD

**Issue by FahadQurashi49** [nwjs/nw.js#7748] opened 2021-07-12 07:45 UTC
NWJS Version : 0.54.1
Operating System : macOS Catilina

### Expected behavior

should open website with cors in iframe on nwjs app

### Actual behavior

not opening website with cors in iframe, throwing error:

> Refused to frame 'https://github.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

### How to reproduce

Just running a simple application with iframe in it, it is not opening iframe and throwing error:
> Refused to frame 'https://github.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

I also have added nwfaketop and node-remote in manifest.json but nothing work:

```
<html>
    <head>
        <title>
            test nw
        </title>
    </head>
    <body>
        <div>iframe: </div>
        <iframe src="https://github.com/" style="width: 100%;height: 100%;" nwfaketop></iframe>
    </body>
</html> 
```

```
{
  "name": "nw-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "node-remote": "https://www.github.com/",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

sample project zip is also attached:
[nw-test.zip](https://github.com/nwjs/nw.js/files/6799463/nw-test.zip)

**Comment by FahadQurashi49** [comment] 2021-07-14 07:07
humble ping

**Comment by FahadQurashi49** [comment] 2021-08-20 11:17
any update on this?

**Comment by Haagimus** [comment] 2021-08-30 17:30
+1

**Comment by Nabeelhassan** [comment] 2021-11-10 10:20
any update on this @rogerwang ?

**Comment by hthetiot** [comment] 2021-11-10 13:51
Have you tried Node Frame using node-remote field.
> What can Node frames do?
> 3. Ignore X-Frame-Options headers for child frames.

Source: https://github.com/nwjs/nw.js/wiki/Security

Aka "remote sites when URL matches the node-remote field"

**Comment by hthetiot** [comment] 2021-11-10 13:53
Note: that sample provided in issue description works for me on nwjs 81.0.4044.138

**Comment by FahadQurashi49** [comment] 2021-11-10 14:04
> Have you tried Node Frame using node-remote field.
> 
> > What can Node frames do?
> > 3. Ignore X-Frame-Options headers for child frames.
> 
> Source: https://github.com/nwjs/nw.js/wiki/Security
> 
> Aka "remote sites when URL matches the node-remote field"

yes I've used "node-remote" field in above [example](https://github.com/nwjs/nw.js/issues/7748#issue-941770471), see my package.json

**Comment by FahadQurashi49** [comment] 2021-11-10 14:26
> Note: that sample provided in issue description works for me on (OLD) nw@0.45.6 (81.0.4044.138) and does display github.com
> 
> <img alt="Screenshot 2021-11-10 at 14 54 34" width="801" src="https://user-images.githubusercontent.com/8635/141125722-b82a54a6-d422-4e2b-b4fd-f5aae5454d39.png">

provided sample not working on latest version (0.58.0), the query was about the latest version (0.54.1 at that time). We already have our app deployed on an old version. we want to update it to latest version. thanks.

**Comment by hthetiot** [comment] 2021-11-10 18:28
> any other suggestions @hthetiot ?

Not for now, but if it works on older version, that a regression, and he'll this issue to move forward in term of scope i think. You may try other older version to find what version broke it to help find the source of the regression.

**Comment by Nabeelhassan** [comment] 2021-12-29 10:47
@rogerwang any update on this?

**Comment by runekaagaard** [comment] 2022-04-02 11:43
Yes got this issue too with the error: Refused to frame 'https://MYCOMPANY.awsapps.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

Did the following testing:

nwjs-sdk-v0.49.2-linux-x64: Works
nwjs-sdk-v0.59.1-linux-x64: Fails

If it's any help I can try to narrow that down to find the exact version!?

**Comment by rogerwang** [comment] 2022-05-06 16:20
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed** 2022-05-06 16:19 UTC
