### ISSUE TITLE
Windows loading icon stays visible after launching app

### ISSUE THREAD

**Issue by Dillybob92** [nwjs/nw.js#4685] opened 2016-04-06 12:21 UTC
Hey, I'm not sure if this is a bug, but I think it's a little abnormal.

But basically, when you click on nw.exe, the loading icon next to your mouse cursor appears for 3-5 seconds. Example:
https://i.gyazo.com/b8c93f501b77d6a811a7750dc8f805d0.gif

I thought this had to do with what was inside my `index.html`, but you can have a blank `index.html` and it still does it.

**My operating system is:**
Windows 7, 64-bit Professional
Samsung EVO 250GB SSD

**Build Tested Under**
nwjs-sdk-v0.13.3-win-x64

So, I don't think performance here is an issue. But, as you can see from the gif the app is already loaded, but the loading icon next to the cursor stays there for an excessive period of time. 

If you need any other OS spec's please let me know. I am not sure if this classifies as a 'bug', and maybe it's just how `nw.js` runs, so I apologize. I just think it's a bit strange the loading icon stays there even after the app is loaded. :8ball: 

Edit: Maybe it's just happening on Windows 7? Can anyone else confirm for 7, or if it's not happening on 8 or 10?

**Comment by rogerwang** [comment] 2016-04-07 08:46
I can reproduce this in a win7 system, but not on a win10 system.

The reason should be: 

a) NW inherits the Chromiuim's multi-process architecture, so it launches multiple processes; and windows changes the cursor to IDC_APPSTARTING (feedback cursor) for 2 seconds when CreateProcess is called. "If during those two seconds the process makes the first GUI call, the system gives five more seconds to the process. If during those five seconds the process shows a window, the system gives five more seconds to the process to finish drawing the window.
The system turns the feedback cursor off after the first call to GetMessage, regardless of whether the process is drawing." -- https://msdn.microsoft.com/en-us/library/windows/desktop/ms686331(v=vs.85).aspx

b) In that win7 system, if you watch the number of nw processes when it starts, at first it's 4 processes, then after a while it goes down to 3. That's the GPU process quits for some reason. So the feedback cursor should be waiting for the GPU process's first call to GetMessage, and timeouts when it quits.

Why the GPU process quits in that system is not known yet, but Chrome browser in the same system shares the same behavior.

**Comment by rdtsc** [comment] 2016-04-14 12:52
@rogerwang: In addition to Windows 7, I can reproduce this in a Windows 10 x64 environment without fail with the latest NW.js release. This same behavior is present in Chromium on both Windows 7 and 10.

![nwjs-cursor-behavior](https://cloud.githubusercontent.com/assets/6773893/14528157/2fd7d860-021c-11e6-94a8-c2b2787f4928.gif)

**Comment by FiatPax** [comment] 2016-04-15 09:18
I can reproduce this on Win 10 x64 with nwjs version v0.14.0

**Comment by rogerwang** [comment] 2016-04-15 12:33
@rdtsc @FiatPax could you please keep watching the number of nw.exe processes during startup? Does it change from 4 to 3 as I described?

**Comment by FiatPax** [comment] 2016-04-15 12:47
For me it is always 4 processes, using the SDK version.
![nwjsprocesses](https://cloud.githubusercontent.com/assets/7773544/14561779/61d44dc0-0321-11e6-90f2-9479e77a12af.PNG)

**Comment by rdtsc** [comment] 2016-04-15 17:07
@rogerwang: On Windows 10, my results are identical to @FiatPax's. Four processes are spawned and keep running:
![nwjs-cursor-behavior-2](https://cloud.githubusercontent.com/assets/6773893/14568970/e8d7fb54-0309-11e6-85a3-b3ac0c6e2896.gif)

On Windows 7, however, four processes are spawned and one of them quits ~2.2 seconds later:
![nwjs-cursor-behavior-3](https://cloud.githubusercontent.com/assets/6773893/14569036/2933b864-030a-11e6-99e6-d4c5ad123dbd.gif)

As you can see from the GIFs, both cases result in the system cursor being changed to `OCR_APPSTARTING`.

For reference, here's the test DLL I had Windows inject to log this:
```cpp
#include <fstream>
#include <iomanip>
#include <string>

#undef UNICODE
#include <windows.h>

BOOL APIENTRY DllMain(HMODULE, const DWORD reason, LPVOID)
{
  const auto imageName = []
  {
    char buffer[MAX_PATH] = {};

    ::GetModuleFileName(nullptr, buffer, sizeof buffer);

    std::string result(buffer);

    const auto marker = result.find_last_of('\\');

    if(marker != std::string::npos) result = result.substr(marker + 1);

    return result;
  }();

  if(imageName != "nw.exe") return TRUE;

  std::ofstream outputStream("c:/nwjs-process.log", std::ios::app);

  const auto log = [&]() -> std::ostream&
  {
    outputStream << '@' << ::GetTickCount();
    outputStream << " [" << std::setw(4) << ::GetCurrentProcessId() << "] ";

    return outputStream << imageName << " - ";
  };

  switch(reason)
  {
    case DLL_PROCESS_ATTACH: log() << "started.\n"; break;
    case DLL_PROCESS_DETACH: log() << "ended.\n";   break;
  }

  return TRUE;
}
```

**Comment by rogerwang** [comment] 2016-04-19 15:33
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-04-19 15:33 UTC
Labels: nw13

**Comment by rogerwang** [comment] 2016-04-19 22:51
Please try 
http://dl.nwjs.io/live-build/04-19-2016/f0a0ece-fda17ad-6f7e880-c56a187/v0.14.2/
http://dl.nwjs.io/live-build/04-20-2016/f0a0ece-fda17ad-6f7e880-c56a187/v0.14.2/

**Comment by rdtsc** [comment] 2016-04-20 01:17
@rogerwang: Confirming desired cursor behavior on Windows 7/10 x64. Thanks a lot for the prompt fix.

**Comment by Dillybob92** [comment] 2016-04-20 07:26
Can confirm it's working as well on the 0.24.2 4/20 build.

In fact, the app actually boots up quite a bit faster too.. Which is great! Thank you @rogerwang for your hard work

**Comment by FiatPax** [comment] 2016-04-20 12:01
@rogerwang App boots up faster as @Dillybob92 said. That's great thanks.
