### ISSUE TITLE
Why is reloaddev() not supported in v0.14.6?

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#4926] opened 2016-06-01 18:56 UTC
Just curious. I have an app that we use it on to clear memory out, and we want to upgrade, but not if reloaddev() isn't supported. Thinking of creating a branch and putting it back in for my own implementation, but want to know why it's not supported anymore. Thanks.

**Comment by iteufel** [comment] 2016-06-01 20:51
@joshterrill you can try `chrome.runtime.reload()`

**Comment by rogerwang** [comment] 2016-06-02 06:03
close as duplicate of #4856

**Closed by rogerwang** 2016-06-02 06:03 UTC
