### ISSUE TITLE
NW.js v0.13.0-rc2 Release Notes win64 application icon can't work by Manifest setting

### ISSUE THREAD

**Issue by yeaphone** [nwjs/nw.js#4548] opened 2016-03-11 06:01 UTC
![Uploading QQ图片20160311140840.png…]()
![Uploading 20160311140840.png…]()

**Comment by c-geek** [comment] 2016-03-12 14:14
We can't see your screenshots...

**Comment by GnorTech** [comment] 2016-03-13 00:52
This should be duplicate of #4486 .

**Closed by GnorTech** 2016-03-13 00:52 UTC
