### ISSUE TITLE
Calling Devtools on MacOs crashes NW

### ISSUE THREAD

**Issue by MichalMisiaszek** [nwjs/nw.js#4437] opened 2016-02-23 00:15 UTC
Hi,
My app is very simple and working until I call Developer Tools from main menu.
Then it crashes with error:
FATAL ERROR: v8::Object::GetAlignedPointerFromInternalField() Not a Smi
Received signal 6
 [0x00010c96069a]
 [0x7fff90e76f1a]
 [0x7fff537f8aa0]
 [0x7fff85d849ab]
 [0x0001173e924a]
 [0x00010dc03c62]
 [0x00010ede2e75]
 [0x00010eacf0ff]
 [0x00010dc1b653]
 [0x00010dc3eaf6]
 [0x00010dc43ef1]
 [0x1b3a9b40b61b]
[end of stack trace]

Thanks
Michal

**Comment by rogerwang** [comment] 2016-02-23 02:58
Are you using the SDK build?

**Comment by MichalMisiaszek** [comment] 2016-02-23 03:19
Yes. It is stable until I call Devtools menu.

**Comment by ghostoy** [comment] 2016-02-23 05:07
@MichalMisiaszek I could not reproduce this issue with 0.13.0 beta6 on Mac. Could you provide a sample app and NW version you are using?

**Comment by MichalMisiaszek** [comment] 2016-02-23 06:07
My app is working with external source and ip protected. Unfortunately I can't share it.
But I will try to narrow down what part of code does not work with Devtools on a Mac.
I know for fact that this is no happening on Ubuntu with the same code.
Regards
Michal

**Comment by rogerwang** [comment] 2016-02-23 06:41
A crash dump file (.dmp) should be helpful as well:

http://docs.nwjs.io/en/v0.13.0-beta6/For%20Developers/Understanding%20Crash%20Dump/

**Comment by MichalMisiaszek** [comment] 2016-02-23 18:07
Here is a crash dump file.

KOfinder Technologies Inc.
Director of Software Engineering
Michal Misiaszek
cell USA: +1 (916) 220-9250
email: michal.misiaszek@kofinder.com
www.kofinder.com

**Comment by ghostoy** [comment] 2016-02-24 02:00
@MichalMisiaszek I can't see the crash dump file. Github ignores the attachments in email. Would you mind to repost the crash dump shared via Dropbox or similar tools?

**Comment by MichalMisiaszek** [comment] 2016-02-24 03:37
Ok, here is a link to my Dropbox. In general we have own implementation of ProtoBuf in Javascript. It works well and without crash unless we start Devtools. In this case it crashes immediately. If I stop server sending messages then it does not crash unless I want to examine objects dropped to Console.
[00fc8255-355f-4358-92d1-32a3ab972d2d.dmp.zip](https://github.com/nwjs/nw.js/files/143894/00fc8255-355f-4358-92d1-32a3ab972d2d.dmp.zip)

**Comment by ghostoy** [comment] 2016-02-24 05:14
@MichalMisiaszek Which NW version are you using?

**Comment by MichalMisiaszek** [comment] 2016-02-24 05:16
nw.js v0.13.0-beta6
Node v5.6.0
Chromium 48.0.2564.109
commit hash: b56bc84-0ea2dd87-12e9f94-44456c1

KOfinder Technologies Inc.
Director of Software Engineering
Michal Misiaszek
cell USA: +1 (916) 220-9250
email: michal.misiaszek@kofinder.com
www.kofinder.com

**Comment by ghostoy** [comment] 2016-02-24 06:23
@rogerwang @MichalMisiaszek The crash dump file on OSX doesn't match the hash of the symbol files. And looks like it's a general issue on Mac. I've reported it in #4450. So far the crash dump file is not useful. Could you be possible to provide a minimal sample app to reproduce the issue?

**Comment by MichalMisiaszek** [comment] 2016-02-24 06:25
Let me try but not today. Server compiled for Mac is OK ? 

KOfinder Technologies Inc.
Director of Software Engineering
Michal Misiaszek
cell USA: +1 (916) 220-9250
email: michal.misiaszek@kofinder.com
www.kofinder.com

**Comment by rogerwang** [comment] 2016-02-24 06:27
@ghostoy could you please try build a release version, verify the dump decoding is working and send it to @MichalMisiaszek ? So the crash dump will be good.

**Comment by ghostoy** [comment] 2016-02-24 07:18
I'll try.

**Comment by ghostoy** [comment] 2016-02-25 03:13
@MichalMisiaszek Please try use this build and send back the crash dump. https://www.dropbox.com/s/xilc0hew09nd0m6/issue-4437.tar.gz?dl=0

**Comment by ghostoy** [comment] 2016-03-03 06:57
@MichalMisiaszek Any updates?

**Comment by MichalMisiaszek** [comment] 2016-03-03 07:44
I will test it on Friday and let you know.

**Comment by ghostoy** [comment] 2016-03-08 02:05
@MichalMisiaszek Could you also test if latest RC1 works for you?

**Comment by ghostoy** [comment] 2016-03-28 02:05
@MichalMisiaszek 0.13.0 final is released. Could you test if it crashes on your Mac?

**Comment by ghostoy** [comment] 2016-04-01 01:29
Close the issue since no response for 3 weeks.

**Comment by MichalMisiaszek** [comment] 2016-04-21 17:05
Hi, I downloaded version 0.14 still crashes.

**Comment by ghostoy** [comment] 2016-04-22 13:37
@MichalMisiaszek Could you upload crash dumps from 0.14?

**Comment by MichalMisiaszek** [comment] 2016-04-22 15:57
Hi,
I have problem to locate crash dump.
Regards
Michal

**Comment by MichalMisiaszek** [comment] 2016-04-22 16:31
[ba0d9f96-de1b-4399-9d17-b8ed7d45bcff.dmp.zip](https://github.com/nwjs/nw.js/files/232191/ba0d9f96-de1b-4399-9d17-b8ed7d45bcff.dmp.zip)

Here is a crash dump. I am using Google Buffers and once message arives from server then app crashes only if Devtools are open. If I stop server and do not send messages I can inspect app with Devtools.

**Comment by MichalMisiaszek** [comment] 2016-04-28 16:22
Hello, 
Any findings ? Shall I do something more ? In my opinion using protoc is somehow crashing the tool.

**Comment by MichalMisiaszek** [comment] 2016-05-19 16:25
I noticed that crashing line is: v8::Object::GetAlignedPointerFromInternalField()
I saw something very similar on Ubuntu but fixed when I updated to newest version.

**Comment by ghostoy** [comment] 2016-08-03 02:14
@MichalMisiaszek Does it still happen in latest stable version 0.16.0?

**Comment by ghostoy** [comment] 2016-08-08 06:40
@MichalMisiaszek Close this issue since not able to reproduce. Please reopen it if you still see this issue in latest stable version.

**Comment by MichalMisiaszek** [comment] 2016-08-11 23:15
Still with 0.16.0 is happens. I can open DevTools, and when switch to Console to read objects the app dies and I am getting exception:
```FATAL ERROR: v8::Object::GetAlignedPointerFromInternalField() Not a Smi

 1: node::UVException(v8::Isolate*, int, char const*, char const*, char const*, char const*) [/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/libnode.dylib]
 2: node_module_register [/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/libnode.dylib]
 3:
v8::Object::SlowGetAlignedPointerFromInternalField(int) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 4: v8::Unlocker::~Unlocker() [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 5: ChromeMain [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 6:
v8::FixSourceNWBin(v8::Isolate*, v8::Local<v8::UnboundScript>) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 7: v8::FixSourceNWBin(v8::Isolate*, v8::Local<v8::UnboundScript>) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 8:
v8::FixSourceNWBin(v8::Isolate*, v8::Local<v8::UnboundScript>) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116711-37177-1lpig4l.dk5gqtzkt9/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 9: 0x375cd6308ba7
10: 0x375cd71e5427```

**Comment by proclaim** [comment] 2016-11-18 01:55
I'm using the latest v0.18.7, with node 7.1.0, still crash when I try to open dev tool

**Comment by ghostoy** [comment] 2016-11-18 07:43
@proclaim Do you have a sample app to reproduce the crash?

**Comment by proclaim** [comment] 2016-11-21 09:10
here's the download, FLUX studio 0.5.0
https://flux3dp.com/downloads

however, when you hover to the top left icon and use "inspect" to call out the devtool seems fine
ps. use ctrl + alt + d to call out the devtool

**Comment by ghostoy** [comment] 2016-11-22 08:36
@proclaim The crash looks happens only on 10.12. And the crash stack shows related to key press handling. I'll open another issue tracking on your case.

**Comment by proclaim** [comment] 2016-11-22 08:51
thank you =)

**Comment by ghostoy** [comment] 2016-11-29 05:10
Close it since it is different issue. See #5497.

**Closed by ghostoy** 2016-11-29 05:10 UTC
