### ISSUE TITLE
callback Nw.Win.open return null

### ISSUE THREAD

**Issue by osan15** [nwjs/nw.js#4788] opened 2016-04-28 12:42 UTC
Hi,

When  I do nw.Window.open with an external URL like below, the callback parameter is "undefined" but Window opens.

```
nw.Window.open('https://github.com', {}, function(new_win) {
   //new_win => undefined
});
```

Is that normal ?

I use NWJS v14.2 with Windows 7

Thank you in advance for your help

**Comment by rogerwang** [comment] 2016-04-29 02:17
Could you please try again with the nightly build? : http://dl.nwjs.io/live-build/04-29-2016/nw14-6a70963-b0cc05f-3d8c7fc-24751d8

**Comment by osan15** [comment] 2016-04-29 12:59
It is still not working, half the time

**Comment by osan15** [comment] 2016-04-29 13:15
The call Stack associated with debugger in callback : 

(anonymous function) (VM24861:2)
(anonymous function) (extensions::nw.Window:648)
(anonymous function) (extensions::app.window:137)
safeCallbackApply (extensions::sendRequest:21)
handleResponse (extensions::sendRequest:64)

**Comment by rogerwang** [comment] 2016-04-29 13:19
Could you please provide a full sample which reproduce the issue?

**Comment by osan15** [comment] 2016-04-29 13:31
![errors_sample](https://cloud.githubusercontent.com/assets/10058753/14917435/4fa3cc76-0e1f-11e6-8b3f-c0cd2a3a7295.JPG)

Its is random way

**Comment by AndryBray** [comment] 2016-04-29 14:13
Old issue (just for reference) 
https://github.com/nwjs/nw.js/issues/4188

**Comment by AndryBray** [comment] 2016-05-02 18:30
Hi @rogerwang 
could you please tell us what the priority of this issue is?
This is a blocking bug for who need to listen for events soon after the new window opening...
I hope you could fix it asap.

Thank you

**Comment by rogerwang** [comment] 2016-05-02 22:32
It's very high priority. The problem is I cannot reproduce it. I'll try
again with this sample.

**Comment by frankhale** [comment] 2016-05-02 23:24
I just tested on 0.15 beta1 and it's pretty easy to reproduce the issue. Here is a screenshot:

![nw-new-window-issue](https://cloud.githubusercontent.com/assets/190154/14970941/65f60e52-109b-11e6-98ce-6e3a0219ee8b.PNG)

**Comment by rogerwang** [comment] 2016-05-02 23:37
I see. It's easy to reproduce with devtools opening. Previously I was testing it with an automated case.
Will fix it today. Thanks.

**Comment by rogerwang** [comment] 2016-05-03 02:18
Please try again with this build: http://dl.nwjs.io/live-build/05-03-2016/nw14-d154648-1208bce-756e507-24751d8/v0.14.3/

**Comment by osan15** [comment] 2016-05-03 07:57
I tested and it seems that the window is defined all of the time.
But i found another problem, its impossible to catch Window event like document-start,document-end,loaded.

An example : 

```var win;
nw.Window.open('https://google.fr', {}, function(new_win) {
    console.log("This WIN : ", new_win);
    new_win.on("loaded", function() {
        console.log("windows loaded");
    })
    new_win.on("document-start",function(){
        console.log("document loaded");
    })
    new_win.on("document-end",function(){
        console.log("document-end");
    })
    win = new_win;
});```

**Comment by rogerwang** [comment] 2016-05-04 09:28
The callback fires in the same time with 'document-start'. I'll check the other events.

**Comment by rogerwang** [comment] 2016-05-04 13:41
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-05-04 13:41 UTC
Labels: test-todo

**Comment by rogerwang** [comment] 2016-05-04 23:20
Please try with this build: http://dl.nwjs.io/live-build/05-05-2016/nw14-9726928-f31ba84-756e507-24751d8/v0.14.4/
