### ISSUE TITLE
Taskbar icon bug - v0.14.1 SDK - Win x64

### ISSUE THREAD

**Issue by FiatPax** [nwjs/nw.js#4738] opened 2016-04-18 09:14 UTC
![tskbricon](https://cloud.githubusercontent.com/assets/7773544/14599114/3620b7ba-055e-11e6-81fc-21eaa99b1256.PNG)

The taskbar icon of the app is displayed wrong like in the picture, using a custom icon in manifest like:

"icon": "appicon.png",

**Comment by rogerwang** [comment] 2016-04-18 10:07
It works for me. Could you please upload a sample?

**Comment by FiatPax** [comment] 2016-04-18 10:32
[sample-taskbar-icon-bug.zip](https://github.com/nwjs/nw.js/files/223552/sample-taskbar-icon-bug.zip)

Please let me know if you can reproduce.

**Comment by rogerwang** [comment] 2016-04-19 01:04
It still works for me ... what's your OS version?
![1](https://cloud.githubusercontent.com/assets/165401/14624494/bfdd7254-060d-11e6-910b-2486362a25fd.png)

**Comment by FiatPax** [comment] 2016-04-19 10:53
I tested it again cleaning the cache nwjs creates in appdata folder also cleaned the temp folder just in case but the problem is still exist. I am using Windows 10 x64 and I have a doubt that in this issue https://github.com/nwjs/nw.js/issues/4635 he had the same problem.

**Comment by rogerwang** [comment] 2016-04-19 10:59
Could you please attach a full screenshot so I can see other details like the window borders etc?

**Comment by FiatPax** [comment] 2016-04-19 11:54
You may now watch on here: https://www.youtube.com/watch?v=EaliNm1SJ7Y
While I was on it I also recorded another weird behaviour, when I run my app on non-sdk version, it behaves different, some texts are not visible and I can't debug it since I can't turn console on on non-sdk version of nwjs: https://www.youtube.com/watch?v=99jyInjZlmo&feature=youtu.be

**Comment by rogerwang** [comment] 2016-04-19 12:21
Tried from win10 and it still works for me .. will try to figure out why ...

![1](https://cloud.githubusercontent.com/assets/165401/14638906/4ff29f82-066c-11e6-9b8d-4b50e1dd36f3.png)

**Comment by FiatPax** [comment] 2016-04-19 12:40
That's really weird, I'll also try to find out why good luck till then.

**Comment by DankoHR** [comment] 2016-06-17 09:11
Any progress on this? I have similar behaviour with Windows 10 Pro x64.
The icon in taskbar is not set correct:
![nwjs_taskicon_win10](https://cloud.githubusercontent.com/assets/18575203/16145788/cdce8fb0-347a-11e6-8920-62740869b1a6.PNG)
I have tried to delete Windows image cache and also changing the icon with resource hacker but to no  avail. Tried it on several Windows 10 machines and always had wrong taskbar icon.
When opening task manager the icon for process nwjs is correct, so it is only wrong for the taskbar under Windows 10 (Windows 7 and 8 do show correct icon).
![nwjs_taskmanager_win10](https://cloud.githubusercontent.com/assets/18575203/16146011/1dc82dea-347c-11e6-83ba-6dfedc5679fb.PNG)

**Comment by Pumpernickel61** [comment] 2016-07-17 14:05
+1 Same problem here like DankoHR. Just wondering from where this icon is coming from. It does not seem to be part of any file of nwjs-sdk-v0.15.4-win-x64 folder ...

**Comment by sourceskyboxer** [comment] 2016-07-17 21:36
Eh that is same my goal like @DankoHR !!!
Please fix it....

**Comment by Pumpernickel61** [comment] 2016-07-19 14:09
@ sourceskyboxer

Icon has be in PNG format, size 128*128 pixels. A bit depth of 32 bit works for me. Other size works only in window frame but not in taskbar. Tested with nwjs-sdk-v0.15.4-win-x64 and Windows 10 x64.

**Comment by patrickm** [comment] 2016-07-19 14:10
Please see #5006 for a fix.
Basically you need to add in your **package.json** window key (as we used to back in 12.x)
```
  "window": {
    "icon": "path/to/icon.png"
  }

```
And windows taskbar will now properly display it

**Comment by sourceskyboxer** [comment] 2016-07-20 16:15
Thanks for explanatory. Sorry for late because i am busy from my work. I know you said I must to bind path to png files. right. But it sees like fresh from nw.js dev or normal packages without icons.. That is failure. - If I use custom icons like path to png files like @patrickm suggests. I know that it is good for resolved solution. But they think because fresh nw binary hasn't to load original icons from nw.exe - If you open nw.exe than Taskbar Space doesn't show original icon from nw.exe that is why it has to fail for "default icon" - Who doesn't use custom icons??

**Comment by Pumpernickel61** [comment] 2016-07-20 19:16
@sourceskyboxer 
I agree. Indeed this "standard icon" looks strange especially because it is not the compass icon of nw.exe what one would expect. Chrome packed apps show the same strange taskbar icon when no custom icon is included in the related manifest file. Therefore I think/guess that this issue is caused by Chrome and not NW.js.

**Comment by sourceskyboxer** [comment] 2016-07-21 21:38
@Pumpernickel61 ah okay I understand now... That is reason of chrome instance. You're right. Thanks we can close it?

**Comment by Pumpernickel61** [comment] 2016-07-24 08:36
@sourceskyboxer
Yes, we can close it.

**Closed** 2016-11-08 01:51 UTC
Labels: nw13
