### ISSUE TITLE
inject_js_start effects iframe , and occurs some errors

### ISSUE THREAD

**Issue by lili21** [nwjs/nw.js#5460] opened 2016-11-10 11:15 UTC
looks like the inject_js_start will effect main html and iframe within main html. and this behavior occurs errors in iframe.

![2016-11-10 7 14 27](https://cloud.githubusercontent.com/assets/4456380/20174615/ae798472-a779-11e6-9355-c048f8a9f7de.png)

Just wanna inject_js_start effect main html. any ideas ?

* macOS sierra
* nw v0.14.7

**Comment by georgir** [comment] 2016-11-10 12:19
One option would be to address the error you get - just wrap your injected code in if(window.nw){...}
Another would be to not use inject_js and instead use a script tag in your main html. Since you provide almost no info, it is hard to tell if you really need injecting here.
Also do you have any reason to be using 0.14 when 0.18 is out already?

**Comment by ghostoy** [comment] 2016-11-11 01:43
You can test with the `location` to see if it's the URL of your main frame.

**Comment by lili21** [comment] 2016-11-11 02:20
@georgir I need to support windows XP. so I have to use 0.14.
currently my main html is a  url, I guess I can use webview tag,
thanks for the helping.

**Comment by lili21** [comment] 2016-11-11 04:03
@ghostoy ???

**Comment by ghostoy** [comment] 2016-11-11 08:11
`inject_js_start` works for both 0.14 (LTS) and 0.18 (stable). You can test if following sample works for you.

```javascript
// inject.js
if (location.href === 'http://url/of/your/main/frame') {
   // put your original code in here
}
```

**Comment by lili21** [comment] 2016-11-11 10:43
@ghostoy 
I guess what I really want is the js file just ignore iframe, cause the default behavior would make iframe load twice.

new issue , config `node-remote` for local file ? like `inject_js_start` file?

**Comment by ghostoy** [comment] 2016-11-14 05:37
What do you mean by "iframe load twice"?
And please open another issue for difference problems.

**Comment by lili21** [comment] 2016-11-14 06:56
I just figure out what happened. most part I guess.

the iframe content is using `angular` and `ui-router`. according to #3170, html5Mode is not supported well in nw.js. that make the iframe redirect, just looks like "reloading". 

the `node-remote` config, If I remove that, or do not config it proper, `nw` and `require` will also be undefined in `inject_js_start` and `inject_js_end`.Guess it is same proble,  that's why I asked here. If you insist, I can open a new issue.

**Comment by ghostoy** [comment] 2016-11-14 07:48
Could you please post a sample app to reproduce the issue?

`inject_js_start` is executed in the same context as in each frame. That means, if the frame is not a node frame, script in `inject_js_start` won't access nw and other Node.js APIs as well.

**Comment by lili21** [comment] 2016-11-14 10:01
How about some screen recoding videos ?  I did try to convert those videos to gifs, didn't work out.

1. [iframe redirect situation](https://youtu.be/0jGZ25wImgY)

2. [iframe loads as expecting](https://youtu.be/Oi5iEqW9y0A)

    Just make `node-remote` config unmatch the iframe src.

3. [html5Mode works well in main page](https://youtu.be/CHOIt-CedKU)

    the main page, which is `http://localhost:3000`, which is also using `angular` and `ui-router`  and set html5Mode true, just like iframe content. But the url is normal, as expecting, does not contain `/#/` stuff.

now I am really confused.

**Comment by ghostoy** [comment] 2016-11-14 13:51
I'm just wondering whether the snippet provided above, can prevent the injected script running in iframe.

As for the issues with angular framework or html5Mode, please create a new issue with a sample app. The video didn't help much.

**Comment by lili21** [comment] 2016-11-15 02:24
It can, sort of. But the iframe still redirect.

**Comment by lili21** [comment] 2016-11-15 05:13
#5478

**Comment by ghostoy** [comment] 2016-11-15 06:09
@lili21 That's a different issue. `inject_js_start` worked as expected.
I'm closing this issue. Reopen it if you see different.

**Closed by ghostoy** 2016-11-15 06:09 UTC

**Comment by lili21** [comment] 2016-11-15 06:30
well .as expected, inject_js_start should only be executed in main page.

**Comment by ghostoy** [comment] 2016-12-08 02:45
I don't understand why you insist "inject_js_start should only be executed in main page".

`inject_js_start` makes the script injected in **every frame**. That's the expected behavior. And I've already provided script above to prevent it running in sub frames if you don't like.

**Comment by lili21** [comment] 2017-02-16 10:11
what's about the errors ?. there shouldn't be errors if it is the expected behavior.

**Comment by georgir** [comment] 2017-02-16 17:58
if the code you inject is wrong, there should be errors. that is expected behavior.

**Comment by lili21** [comment] 2017-02-17 02:27
the error occurred while inject code run in iframe, but the code works well in iframe. I can use `nw` and `require`, they are not undefined.
