### ISSUE TITLE
OSX app crash on start with version 0.22

### ISSUE THREAD

**Issue by bengyles** [nwjs/nw.js#5878] opened 2017-04-26 21:10 UTC
I've built my app with nwjs version 0.22 and it crashes on osx. The previous time I built the app was with version 0.19.5 and everything worked, I just rebuild it with that version and it still works that way. I attached a log file below so maybe you can see what happened. It's from the osx machine of a collegue, I never worked with a Mac so don't really know where to start to troubleshoot. Please help :) 
[AppCrashMac.docx](https://github.com/nwjs/nw.js/files/959785/AppCrashMac.docx)

**Comment by rogerwang** [comment] 2017-04-26 23:26
It should be the duplicate of #5873

**Comment by bengyles** [comment] 2017-04-27 00:13
That could be it... sorry I didn't see that. So the symlinks started in version 0.22? In that case I can still build with nwjs 0.21 right? Thanks for the quick response.

**Comment by rogerwang** [comment] 2017-04-27 02:06
yes.

**Closed by rogerwang** 2017-04-27 02:06 UTC
