### ISSUE TITLE
[BUG]0.13.0beta6 can't use debugger

### ISSUE THREAD

**Issue by Hsinky** [nwjs/nw.js#4451] opened 2016-02-24 08:50 UTC
In my page,add code“nw.Window.get().showDevTools()”,and run the app,the DevTools is empty
![qq 20160224164948](https://cloud.githubusercontent.com/assets/10111222/13280045/b0c0d6ca-db16-11e5-97a5-f6929affb130.png)

**Comment by rogerwang** [comment] 2016-02-24 08:51
duplicate of #4438

**Closed by rogerwang** 2016-02-24 08:51 UTC
