### ISSUE TITLE
User data dir and User data nor work

### ISSUE THREAD

**Issue by machadoapoena** [nwjs/nw.js#7931] opened 2022-08-01 23:28 UTC
In my package.json i have all these args

` "chromium-args": "--remember-cert-error-decisions --ignore-certificate-errors --ignore-urlfetcher-cert-requests --allow-file-access-from-files --allow-file-access --allow-external-pages --accept-resource-provider --allow-cross-origin-auth-prompt --allow-http-background-page --allow-insecure-localhost --allow-running-insecure-content --ignore-urlfetcher-cert-requests --user-data-dir='c:/CONAB/SIFISC_PG/dados' --data-path='c:/CONAB/SIFISC_PG/dados/'"`

The --user-data-dir not create files on set directory.

Otherwise its create an C:\Users\%userprofile%\AppData\Local\%app_name%

whats wrong? Version 0.66

**Comment by ayushmxn** [comment] 2022-08-03 04:30
Could you provide a link to repro/steps to reproduce? Something similar to this?
https://github.com/ayushmxn/nw-repro

**Comment by machadoapoena** [comment] 2022-08-04 10:53
> Could you provide a link to repro/steps to reproduce? Something similar to this? https://github.com/ayushmxn/nw-repro

I have a old angular 1.6 application using version nwjs version 0.12 . So I decided to update to the last version 0.66. In the previous version of my application i was using the chromium-args like this below

`"chromium-args": "--remember-cert-error-decisions --ignore-certificate-errors --ignore-urlfetcher-cert-requests --allow-file-access-from-files --allow-file-access --allow-external-pages --accept-resource-provider --allow-cross-origin-auth-prompt --allow-http-background-page --allow-insecure-localhost --allow-running-insecure-content --ignore-urlfetcher-cert-requests --data-path="c:/CONAB/SIFISC_PG/dados/"`

Everything works good and indexeddb was generated in the data-path folder that I set. But when i changed to 0.66 the "--data-path" stop to work and the database was generated in the profile directory of OS. I tried to use "--user-data-dir='c:/CONAB/SIFISC_PG/dados'" but no success. If i create a shortcut EXE file and add the parameter --user-data-dir its works. But if i define in package.json at chromium-args property  its not work.

**Comment by JohnLego** [comment] 2022-08-04 22:18
@machadoapoena, you could try using an older NW.js version from earlier this year.
For instance, try v0.62.2.

https://dl.nwjs.io/v0.62.2/

I also notice that you are using one quotation mark for the data-path argument. I think you need to check your quotation marks and see.

**Comment by ayushmxn** [comment] 2022-08-05 15:49
I tried to [reproduce](https://github.com/ayushmxn/nw-repro/tree/dev-7931) on Ubuntu 22.04 and noticed that the directory was not created.

@TheJaredWilcurt @sysrage Can you confirm if it's happening on your end also?

**Comment by machadoapoena** [comment] 2022-08-05 16:05
I have been testing a lot of options...and what i found its the chromium-args property is limiting de number of letters. Or there is some arg that mess with this. Firs i think the --data-path is no more a valid arg. So  I changed to -user-data-dir. But at start was the last arg of my chromium-args and not working. So i changed to the beginning of the args and now the folder has been created.

So what works for me is change the arg "data-path" to "user-data-dir" and put at the start of args.

**Comment by ayushmxn** [comment] 2022-08-05 17:26
Ahh ok this is basically #7670. Closing this since it's a duplicate.

Since you upgraded from v0.12, have a look at the [migration guide](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/)

**Closed by ayushmxn** 2022-08-05 17:26 UTC
Labels: needinfo
