### ISSUE TITLE
nw.js 0.13.0-rc1 - "node-main" is never executed?

### ISSUE THREAD

**Issue by finim** [nwjs/nw.js#4514] opened 2016-03-07 10:25 UTC
System: Windows 8.1. x64
nw.js: nw.js 0.13.0-rc1 x64 sdk build

When declaring a "node-main" in the manifest (package.json), this file never gets executed?
Only the "main" entry is working.
This happens even only a "node-main" and no "main" is declared.

**Comment by rogerwang** [comment] 2016-03-07 11:03
close as duplicate of #4495

**Closed by rogerwang** 2016-03-07 11:03 UTC
