### ISSUE TITLE
Il n'y a pas d'action quand on clique sur un élément du menu

### ISSUE THREAD

**Issue by stephcache** [nwjs/nw.js#8238] opened 2024-12-04 19:53 UTC
Je viens de passé de la version 93 à 94 et quand je clique sur un élément du menu rien ce passe

**Comment by hthetiot** [comment] 2024-12-05 11:46
Issue Translated for community:
> I just upgraded from version 93 to 94 and when I click on a menu item nothing happens

@stephcache, je te recommande de fournir un petit example pour reproduire, meme si facile ça aide a qualifier ton probleme.
Je recomande l'anglais aussi, tu aurra plus d'aide :)

> My reply Translated 
I recommend that you provide a small example to reproduce, even if easy it helps to qualify your problem.
I recommend English too, you will get more help :)

**Comment by prominentdetail** [comment] 2024-12-06 01:07
I updated to 94 as well, and the menus don't work anymore. They aren't calling the functions.

**Comment by hthetiot** [comment] 2024-12-11 11:51
Close this Frenchy bug in favor of proper repported issue here https://github.com/nwjs/nw.js/issues/8240

I'm french and I approve this one should be close because not matching reporting requirements even after telling repporter in French to do so. Not acceptable Github behavior.

**Closed** 2024-12-11 11:53 UTC
Labels: needinfo
