### ISSUE TITLE
Better testing tool setup!

### ISSUE THREAD

**Issue by marnen** [nwjs/nw.js#3167] opened 2015-03-03 18:55 UTC
After a lot of struggling, I've managed to get my NW.js application set up with Mocha (browserless) for unit tests and Cucumber (on top of Protractor) for integration tests, and grunt-contrib-watch to automate it all (and to autobuild Haml and CoffeeScript). The relevant branch is http://github.com/marnen/sms-exporter/tree/89369384-testing-tools, and I'd be happy to have it used as a reference example, clone it into a separate repo, or write it up in the wiki if that seems good. The state of testing documentation for NW.js is perhaps not where it should be...
##

**Comment by brian-mann** [comment] 2015-03-25 05:06
I'm currently using your `protractor.conf.js` as inspiration.  However, because we're not going through `nw` when starting our app, the `require("nw.gui").App.manifest` is always undefined.  How do you get around this?  Am I missing something?  It seems doing integration testing with protractor isn't really the same as really running your NW app.

**Comment by marnen** [comment] 2015-03-25 05:09
I don't think I ever had that issue, but I've never used any `nw.gui` calls. Do you have problematic code available to look at?

**Comment by marnen** [comment] 2015-03-25 05:11
I should also mention that if Protractor isn't really running your NW app, that's likely to be the problem right there -- in my setup, it does run the NW app. Are you using Chromedriver?

**Comment by brian-mann** [comment] 2015-03-25 05:36
Yes, I'm using the special chromedriver for `0.12.0`.  My app does load in
protractor, but it's not exactly the same thing as launching it with `nw`.

For instance, in protractor I have to set a `baseUrl`, which I have set to:
`'file://' + process.env.PWD + '/nw/public/'`

But in my `package.json` file I use: `"main":
"app://app/nw/public/index.html"`

Of course there are also things like arguments I pass to the `nw` app,
which change its behavior, that I'm also obviously missing.  What I'm
getting at is that with protractor it seems like we're just hitting the app
files via the `file://` protocol.  I mean, yah It's launching node webkit
behind the scenes but I can tell it hasn't passed through my
`package.json`.  Where are all of my `window` settings?  The height / width
aren't correct amongst other problems.

At the moment I'm just wrapping require("nw.gui").App.manifest in a
try/catch and then reading the JSON from node.

I'm not sure how you could ever write an app without using
require("nw.gui").  That's the only way to dynamically manage the
application, window, etc.

**Comment by brian-mann** [comment] 2015-03-25 05:37
Yes, I'm using the special chromedriver for `0.12.0`.  My app does load in
protractor, but it's not exactly the same thing as launching it with `nw`.

For instance, in protractor I have to set a `baseUrl`, which I have set to:
`'file://' + process.env.PWD + '/nw/public/'`

But in my `package.json` file I use: `"main":
"app://app/nw/public/index.html"`

Of course there are also things like arguments I pass to the `nw` app,
which change its behavior, that I'm also obviously missing.  What I'm
getting at is that with protractor it seems like we're just hitting the app
files via the `file://` protocol.  I mean, yah It's launching node webkit
behind the scenes but I can tell it hasn't passed through my
`package.json`.  Where are all of my `window` settings?  The height / width
aren't correct amongst other problems.

At the moment I'm just wrapping `require("nw.gui").App.manifest` in a
try/catch and then reading the JSON from node.

I'm not sure how you could ever write an app without using
`require("nw.gui")`.  That's the only way to dynamically manage the
application, window, etc.

**Comment by marnen** [comment] 2015-03-26 19:21
@brian-mann:

> My app does load in protractor, but it's not exactly the same thing as launching it with `nw`.

Yes it is, or something is going seriously wrong.

> For instance, in protractor I have to set a baseUrl, which I have set to: `'file://' + process.env.PWD + '/nw/public/'`
> But in my package.json file I use: `"main": "app://app/nw/public/index.html"`

That's sort of irrelevant. It may be going to a different URL at the beginning, but otherwise it should be running it exactly as you would with `nw`. Does it open the `nw` application when you run with Protractor, or is it running in some other browser? If the latter, then there's your problem.

> What I'm getting at is that with protractor it seems like we're just hitting the app files via the file:// protocol. I mean, yah It's launching node webkit behind the scenes but I can tell it hasn't passed through my `package.json`.

On what basis do you believe that?

> Where are all of my window settings? The height / width
aren't correct amongst other problems.

Who cares? As long as it's launching `nw` and getting the proper DOM, does it really matter for testing purposes if the height and width are correct? (I haven't yet set height and width for my application, so I didn't realize this.) The user is likely to resize the window anyway, so you can't rely on any one size, can you?

> At the moment I'm just wrapping `require("nw.gui").App.manifest` in a try/catch and then reading the JSON from node.

What does that do? Does it read the `package.json` settings?

> I'm not sure how you could ever write an app without using `require("nw.gui")`. That's the only way to dynamically manage the application, window, etc.

Not every application needs that, at least early in development, which is why I haven't used it and don't know how it behaves. (Of course, though, it should work for testing when it's used.)

**Comment by Paxa** [comment] 2015-03-27 17:18
Having same problem, seems like nwjs chromedriver not reading `package.json`, I'm using it with ruby and capybara.

**Comment by marnen** [comment] 2015-03-27 17:33
@brian-mann and @Paxa: if you have code you can point me to, I'd like to take a look.

**Comment by Paxa** [comment] 2015-03-27 17:57
I try test with following code:

```ruby
require "capybara"
require "selenium-webdriver"

ENV["PATH"] = "~/Downloads/chromedriver:" + ENV["PATH"]

Dir.chdir("~/Sites/postbird") do
  Capybara.register_driver :chrome do |app|
    Capybara::Selenium::Driver.new(app, browser: :chrome)
  end

  Capybara.javascript_driver = :chrome

  Capybara.configure do |config|
    config.current_driver = :chrome
    config.run_server = false
  end

  include Capybara::DSL

  visit 'file:///Users/pavel/Sites/postbird/index.html'

  p evaluate_script('process.version');
  #p evaluate_script('JSON.stringify(require("nw.gui").App.manifest)');

  p page.title
end
```

Folder `~/Downloads/chromedriver` contains:

```
chromedriver
node-webkit.app
selenium-server-standalone-2.45.0.jar
```

chromedriver for version v0.11.6, if I take for version 0.12, it will try to find node-webkit.app (instead of nwjs.app, bug #3304)

When I start test I see this window for half second, then I see my application loaded, but window is small. I think it don't read `package.json`

![screen shot 2015-03-28 at 0 39 40](https://cloud.githubusercontent.com/assets/26019/6873516/72b36cce-d4e3-11e4-98c1-3f4830640522.png)

test output is:
```
% ruby test.rb
including Capybara::DSL in the global scope is not recommended!
"Postbird"
"v0.11.13-pre"
/Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/response.rb:51:in `assert_ok': unknown error: Unexpected end of input (Selenium::WebDriver::Error::UnknownError)
  (Session info: content shell=)
  (Driver info: chromedriver=2.10.290379,platform=Mac OS X 10.9.5 x86_64)
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/bridge.rb:634:in `raw_execute'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/bridge.rb:612:in `execute'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/remote/bridge.rb:333:in `executeScript'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/common/driver.rb:213:in `execute_script'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:84:in `evaluate_script'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara/session.rb:527:in `evaluate_script'
	from /Users/pavel/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	from test.rb:30:in `block in <main>'
	from test.rb:6:in `chdir'
	from test.rb:6:in `<main>'
```

If I add `--verbose --log-path=/tmp/chd.log` for chromedriver command, then output is https://gist.github.com/Paxa/028d937d5c68729fb6ff

I can see in log file:
```
 /Users/pavel/Downloads/chromedriver/node-webkit.app/Contents/MacOS/node-webkit --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/var/folders/nr/35h2m_wn6h143w_cdp_hrn4w0000gn/T/.org.chromium.Chromium.AFOCMd/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12020 --safebrowsing-disable-auto-update --safebrowsing-disable-download-protection --test-type=webdriver --use-mock-keychain --user-data-dir=/var/folders/nr/35h2m_wn6h143w_cdp_hrn4w0000gn/T/.org.chromium.Chromium.mIFY1b data:,
```
I think "data:" in the end give a problem.

**Comment by Paxa** [comment] 2015-03-27 17:59
Ruby library execute command `/Users/pavel/Downloads/chromedriver/chromedriver --port=9515`, seems correct

**Comment by marnen** [comment] 2015-03-27 19:17
@Paxa: Yeah, the data URL looks bogus. 

@Paxa and @brian-mann: what does your `protractor.conf` file look like?

@Paxa: Why are you writing your tests in Ruby instead of CoffeeScript/JavaScript? I understand why you'd do that in a Rails application, but in a NW.js application, there seems no reason to do that, and it may make it harder to configure Protractor.

**Comment by Paxa** [comment] 2015-03-28 00:18
I'm not using Protractor, I use capybara because I have experience with it, and I don't need to handle callback/prmises hell, ruby is synchronous.

But point is it runs chromedriver. Where can I see source code of chromedriver for nwjs? Is there any example how to load and run nwjs application with package.json? (not wikipedia or google)

**Comment by marnen** [comment] 2015-03-28 16:55
@Paxa I'm not going to give you any support for getting this to work with Ruby, because I think it's probably a terrible idea, and it's certainly more trouble than it's worth. If you want to do Node or NW.js development, you have to learn to work with asynchronous code (chai-as-promised is an extremely helpful library; I highly recommend it). 

As for source of NW Chromedriver, I know I've seen it in the repo *somewhere* (perhaps @rogerwang can remind us where).

**Comment by Paxa** [comment] 2015-03-28 17:22
Can you give an example how to use it with nodejs and wd (or with anything else) ?
I want it to load `package.json`, this example only load external url
https://github.com/nwjs/nw.js/wiki/Chromedriver#running

When I run
```
$ (your_project_path)/node_modules/.bin/wd shell
(wd): x = wd.remote()
(wd): x.init({ browserName: "chrome" })
(wd): x.get('file:///Users/pavel/Sites/postbird/index.html')
```

It shows

![screen shot 2015-03-29 at 0 16 58](https://cloud.githubusercontent.com/assets/26019/6882004/fa69d034-d5a8-11e4-9a09-2c0466a70003.png)

Selenium log is
```
% java -jar selenium-server-standalone-2.45.0.jar -Dwebdriver.chrome.driver=./chromedriver
00:15:36.011 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to ./chromedriver
00:15:36.078 INFO - Java: Apple Inc. 20.65-b04-462
00:15:36.078 INFO - OS: Mac OS X 10.9.5 x86_64
00:15:36.099 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
00:15:36.189 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: MAC
00:15:36.302 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
00:15:36.304 INFO - Version Jetty/5.1.x
00:15:36.305 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
00:15:36.307 INFO - Started HttpContext[/selenium-server,/selenium-server]
00:15:36.307 INFO - Started HttpContext[/,/]
00:15:36.376 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@b113622
00:15:36.377 INFO - Started HttpContext[/wd,/wd]
00:15:36.386 INFO - Started SocketListener on 0.0.0.0:4444
00:15:36.387 INFO - Started org.openqa.jetty.jetty.Server@4a79717e
00:15:59.082 INFO - Executing: [new session: Capabilities [{platform=ANY, javascriptEnabled=true, browserName=chrome, version=}]])
00:15:59.109 INFO - Creating a new session for Capabilities [{platform=ANY, javascriptEnabled=true, browserName=chrome, version=}]
Starting ChromeDriver (v2.10.290379) on port 24511
Only local connections are allowed.
00:16:01.015 INFO - Done: [new session: Capabilities [{platform=ANY, javascriptEnabled=true, browserName=chrome, version=}]]
```

ps. I believe if can run with python, it can run with ruby too

**Comment by marnen** [comment] 2015-03-28 17:41
@Paxa https://github.com/marnen/sms-exporter/tree/89369384-testing-tools isn't a sufficient example? If not, I'll try to improve it.

**Comment by Paxa** [comment] 2015-03-28 18:45
@marnen, good example, thank you

I clone it, run `npm install` then `grunt build` and I have folder `./build` with prepared app.

As I understand, chromedriver don't load `package.json`, just open requested `index.html`. It also fails on more complex things as take screenshot.

In you code in folder ./build i create file indicator.js

```js
// ./build/indicator.js
window.indicator = "INDICATOR 123";
```

Then add one line to `build/package.json`
```
"inject-js-start": "indicator.js",
```

I run app:
```
/Applications/nwjs.app/Contents/MacOS/nwjs ./build
```

In inspector I can see variable `window.indicator` is defined.

Then I run your protractor + cucumber tests and add my debuger anywhere in steps

```coffeescript
    browser.executeScript("return window.indicator").then (result) ->
      console.log(result)
```

It will print `null`, but if I append same line in `build/scripts/app.js` it will print correctly.

This means that chromedriver don't load your package.json in your test

---

Also have same problems that case some errors:
```coffeescript
browser.executeScript('return JSON.stringify(require("nw.gui").App)').then (result) ->
      console.log(result)
# works, print {}

browser.executeScript('return JSON.stringify(require("nw.gui").App.foo)').then (result) ->
      console.log(result)
# works, print null

browser.executeScript('return JSON.stringify(require("nw.gui").App.foo)').then (result) ->
      console.log(result)
# crashes, with
# UnknownError: unknown error: Unexpected end of input
#  (Session info: content shell=)
#  (Driver info: chromedriver=2.13 (a265cffc44f11287b4e3b12f0aac3f99bdee70ca),platform=Mac OS X 10.9.5 x86_64)
```

Other bug (or my misunderstanding):
```coffeescript
browser.takeScreenshot("1.png");
# UnknownError: unknown error: cannot get automation extension
# from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
#   (Session info: content shell=)
#   (Driver info: chromedriver=2.13 (a265cffc44f11287b4e3b12f0aac3f99bdee70ca),platform=Mac OS X 10.9.5 x86_64)
```

**Comment by marnen** [comment] 2015-03-29 14:31
@Paxa interesting. I actually hadn't yet done anything where `package.json` was significant, so I didn't realize this. I'm mostly working on other projects at the moment, but I'll try to find time to do something about that; you're right that it's a serious problem.

**Comment by marnen** [comment] 2015-03-29 15:28
@brian-mann Right, I realize that.

**Comment by Paxa** [comment] 2015-03-31 07:00
I dig inside and find some workaround.

We need to make chromedriver start node-webkit with extra argument. If we add `args` when create session it will append `--` in front. (node-webkit --bla-bla --/path/to/app)

I find solution if we build application and put in same folder with chromedriver, then app parameter `binary` in chromeOptions. So chromedriver will start your application directly instead nwjs and `require("nw.gui").App.manifest` will work too.

I could make it in ruby, with protractor it will be:

```js
// protractor.conf.js
  capabilities: {
    chromeOptions: { binary: "~/nw_testing/myapp.app/Contents/MacOS/nwjs" }
  },
```

To make package I use symlinks:

```
mkdir ~/nw_testing
cp -r /Applications/nwjs.app/ ~/nw_testing/myapp.app

rm ~/nw_testing/myapp.app/Contents/info.plist
ln -s /path/to/application/source/build_files/icon.icns  ~/nw_testing/myapp.app/Contents/info.plist
ln -s /path/to/application/source/build_files/icon.icns  ~/nw_testing/myapp.app/Contents/Resources/

ln -s /path/to/application/source ~/nw_testing/myapp.app/Contents/Resources/app.nw
```

----

When https://github.com/ghostoy/node-webkit/commit/4295eaef938ef9b70409873bc4462ec541e65e00 will be merged we can do just:

```js
// protractor.conf.js
  capabilities: {
    chromeOptions: { args: ["app-path=/path/to/your.app"] }
  },
```

**Comment by marnen** [comment] 2015-03-31 17:21
@Paxa Thanks, this is potentially quite helpful. I haven't had a chance to work on this issue in the last few days.

**Comment by karlrwjohnson** [comment] 2015-12-17 02:26
[As of **v0.13**](https://github.com/nwjs/nw.js/pull/3319#issuecomment-161318720), the flag is changed to `nw --nwapp=path/to/your.app`.

While I'm being leaving notes for the next person who tries to do what I'm doing, the total desiredCapabilities to pass to Selenium are as follows:
```
desiredCapabilities: {
  browserName: 'chrome',
  chromeOptions: {
    // The "--" is automatically prepended
    args: ['nwapp=/path/to/project/folder'],
    // It took me too long to figure out where this line belonged in chromeOptions
    binary: '/path/to/nwjs/nw'
  }
},
```

**Comment by Christywl** [comment] 2017-08-04 06:05
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment] 2017-10-09 07:49
close until there is more information.

**Closed by Christywl** 2017-10-09 07:49 UTC
Labels: needinfo
