### ISSUE TITLE
new-win-policy event handler not getting called

### ISSUE THREAD

**Issue by kumarasinghe** [nwjs/nw.js#7121] opened 2019-07-29 11:13 UTC
NWJS Version : 0.39.0
Operating System : Windows 7, 10

Following is not working:

```
nw.Window.open('http://ww.github.com/', {}, (nwWindow) => {
    nwWindow.on('new-win-policy', function (frame, url, policy) {
       // Never get called
     })
}
```

**Comment by hrocha1** [comment] 2019-08-02 12:19
possibly related to #7125? can you try the same thing with local file?

**Comment by rogerwang** [comment] 2019-08-03 07:02
yes, this is duplicate of #7125, which was just fixed in git.

**Closed by rogerwang** 2019-08-03 07:02 UTC
