### ISSUE TITLE
Program doesn't fully quit when a webview's devtools are opened in a webview

### ISSUE THREAD

**Issue by BrandonXLF** [nwjs/nw.js#7588] opened 2020-10-12 02:56 UTC
NWJS Version : 0.49.0
Operating System : Windows 10

### Expected behavior

When all windows in the application are closed, the application closes and the .exe can be run again, deleted etc.

### Actual behavior

When all windows are closed, some processes remaining running, preventing the .exe from being run again, deleted etc.

The following processes remain:

![image](https://user-images.githubusercontent.com/42590338/95700170-59c69d80-0c14-11eb-870b-e1370a26b735.png)

The bottom process needs to be forced closed for the app to stop running
### How to reproduce

1. Go to the folder with nwjs
1. Set the package.json `main` key to `index.html`
1. Create index.html with:
```html
<button onclick="browser.showDevTools(true, devtools)">Open</button>
<webview id="browser" src="about:blank"></webview>
<webview id="devtools" src="about:blank"></webview>
```
1. Click on the "Open" button
1. Close the program
1. Try deleting nw.exe

### Note
This only occurs when the second parameter of `browser.showDevTools` is set.

**Comment by CosmoMyzrailGorynych** [comment] 2020-11-24 03:20
A script to reproduce:

```js
const webviewPage = document.createElement('webview');
const webviewTools = document.createElement('webview');
document.body.appendChild(webviewPage);
document.body.appendChild(webviewTools);
webviewPage.src = webviewTools.src = `https://google.com/`; // init some page
setTimeout(() => { // wait 5s so both pages load
    webviewTools.showDevTools(true, webviewTools);
}, 5000);
```
After 5 seconds, once you see devTools, close the app. You will see several exe and nw processes in your process list, and won't be able to run the app again unless you kill these processes.

**Comment by CosmoMyzrailGorynych** [comment] 2020-11-24 04:21
The issue appeared at `0.49.0-beta1`. It is not present on `0.48.4`.

**Comment by CosmoMyzrailGorynych** [comment] 2020-12-13 22:02
@rogerwang, pardon pinging you directly, but this issue could slip out of your attention. And I suppose that the issue where an app cannot be re-launched by a user without proper technical skills, regardless of OS, is a critical one.

The issue is still present in v0.50.2.

**Comment by rogerwang** [comment] 2020-12-14 00:37
Will see it soon. Thanks.

**Comment by rogerwang** [comment] 2020-12-15 14:42
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed** 2020-12-15 14:41 UTC

**Comment by CosmoMyzrailGorynych** [comment] 2020-12-15 21:46
![](https://media1.tenor.com/images/743df11bb5b286f4229652f2c15c2487/tenor.gif?itemid=7490790)
