### ISSUE TITLE
nw.App undefined on version 0.19.4 node main script

### ISSUE THREAD

**Issue by mari-myk** [nwjs/nw.js#5580] opened 2016-12-20 16:27 UTC
Hi, there. 
I'm running version 0.19.4 of nw in windows 7. 
I have 2 javascripts, one for the main and other one for node-main. 
When I run the node-main, the property of nw.App is undefined, even after I wait for sometime. 
Tested with the version 0.18.8 and the property is correctly defined. 
Did anyone had the same issue? 

thanks.

**Comment by ghostoy** [comment] 2016-12-21 05:09
Could you post a sample app?

**Comment by mari-myk** [comment] 2016-12-21 11:05
my package.json
```json
{
  "name": "test",
  "version": "0.1.0",
  "license": "UNLICENSED",
  "description": "test",
  "main": "src/pipeline.js",
  "node-main": "src/nodemain.js"
}
```
my pipeline.js
```javascript
const gui = require('nw.gui');
var splash;

setTimeout(function () {
    const Splash = require('./modules/splash/splash.js');
    splash = new Splash.Splash();
    splash.open(gui, () => {
        splash.updateMessage('Opening . . .');
        executeNodeMain();
    });
}, 1000);

function executeNodeMain() {
    nw.process.mainModule.exports.RunNodeMain();
}
```
my nodemain.js
```javascript
function RunNodeMain() {
    console.log(nw);
    console.log(nw.App);    
}
exports.RunNodeMain = RunNodeMain;
```
my splash class
```javascript

class Splash {

    constructor() {
        this.configuration = {
            main: "src/assets/views/default.html",
            window: {
                fullscreen: false,
                width: 800,
                height: 800
            }
        };
    }

    open(gui, callback) {
        gui.Window.open(this.configuration.main, this.configuration.window, win => {
            win.on('loaded', () => {
                this.mensagem = win.window.document.getElementById('message');
                this.window = win;
                if (callback && typeof callback === 'function') return callback();
            });
        });
    }

    close() {
        this.window.close(true);
    }

    updateMessage(msg, callback) {
        this.mensagem.innerHTML = msg;
        if (callback && typeof callback === 'function')
            return callback();
    }
}

module.exports.Splash = Splash;
```

**Comment by ghostoy** [comment] 2016-12-22 02:11
I cannot reproduce it with 0.19.4 downloaded from https://dl.nwjs.io/live-build/12-22-2016/nw19-5c0f707-8643404-287bf0e-c24e9c9/v0.19.4/.

**Comment by ghostoy** [comment] 2017-01-16 08:42
Close it since not receiving feedback for more than 3 weeks. Please reopen it if you have any updates.

**Closed by ghostoy** 2017-01-16 08:42 UTC
Labels: needinfo
