### ISSUE TITLE
autocomplete=off  NOT WORK

### ISSUE THREAD

**Issue by zytse** [nwjs/nw.js#5348] opened 2016-10-07 13:20 UTC
autocomplete=off  NOT WORK

**Comment by ghostoy** [comment] 2016-10-11 07:31
Chrome ignores `autocomplete` attribute. See https://crbug.com/468153#c164

**Comment by sean220** [comment] 2016-10-26 02:21
It's fixed in 17.x,It reproduced In the new version of 18.x. #5184

**Comment by ghostoy** [comment] 2016-12-27 03:04
Closed as duplicate of #5184.

**Closed by ghostoy** 2016-12-27 03:04 UTC
