### ISSUE TITLE
nwdirectory input returning contents instead of top-level folder as documented

### ISSUE THREAD

**Issue by RickyRomero** [nwjs/nw.js#2961] opened 2015-01-16 19:47 UTC
The [documentation](https://github.com/nwjs/nw.js/wiki/File-dialogs#select-directory-node-webkit) for `nwdirectory` file choosers says:
> nwdirectory is a bit similar to webkitdirectory because it let user select a directory too, but it will not enumerate all files under the directory but directly returns the path of directory

So, I wrote a little file chooser that's triggered programmatically, but it still enumerates all files:
```javascript
function fileChooser()
{
    var chooser = document.createElement('input');
		chooser.setAttribute('type', 'file');
		chooser.setAttribute('nwdirectory', 'true');
	    chooser.addEventListener('change', function(evt) {
			console.log(this.value);
	    }, false);

	    chooser.click();
}
```

OS X v10.10.1, nw.js 0.12.0-alpha1.

**Comment by aio1108** [comment] 2015-01-20 06:08
I got the same problem...

I use OS X v10.10.1 and nwjs-v0.12.0-alpha2-osx-x64

**Comment by zefhemel** [comment] 2015-01-20 13:17
Indeed, deal breaker for me.

**Comment by MarcFowler** [comment] 2015-01-21 13:53
Can you not just parse the path and remove the file name? Check http://nodejs.org/api/path.html#path_path_basename_p_ext to get the file name itself, and then replace that with nothing.

```var path = this.value.replace(path.basename(this.value), '');```

Also, to help whether this is a regression from the stable branches, try with an older version of nw instead of 0.12.

**Comment by MaxSvargal** [comment] 2015-01-21 13:56
This dialog returned all files in selected folder, but not a folder itself!
Problem on OS X.
@MarcFowler omg duct tape

**Comment by zefhemel** [comment] 2015-01-21 13:57
This is a regression for sure, worked fine in 0.9.x (granted that's an old release but I hadn't updated since). @MarcFowler's workaround could be made to work, but then everything breaks again when this actually works as it's supposed to.

**Comment by GnorTech** [comment] 2015-01-21 14:04
Will fix this soon.

**Comment by MarcFowler** [comment] 2015-01-21 14:04
Haha yes it's an ugly hack but it'll work! Sometimes you got a deadline!

I can confirm that it works fine on OSX 10.10.1 on node-webkit **0.11.5**. So looks like a regression between those.

**Comment by kingslou** [comment] 2015-01-21 14:07
发自网易邮箱 iPhone 版
在2015年01月21日 22:04，Kevin Fan 写道:
Will fix this soon.

**Comment by kingslou** [comment] 2015-01-21 14:07
不过尔尔





发自网易邮箱 iPhone 版
在2015年01月21日 22:04，Kevin Fan 写道:
Will fix this soon.

**Comment by s6joui** [comment] 2015-02-02 23:53
This happens to me as well and if you select an empty folder it doesn't return anything at all so I can't even parse the path.

**Comment by akumpf** [comment] 2015-02-04 22:36
Same issue for me on OSX 10.10.1 with nw.js 0.12.0-alpha2 -- I can't let the user select an empty directory.

Also the "open" button says "upload" which seems a bit misleading (especially since normal file selection correctly say "open").

**Comment by felicienfrancois** [comment] 2015-02-05 08:07
+1

**Comment by akumpf** [comment] 2015-02-05 10:51
Perhaps I'm missing it, and this is only tangentially related, but I haven't found a way to add a **title** to the Directory selection dialog. Not sure if this is specific to the Directory selection, but seems like an important consideration to address soon if possible (unless I'm missing it and it's already there!).

This is helpful to give finer detail to the action clicked. For example, a user might click on a button titled "Select PDF Directory", but then once they are looking at the dialog (which naturally occludes what they just clicked), it's easy to feel hesitant and doubtful without a informative title like "Select the directory containing your PDF files".

**Comment by stereoplegic** [comment] 2015-02-05 18:31
@akumpf I'm not sure where nw.js could help in this regard. File/folder choosers opened via HTML5 file input are native (Windows Explorer/Finder/Nautilus/etc.), and as such their titles are handled natively.

**Comment by b1rdex** [comment] 2015-02-11 07:05
@GnorTech any news on this?

**Comment by rogerwang** [comment] 2015-02-13 07:28
would like to fix this in v0.12.0 beta. Thanks for your patience.

**Comment by matthew-dean** [comment] 2015-02-14 20:23
> Also the "open" button says "upload" which seems a bit misleading (especially since normal file selection correctly say "open").

Seeing that too.

**Comment by matthew-dean** [comment] 2015-02-14 20:35
Note that ```webkitdirectory``` is also non-functional as an attribute. (Creates the same problem.) I didn't see that mentioned yet.

**Comment by rurigk** [comment] 2015-02-15 07:55
It also happens in nwjs-v0.12.0-alpha3-linux-ia32
I noticed when trying to use it in a builder for nwjs in linux I'm doing

**Comment by murrah** [comment] 2015-02-19 11:11
@marcfowler While parsing the path from the returned list of files works as a workaround, when i selected a network root folder it grabbed 10,131file path names over a 5 minute period before the change event fired! It didnt crash though! ;-) 

So, it's back to v0.11.6 for me. :-(

Murray

**Comment by rogerwang** [comment] 2015-02-19 15:20
Fixed in git, will be released in the next version.

**Closed by rogerwang** 2015-02-19 15:20 UTC

**Comment by murrah** [comment] 2015-02-19 19:53
Great! Thanks Roger! :-)

**Comment by rogerwang** [comment] 2015-02-19 23:49
The live build from git tip can be downloaded from: http://dl.nwjs.io/live-build/02-19-2015/fcf09f1-4aad9fe-b1a5bb9-add523e-2bdc251-c114bb7/

**Comment by murrah** [comment] 2015-02-20 00:23
Great! Thanks! I will download and test now.

**Comment by aidansteele** [comment] 2015-03-09 09:39
This can be closed now as of the release of 0.12.0. :)

**Comment by docotronic** [comment] 2016-04-08 12:14
The Problem seems to be back in Version v0.14.0-rc3

**Comment by Docteur-RS** [comment] 2018-01-21 21:18
Version 0.27 is affected... I'm using NW for a school project. This is really not helping...

**Comment by b1rdex** [comment] 2018-01-22 03:15
@Docteur-RS please file a new issue with reproducible example with reference to this issue.
