### ISSUE TITLE
nw2: tray icon from bg-script is detached from app after reloading the app

### ISSUE THREAD

**Issue by Luzzifus** [nwjs/nw.js#7223] opened 2019-11-19 09:05 UTC
NWJS Version : 0.42.5
Operating System : Win10 (1903)

### Expected behavior

Initializing a tray icon via bg-script, according to [the tray doc page](http://docs.nwjs.io/en/latest/References/Tray/), the tray icon should still work after an app page reload via context menu or dev tools.

### Actual behavior

Well, it does not. It still gets detached from the app after reloading and it also won't be destroyed when the app is closed.

### How to reproduce

Only happens in NW2 mode, works as expected with "chromium-args": "--disable-features=nw2".

My tray script: 

    let requestAction = action => global.model.app.requestAction = action;
    let trayOptions = { title: 'Test', tooltip: 'test', icon: 'html/icon/icon016.png' };
    let tray = new nw.Tray(trayOptions);
    tray.on('click', () => requestAction('show'));

    let menu = new nw.Menu();
    menu.append(new nw.MenuItem({ label: 'Exit', click: () => requestAction('exitApp') }));
    tray.menu = menu;

Initialized via package.json:

    "bg-script": "lib/app/trayIcon.js",

#7230

**Comment by rogerwang** [comment] 2019-12-30 02:32
Could you please provide a full sample (not code snippets) so I can reproduce? I tried a sample but the behaviour is the same between nw1 and nw2.

**Comment by Luzzifus** [comment] 2019-12-30 08:21
@rogerwang I tested again with 0.43.2.

The problem is actually not the bg-script being detached. As it seems to me, the document-end event is not fired anymore in nw2 mode when reloading the app via CTRL + SHIFT + R in the dev tools window.

Further explanation: My app spawns and manages a variable amount of child windows on startup (they're frameless, transparent and have no taskbar icon, so they can only be managed by the app). It keeps handles of all child windows and when the app is closed via either the main window close button or the tray icon exit option, it closes and destroys all child windows and the tray icon before closing itself. This still works fine.

Now for the case of reloading via dev tools: I have handled this case by using the "document-end" event of the main app window to do all the child windows / tray icon closing stuff before the main app is reloaded. This only works with nw2 disabled. With nw2 enabled, the "document-end" event is not being fired. This results in the child windows and tray icon from before reloading the app remaining open, so that I have all child windows doubled after reloading.

I tested this by changing the background color of the child windows instead of closing them in the "document-end" event handler. I only saw the changed background with disabled nw2 mode.

I can't seem to find any changes about the "document-end" event in the documentation, so I'm not sure if I need to adjust something or if this is indeed a bug. 

Because of all the child window spawning, providing you with a working code example would be a bit of work. If you absolutely need to see it in action, I could give you access to the private repository of my app.

**Comment by rogerwang** [comment] 2019-12-30 13:14
Could you write a small case to verify your thoughts? I just tried a case which depends on 'document-end' and it works well: https://github.com/nwjs/nw.js/tree/nw43/test/sanity/document-start-end

**Comment by Luzzifus** [comment] 2019-12-30 14:44
I investigated a bit further and found out:

"document-end" will not be fired when I register it in jQuerys .ready() function. I attached a small test app, which includes two .html files of which only one is loaded via init.js. For one html-file "document-end" works as expected, for the other one it doesn't. Switch between both files in init.js and then reload the app in the dev tools with CTRL + SHIFT + R.

Again, it works for both test cases if nw2 is disabled.

[docEnd_test.zip](https://github.com/nwjs/nw.js/files/4010015/docEnd_test.zip)

**Comment by rogerwang** [comment] 2020-01-01 05:04
First, the sample code doesn't have the event fired before reload -- it's not supposed to fire because when the event handler is registerred in jQuery's ready(), it's already late.

With NW1 the event is fired after reload. But it is from the handler in the previous Window object, which should be destroyed when the reloading happens. It's fixed in NW2. 

btw, in NW1 when you reload it again the event handler is called twice.

**Comment by rogerwang** [comment] 2020-01-01 05:18
closing for now since there is no actual bug here.

**Closed by rogerwang** 2020-01-01 05:18 UTC
Labels: nw2

**Comment by Luzzifus** [comment] 2020-01-01 08:07
@rogerwang 

> First, the sample code doesn't have the event fired before reload -- it's not supposed to fire because when the event handler is registerred in jQuery's ready(), it's already late.

Of course the registered event does not fire for the reload which caused the execution of the .ready() function. That's not what it's supposed to do. It is supposed to register an event handler for a reload which is initiated AFTER that. 

> With NW1 the event is fired after reload. 

It is not though, since if it were like that, my child windows from the previous instance would not be destroyed correctly. Also, if the event handler is registered correctly, shouldn't it fire the event independent of when it was registered? I mean even if I register the handler dynamically when the user clicks a button (just an example) shouldn't it fire when the app actually reloads at some point of time after that? I really don't understand why it doesn't fire when I register it later. Also that would severely limit the usefulness of that event.

> btw, in NW1 when you reload it again the event handler is called twice.

I don't see two alerts no matter how often I reload.

**Comment by rogerwang** [comment] 2020-01-01 09:02
By 'late' I mean the handler is registered after the point when the event should be fired.

When a page reloads, all the JS objects in it should be destroyed, including the event handler. A correct way to survive the page reload is to put the code in the background page, where 'init.js' is running.

**Comment by Luzzifus** [comment] 2020-01-01 10:05
Thanks for your patience!

> A correct way to survive the page reload is to put the code in the background page, where 'init.js' is running.

This does actually fire the events all the time. One step forward. But when I try to close my child windows in the background page, I get an exception "extension context invalidated". 

When using "document-end", my model was already reset and the child window objects/handles were gone. So I used "document-start". Now the handles are still available but the windows still can't be closed because of the exception.

```
let closeActiveWidget = widgetModel => {
  if (typeof widgetModel.win == 'object')
    widgetModel.win.close();  // <-- this causes the "extension context invalidated" exception
}

let cb = win => {
  win.on('document-start', () => {
    model.activeWidgets.m_children.forEach(closeActiveWidget);
    win.removeAllListeners();
  });
}

nw.Window.open('index.html', {width: 850, height: 600}, cb);
```

**Comment by rogerwang** [comment] 2020-01-02 03:34
This could be another issue. You can file a new one with reproducible sample. Thanks.
