### ISSUE TITLE
nwjs process not starting v0.18.0 appended zipfile

### ISSUE THREAD

**Issue by swouters** [nwjs/nw.js#5364] opened 2016-10-14 19:28 UTC
Version: 0.18.0 x64 and i32
OS: Windows 10 64bit

When running an application appended as a zipfile, no nwjs window opens.
There is no visible nwjs process running.
A Node.js process starts and does not stop unless I kill the process manually.

I append the build.nw file using the following command:
copy /b nw.exe+build.nw test.exe

No crash dump file is created. 
Removing Appdata does not solve the problem.

The same build.nw file appended to version 0.17.6 and previous versions works fine.

The build.nw and the source files are attached here:
[source_and_build.zip](https://github.com/nwjs/nw.js/files/530317/source_and_build.zip)

**Comment by mahadeokr** [comment] 2016-10-14 20:29
IMEI 353310076723556

**Comment by leknoppix** [comment] 2016-10-16 08:21
hello, i have the same problem than swouters. When I compile my project, the executable no work.
So, for the moment, I use the version v.0.17.6.

**Comment by chadams77** [comment] 2016-10-16 17:01
It'll work if you rename the exe back to nw.exe, there's a glitch in this version that prevents it from starting under windows if the exe has been renamed. I also tried renaming nw.dll to {myapp}.dll, that didn't work either.

**Comment by leknoppix** [comment] 2016-10-16 18:30
It work for my project! Thanks

**Comment by rogerwang** [comment] 2016-10-17 12:13
close as duplicate of #5362

**Closed by rogerwang** 2016-10-17 12:13 UTC
