### ISSUE TITLE
App does not quit on Window.get().close(true) or App.quit() on macOS in some cases

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#7226] opened 2019-11-19 18:03 UTC
I've noticed this behavior on 0.42.x builds on macOS Catalina, not sure what version it was introduced in, but have not seen it in 0.39.x builds, have not tried reproducing it on older macOS either.

I'm going to describe how to reproduce something like this reliably with latest sdk build, but I'm still trying to figure out if I can get some minimalistic example on normal build and maybe I'm actually talking about two different defects here.

NWJS Version : 0.42.5
Operating System : macOS Catalina

### Expected behavior

App should exit.

### Actual behavior

App is hidden, can not be restored, but app icon shows app as running and chrome_crashpad_hander and app / GPU / Renderer helpers keep running.

### How to reproduce

1) start nwjs from sdk build
2) open dev tools via right click + Inspect
3) focus back on nwjs window
4) press `⌘ + Q`

after that nwjs and dev tools windows are closed and can not be opened, but app is still running, and it shows `Hold ⌘ Q to Quit` message on top of  screen if you try switch to the app, ignoring any events

<img width="370" alt="Screenshot 2019-11-19 12 16 00" src="https://user-images.githubusercontent.com/1192686/69169483-6acf6300-0ac6-11ea-8d4e-85b335899223.png">

After that it's only possible to `Force Quit` it, regular `Quit` does not work.

If instead of `⌘ + Q` you do `Quit nwjs` from nwjs menu it closes dev tools, but app keeps running and at that point it would not react to any form of quit command (`Quit nwjs` from menu, `Quit` on app icon, executing `nw.App.quit()` or `nw.Window.get().close(true)` in console if you re-open dev tools, which is possible in this case)

If I close dev tools before doing `⌘ + Q` it all works fine empty app.

In real app we periodically run into situation with 0.42.x builds when you do `Window.get().close(true)` or `App.quit()` after interacting with app for a while and everything gets closed, but app processes keep running.
The difference in this case is that if we click `Quit` on app icon the app exits right away after that, no `Force Quit` is necessary.
Unfortunately it's not clear how to debug this scenario, as after `Window.get().close(force)` or `App.quit()` dev tools exit and can not be reopened.
My only idea is to try to trigger crash of the app right after calling `win.close(true)` and app being stuck in that state, not sure though how to do that yet.

Actually, if you try those 4 steps on nwjs sdk build 0.42.3 then you `Force Quit` is not required, just `Quit` on app icon after that is enough. So, there is a chance that app not handling `win.close(true)` has always been observed on sdk builds only and we just did not realize it.

**Comment by arudnev** [comment] 2019-11-19 18:38
Just wanted to clarify that even though this behavior when app does not exit has potentially been observed on sdk builds only (need to do more testing on normal builds) we are getting in this state repeatedly without dev tools being ever opened and I hope that by fixing defect that is easily reproducible with dev tools the issue that we observe in the real app will also be resolved.

**Comment by arudnev** [comment] 2019-11-19 19:14
And one more variation of the same with 0.42.5 that kind of mimics what was happening in 0.42.3.

1) run `nwjs.app/Contents/MacOS/nwjs --disable-features=nw2`
2) open dev tools, close dev tools
3) try to quit the app from app top bar menu or by `⌘ + Q`

The app keeps running until you do `Quit` on app icon in the task bar, dev tools can not be re-opened.

**Comment by arudnev** [comment] 2019-11-21 17:46
I have not been able to reproduce this issue on normal build, so as of now it seems that this issue is specific to sdk builds only.

**Comment by nurishi** [comment] 2019-11-22 00:06
I've been facing the same issue and struggling to find out the cause as it's just randomly happening. I also have jumped from 0.39.* which had no issues  to 0.42.* and started to see.

I will also try with normal build and confirm whether the issue happens or not.

**Comment by nurishi** [comment] 2019-11-22 02:06
I've done with my tests with 0.42.*. I can confirm it's definitely issue with SDK devtool and both nw1/nw2 has problem but the result is slightly different.

[Not reproducible]
-nw1/nw2 normal build
-nw1/nw2 sdk build (never open devtool)
-nw2 sdk build (once open devtool and close it)

[Reproducible] *When calling close(true), app disappears but process is still alive.
-nw1 with sdk build (keep the devtool open and try closing the app)
-nw1 with sdk build (once open devtool and close it and then try closing the app)

[Reproducible] *When calling close(true), only devtool get closed but the app stays visible until calling close(true) once again.
-nw2 with sdk build (keep the devtool open and try closing the app)

For nw2, it seems also happening on Windows 10, but for nw1 seems not.
Hope that helps.

**Comment by jtg-gg** [comment] 2019-11-22 10:20
@rogerwang please accept my pull request https://github.com/nwjs/chromium.src/pull/144
for this issue

**Comment by rogerwang** [comment] 2019-11-23 14:06
Merged and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Closed by rogerwang** 2019-11-23 14:06 UTC
