### ISSUE TITLE
The "name" in package.json cannot be defined as "main":"../update.html"

### ISSUE THREAD

**Issue by liufangfang** [nwjs/nw.js#4700] opened 2016-04-11 03:50 UTC
How to direct  to path (relative to the directory). The "main":"../update.html" is OK in 0.12, but not work in 0.13. @rogerwang

**Comment by rogerwang** [comment] 2016-04-11 04:12
close as duplicate of #4672

**Closed by rogerwang** 2016-04-11 04:12 UTC
