### ISSUE TITLE
Pinch zoom does not work on Mac (0.28.2 - 0.28.3)

### ISSUE THREAD

**Issue by smotaal** [nwjs/nw.js#6491] opened 2018-03-01 12:42 UTC
NWJS Version : 0.28.2 - 0.28.3
Operating System : macOS 10.13.3 (17D102)

### Expected behavior

Pages that do not explicitly declare `<meta name="viewport" content="user-scalable=no">` in the header should be expected to behave exactly the same as they would in the equivalent Chrome version.

### Actual behavior

I have tried all the flags I could find for days and sans-flags, but pinch zoom does not work under any condition. This issue also affects WebViews, there seems to be some disconnect regarding certain events in NW.js.

### How to reproduce

The best test is to run this in console:

```js
open('http://maps.google.ca')
```

Try this across Chrome, Electron (2.0 beta) and NW.js (SDK).

**Comment by Christywl** [comment] 2018-03-02 02:46
I can reproduce this issue on Mac with nwjs-sdk-v0.28.3.

**Comment by rogerwang** [comment] 2018-03-05 12:53
It should be caused by the macOS SDK version used on the build slave. Will try to upgrade it after 0.29.0 release.

**Comment by rogerwang** [comment] 2018-03-08 13:05
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2018-03-08 13:05 UTC
Labels: P2, bug, triaged

**Comment by smotaal** [comment] 2018-03-08 18:27
Awesome, thanks Roger
