### ISSUE TITLE
Spellchecker API

### ISSUE THREAD

**Issue by Z3TA** [nwjs/nw.js#3603] opened 2015-06-23 14:53 UTC
I need to be able to access the internal spell-checker in JavaScript. I'm currently working on a canvas based editor.

Suggested API:

window.spellcheck.language= "en_US";
window.spellcheck.check = function(word) {
  return true; // or false
}
window.spellcheck.suggest = function(word) {
  return ["word1", "word2"]; // array of words
}

**Comment by adam-lynch** [comment] 2015-11-08 22:02
Duplicate of #332. Will be coming in 0.13.0. See https://github.com/nwjs/nw.js/issues/332#issuecomment-110973316.

**Closed by adam-lynch** 2015-11-08 22:02 UTC
