### ISSUE TITLE
Please update the MAS build to the latest NWJS

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6653] opened 2018-05-29 21:35 UTC
The current NWJS MAS build is on 0.19.5 see http://docs.nwjs.io/en/latest/For%20Users/Advanced/Support%20for%20Mac%20App%20Store/

while official NWJS is already at 0.30.5

@rogerwang can you please update the MAS build to the latest, we would really like to submit our app to the app store but we depend on the latest 0.30.5

**Comment by tankakatan** [comment] 2018-06-01 08:43
@gpetrov I am afraid it will not help. I have signed my app properly (via my own script), but so signed app crashes on start. I've tried to discover the reasons of that crash very carefully. Please read what i have found in #6338

**Comment by gpetrov** [comment] 2018-06-01 09:02
@tankakatan - signing is a different issue. We should first have a well compiled NWjs with the libraries that apple only allows. That is why the special MAS build is required. Then we can sign it.

@rogerwang - all true right Roger? Can you please, please add the MAS build to the live building process so it is always available?

**Comment by tankakatan** [comment] 2018-06-01 09:07
@gpetrov You are right, signing first )

**Comment by rogerwang** [comment] 2018-06-05 05:17
close as duplicate of #4556 

@gpetrov it's not a simple task as adding it to live build. It requires rebasing the MAS branch and test with MAS review process. @sunlin-link has been working on it.

**Closed by rogerwang** 2018-06-05 05:17 UTC
