### ISSUE TITLE
Transparent is a problem

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#6345] opened 2017-12-21 06:00 UTC
The interface has a problem after setting these two properties！
```
"transparent":true,
"frame": false
```

======== TEMPLATE BUG FORM ========

NWJS Version : 0.27.2
Operating System : win10 x64

### Expected behavior

After loading a web page, no explicit form should be produced！
Please look at the following picture. I set the window transparent, but a toolbar appears after a page with an opaque part in the middle part is loaded!
![qq 20171221135333](https://user-images.githubusercontent.com/6937002/34242559-fedfc4ae-e656-11e7-810a-4b8a3b5db095.png)

**Comment by phpjishu** [comment] 2017-12-21 06:00
@rogerwang

**Comment by Christywl** [comment] 2017-12-22 01:37
Could you please provide a sample to reproduce this?

**Comment by gpetrov** [comment] 2017-12-23 13:31
@Christywl just add transparent: true, frame: true
to your package.json and you will see it
a window title is always displayed - page is transparent 

tested in 0.27.3 still a problem. Using Windows 10 64 bit

Seems in the main chromium branch the frame options have changed as when adding frame: true I get the error:

[11380:2616:1223/142233.266:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running app.window.create: The alphaEnabled option can only be used with "frame: 'none'".

**Comment by Christywl** [comment] 2017-12-25 07:21
I can reproduce this issue on Windows 10 with nwjs-sdk-v0.27.3. It works fine on my Windows 8 device.

**Comment by phpjishu** [comment] 2017-12-26 03:15
When will the problem be repaired?

**Comment by jtg-gg** [comment] 2017-12-27 02:32
I can't reproduce this on Win10 version 1709, build 16299.125

**Comment by Christywl** [comment] 2017-12-27 02:51
@jtg-gg , My device: Windows 10, Version 10.0.16299.125
package.json:
```
{
  "name": "6345",
  "main": "index.html",
  "window":{
    "transparent": true,
	"frame":false
   }
}
```
index.html:
```
<html>
<title>Test</title>
<body>
<p>Hello</p>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/20039821/34368916-c7968f00-eaf2-11e7-9183-98a0a2f7f71e.png)

**Comment by gpetrov** [comment] 2017-12-27 08:00
@jtg-gg  I'm having exactly the same problem as @Christywl - the titlebar is just still visible while the window is transparent.

**Comment by tolrtd** [comment] 2018-01-03 23:11
Seeing same issue. 0.27.3 Windows 10 "Creator's Update" x64

**Comment by gpetrov** [comment] 2018-01-09 07:43
@rogerwang could you please check this issue - the ghost titlebar in transparent windows is really annoying - thanks!

**Comment by jtg-gg** [comment] 2018-01-16 03:47
@gpetrov I've tried on 3 different laptop, I can't reproduce it :(
so I'll need your help, to go through older nwjs version, to check which version works
only then I can compare the code

**Comment by gpetrov** [comment] 2018-01-16 10:04
@jtg-gg and @rogerwang - **found the problem** cause when making a case for you! The title appears on the transparent window when you have also an **icon** on it! Like this:

```javascript
{
  "main": "index.html",
  "name": "nw-transparent-demo",
  "window": {
    "show": true,
    "icon": "img/blue-dot.png",
    "frame": false,
    "width": 260,
    "height": 260,
    "min_width": 260,
    "min_height": 260,
    "always_on_top": true,
    "transparent": true,
    "toolbar": false
  }
}
```

Here is the test case:
[transparent_title_bug.zip](https://github.com/nwjs/nw.js/files/1634505/transparent_title_bug.zip)

**Comment by tolrtd** [comment] 2018-01-16 23:01
@gpetrov Confirmed this is an issue for me too.  If you have the "icon" in package.json then the toolbar appears; no "icon" then it works fine.  But no icon uses the default nw.js icon for the application.

**Comment by jtg-gg** [comment] 2018-01-18 04:11
ok I can reproduce this, but I have a workaround, I've explained it here https://github.com/nwjs/nw.js/issues/6265#issuecomment-343376723

but, anyway, in your packge.json:
"window": {
    "show": false,
}

then in your html file:
<body onload="nw.Window.get().show()">

with this workaround, you also solved https://github.com/nwjs/nw.js/issues/6217

I think I'll make an official documentation about this work around

**Comment by gpetrov** [comment] 2018-01-18 07:53
thanks @jtg-gg - I hope it will be solved soon in the core, so we don't have to bypass it like this as this introduces app load delays.

**Comment by jtg-gg** [comment] 2018-01-23 02:53
@gpetrov, I've made a fix https://github.com/nwjs/chromium.src/pull/104
@rogerwang please accept my pull request and also patch nw28

**Comment by rogerwang** [comment] 2018-01-23 03:00
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2018-01-23 03:00 UTC
Labels: P2, bug, triaged
