### ISSUE TITLE
NWJS sometimes doesn't re-open until "name" is changed

### ISSUE THREAD

**Issue by Qix-** [nwjs/nw.js#7633] opened 2020-11-26 21:10 UTC
It appears the `"name"` field in the package manifest cannot contain the `:` character. NW.js just crashes with no output (even with logging enabled), causing a considerable amount of headache.

```
nw.js v0.50.1
Node v15.3.0
Chromium 87.0.4280.66
commit hash: 2d5b629-518f361-e10550e-d168d6d
```

**Comment by Qix-** [comment] 2020-11-26 21:41
Actually I'm not entirely sure what the issue is. It seems it chokes on certain words altogether.

For now, simply putting an empty string in there works. The `<title>` tag is picked up anyway, which seems like it should be the default anyway... I don't really understand the use of the `name` field.

**Comment by Qix-** [comment] 2020-11-27 00:00
Nevermind, the initial quickstart tutorial is not clear about the usage of `name`. Buried deep in the docs explains why certain names are not allowed.

**Comment by Qix-** [comment] 2020-11-27 00:36
Okay, figured out the problem. Sometimes, killing NWJS and restarting it will cause it to silently exit until you change the `"name"` propert in the manifest.

This is causing a ton of development headache early on as I can't even begin to debug the issue without some sort of log as to why it's dying.

**Comment by djmisterjon** [comment] 2020-12-02 04:12
i know this issue me too, always check the `zombie nw.exe `  it happening randomly and will also keep debugging port alive and make you crazy.
for me it happening when i fast close the app from window `win+tab` on dev env with a error from bundler.
The memory will also grow infinitely and reach 100% and the PC will start very slow !
Hard to say why,when !

**Comment by gpetrov** [comment] 2020-12-08 10:15
We also also experience zombie nwjs running in the background and eating all the memory - till your pc crashes.
Seems to be somehow related in nwjs restart/reload or close/open of the main window. Might be also only the SDK version.
Can't really narrow it down - just happens few times a week.

It is really nasty because the zombie nwjs process has really nothing to do with your main nwjs and keeps eating all the memory and till Windows 10 completely freezes due to out of memory (even with 32GB RAM)

**Comment by djmisterjon** [comment] 2020-12-08 11:04
> Can't really narrow it down - just happens few times a week.
> 
> It is really nasty because the zombie nwjs process has really nothing to do with your main nwjs and keeps eating all the memory and till Windows 10 completely freezes due to out of memory (even with 32GB RAM)
Exactly !,
I am delighted to see that I am not the only one, yes I also realize that when my 32GB is 100% saturated and my OS becomes super slow.
Note that if you inject debug remote ports, they will also no longer be available until you kill nwjs ghost process.
**The funniest thing is that when I try to cause this error, I can't do it anymore.** and seem only append in SDK! Never seen this in productions.

Maybe @rogerwang have theory ! this behavior is very mysterious !!

**Comment by Qix-** [comment] 2020-12-08 11:08
> Might be also only the SDK version.

I hope that's the case - I'd be mostly OK with that.

A helpful tip for anyone who's frustrated with this: keep task manager open, if you notice your app isn't restarting and there are zombie processes, you'll probably see not one, but 3 or 4 nwjs.exe's. **Kill the one with the most memory usage** - the others will be respawned if you kill them. Killing the largest one will kill all the others.

**Comment by djmisterjon** [comment] 2020-12-08 13:23
here screenshoted , it just appened, close and alive in background process 
i will not wait memory grow, but it also seem consume cpu ! 
![image](https://user-images.githubusercontent.com/24865815/101489189-9837ba80-392e-11eb-95ca-0ab0fa1bc737.png)

**Comment by rogerwang** [comment] 2020-12-08 13:46
could you get the full command line of that process?

**Comment by djmisterjon** [comment] 2020-12-08 15:16
Sry Roger, i cant reproduce ghost again but when it will happened again i will give you the detail.

or if another guys catch it before me, **plz just tape this in your cmd window**
```bash
wmic process where caption="nw.exe" get commandline
```

this should give all process details from the ghost nwjs and just past here for @rogerwang 



it should give something like this :)
```cmd
wmic process where caption="nw.exe" get commandline

"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\nw.exe" ./dist --remote-debugging-port=9222                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\nw.exe" --type=crashpad-handler "--user-data-dir=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data\Crashpad" "--metrics-dir=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --annotation=plat=Win64 --annotation=prod=appname --annotation=ver=0.1.0 --initial-client-data=0x258,0x25c,0x260,0x228,0x264,0x7ffd6ce36ec8,0x7ffd6ce36ed8,0x7ffd6ce36ee8                                                         
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\nw.exe" --type=gpu-process --field-trial-handle=1648,9565040428614712183,5470451989607955271,131072 --no-sandbox --user-data-dir="C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --nwapp-path=./dist --start-stack-profiler --gpu-preferences=MAAAAAAAAADgAAAwAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAAKAAAAAQAAAAgAAAAAAAAACgAAAAAAAAAMAAAAAAAAAA4AAAAAAAAABAAAAAAAAAAAAAAAAUAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAABAAAABQAAABAAAAAAAAAAAQAAAAYAAAA= --mojo-platform-channel-handle=1716 /prefetch:2                                                   
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\nw.exe" --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=1648,9565040428614712183,5470451989607955271,131072 --lang=fr --service-sandbox-type=network --no-sandbox --enable-audio-service-sandbox --user-data-dir="C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --nwapp-path=./dist --mojo-platform-channel-handle=1940 /prefetch:8                                                                                                                                                                                     
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\nw.exe" --type=utility --utility-sub-type=storage.mojom.StorageService --field-trial-handle=1648,9565040428614712183,5470451989607955271,131072 --lang=fr --service-sandbox-type=none --no-sandbox --enable-audio-service-sandbox --user-data-dir="C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --nwapp-path=./dist --mojo-platform-channel-handle=2228 /prefetch:8                                                                                                                                                                                        
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\nw.exe" --type=renderer --no-sandbox --enable-spell-checking --file-url-path-alias="/gen=C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\gen" --no-zygote --remote-debugging-port=9222 --field-trial-handle=1648,9565040428614712183,5470451989607955271,131072 --lang=fr --user-data-dir="C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --nwapp-path=./dist --nwjs --extension-process --enable-auto-reload --enable-spell-checking --device-scale-factor=1.25 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --mojo-platform-channel-handle=2644 /prefetch:1
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\nw.exe" --type=renderer --no-sandbox --enable-spell-checking --file-url-path-alias="/gen=C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge ls\node_modules\nw\nwjs\gen" --no-zygote --remote-debugging-port=9222 --field-trial-handle=1648,9565040428614712183,5470451989607955271,131072 --lang=fr --user-data-dir="C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --nwapp-path=./dist --nwjs --extension-process --enable-auto-reload --enable-spell-checking --device-scale-factor=1.25 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=6 --mojo-platform-channel-handle=2808 /prefetch:1
```

**Comment by gpetrov** [comment] 2020-12-09 14:35
OK got another zombie instance, here is the output, just before my system hang:

during the hanging
```
wmic process where caption="nw.exe" get commandline
CommandLine
C:\Develop\Wappler\windows\nw.exe --type=crashpad-handler "--user-data-dir=C:\Users\George\AppData\Local\Wappler\User Data" /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\George\AppData\Local\Wappler\User Data\Crashpad" "--metrics-dir=C:\Users\George\AppData\Local\Wappler\User Data" --annotation=plat=Win64 --annotation=prod=Wappler --annotation=ver=3.5.7 --initial-client-data=0x21c,0x220,0x224,0x1f8,0x228,0x7ff99ae86ec8,0x7ff99ae86ed8,0x7ff99ae86ee8
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --enable-logging --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --log-level=0 --no-zygote --field-trial-handle=1652,17357810516090305968,3390567644046782719,131072 --lang=nl --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=app --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=41 --mojo-platform-channel-handle=3548 /prefetch:1
C:\Develop\Wappler\windows\nw.exe .
C:\Develop\Wappler\windows\nw.exe --type=crashpad-handler "--user-data-dir=C:\Users\George\AppData\Local\Wappler\User Data" /prefetch:7 --monitor-self --monitor-self-argument=--type=crashpad-handler "--monitor-self-argument=--user-data-dir=C:\Users\George\AppData\Local\Wappler\User Data" --monitor-self-argument=/prefetch:7 --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\George\AppData\Local\Wappler\User Data\Crashpad" "--metrics-dir=C:\Users\George\AppData\Local\Wappler\User Data" --annotation=plat=Win64 --annotation=prod=Wappler --annotation=ver=3.5.7 --initial-client-data=0x208,0x20c,0x210,0xd8,0x214,0x7ff99ae86ec8,0x7ff99ae86ed8,0x7ff99ae86ee8
C:\Develop\Wappler\windows\nw.exe --type=crashpad-handler "--user-data-dir=C:\Users\George\AppData\Local\Wappler\User Data" /prefetch:7 --no-periodic-tasks --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\George\AppData\Local\Wappler\User Data\Crashpad" --annotation=plat=Win64 --annotation=prod=Wappler --annotation=ver=3.5.7 --initial-client-data=0x1b8,0x1bc,0x1c0,0x17c,0x1c4,0x7ff66fbc1f30,0x7ff66fbc1f40,0x7ff66fbc1f50
"C:\Develop\Wappler\windows\nw.exe" --type=gpu-process --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --no-sandbox --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --start-stack-profiler --gpu-preferences=MAAAAAAAAADgAAAwAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAAKAAAAAQAAAAgAAAAAAAAACgAAAAAAAAAMAAAAAAAAAA4AAAAAAAAABAAAAAAAAAAAAAAAAUAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAABAAAABQAAABAAAAAAAAAAAQAAAAYAAAA= --mojo-platform-channel-handle=1708 /prefetch:2
"C:\Develop\Wappler\windows\nw.exe" --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --service-sandbox-type=network --no-sandbox --enable-audio-service-sandbox --ignore-certificate-errors --ignore-certificate-errors --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --extensions-on-chrome-urls --mojo-platform-channel-handle=2004 /prefetch:8
"C:\Develop\Wappler\windows\nw.exe" --type=utility --utility-sub-type=storage.mojom.StorageService --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --service-sandbox-type=none --no-sandbox --enable-audio-service-sandbox --ignore-certificate-errors --ignore-certificate-errors --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --extensions-on-chrome-urls --mojo-platform-channel-handle=2248 /prefetch:8
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --extension-process --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --mojo-platform-channel-handle=2768 /prefetch:1
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=24 --mojo-platform-channel-handle=5956 /prefetch:1
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=25 --mojo-platform-channel-handle=4464 /prefetch:1
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=26 --mojo-platform-channel-handle=3944 /prefetch:1
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --start-stack-profiler --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=27 --mojo-platform-channel-handle=4948 /prefetch:1
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=28 --mojo-platform-channel-handle=5344 /prefetch:1
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=29 --mojo-platform-channel-handle=840 /prefetch:1
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=30 --mojo-platform-channel-handle=5972 /prefetch:1
```
after killing the hang process:

```
wmic process where caption="nw.exe" get commandline
CommandLine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
C:\Develop\Wappler\windows\nw.exe .                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
C:\Develop\Wappler\windows\nw.exe --type=crashpad-handler "--user-data-dir=C:\Users\George\AppData\Local\Wappler\User Data" /prefetch:7 --monitor-self --monitor-self-argument=--type=crashpad-handler "--monitor-self-argument=--user-data-dir=C:\Users\George\AppData\Local\Wappler\User Data" --monitor-self-argument=/prefetch:7 --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\George\AppData\Local\Wappler\User Data\Crashpad" "--metrics-dir=C:\Users\George\AppData\Local\Wappler\User Data" --annotation=plat=Win64 --annotation=prod=Wappler --annotation=ver=3.5.7 --initial-client-data=0x208,0x20c,0x210,0xd8,0x214,0x7ff99ae86ec8,0x7ff99ae86ed8,0x7ff99ae86ee8
C:\Develop\Wappler\windows\nw.exe --type=crashpad-handler "--user-data-dir=C:\Users\George\AppData\Local\Wappler\User Data" /prefetch:7 --no-periodic-tasks --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\George\AppData\Local\Wappler\User Data\Crashpad" --annotation=plat=Win64 --annotation=prod=Wappler --annotation=ver=3.5.7 --initial-client-data=0x1b8,0x1bc,0x1c0,0x17c,0x1c4,0x7ff66fbc1f30,0x7ff66fbc1f40,0x7ff66fbc1f50                                                                                                                                                      
"C:\Develop\Wappler\windows\nw.exe" --type=gpu-process --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --no-sandbox --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --start-stack-profiler --gpu-preferences=MAAAAAAAAADgAAAwAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAAKAAAAAQAAAAgAAAAAAAAACgAAAAAAAAAMAAAAAAAAAA4AAAAAAAAABAAAAAAAAAAAAAAAAUAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAABAAAABQAAABAAAAAAAAAAAQAAAAYAAAA= --mojo-platform-channel-handle=1708 /prefetch:2                                                                              
"C:\Develop\Wappler\windows\nw.exe" --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --service-sandbox-type=network --no-sandbox --enable-audio-service-sandbox --ignore-certificate-errors --ignore-certificate-errors --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --extensions-on-chrome-urls --mojo-platform-channel-handle=2004 /prefetch:8                                                                                                                            
"C:\Develop\Wappler\windows\nw.exe" --type=utility --utility-sub-type=storage.mojom.StorageService --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --service-sandbox-type=none --no-sandbox --enable-audio-service-sandbox --ignore-certificate-errors --ignore-certificate-errors --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --extensions-on-chrome-urls --mojo-platform-channel-handle=2248 /prefetch:8                                                                                                                               
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --extension-process --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --mojo-platform-channel-handle=2768 /prefetch:1                                        
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=24 --mojo-platform-channel-handle=5956 /prefetch:1                                              
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=25 --mojo-platform-channel-handle=4464 /prefetch:1                                              
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=26 --mojo-platform-channel-handle=3944 /prefetch:1                                              
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --start-stack-profiler --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=27 --mojo-platform-channel-handle=4948 /prefetch:1                       
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=28 --mojo-platform-channel-handle=5344 /prefetch:1                                              
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --nwjs-guest --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=29 --mojo-platform-channel-handle=840 /prefetch:1                                               
"C:\Develop\Wappler\windows\nw.exe" --type=renderer --no-sandbox --enable-node-worker --file-url-path-alias="/gen=C:\Develop\Wappler\windows\gen" --no-zygote --field-trial-handle=1672,9241733183023380930,17879751995205451005,131072 --lang=nl --user-data-dir="C:\Users\George\AppData\Local\Wappler\User Data" --nwapp-path=. --nwjs --enable-auto-reload --extensions-on-chrome-urls --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=30 --mojo-platform-channel-handle=5972 /prefetch:1  
```

Seems the first two processes were causing the hang - a crash handler and a renderer without a main process.

**Comment by djmisterjon** [comment] 2020-12-12 02:03
@rogerwang
After closed, here : this is maybe not good for ram !
![image](https://user-images.githubusercontent.com/24865815/101969648-8b97b880-3bf3-11eb-9c99-76c2152c95b2.png)
and not nwjs in task or tray (closed confirmed)
![image](https://user-images.githubusercontent.com/24865815/101969743-0fea3b80-3bf4-11eb-8e3b-15bdcb2be6f0.png)

full command line
```
wmic process where caption="nw.exe" get commandline
CommandLine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge LepSoft\node_modules\nw\nwjs\nw.exe" --type=crashpad-handler "--user-data-dir=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" /prefetch:7 --monitor-self --monitor-self-argument=--type=crashpad-handler "--monitor-self-argument=--user-data-dir=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --monitor-self-argument=/prefetch:7 --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data\Crashpad" "--metrics-dir=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --annotation=plat=Win64 --annotation=prod=appname --annotation=ver=0.1.0 --initial-client-data=0x204,0x208,0x20c,0x1e0,0x210,0x7ff9f1cb1f68,0x7ff9f1cb1f78,0x7ff9f1cb1f88
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge LepSoft\node_modules\nw\nwjs\nw.exe" --type=crashpad-handler "--user-data-dir=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" /prefetch:7 --no-periodic-tasks --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\InformatiqueLepage\AppData\Local\appname\User Data\Crashpad" --annotation=plat=Win64 --annotation=prod=appname --annotation=ver=0.1.0 --initial-client-data=0x1bc,0x1c0,0x1c4,0x198,0x1c8,0x7ff7c241cf88,0x7ff7c241cf98,0x7ff7c241cfa8                                                                                                                                                                                                   
"C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge LepSoft\node_modules\nw\nwjs\nw.exe" --type=renderer --no-sandbox --enable-spell-checking --file-url-path-alias="/gen=C:\Users\InformatiqueLepage\Documents\Dev\repo\Vudge LepSoft\node_modules\nw\nwjs\gen" --no-zygote --remote-debugging-port=9222 --field-trial-handle=1640,5889116742445265327,3035487063402570191,131072 --lang=fr --user-data-dir="C:\Users\InformatiqueLepage\AppData\Local\appname\User Data" --nwapp-path=./dist --nwjs --extension-process --enable-spell-checking --device-scale-factor=1.25 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=6 --mojo-platform-channel-handle=1928 /prefetch:1                              

```

**Comment by CosmoMyzrailGorynych** [comment] 2020-12-21 05:07
@djmisterjon @Qix- @gpetrov Do you use webviews with DevTools opened in another webview?
Some of you might face the same issue as in #7588.

Otherwise, try narrowing the circumstances to make the bug reproducible and not stochastic.

**Comment by vulcan9** [comment] 2020-12-21 08:54
+++++++++++++1
sometimes not open!

**Comment by gpetrov** [comment] 2020-12-21 10:17
Thanks @CosmoMyzrailGorynych yes we use a lot of webviews so it might be definitely related!

**Comment by djmisterjon** [comment] 2020-12-22 00:28
am not using WebView on my side.
All my projet nw projets have this king of base
https://github.com/djmisterjon/nw-Parcel-hmr-boilerplate/tree/helloWorld

**Comment by djmisterjon** [comment] 2020-12-22 02:10
Actually, it maybe overkill, but am thinking about a way to execute maybe a bash cmd just before kill child_process .
somethin like this for window .
```bash
taskkill /F /IM nw.exe /T
```
I think when i kill `nwjs`  child_process with a terminal `ctrl+c *2` very fast, (sometime) nwjs dont exist correctly !?
Or it will keep alive some process in background !?
I have no more theorie because i dont know nwjs lowLevel.:(

---

But hey!
@rogerwang  I success to capture a video after try X10 time loll
So this can maybe help to understand how and why.
I dont know if other people work in same way for close nwjs dev env !?
https://youtu.be/NNVjv-cPzvk

So what you see in video it happened sometime , not all time.
Hope this can give a hint !?  these very annoying and bad for the hardware. ☹

**Comment by djmisterjon** [comment] 2021-01-06 19:10
Ok i share this because its made me think about this problem !!! 😁
It is likely that this is from chromium.
Chromium can be unstable with some external software accessibility !
`--disable-renderer-accessibility`  in vscode and in nwjs can fix this weird ghost issue !

https://github.com/microsoft/vscode/issues/107016#issuecomment-697713704

Thas mean check all background software in your machine, they can break vscode or nwjs **because(chromium).**
like:
*Mouses macro softwares
*Keyboards macro softwares .... ext

**Comment by sirisian** [comment] 2021-07-27 23:31
> Might be also only the SDK version.

This happens with the release builds also. I run a lot of devices with nw.js and see this zombie process once in a while.

For reference, this started when I updated to **0.49.0** so started around Oct 2020. I want to say it did not happen with 0.48.4 (the last version I used), but I can't be 100% sure. Essentially something was introduced into the codebase around the time that causes this zombie behavior. Kind of annoying for programs that need to be always running. (Also as additional information the devices I have this running on have like nothing installed/running except this program).

**Comment by betsonserviceportal** [comment] 2021-08-20 17:19
I have this sitting in the system tray when a user tries to close our application.

```
					item = new gui.MenuItem({
						label: 'Restart Intranet',
						click: function () {
							menu.remove(item);
							tray.remove();
							tray = null;
							//gui.App.closeAllWindows();
							//gui.App.quit();
							chrome.runtime.reload();
						}
					});
```

I left the //comments in there in case it spurs an idea.  
This menu option works most of the time, but sometimes it does not.  So we came up with this .bat file that exists on every user's computer:
```
taskkill /f /im nw.exe
echo killing all instances of intranet
TIMEOUT /T 3
echo restarting intranet
TIMEOUT /T 3
start nw c:\intranet\app
TIMEOUT /T 3
echo ending batch file
TIMEOUT /T 3
exit
taskkill /f/im cmd.exe
```

Along the lines of what @djmisterjon mentioned, this works every time.

Now I'm trying to replace my chrome.runtime.reload with the .bat commands, but failing miserably.  It always shuts down the application, but doesn't always open.  I have a feeling the taskkill is killing my newly opened app?

```
					item = new gui.MenuItem({
						label: 'Restart Intranet',
						click: function () {
							/*menu.remove(item);
							tray.remove();
							tray = null;
							//gui.App.closeAllWindows();
							//gui.App.quit();
							chrome.runtime.reload();*/

							const cmd0 = 'taskkill /f /im nw.exe';
							const cmd1 = 'start nw .c/intranet/app';
							const childProcess = require('child_process');

							childProcess.execSync(cmd0);
							childProcess.execSync(cmd1);

						}
					});
```

**Comment by djmisterjon** [comment] 2021-09-13 07:37
@betsonserviceportal 
It not good idea to include  bat commands in you app, because they work only for Window os.
(not work on apple or linux OS) but is ok if is for dev only.
 
But since i migrate to `Vitejs` and make some update with my envs libs and vscode
I haven't had this ghost problem at nwjs shutdown for several months already.
So i think it solved for me !

here example of `package.json`
![image](https://user-images.githubusercontent.com/24865815/133040926-e32ea76e-9dcb-4a99-9cad-ba1b132bf791.png)

And maybe try  update all those dependency if you have it !
- **concurrently** (i also had some suspicion about it, because it create scope for nwjs, server and bundlers)
and before , i use `ctrl+c` very fast for close all, but now i use `trash can icon` from vscode to kill the session.
![image](https://user-images.githubusercontent.com/24865815/133041767-0d2b8221-523b-45b7-b18e-ec88c144074f.png)

- bundler (vitejs is really fast and nice to use with nwjs & electron: before i was use Snowpack and Parcel )

**Comment by tharatau** [comment] 2022-12-25 08:25
Closing this since this issue is being tracked in #7852.

**Closed by tharatau** 2022-12-25 08:25 UTC

**Comment by shixued** [comment] 2024-09-03 02:34
V0.91 has the same problem
