### ISSUE TITLE
Cannot screenshare from within iframe Cross domain. InvalidStateError

### ISSUE THREAD

**Issue by andyryan** [nwjs/nw.js#6212] opened 2017-10-17 14:23 UTC
I have an app that is connecting to a webapp across domains through an iframe. This embedded app is trying to initialise a screen share but the `getUserMedia` request fails with `InvalidStateError`.

I have tried using both the `chooseDesktopMedia` and `DesktopCaptureMonitor`(and yes I am remembering to use `registerStream` functions and both lead to the same error on `getUserMedia`.

Note: this flow works correctly on Chrome. Even cross domain.

**Comment by Christywl** [comment] 2017-10-18 08:48
Could you please share your sample to reproduce this issue?

**Comment by andyryan** [comment] 2017-10-18 10:44
I can't share the actual code due to IP, but heres roughly what it's doing.

Parent frame

    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title></title>
        <script type="text/javascript" src="demo.js"></script>
        <link rel="stylesheet" type="text/css" href="demo.css" >
    </head>
    <body>
        <iframe src="{some other domain}" style="width:100%; height:400px;"></iframe>
    </body>
    </html>

embedded iframe

    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title></title>
        <script type="text/javascript" src="demo.js"></script>
        <link rel="stylesheet" type="text/css" href="demo.css" >
    </head>
    <body>
        <div class="screen-share-demo">
            <video id="screen-share" autoplay></video>
            <div class="tools">
            <button onclick="chooseDesktopMedia()">screen.chooseDesktopMedia</button>
            </div>
        </div>
    </body>
    </html>

demo.js

```
function chooseDesktopMedia(){
    if(nw.Screen.Init){
        nw.Screen.Init();
    }
    nw.Screen.chooseDesktopMedia(["screen"],function(streamId){
        if(streamId) {
            var conf = {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: streamId,
                    maxWidth: 1920,
                    maxHeight: 1080
                },
                optional: []
            };
            console.log("[nw.chooseDesktopMedia] stream id:" + streamId);
            showScreenShare({audio: false, video: conf});
        }
    })
}

function showScreenShare(conf){
    var ve = document.getElementById("screen-share");

   navigator.mediaDevices.getUserMedia(conf)
    .then(function(stream){
        var url = window.URL.createObjectURL(stream);
        ve.src = url;
    })
    .catch(function(e){
        console.log(e);
        alert(e);
    });

}
```

NOTE: bug only occurs when the iframe src is on a separate domain

**Comment by andyryan** [comment] 2017-10-18 14:06
Tried something new today. I tried getting the iFrame to request that the parent frame get the media source ID and passing that back to the iframe and the iframe initiating screen sharing. Still no luck.

Another thing I have tried is the `--disable-web-security` and `--no-sandbox` chromium launch flags and they don't work either

**Comment by rogerwang** [comment] 2017-10-19 02:37
@andyryan could you please extract some minimal reproducible case from the app. It would be best if the same code works in Chrome but breaks in NW. PS, you can use nw --url=<some url> to test any web page.

**Comment by andyryan** [comment] 2017-10-19 12:40
Does the above code not reproduce?

**Comment by Christywl** [comment] 2017-10-23 06:55
I try to reproduce this with the codes above:
1. Set up a http-server(npm) and put the iframe html and demo.js in this server.
2. Replace src to my server address `http://*****:8080/child.html` in index.html.
3. Add `chromium-args` in `package.json` due to my server is http, or it will throw `NotSupportedError: Only secure origins are allowed`:
```
{
    "name": "6212",
    "main": "index.html",
    "nodejs":true,
    "chromium-args": "--unsafely-treat-insecure-origin-as-secure=http://*****:8080",
    "node-remote": "<all_urls>"
}
```
4. Launch the app with nwjs-sdk-v0.26.0, and click the `screen.chooseDesktopMedia` button:
![image](https://user-images.githubusercontent.com/20039821/31875627-965fd398-b801-11e7-9a32-b469d34019c2.png)
  _note: please ignore demo.css error._

@andyryan , is the result same as yours? And please let me know if there are some wrong steps.

**Comment by andyryan** [comment] 2017-10-23 07:24
Yes thats what I'm seeing precisely. Thanks for reproducing. 

One thing that may be of note. I've managed to work around this by using a reverse proxy to give the appearance that the contents of the iframe and from the same domain. This seems to have ben successful.

However I also tried changing the `document.domain` property so both were the same (as they only had different subdomains in the first place) however that alone did not seem to fix the problem

**Comment by rogerwang** [comment] 2017-10-24 05:41
@Christywl since OP said "this flow works correctly on Chrome. Even cross domain.", could you please try it in Chrome browser?

**Comment by Christywl** [comment] 2017-10-24 07:42
I have no idea about how to check it on chrome browser. I remove `nw` and modify the codes to `chrome.desktopCapture.chooseDesktopMedia` and open index.html with chrome, but it returns undefined. 
@andyryan , could you please kindly tell me how to check this on Chrome?

**Comment by andyryan** [comment] 2017-10-24 09:18
Screensharing with Chrome is only possible from an extension which must be called from your app

**Comment by rogerwang** [comment] 2017-10-31 13:31
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2017-10-31 13:31 UTC
Labels: bug, P2, triaged, WIP

**Comment by rogerwang** [comment] 2017-11-01 02:14
https://dl.nwjs.io/live-build/11-01-2017/nw26-95c0990-9d2f46a-e2f0133-7d1aaec/v0.26.3/
