### ISSUE TITLE
0.13.0-beta5: app not loaded when appending the zip file to the end of nw.exe

### ISSUE THREAD

**Issue by jonathan-roy** [nwjs/nw.js#4360] opened 2016-02-04 10:51 UTC
We distribute our application with the ZIP file (app.nw) appended to nw.exe using the following command: `copy /b nw.exe+app.nw app.exe`

This worked well before v0.12.3 but with v0.13.0-beta5 the app is not loaded, we can see instead the default NW.js page (the grey one with versions numbers). Sometimes this default page is not even open, no window is open but the process exists and seems to load something indefinitely.

**Comment by kucix** [comment] 2016-02-04 11:01
This is known issue
http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues

Appending zip to the executable is currently not supported. Please use plain files or a separate zip file.

**Comment by rogerwang** [comment] 2016-02-05 05:48
close as duplicate of #4071

**Closed by rogerwang** 2016-02-05 05:48 UTC

**Comment by rogerwang** [comment] 2016-02-15 04:51
Fixed in git and will be available in the next nightly build.
