### ISSUE TITLE
BUG - when executing the NW showing strange popup?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#6182] opened 2017-09-29 14:22 UTC
BUG - when executing the NW showing strange popup?

![image](https://user-images.githubusercontent.com/107349/31020082-34ff6c44-a532-11e7-8fca-e297ca5d3cfc.png)

**Comment by Christywl** [comment] 2017-09-30 02:22
Try more times, and find the way to reproduce this:
 Run the app with the newer nwjs, and then run the app with the older version, it may pop up this window.

**Comment by rogerwang** [comment] 2017-09-30 02:44
@Christywl what did it say? Please attach a screenshot.

**Comment by Christywl** [comment] 2017-09-30 06:30
![6182](https://user-images.githubusercontent.com/20039821/31043279-d06bbe26-a5eb-11e7-99b6-857a6005287a.png)

**Comment by deltapath-eric** [comment] 2017-10-03 01:08
For information, I also encounter this in macOS.

**Comment by tekrat** [comment] 2017-10-03 12:15
Since NW.js is a variant of Chrome we can look at the matching Chrome error:

https://www.wintips.org/how-to-fix-your-preferences-can-not-be-read-error-in-chrome-solved/

Its looks like NW created a corupted profile.  I'm not sure where its on
your respective systems but I would try deleting the C:\Users\<Your User
ID>\AppData\Local\node-webkit folder on Windows.  Backup up the folder if
you want to be safe.  I'm pretty sure that NW rebuilds the profile every
time its ran.

Otherwise it mayeb bug in your version of NW and getting confused on if it
shoudl look for Chrome/Chromium preferences file of teh NW one.

**Comment by oaleynik** [comment] 2017-10-04 18:54
Isn't this the same as https://github.com/nwjs/nw.js/issues/6188?

**Comment by rogerwang** [comment] 2017-10-05 12:39
close as duplicate of #6188 . Thanks.

**Closed by rogerwang** 2017-10-05 12:39 UTC
Labels: bug, P3, triaged
