### ISSUE TITLE
WebRTC usb headset Windows 10 no audio output

### ISSUE THREAD

**Issue by markhorsman** [nwjs/nw.js#5609] opened 2017-01-03 15:10 UTC
First off all, happy new year to all developers of nwjs!

This week me and my colleague stumbled upon a problem with our Windows softphone application build with nwjs. 
We noticed that USB headsets on Windows 10 do not output audio during webrtc sessions.
In our application, it is possible to select audio input/output devices for use with WebRTC conversations.
If we plug an USB headset in a device with Windows 10, the device is displayed in the list with input/output devices and the device audio output works fine in Windows when using other application, but unfortunately not in our nwjs application. 

We also have a browser version of our application which has basically the same code base (except for the nwjs integration). The weird thing is that it works perfectly in a Chrome browser (and Firefox, Safari).

We noticed that analog headsets have no problems, just USB headsets.

We are using nwjs version 0.19.4 and Windows as platform. We tested on Windows 10 Home 1607 (build 14393.447) and used multiple Jabra and Sennheiser USB headsets.

We have no idea what the problem is, since we don't get any errors and there is nothing wrong with the headsets. We really hope you can help us since a lot of our clients use our application with an USB headset to make calls and we would like to keep using nwjs in the future.

With kind regards,

Mark Horsman
Tam One
mark.horsman@tam-one.nl

**Comment by shamun** [comment] 2017-01-03 15:23
Which exact model is it? which interface USB2.0, 3 or USB-C?

**Comment by markhorsman** [comment] 2017-01-03 15:32
We have tested with USB 2.0 and 3.0 using Sennheiser DW Pro1 USB

**Comment by rogerwang** [comment] 2017-01-03 16:03
To isolate the issue could you please try running plain NW without any app,
but with '--url=' pointing to some online webrtc demo and see whether your
hardware works?

**Comment by markhorsman** [comment] 2017-01-04 08:14
When I direct the main app in package.json to our web version (url) of the application it work just fine.
I think I have to mention that normally I build a Windows installer using a program call Inno Setup Compiler.

**Comment by shamun** [comment] 2017-01-04 08:18
OK - that means its not our issue. Please close the issue (it has something to do with your own script, etc etc not related to NW.js)

**Closed** 2017-01-04 08:23 UTC

**Comment by rogerwang** [comment] 2017-01-04 08:45
It could be the app issue, another possibility is that webrtc code in
Chromium has issue with the chrome-extension protocol...

**Comment by markhorsman** [comment] 2017-01-04 08:55
If I run a website through nwjs app, it uses chromium right?

**Comment by rogerwang** [comment] 2017-01-04 08:57
Yes, with different protocol than local app.

**Comment by markhorsman** [comment] 2017-01-04 09:02
It is not just related to webrtc code because our app also plays simple dial sounds when dialing a number, and these don't work either when using our nwjs app. So it looks like a Chromium issue with the chrome-extension protocol like you said earlier?

**Comment by rogerwang** [comment] 2017-01-05 09:31
To tell whether the issue is in app code or it's the protocol thing, you can try to host the code of local app with a local http server and add the domain to 'node-remote' field of package.json. In this way the code would be identical and only the protocol is different.
