### ISSUE TITLE
registerGlobalHotKey  and  alert

### ISSUE THREAD

**Issue by xland** [nwjs/nw.js#4992] opened 2016-06-16 08:39 UTC
nw version:0.15.2
os version:windows 10 x64
code:

``` javascript
var option = {
    key: "Ctrl+Shift+N",
    active: function() {
        alert("1")
    },
    failed: function(msg) {
        alert("2")
    }
};
var shortcut = new nw.Shortcut(option);
nw.App.registerGlobalHotKey(shortcut);
```

description:
When app is minsized and the shortcut is pressed, the alert dialog can not  show and the app is disabled.

**Comment by ghostoy** [comment] 2016-07-05 02:13
I can confirm this issue. Looks like it only happens on Windows. I will try to fix it.

**Comment by rogerwang** [comment] 2016-11-08 02:21
This is fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-11-08 02:21 UTC
Labels: bug

**Comment by xland** [comment] 2016-11-08 03:22
OK~Thanks a lot!
