### ISSUE TITLE
nwsaveas doesn't work in 0.35.0

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#6888] opened 2018-12-06 12:43 UTC
NWJS Version : 0.35.0
Operating System : Windows 10 x64

### Expected behavior

In NW.js 0.34, `<input type="file" nwsaveas>` shows a save dialog.

### Actual behavior

In NW.js 0.35, it shows an "open" dialog, which appears to be identical to as if the nwsaveas attribute was not present.

### How to reproduce

`<input type="file" nwsaveas>` in a HTML file is sufficient to reproduce this issue.

**Comment by rogerwang** [comment] 2018-12-06 22:58
This is the duplicate of #6886, which has been fixed in git.

**Closed by rogerwang** 2018-12-06 22:58 UTC
