### ISSUE TITLE
nwjs 0.13 beta3 - google oauth login callback not working

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4184] opened 2016-01-07 20:33 UTC
Hello @rogerwang 
I'm testing latest nightly build (Jan 8, 2016), now the google login and page load is working... 

there is still some problem with oauth api / callback, indeed after the login nothing will happen.

You can test it here: http://jsfiddle.net/thyb/JMTVz/5/ 

In my app I'm using oauth2 method with gapi.client library (https://developers.google.com/identity/protocols/OAuth2)

**Comment by eemi2010** [comment] 2016-01-08 03:02
I think this is due to the fact that that window.opener returns null in nw.js.
So if I do window.open(someUrl); then calls window.opener on the window that displays someUrl it returns null, which is breaking oAuth2. Should I fill an extra bug for this ?

**Comment by ghostoy** [comment] 2016-01-08 03:50
@AndryBray @eemi2010 I tried your case by setting `node-remote` to `"<all_urls>"`, and it worked.

package.json:

```json
{
  "name": "oauth",
  "main": "http://jsfiddle.net/thyb/JMTVz/5/",
  "node-remote": "<all_urls>"
}
```

You can even reduce the `node-remote` to `["*://*.jsfiddle.net/*", "*://*.google.com/*", "*://oauth.io/*"]`, which also works.

**Comment by rogerwang** [comment] 2016-01-08 04:23
Adding note-remote is not a solution. Still need to find the root cause.

**Comment by eemi2010** [comment] 2016-01-08 09:27
@ghostoy  In my case not really a solution since we are relying on window.opener which return null on a window opened with window.open

**Comment by AndryBray** [comment] 2016-01-08 09:56
@ghostoy I think this solution could be dangerous because of nodejs access from external domains

**Comment by ghostoy** [comment] 2016-01-09 01:29
I will look into this problem.

**Comment by rogerwang** [comment] 2016-01-11 07:13
Fixed in git and will be available in the next nightly build.

**Closed by rogerwang** 2016-01-11 07:13 UTC
Labels: bug, nw13, regression, test-todo

**Comment by ghostoy** [comment] 2016-01-12 06:36
The issue seems only happens for secured `https` protocols. I will submit a test case later.
