### ISSUE TITLE
0.13 beta5 -windows High processor usage when open pdf in nwjs app

### ISSUE THREAD

**Issue by ratones** [nwjs/nw.js#4335] opened 2016-01-29 13:35 UTC
I have to display some pdf files in my app. User clicks on a link and a new window opens the pdf file from external address(link). 
In task manager I see the new window consuming 40-50 percent of CPU constantly.
This doesn't happens in Chrome.

**Comment by rogerwang** [comment] 2016-02-02 05:48
fixed in git. will be available in the next nightly build.

The root cause is we're reusing renderer process for all new pages, which should not be the cause for the PDF viewer extension.

**Closed by rogerwang** 2016-02-02 05:48 UTC
