### ISSUE TITLE
Menu does not work on version 0.14.0

### ISSUE THREAD

**Issue by zsoltpardi** [nwjs/nw.js#4734] opened 2016-04-17 18:47 UTC
It seems the menu is not operational anymore on Windows 64-bit. I haven't tried Linux nor MAC OS X. Not any existing menu initialization code nor the below example code from the documentation works. The menu works fine on the latest 0.13.4 version.

```
var your_menu = new nw.Menu({ type: 'menubar' });

var submenu = new nw.Menu();
submenu.append(new nw.MenuItem({ label: 'Item A' }));
submenu.append(new nw.MenuItem({ label: 'Item B' }));
        
// the menu item appended should have a submenu
your_menu.append(new nw.MenuItem({
    label: 'First Menu',
    submenu: submenu
}));
 
nw.Window.get().menu = your_menu;
```

This will show the top level "First Menu" menu item, but doesn't render "Item A" and "Item B" menu items.

**Comment by rogerwang** [comment] 2016-04-17 23:19
It's duplicate of #4727 and fixed in the nightly build.

**Closed** 2016-04-17 23:22 UTC

**Comment by zsoltpardi** [comment] 2016-04-17 23:29
Fantastic, thanks, and sorry for not realizing the issue was raised already.
