### ISSUE TITLE
Tray stops working after reload page

### ISSUE THREAD

**Issue by edelciomolina** [nwjs/nw.js#5708] opened 2017-02-15 12:02 UTC
Sometimes the tray seems like that lose the "link" with the application, so I cant re-open it because the tray is in the Windows bar, but the left click that has an event to my code doesn't work, seems like the event handler for tray event was removed.
Is clear to me that the tray is working because my right button opens a menu and I can see it open.

I do not know when and why this happens, but I discovered a way to simulate this problem.
You just have to open the application and into devtools refresh the page, so, the tray icon will stops.

The mainly question here is, is a way to recreate the tray icon events after reload the page or is it really a issue?

Attached is a example how to simulate what I described;
[test_tray.zip](https://github.com/nwjs/nw.js/files/776925/test_tray.zip)

![image](https://cloud.githubusercontent.com/assets/4604923/22972976/31870d3c-f363-11e6-8301-1a5470fbd08b.png)

**Comment by RohitSharma27** [comment] 2017-02-15 15:30
Please check out the issue #4773

**Comment by rogerwang** [comment] 2017-02-16 01:56
Close as duplicate of #5537

**Closed by rogerwang** 2017-02-16 01:56 UTC

**Comment by edelciomolina** [comment] 2017-02-16 19:39
@RohitSharma27 thank you, but I´m with another problem;
I follow one of solutions in [#5537 ](https://github.com/nwjs/nw.js/issues/5537), but how you can see below, I cant open my mainly page with gui.Window.open because when I pass 'toolbar' or 'frame' option to my window (as https://github.com/nwjs/nw.js/wiki/Frameless-window#enable-frameless-window) an exception happens.

Is there another way to do that? Thks!

![image](https://cloud.githubusercontent.com/assets/4604923/23037492/b79b83c0-f46d-11e6-8050-becd85362a52.png)

**Comment by RohitSharma27** [comment] 2017-02-17 09:23
That's because toolbar property has been depreciated and is always set to false. Please refer to the news.io for the latest and updated documentation.

**Comment by RohitSharma27** [comment] 2017-02-17 09:24
I meant nwjs.io

**Comment by lishichao1002** [comment] 2018-12-11 13:57
window.addEventListener('beforeunload', function (event) {
    removeTray()
  })
